### ISSUE TITLE
sensuctl can display a cluster member ID in different formats

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-docs#1005]
A cluster member can have an ID outside the 64 bit range.

## Expected Behavior
`http://127.0.0.1:8080/api/core/v2/cluster/members/9882886658148554927?peer-addrs=http://127.0.0.1:2380` **PUT** should update the peer urls of a cluster member with the auto-generated ID of `9882886658148554927`.

## Current Behavior
400 Bad Request: `bad id (9882886658148554927): strconv.ParseUint: parsing "9882886658148554927": value out of range`

## Possible Solution
Investigate how etcd generates the ID, or parse the ID using a different approach. https://github.com/sensu/sensu-go/blob/ae978f830e8fcb07da289d36c0d0876777222614/backend/apid/routers/cluster.go#L53

## Steps to Reproduce (for bugs)
1. **PUT** `http://127.0.0.1:8080/api/core/v2/cluster/members/9882886658148554927?peer-addrs=http://127.0.0.1:2380`
2. Max 64 bit int = `9223372036854775807`
3. Observe `bad id (9882886658148554927): strconv.ParseUint: parsing "9882886658148554927": value out of range`

## Context
Cannot update cluster members with ID's larger than `9223372036854775807`. Ran across this issue when pairing with @apaskulin on API requests. The ID given to my default cluster member was `9882886658148554927` and I could not complete the request.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): https://github.com/sensu/sensu-go/commit/3fff14d47f401f13e72c37820402c27d9f4c893d
* Installation method (packages, binaries, docker etc.): local binaries
* Operating System and version (e.g. Ubuntu 14.04): MacOS

**Comment by cwjohnston** [comment]
I think https://github.com/etcd-io/etcd/blob/master/Documentation/v2/members_api.md may be a useful upstream documentation reference for the issue at hand.

With regard to Deleting and Modifying an existing cluster member, the doc states:

> The member ID must be a hex-encoded uint64.

**Comment by apaskulin** [comment]
Making sure I understand correctly here: The only place where users could get tripped up by this is when using the cluster API PUT and DELETE endpoints. In #1047, I've added a note to those endpoints that the ID needs to be a hex-encoded uint64. Let me know if anything else is needed here.
