### ISSUE TITLE
Sensu GO Better explanation of securing agent to server communications

### ISSUE THREAD

**Issue by nixwiz** [sensu/sensu-docs#1018]
In trying to work from [Securing Sensu agent to server communication](https://docs.sensu.io/sensu-go/5.0/guides/securing-sensu/#securing-sensu-agent-to-server-communication).  It specifies only what to change on the agent side (ws:// -> wss://) but not what changes need to happen on the backend side to expect/provide SSL/TLS websocket connections from agents.

## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [X] Update (Add missing or refresh existing content)

## Expected Behavior

That the documentation for securing from the agent side references the necessary changes on the backend side when attempting to secure the communications.
## Current Behavior

If you simply change the ws://<backend IP>:8081 to wss://<backend IP>:8081 the agent stops communicating with the backend with the following error:

` {"component":"agent","error":"tls: oversized record received with length 20527","level":"error","msg":"reconnection attempt failed","time":"2018-12-13T13:29:51-08:00"}`

## Steps to Reproduce (for bugs)

1.  Attempt to use instructions provided (solely changing ws:// to wss://)
2.  
3.

## Context

This is preventing me from securing my agent -> backed communication.
* Browser(s) and version(s): 
* OS:

**Comment by cwjohnston** [comment]
Thanks for raising this issue @nixwiz. We will review and determine necessary updates.

**Comment by nixwiz** [comment]
#1079 Claims to fix this.  However, please see my [comment ](https://github.com/sensu/sensu-docs/pull/1079#issuecomment-454089009) there.

**Comment by asachs01** [comment]
@nixwiz we just pushed an update to the doc that should make things a bit clearer. Let us know if it's not, or if you think it needs any additional tweaking.

**Comment by nixwiz** [comment]
@asachs01 that looks good to me.  Thanks for the update!
