### ISSUE TITLE
Sensu Go better continuity of examples for handlers and filters

### ISSUE THREAD

**Issue by nixwiz** [sensu/sensu-docs#1019]
There's a lack of continuity between the examples of creating a handler and filters.  The handler example is explicitly titled "Sending Slack Alerts", but the link in [Using filters to reduce alert fatigue](https://docs.sensu.io/sensu-go/5.0/guides/reduce-alert-fatigue/#using-filters-to-reduce-alert-fatigue) says "how to send alerts with handlers".  Also the remaining examples following that ("Assigning the filter to a handler" and "Validating the filter") both reference a mail handler that is not part of the example.

I would like to see additional examples of handlers and not just the Slack one as that is not quite as generic as say a mail one.  Creating a mail handler example will then also provide the missing continuity in the filters section.

## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [X] Update (Add missing or refresh existing content)

## Expected Behavior

Continuity between examples.
## Steps to Reproduce (for bugs)

1.
2.
3.

## Context

* Browser(s) and version(s): 
* OS:

**Comment by cwjohnston** [comment]
Thanks for raising this issue @nixwiz, I think this makes a lot of sense. 

We have recently released the initial version of https://github.com/sensu/sensu-email-handler which should make it possible for us to provide a cohesive example of handlers + filters centered on the email notification use case. 👍

**Comment by apaskulin** [comment]
I think we should address this is two parts: #1047 switches the filters guide to use the existing Slack handler example to remedy the immediate confusion, and #1022 tracks the creation of a new guide for creating an email handler.
