### ISSUE TITLE
Remove Enterprise Dashboard documents duplicated under Enterprise

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#102]
The following documents currently under Sensu Enterprise should be part of the documentation for Sensu Enterprise Dashboard instead:

http://sensu-docs-site.herokuapp.com/sensu-enterprise/2.7/dashboard/
http://sensu-docs-site.herokuapp.com/sensu-enterprise/2.7/collections/
http://sensu-docs-site.herokuapp.com/sensu-enterprise/2.7/hud/

**Comment by asachs01** [comment]
I believe this is fixed by #136 .
