### ISSUE TITLE
Check flapping threshold attributes should describe reasonable values

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#103]
Migrating from https://github.com/sensu/sensu-docs/issues/305

Per the original issue, we should add text similar to `Typical values are in the 10%-30% range.` to the description of the `low_flap_threshold` and `high_flap_threshold` check attributes.

**Comment by apaskulin** [comment]
Page: https://docs.sensu.io/sensu-core/1.4/reference/checks

**Comment by hillaryfraley** [comment]
Pending EOL: won't fix
