### ISSUE TITLE
Add Ubuntu 14.04 to supported platforms

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-docs#1034]
We are adding support for Ubuntu 14.04, Debian 8, and Debian 9 with the release of 5.1.0 (for agent, backend, and sensuctl). The supported platforms list will need to be updated to reflect these additions.

**Comment by apaskulin** [comment]
Per @amdprophet, we'll only be adding Ubuntu 14.04 for the 5.1 release.

**Comment by apaskulin** [comment]
Closed by #1040
