### ISSUE TITLE
Explain that clients created via the /clients API are "proxy clients"

### ISSUE THREAD

**Issue by Blue0ctober** [sensu/sensu-docs#105]
Migrating https://github.com/sensu/sensu/issues/1203 

Add extra clarification on how proxy clients are not able to have a "keepalive" as the client is not registering itself.

**Comment by asachs01** [comment]
Closing this one out since it appears that we have a note in the docs now about this (see https://github.com/sensu/sensu-docs/blob/master/content/sensu-core/1.3/reference/clients.md#proxy-clients)
