### ISSUE TITLE
Docs Feedback

### ISSUE THREAD

**Issue by ntwish** [sensu/sensu-docs#1057]
"entity.EntityClass == 'proxy'" - > "entity.entity_class == 'proxy'"
need to be compatible with "Entity" section.
Link to page: 
https://docs.sensu.io/sensu-go/5.1/reference/checks/#proxy-requests-attributes
### Feedback

**Comment by apaskulin** [comment]
Great catch! Thanks, @ntwish! I've opened #1066 to fix this.
