### ISSUE TITLE
Docs Feedback: Using annotations in query expressions

### ISSUE THREAD

**Issue by Jazun713** [sensu/sensu-docs#1061]
Link to page: https://docs.sensu.io/sensu-go/5.1/reference/sensu-query-expressions/

### Feedback
No example on how to use check annotations in SQE.  I've looked in the following areas:
https://docs.sensu.io/sensu-go/5.1/reference/filters/
https://docs.sensu.io/sensu-go/5.1/reference/checks/
and the above link for sensu-query-expressions.

**Comment by apaskulin** [comment]
This is great feedback, thanks @Jazun713! We'll add some examples of using annotations in Sensu query expressions to the reference docs.

**Comment by hillaryfraley** [comment]
Best practices is to use labels for event filters because they provide identifying information.
Add an example of using labels in event filter. Add note that you can use annotations, but we recommend using labels.
