### ISSUE TITLE
Sensu-go role rule specification incorrectly references resourceNames

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-docs#1062]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [x] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior

I'd expect role specification for `rule` to reference `resource_names` and not `resourceNames`.

## Current Behavior

Currently a rule shows as allowing `resourceNames`.

## Possible Solution

Change `resourceNames` to `resource_names`.

## Steps to Reproduce (for bugs)

https://docs.sensu.io/sensu-go/5.1/reference/rbac/#rule-attributes

## Context

I am working with @ghoneycutt on sensu-puppet module and noticed from testing that GA release uses `resource_names` and not `resourceNames`.

* Browser(s) and version(s): Google Chrome
* OS: Mac OS

**Comment by apaskulin** [comment]
Thanks, @treydock! I've opened #1066 to fix up these attribute names.
