### ISSUE TITLE
sensu-go entity should not reference keepalive_timeout

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-docs#1063]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [x] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior

I'd expect `keepalive_timeout` to not be in entity specification.  It was removed from sensu-go but lost track of responsible pull request.

## Current Behavior

Currently entity spec references `keepalive_timeout`.

## Possible Solution

Remove `keepalive_timeout` from entity specification.

## Steps to Reproduce (for bugs)

https://docs.sensu.io/sensu-go/5.1/reference/entities/#spec-attributes

## Context

Working with @ghoneycutt on sensu-puppet and updating module to match docs and noticed docs still have `keepalive_timeout` after we removed it from module after sensu-go removed it.

* Browser(s) and version(s): Google Chrome
* OS: Mac OS

**Comment by apaskulin** [comment]
Thanks, @treydock! This is a great catch. We'll remove `keepalive_timeout` from the entity reference.
