### ISSUE TITLE
sensu-go mutator should reference env_vars

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-docs#1064]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [x] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior

I'd expect mutator specification to have `env_vars`.

## Current Behavior

`env_vars` are only mentioned in examples, no reference section.

## Possible Solution

Add reference for `env_vars`.

## Steps to Reproduce (for bugs)

https://docs.sensu.io/sensu-go/5.1/reference/mutators/#spec-attributes

## Context

Working with @ghoneycutt on sensu-puppet and ensure module matches documentation and noticed no reference for `env_vars` on mutators.

* Browser(s) and version(s): Chrome
* OS: Mac OS

**Comment by apaskulin** [comment]
Thanks for submitting this issue, @treydock! We'll get the `env_vars` attribute added to the mutator reference.
