### ISSUE TITLE
Update InfluxDB handler guide to use envvars for database credentials

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-docs#1068]
handler command   arguments are exposed in the process table.. so thinkings like `ps` can see the command arguments.

it's much better to use envvars for sensitive information and reference those envvars in the commandline

example handler command using envvars:
```
sensuctl handler create influx-db \
--type pipe \
--env-vars "INFLUX_USER='user', INFLUX_PASS='pass'"
--command "sensu-influxdb-handler \
--addr 'http://123.4.5.6:8086' \
--db-name 'myDB' 
```

**Comment by apaskulin** [comment]
Depends on to-be-implemented functionality in the InfluxDB handler

**Comment by apaskulin** [comment]
This is ready to document!
