### ISSUE TITLE
Improve configuration reload documentation 

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#107]
_From @calebhailey on April 7, 2016 0:21_

We need to provide a better explanation to help users understand that the server/client/api processes need to be restarted to load configuration changes. 

_Copied from original issue: sensu/sensu-docs#353_

**Comment by cwjohnston** [comment]
_From @calebhailey on April 7, 2016 0:22_

Related: https://github.com/sensu/sensu/issues/1138

**Comment by cwjohnston** [comment]
_From @calebhailey on May 24, 2016 22:38_

Related: https://github.com/sensu/uchiwa/issues/230

**Comment by asachs01** [comment]
This probably needs some better scoping, IMO. For example, we don't know in which docs/guides that we're adding configs, so it'd be helpful to have a list of docs where this needs to happen.

**Comment by hillaryfraley** [comment]
Pending EOL: won't fix
