### ISSUE TITLE
Response Content Filtering should indicate that only string values are supported

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#1080]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

## Expected Behavior

Documentation accurately describes feature requirements/limitations 

## Current Behavior

Response Content Filtering for API requests does not describe the requirement that values be specified as strings, i.e. integer values are not supported.

## Possible Solution

Add words explicitly stating that only string values will be successfully matched.

## Context

In https://github.com/sensu/sensu/issues/1925 a user describes their desire to filter responses based on check status, and in practice they have found that only status `0` returns any matches. Per engineering, the matches being returned for status `0` and not for other integer values are due to Ruby's internal fuzziness around comparing values of differing types.

**Comment by apaskulin** [comment]
Page: https://docs.sensu.io/sensu-core/1.6/api/overview/#response-content-filtering
