### ISSUE TITLE
Document linux binaries

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#1084]
Linux binaries for Sensu Go can be downloaded from https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/5.1.0/sensu-go-5.1.0-linux-amd64.tar.gz. Add this process to the installation guide.

**Comment by cwjohnston** [comment]
We think this requires some reorganization of the installation page.

**Comment by apaskulin** [comment]
Closed by #1162
