### ISSUE TITLE
Attributes missing from Checks attributes

### ISSUE THREAD

**Issue by nixwiz** [sensu/sensu-docs#1094]
Checks is missing documentation for round_robin and subdue.
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [X] Update (Add missing or refresh existing content)

## Current Behavior

Checks attributes for round_robin and subdue are not available in https://docs.sensu.io/sensu-go/5.1/reference/checks/ even though they are part of the available attributes to be edited.
```
# sensuctl check info linux-gw2-wiki-en-site-check --format wrapped-json
{
  "type": "CheckConfig",
  "api_version": "core/v2",
  "metadata": {
    "name": "linux-gw2-wiki-en-site-check",
    "namespace": "AWS"
  },
  "spec": {
    "check_hooks": null,
    "command": "/opt/sensu-plugins-ruby/embedded/bin/check-http.rb -u https://wiki.guildwars2.com/wiki/Main_Page -q Transclusion -e 30",
    "env_vars": null,
    "handlers": [
      "mail"
    ],
    "high_flap_threshold": 0,
    "interval": 300,
    "low_flap_threshold": 0,
    "output_metric_format": "",
    "output_metric_handlers": null,
    "proxy_entity_name": "wiki.guildwars2.com",
    "publish": true,
    "round_robin": true,
    "runtime_assets": null,
    "stdin": false,
    "subdue": null,
    "subscriptions": [
      "wiki-proxied"
    ],
    "timeout": 0,
    "ttl": 0
  }
}
```
## Steps to Reproduce (for bugs)

1.
2.
3.

## Context

* Browser(s) and version(s): 
* OS:

**Comment by apaskulin** [comment]
Thanks, @nixwiz! Round-robin subscriptions and check subdues are not yet implemented in Sensu Go, but I agree that we need some documentation since the attributes are still present in the check definition. We'll add some clarification for those attributes to the checks reference.
