### ISSUE TITLE
Check reference should mention requirements for standalone checks and proxy clients

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-docs#1095]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [X] Update (Add missing or refresh existing content)

## Expected Behavior
Check reference also describes requirements for proxy clients made by standalone checks.

https://docs.sensu.io/sensu-core/1.6/reference/checks

## Current Behavior
Only the process using pub/sub checks to make proxy clients is shown in detail.

## Possible Solution
Add a section about proxy clients and requirements (add `source` attribute).

**Comment by rgeniesse** [comment]
@cwjohnston I'll probably need to pair with you to answer:

- Is the source attribute only used for stand alone checks?
- How do proxy_requests work in Sensu classic?
- Is there a typo on lines 881 and 882 of the Classic check reference?
- Is a change even needed here? If so, where?

I know I opened the ticket, but I am struggling to form the original reason I felt one was needed. I think it revolved around `proxy_requests` not needed for standalone checks, but that may change based on the answers to the above questions.

**Comment by hillaryfraley** [comment]
Pending EOL: won't fix
