### ISSUE TITLE
Documentation on Scalability of sensu

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#110]
_From @RiRa12621 on June 9, 2016 13:21_

I think there is a big need for a real documentation on how to properly scale sense horizontally.

I saw that there is a “coming soon”. Is there an expected date to complete this?

_Copied from original issue: sensu/sensu-docs#394_

**Comment by cwjohnston** [comment]
Scaling section may also be a good place to also talk about configuration uniformity concerns suggested in #256.

**Comment by asachs01** [comment]
@cwjohnston I think this is covered in #342 and #228 . Can we close this?

**Comment by asachs01** [comment]
Closing in favor issues in previous comment.
