### ISSUE TITLE
Enterprise Jira integration issue_type is required if your Jira project does not contain Incident as a type

### ISSUE THREAD

**Issue by mattbeninghof** [sensu/sensu-docs#1101]
### Feedback

Link to page: https://docs.sensu.io/sensu-enterprise/3.3/integrations/jira/#jira-attributes

When using the hosted version of Jira, you must also include "issue_type".

The Jira integration `issue_type` defaults to Incident. If your project does not have that type, the Jira integration will fail. This isn't immediately apparent until looking at logs.

**Comment by apaskulin** [comment]
Add a note to that doc ^ that tells users to make sure they actually have the issue type that Sensu wants to use. This can be a gotcha when the default especially.
