### ISSUE TITLE
documentation for filters is out of date

### ISSUE THREAD

**Issue by exitquote** [sensu/sensu-docs#1119]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

## Expected Behavior

The reference guide for Filters needs to be updated.  It lists "action" as being an attribute of "spec" which is no longer the case.

## Current Behavior

Example filters cannot be successfully added via the API since they don't conform to the new structure.  Documentation also leads to incorrectly formatted requests.

## Possible Solution

Update examples to reflect the new requirements and data structure.

## Steps to Reproduce (for bugs)

1. https://docs.sensu.io/sensu-go/5.1/reference/filters/
2.
3.

## Context

* Browser(s) and version(s): 
* OS:

**Comment by apaskulin** [comment]
Thanks for opening this issue, @exitquote. I'm thinking this might be a result of confusion between the different formats that Sensu uses.

The examples in the filter reference use `wrapped-json` format which includes the `spec` scope. You can use `wrapped-json` format to create filters using `sensuctl create --file my-filter.json`.

The Sensu API accepts `json` format, which does not include the `spec` scope. If you're looking to create filters using the API, you should use the examples in https://docs.sensu.io/sensu-go/5.1/api/filters.

You can see the difference between the two formats using sensuctl:

```
sensuctl filter info my-filter --format wrapped-json

sensuctl filter info my-filter --format json
```

Hope this helps! Let me know if you have any questions.

**Comment by apaskulin** [comment]
Closing this issue for now, but feel free to re-open.
