### ISSUE TITLE
Document WinSW as service manager on Windows

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#112]
_From @amdprophet on October 18, 2016 17:31_

Sensu docs currently details how to use the `sc` command to manage the sensu-client Windows service. Our packages bundle in a `sensu-client.exe` WinSW stub that can be used to manage the service more efficiently. This stub should be used instead of `sc` so long as it's been tested & works on Windows Server 2008, 2012, and 2016.

_Copied from original issue: sensu/sensu-docs#457_

**Comment by cwjohnston** [comment]
_From @cwjohnston on March 20, 2017_

Our existing Windows documentation describes the service wrapper (winsw) but doesn't name it or provide much in the way of details. 

I think we should link to winsw documentation so folks can learn about features like service installation, log rotation, etc. which are outside the scope of Sensu's own documentation.

_Copied from original issue: sensu/sensu-docs#540_

**Comment by hillaryfraley** [comment]
Pending EOL: won't fix
