### ISSUE TITLE
Improve annotation examples

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#1120]
- Remove Slack channel example for annotations to avoid implication that this value could be passed to a Slack handler
- Add a new annotations example that contains more complex data, like `previous_version`

**Comment by cwjohnston** [comment]
We think we need a better example of annotations to replace . Currently we have:

managed_by
playbook
slack_channel

Using `previous_version` doesn't seem helpful/illustrative. Brilliant ideas welcome!

**Comment by apaskulin** [comment]
Closing in favor of #420
