### ISSUE TITLE
Configuration reference doc does not discuss custom attributes

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#114]
_From @cwjohnston on October 10, 2016 18:29_

A number of plugins managed by the Sensu Plugins project, particularly handler plugins, depend on  custom attributes defined in Sensu configuration, but the Configuration reference doc doesn't seem to describe how this works. 

I think we should describe custom configuration attributes just as we have done with custom client and check attributes.

_Copied from original issue: sensu/sensu-docs#449_

**Comment by cwjohnston** [comment]
_From @majormoses on December 18, 2017 23:52_

not sure how true this is anymore I know that we do this for the occurrences and refresh settings. 

Relates to #640 I agree that there probably should be more, that being said I think they should be defined as custom to indicate that this still not something directly supported through the sensu framework but are common things that people consider.

**Comment by cwjohnston** [comment]
I think we need to study this a little to determine where we can explicitly define custom attributes and potentially link to that definition in plugin docs and elsewhere.

**Comment by rgeniesse** [comment]
@cwjohnston both the client and check reference documentation have explanations into custom attributes already:

https://docs.sensu.io/sensu-core/1.4/reference/checks/#custom-attributes
https://docs.sensu.io/sensu-core/1.4/reference/clients/#custom-attributes

So maybe now we just need to discuss the best way to link those up with plugin documentation and anywhere needed?

**Comment by cwjohnston** [comment]
@rgeniesse looks like the plugins reference material already links to our comments on custom check attributes, so I think we can close this 👍
