### ISSUE TITLE
Document API endpoint service requirements

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-docs#1145]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [X] Update (Add missing or refresh existing content)

## Expected Behavior
Add the missing content.

## Current Behavior
Currently do not document what services API endpoints require to return properly, particular the RabbitMQ and Redis services. This would help users troubleshoot where an issue lies if an endpoint is not responding.

## Possible Solution
- [ ] Find endpoints that require Redis (should be all of them).
- [ ] Find endpoints that require RabbitMQ.

**Comment by hillaryfraley** [comment]
Rescope to adding a couple lines to Core troubleshooting doc

**Comment by rgeniesse** [comment]
Specifically, which endpoints can help users know the health of Redis and Rabbitmq to further diagnose issues.
