### ISSUE TITLE
Determine if Erlang R16 should be dropped from supported list

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#118]
_From @cwjohnston on April 10, 2017 15:48_

A number of issues have been opened recently around using Sensu 0.27 (with openssl 1.0.2) and later with Erlang R16 when SSL is enabled. 

We need to determine if R16 is still supportable with newer OpenSSL in Sensu 0.27 and later.

_Copied from original issue: sensu/sensu-docs#578_

**Comment by cwjohnston** [comment]
Per https://www.rabbitmq.com/which-erlang.html, Erlang R17 or later is required for reliable TLS/SSL support.

**Comment by cwjohnston** [comment]
_From @agoddard on June 12, 2017 16:13_

@cwjohnston 👍  I'm in favor of increasing the minimum supported version to R17

**Comment by cwjohnston** [comment]
_From @asachs01 on October 11, 2017 19:28_

One note here that may complicate things: Any users who are running CentOS/RHEL are going to be pulling in 16B03 in via Epel. We may need to update the docs to point to using something like the [Erlang Solutions repos](https://www.erlang-solutions.com/resources/download.html) (which will also require the [compatibility shim repo](https://github.com/jasonmcintosh/esl-erlang-compat)). Alternatively, we could bump up support to at least 18.X, which for our CentOS/RHEL users, would be one less package to install, since Rabbit has that in their [zero-dependency](https://github.com/rabbitmq/erlang-rpm) repo.

**Comment by asachs01** [comment]
@cwjohnston so my question for this one is _should_ we even worry about RMQ at this point? If we're planning on deprecating 1.x, and the documentation is going to be legacy, is it worth keeping around?

**Comment by asachs01** [comment]
Could we ditch the comment in http://localhost:1313/sensu-core/1.2/reference/rabbitmq/#rabbitmq-ssl-and-erlang-183 altogether and just say: "We recommend using Erlang 19.0 +"?

**Comment by cwjohnston** [comment]
@asachs01 I'm comfortable with changing our erlang recommendations in the way you're suggesting, but we should also explain the linkage between rabbitmq version and supported erlang versions. Linking to https://www.rabbitmq.com/which-erlang.html would help explain this as well.
