### ISSUE TITLE
Document event attributes for use with filters

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#1185]
Page: https://docs.sensu.io/sensu-go/5.2/reference/filters
To do: 

- Read https://blog.sensu.io/filters-valves-for-the-sensu-monitoring-event-pipeline
- Document attributes to help users better understand the special event data available to use in filters.

Notes:

               "has_check":     e.HasCheck(),
               "has_metrics":   e.HasMetrics(),
               "is_incident":   e.IsIncident(),
               "is_resolution": e.IsResolution(),
               "is_silenced":   e.IsSilenced(),

**Comment by jspaleta** [comment]
After speaking with @echlebek  about how these dynmic attributes work.
I think we came to the conclusion that this needs to be documented in the context of filters.

These specific attributes are not rendered as part of the event's json representation, and are therefore not passed into mutators or handlers.

These dynamic attributes  are effectively available only inside the context of the filter execution.

**Comment by Blue0ctober** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Document event atributes for use with filters](https://trello.com/c/jvNZ9mui/1-document-event-atributes-for-use-with-filters)
