### ISSUE TITLE
Document time synchronization requirement for Sensu Go

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#1187]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

## Expected Behavior

Docs should explicitly describe the need for time synchronization (using of NTP or similar) to ensure consistency of system clock time between backend(s) and agent(s).

## Current Behavior

Time synchronization requirements are described in the Sensu Core FAQ but do not seem to be covered in Sensu Go documentation.

## Context

From the [Sensu Core FAQ](https://docs.sensu.io/sensu-core/latest/faq/):

> When system clocks are out of sync between Sensu clients (where data is collected) and the Sensu server (where data is processed), Sensu may generate false positive client keepalive events, among other potentially unexpected behaviors.

**Comment by apaskulin** [comment]
To do: Add to agent and backend reference
