### ISSUE TITLE
Document the supported platform/release matrix

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#119]
_From @portertech on July 21, 2017 20:56_

The Sensu documentation should include the platform/release matrix that currently exists in the sensu-omnibus README - https://github.com/sensu/sensu-omnibus#packages-built-using-automation-pipeline

_Copied from original issue: sensu/sensu-docs#611_

**Comment by cwjohnston** [comment]
We should revisit this and determine if it's necessary to document this separately from the platform versions now described on our [downloads page](https://sensuapp.org/downloads).

**Comment by portertech** [comment]
@cwjohnston I still like the redundancy, I don't think it should be necessary to reference link to the downloads page on the Sensu website.
