### ISSUE TITLE
FAQ isn't consistent between 5.0/1 and 5.2

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#1210]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [x] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior
FAQ versions are consistent across versions.

## Current Behavior
https://github.com/sensu/sensu-docs/blob/master/content/sensu-go/5.2/getting-started/faq.md#L33 contains the following line missing from 5.0/1:

```
[Contact the Sensu sales team][6] for a personalized demo, and see the [getting started guide][28] for more information.
```

## Possible Solution
Add the following to version 5.0/1:

```
[Contact the Sensu sales team][6] for a personalized demo, and see the [getting started guide][28] for more information.

[28]: ../enterprise
```

**Comment by apaskulin** [comment]
5.0/1 doesn't include enterprise features

**Comment by asachs01** [comment]
Haderp. Closing.
