### ISSUE TITLE
/checks API doc should describe exclusion of standalone checks

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#123]
_From @cwjohnston on November 8, 2017 21:53_

As described in https://github.com/sensu/sensu/issues/1775, the /checks API documentation does not explicitly indicate that `standalone` checks are excluded from the results returned by this endpoint.

We should explicitly document that standalone checks are not returned by /checks endpoint.

_Copied from original issue: sensu/sensu-docs#654_

**Comment by cwjohnston** [comment]
_From @mbbroberg on December 18, 2017 18:53_

@cwjohnston can you confirm this is resolved by https://github.com/sensu/sensu-docs/pull/673/commits/c8e0c434df8bee6fb812c5c196b38323a1403f60 which is pulled into #675? Thanks!

**Comment by apaskulin** [comment]
Page: https://docs.sensu.io/sensu-core/1.4/api/checks/
To do: Specify that the /checks GET endpoint does not return standalone checks

**Comment by hillaryfraley** [comment]
Similar to in go, GET returns a list of checks configured on the system. In Classic, there is a concept of checks known as "standalone"  -- if configured as standalone, they are not returned in the API response for GET
