### ISSUE TITLE
Add "version added" to Features 

### ISSUE THREAD

**Issue by Blue0ctober** [sensu/sensu-docs#1233]
Adding a `version added` field to features, api endpoints, commands, etc. This will allow for easier look up of when a certain feature or such was added to sensu-go without needing to parse through the change log or release notes. 

The goal for this addition is to be able to see from the current/latest version of the docs when something was added without having to revert to an older version of the doc to see if the feature/etc. was documented there. It will allow us to eventually move to a single version of the docs without requiring to up keep older revisions with some exceptions. 

## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior

Provide an easy way to find when a feature was added to sensu-go from the latest version of the docs. 

# Current Behavior

Requires searching through release notes and change logs for the specific feature in question

## Possible Solution

```
TCP socket        | 
------------------|------
description       | Accepts a JSON [check result][14] body and passes the event to the Sensu backend event pipeline for processing
example command   | {{< highlight shell >}}# Example using /dev/tcp
echo '{"name": "web_service01", "output": "error!", "status": 1, "handlers": ["slack"]}' > /dev/tcp/localhost/3030
```

would be

```
TCP socket        | 
------------------|------
version added     | 5.0
description       | Accepts a JSON [check result][14] body and passes the event to the Sensu backend event pipeline for processing
example command   | {{< highlight shell >}}# Example using /dev/tcp
echo '{"name": "web_service01", "output": "error!", "status": 1, "handlers": ["slack"]}' > /dev/tcp/localhost/3030
```
Or

```
version added     | 5.x
```
Or
```
version     | 5.0 and above
```

## Context

This was brought up in a discussion about looking up features for older versions of sensu if we were to collapse the versions of sensu docs to just a few versions.

**Comment by apaskulin** [comment]
I appreciate the motivations for this idea, however this would add significant complexity and cognitive overhead within the main flow of the docs.
