### ISSUE TITLE
Go Troubleshooting should describe common directory permission issues

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#1236]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior

The troubleshooting guide covers common issues related to directory permissions.

## Current Behavior

Troubleshooting doc doesn't describe the various directories where sensu-backend and other services expect to write data. 

## Context

In a number of cases we've seen operators run into issues where services won't start because `/var/lib/sensu/sensu-backend` or similar is not owned by the `sensu` user. Ideally our troubleshooting document should help to cover cases like these.

**Comment by apaskulin** [comment]
I ran into a similar issue yesterday with the Sensu agent:

```
{"component":"agent","error":"open /var/cache/sensu/sensu-agent/assets.db: permission denied","level":"fatal","msg":"error executing sensu-agent","time":"2019-02-21T22:01:04Z"}
```
