### ISSUE TITLE
Product pull-down doesn't redirect to uchiwa properly

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#1249]
## This is an issue with:

- [x] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior
Clicking on "Uchiwa" from the dropdown should take me to docs.sensu.io/uchiwa/1.0/ rather than docs.uchiwa.io

## Current Behavior
Clicking on "Uchiwa" from the dropdown takes me to docs.uchiwa.io, which is actually docs.sensu.io. 

## Possible Solution
Change the redirect.

**Comment by apaskulin** [comment]
Possible solution: Fix https://github.com/sensu/sensu-docs/blob/master/layouts/partials/productVersionDrawer.html#L40

**Comment by asachs01** [comment]
@apaskulin since we've moved Uchiwa over, maybe we can just ditch that section altogether /shrug

**Comment by apaskulin** [comment]
On the file linked above, make the same change as https://github.com/sensu/sensu-docs/commit/4f107b1c04a40b6d49a6eaee6ede956b008b993c#diff-7d6cf5841c68c68b24ab533db43c03cf
