### ISSUE TITLE
Review docs for any errors

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#125]
Found that something appears wrong in /sensu-core/0.29/reference/transport/#example-transport-definition .  Opening an issue to remind myself to comb through the docs before the soft launch.

**Comment by cwjohnston** [comment]
Please record to-dos around pre-soft-launch error checking in this comment

- [ ] Use [W3C Link Checker](https://validator.w3.org/checklink) to identify obvious breakage

**Comment by cwjohnston** [comment]
Once we've implemented #86 we should 
- [x] update links which should use `/latest` to do so
- [x] check for broken links again

And then close this issue. 👍

**Comment by asachs01** [comment]
Yeesh, this has been hanging around a while. Closing out now.
