### ISSUE TITLE
Configuration parameters for certificates should describe what the certificate is used for

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#1251]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior

Reference documentation for each parameter related to an encryption certificate describes what the certificate is used for.

## Current Behavior

Parameters related to encryption certificates in Backend and Agent references do not describe the specific use of each certificate.

## Context

We believe this will help to satisfy questions arising from folks reading through the Securing Sensu guide as well as external security reviews.

**Comment by asachs01** [comment]
@cwjohnston just for clarification, this is around the reference for security configuration flags, correct?

**Comment by cwjohnston** [comment]
@asachs01 yes, in the backend reference, any security configuration flag which relates to a SSL/TLS certificate or key needs a clear description as to which aspect of the backend (e.g. dashboard, websocket api, http api, etc) the certificate or key corresponds with.
