### ISSUE TITLE
Import platform-specific client installation instructions

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#127]
We've begun to implement client installation instructions in a single page with a pull-down to select the desired platform, but the current page only includes linux variants. 

In order to ensure this content is included and avoid pushing back the soft-launch milestone, I propose that we import existing [platform-specific pages](https://sensuapp.org/docs/latest/platforms) "as-is" with minmal changes needed to reformat them for this new site.

Once those pages are imported, I think we can revisit the single-page client installation guide to include non-linux platforms.

**Comment by asachs01** [comment]
Fixed by #131 . Closing
