### ISSUE TITLE
Change ordering of sections in Assets reference

### ISSUE THREAD

**Issue by nixwiz** [sensu/sensu-docs#1286]
In the [Assets reference](https://docs.sensu.io/sensu-go/5.2/reference/assets/), the section "Sharing on asset on Bonsai" falls right in the middle of the Assets specification sections.  I believe it should be moved.
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [X] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior

For readability,  the order for the [Assets reference](https://docs.sensu.io/sensu-go/5.2/reference/assets/) it should **not** document Bonsai right in the middle of Assets specification.
## Current Behavior

Bonsai is referenced in the middle of defining Asset specifications and seems disjointed.
## Possible Solution

If wanting to leave Bonsai in the Assets reference, at least move it down below the rest of the actual Assets documentation.
## Steps to Reproduce (for bugs)

1.
2.
3.

## Context

It seems out of place and is confusing when working serially through the Assets reference documentation.
* Browser(s) and version(s): N/A
* OS: N/A

**Comment by apaskulin** [comment]
Hi, @nixwiz! Thanks for opening this issue. Can you tell us a little more about what you mean by 
 `However, since Bonsai is not only for assets`?

**Comment by nixwiz** [comment]
Sorry, I misspoke on that.  I'll edit my initial submission.
