### ISSUE TITLE
Authorizing Bonsai to Github needs explanation of privileges required

### ISSUE THREAD

**Issue by nixwiz** [sensu/sensu-docs#1291]
When looking to authorize Sensu access to one of my Github repositories for Bonsai, I was taken aback as to the level of access it was requesting (see attached screenshot).  Given my hesitancy to grant this (yes, I understand it is revokable), I was wondering if the documentation that touches on Bonsai in the Assets reference could include this fact and a justification for needing this level of access.
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [X] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior

Being provided an explanation and reasoning for the level of access that will be needed/requested.
## Possible Solution

Provide documentation to the effect of "When authorizing Sensu access to your Github repository, it will request the following access:"  It will then spell out the requested access.  **And** it should provide reasoning for why such elevated access is needed.  Something like "Issue access is needed to allow Bonsai to submit/manage issues for your asset".  That example is an assumption, by the way, but I'd rather not assume anything.

## Steps to Reproduce (for bugs)

1.
2.
3.

## Screenshots (if appropriate):
<img width="483" alt="screen shot 2019-03-07 at 4 08 38 pm" src="https://user-images.githubusercontent.com/5530473/53998151-90147080-40f3-11e9-9497-c31355421463.png">

## Context

It is making me hesitate in adding my assets to Bonsai.
* Browser(s) and version(s): 
* OS:

**Comment by asachs01** [comment]
@nixwiz thanks for submitting this! I think there is a larger potential issue around the permissions needed. I've opened https://github.com/sensu/bonsai-asset-index/issues/117 to get some clarification on this, as I tend to agree that these seem pretty extensive.

**Comment by cwjohnston** [comment]
Closing in favor of https://github.com/sensu/bonsai-asset-index/issues/117
