### ISSUE TITLE
Document configuration for writing service logs to file on systems using journald

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#1292]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior

As an operator I can learn about configuring my Sensu installation to write logs to files on disk.

## Current Behavior

Operators must do background research on journald, syslog and logrotate.

## Possible Solution

Document process for sending logs from journald to rsyslog, and configuring rsyslog to write Sensu service logs to files in /var/log/sensu

## Context

The desire to log to a file is becoming a somewhat frequent request from a variety of users.

**Comment by cwjohnston** [comment]
Setting this up requires [configuring journald](https://www.freedesktop.org/software/systemd/man/journald.conf.html) with `ForwardToSyslog=true`

Once the messages are being sent to syslog, we can configure rsyslog (for example) to split these messages out to service-specific log files:

```
$ cat /etc/rsyslog.d/99-sensu-backend.conf
if $programname == 'sensu-backend' then {
        /var/log/sensu/sensu-backend.log
        ~
}
$ cat /etc/rsyslog.d/99-sensu-agent.conf
if $programname == 'sensu-agent' then {
        /var/log/sensu/sensu-agent.log
        ~
}
```

**Comment by rgeniesse** [comment]
And for the log rotation portion:

```
cat /etc/logrotate.d/sensu.conf
/var/log/sensu/* {
    weekly
    rotate 5
    size 100M
    compress
    delaycompress
}
```
