### ISSUE TITLE
Update content around deregistration 

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#1293]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior
Content describes configuring deregistration w/out the use of a handler

## Current Behavior
https://docs.sensu.io/sensu-core/1.7/reference/clients/#deregistration-events still notes that a handler is needed. 

## Possible Solution
Update the content

## Additional notes
I'm not quite sure what the exact working configuration is for using the built-in extension as of 1.7. It would be helpful to update the reference. Not quite sure we'd need a guide, but having 2 support requests this week on this topic might warrant one?

**Comment by cwjohnston** [comment]
We've determined that we're not actually missing the updates needed for 1.7 built-in deregistration handler, but we do need to clarify the use cases for `deregister` and `deregistration` attributes .
