### ISSUE TITLE
No mention of config.json in quick-start installation steps

### ISSUE THREAD

**Issue by carnesen** [sensu/sensu-docs#130]
Currently the installation guide instructs the user to create config files api.json, client.json etc into /etc/sensu/conf.d/. There's no mention, however, of the "main" config file /etc/sensu/config.json, which is required to exist and be valid json. I see that older versions of the installation instructions mentioned config.json, and that it's still mentioned elsewhere in the current docs, just not in the setup steps. Something like this would do the trick:

"The main Sensu configuration file /etc/sensu/config.json must exist and be valid json. Sensu also reads any json config files in the /etc/sensu/conf.d directory."

**Comment by calebhailey** [comment]
This has been addressed in a few different ways; see: 

- https://sensuapp.org/docs/latest/the-five-minute-install
- https://sensuapp.org/docs/latest/configuration

Also, I don't believe Sensu requires a config.json file to exist anymore if you prefer storing all configuration in `/etc/sensu/conf.d/`.
