### ISSUE TITLE
Round Robin checks not documented in Sensu Go

### ISSUE THREAD

**Issue by john-auld** [sensu/sensu-docs#1303]
Round robin checks are not described in the Sensu Go documentation for version 5.3.

Please add a section on that feature.

**Comment by asachs01** [comment]
@john-auld can you elaborate on what you'd like to see? The attribute is present in the checks reference document here: https://docs.sensu.io/sensu-go/5.3/reference/checks/#spec-attributes

**Comment by john-auld** [comment]
@asachs01 Thank you for adding that link. The search function on the 5.3 docs page does not find that.

I would like to see something along the lines of the guide on sensu core, but updated for Sensu Go. That would make a good guide for new users, who are starting with Sensu Go without experience of Sensu Core.

https://docs.sensu.io/sensu-core/1.1/reference/clients/#round-robin-client-subscriptions

**Comment by asachs01** [comment]
Gotcha! I think we'll also have to have some additional content under the checks reference doc.

**Comment by asachs01** [comment]
So in this case we'll need to update content in:
- [ ] sensu-go/entities #1307 
- [ ] sensu-go/checks #1306 

To mirror what we have in Core
