### ISSUE TITLE
Re-order sandbox steps in lesson 3

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#1305]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Description
This issue arises from some community feedback [here](https://sensucommunity.slack.com/archives/C9BBMSZA4/p1552505369002700). There are a couple of things in it:

- [ ] Check is created before the influxdb handler, which is confusing. Not sure if this is intended.
- [ ] Grafana may need to be updated in the sandbox since new version was released (https://github.com/sensu/sandbox/issues/47)
- [x] InfluxDB handler should use the asset (see https://github.com/sensu/sensu-docs/pull/1248)
- [x] Service verification just seems to be the "help" flag (see https://github.com/sensu/sensu-docs/pull/1304)
- [x] Once https://github.com/sensu/sensu-docs/pull/1248 is merged, get rid of Slack and InfluxDB handler pull downs in Sensu sandbox setup script (https://github.com/sensu/sandbox/pull/46)

**Comment by apaskulin** [comment]
Page: https://docs.sensu.io/sensu-go/5.4/getting-started/learn-sensu
To do: Change the order of the steps in lesson 3 to create the Influx pipeline before the check.
