### ISSUE TITLE
Update content for entities to show round_robin subscription

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#1307]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior
Related to #1306 and #1303 we have examples in core/clients reference showing `roundrobin` subscriptions. The current content should mirror that.

## Current Behavior
Presently, our docs for entities doesn't show `round_robin` as a subscription in the examples for proxy entities.

**Comment by apaskulin** [comment]
The ability to prepend `roundrobin` to a subscription name is not supported by Sensu Go. Instead, Sensu Go uses the `round_robin` check attribute to enable round-robin scheduling.
