### ISSUE TITLE
Unable to install sensu-plugin-mailer

### ISSUE THREAD

**Issue by sagarreddyg** [sensu/sensu-docs#1315]
## This is an issue with:

- [x] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Steps to Reproduce (for bugs)

1.
2.
3.

## Context

* Browser(s) and version(s): 
* OS:

**Comment by sagarreddyg** [comment]
I try to install sensu plugin mailer but it's giving error.
below is the out put.

root@ip-172-31-36-56:~# sensu-install -p mailer                                                                                                                                                  [SENSU-INSTALL] installing Sensu plugins ...                                                                                                                                                     [SENSU-INSTALL] determining if Sensu gem 'sensu-plugins-mailer' is already installed ...                                                                                                         false                                                                                                                                                                                            [SENSU-INSTALL] Sensu plugin gems to be installed: ["sensu-plugins-mailer"]                                                                                                                      [SENSU-INSTALL] installing Sensu gem 'sensu-plugins-mailer'                                                                                                                                      Building native extensions.  This could take a while...                                                                                                                                          ERROR:  Error installing sensu-plugins-mailer:                                                                                                                                                           ERROR: Failed to build gem native extension.                                                                                                                                                                                                                                                                                                                                                  current directory: /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.5/ext/unf_ext                                                                                                  /opt/sensu/embedded/bin/ruby -r ./siteconf20190317-11558-1nugefy.rb extconf.rb                                                                                                                   checking for -lstdc++... *** extconf.rb failed ***                                                                                                                                               Could not create Makefile due to some reason, probably lack of necessary                                                                                                                         libraries and/or headers.  Check the mkmf.log file for more details.  You may                                                                                                                    need configuration options.                                                                                                                                                                                                                                                                                                                                                                       Provided configuration options:                                                                                                                                                                          --with-opt-dir                                                                                                                                                                                   --with-opt-include                                                                                                                                                                               --without-opt-include=${opt-dir}/include                                                                                                                                                         --with-opt-lib                                                                                                                                                                                   --without-opt-lib=${opt-dir}/lib                                                                                                                                                                 --with-make-prog                                                                                                                                                                                 --without-make-prog                                                                                                                                                                              --srcdir=.                                                                                                                                                                                       --curdir                                                                                                                                                                                         --ruby=/opt/sensu/embedded/bin/$(RUBY_BASE_NAME)                                                                                                                                                 --with-static-libstdc++                                                                                                                                                                          --without-static-libstdc++                                                                                                                                                                       --with-stdc++lib                                                                                                                                                                                 --without-stdc++lib                                                                                                                                                                      /opt/sensu/embedded/lib/ruby/2.4.0/mkmf.rb:468:in `try_do': The compiler failed to generate an executable file. (RuntimeError)                                                                   You have to install development tools first.                                                                                                                                                             from /opt/sensu/embedded/lib/ruby/2.4.0/mkmf.rb:553:in `try_link0'                                                                                                                               from /opt/sensu/embedded/lib/ruby/2.4.0/mkmf.rb:568:in `try_link'                                                                                                                                from /opt/sensu/embedded/lib/ruby/2.4.0/mkmf.rb:786:in `try_func'                                                                                                                                from /opt/sensu/embedded/lib/ruby/2.4.0/mkmf.rb:1013:in `block in have_library'                                                                                                                  from /opt/sensu/embedded/lib/ruby/2.4.0/mkmf.rb:956:in `block in checking_for'                                                                                                                   from /opt/sensu/embedded/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpone'                                                                                                            from /opt/sensu/embedded/lib/ruby/2.4.0/mkmf.rb:321:in `open'                                                                                                                                    from /opt/sensu/embedded/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'                                                                                                                       from /opt/sensu/embedded/lib/ruby/2.4.0/mkmf.rb:321:in `open'                                                                                                                                    from /opt/sensu/embedded/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'                                                                                                                                from /opt/sensu/embedded/lib/ruby/2.4.0/mkmf.rb:955:in `checking_for'                                                                                                                            from /opt/sensu/embedded/lib/ruby/2.4.0/mkmf.rb:1008:in `have_library'                                                                                                                           from extconf.rb:6:in `'                                                                                                                                                                                                                                                                                                                                                             To see why this extension failed to compile, please check the mkmf.log which can be found here:                                                                                                                                                                                                                                                                                                     /opt/sensu/embedded/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0/unf_ext-0.0.7.5/mkmf.log                                                                                                                                                                                                                                                                                                  extconf failed, exit code 1                                                                                                                                                                                                                                                                                                                                                                       Gem files will remain installed in /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.5 for inspection.                                                                                  Results logged to /opt/sensu/embedded/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0/unf_ext-0.0.7.5/gem_make.out                                                                             [SENSU-INSTALL] failed to install Sensu gem 'sensu-plugins-mailer'                                                                                                                               [SENSU-INSTALL] you can run the sensu-install command again with --verbose for more info                                                                                                         [SENSU-INSTALL] please take note of any failure messages above                                                                                                                                   [SENSU-INSTALL] make sure you have build tools installed (e.g. gcc)                                                                                                                              [SENSU-INSTALL] trying to determine the Sensu plugin homepage for sensu-plugins-mailer ...                                                                                                       homepage: https://github.com/sensu-plugins/sensu-plugins-mailer
--

**Comment by asachs01** [comment]
Hi @sagarreddyg thanks for opening this. You're likely seeing the error due to a lack of development tools being installed on your system. You can run either `yum groupinstall "Development Tools"` or `apt-get install build-essential`. If that doesn't resolve the issue, please use either slack.sensu.io or discourse.sensu.io for further help, as we don't generally troubleshoot issues for plugin installation on our docs repo.
