### ISSUE TITLE
Docs Feedback

### ISSUE THREAD

**Issue by spykermj** [sensu/sensu-docs#1323]
Link to page: https://docs.sensu.io/sensu-go/5.3/getting-started/learn-sensu/#lesson-3-automate-event-production-with-the-sensu-agent

Did this when 155c5cbe6bf68c3e42da1f2c2882393c651c47c8 was the commit at the head of the master branch.

```
ENABLE_SENSU_SANDBOX_PORT_FORWARDING=1 vagrant up
vagrant ssh
sudo systemctl start sensu-agent
sudo yum install -y nginx && sudo systemctl start nginx
sudo sensu-install -p sensu-plugins-http
sensuctl create --file curl_timings-check.json
sensuctl asset create sensu-influxdb-handler --url "https://github.com/sensu/sensu-influxdb-handler/releases/download/3.1.2/sensu-influxdb-handler_3.1.2_linux_amd64.tar.gz" --sha512 "612c6ff9928841090c4d23bf20aaf7558e4eed8977a848cf9e2899bb13a13e7540bac2b63e324f39d9b1257bb479676bc155b24e21bf93c722b812b0f15cb3bd"
sensuctl handler list
```

### Feedback

if you follow the sensu go instructions, you end up creating an influx handler that doesn't work.

Note how the grafana dashboards do not show the http status page.

You can make this work by running these commands, but it would be much nicer to have it work correctly from the asset method.

```
wget -q -nc https://github.com/sensu/sensu-influxdb-handler/releases/download/3.1.2/sensu-influxdb-handler_3.1.2_linux_amd64.tar.gz -P /tmp/
tar xvzf /tmp/sensu-influxdb-handler_3.1.2_linux_amd64.tar.gz -C /tmp/
sudo cp /tmp/bin/sensu-influxdb-handler /usr/local/bin/
```

As a side issue, this did not produce any errors. I would expect some kind of indication that there was a problem if a specified handler could not be executed.

**Comment by apaskulin** [comment]
Hi @spykermj, thanks for this feedback! I've updated the doc to include the missing step (#1330): creating an asset and updating the Influx handler definition to include the asset. This will let Sensu download and install the asset, resulting in a working Influx handler. I've included the related portion of the doc below.

**4. Create an InfluxDB pipeline**

To create a pipeline to send metric events to InfluxDB, start by registering the [Sensu InfluxDB handler asset](https://bonsai.sensu.io/assets/sensu/sensu-influxdb-handler).

```
sensuctl asset create sensu-influxdb-handler --url "https://github.com/sensu/sensu-influxdb-handler/releases/download/3.1.2/sensu-influxdb-handler_3.1.2_linux_amd64.tar.gz" --sha512 "612c6ff9928841090c4d23bf20aaf7558e4eed8977a848cf9e2899bb13a13e7540bac2b63e324f39d9b1257bb479676bc155b24e21bf93c722b812b0f15cb3bd"
```

You should see a confirmation message from sensuctl.

```
Created
```

The `sensu-influxdb-handler` asset is now ready to use with Sensu.
You can use sensuctl to see the complete asset definition.

```
sensuctl asset info sensu-influxdb-handler --format yaml
```

Open the `influx-handler.json` handler definition provided with the sandbox, and edit the `runtime_assets` attribute to include the `sensu-influxdb-handler` asset.

```
"runtime_assets": ["sensu-influxdb-handler"]
```

Now you can use sensuctl to create the `influx-db` handler.

```
sensuctl create --file influx-handler.json
```

**Comment by spykermj** [comment]
@apaskulin, thanks for updating the document. It still doesn't work for me.

I've tried the asset create command, it did show "Created"

```
sensuctl asset info sensu-influxdb-handler --format yaml
type: Asset
api_version: core/v2
metadata:
  name: sensu-influxdb-handler
  namespace: default
spec:
  filters: []
  sha512: 612c6ff9928841090c4d23bf20aaf7558e4eed8977a848cf9e2899bb13a13e7540bac2b63e324f39d9b1257bb479676bc155b24e21bf93c722b812b0f15cb3bd
  url: https://github.com/sensu/sensu-influxdb-handler/releases/download/3.1.2/sensu-influxdb-handler_3.1.2_linux_amd64.tar.gz
sensuctl create --file influx-handler.json
sensuctl handler list
    Name      Type   Timeout   Filters   Mutator                      Execute                                                   Environment Variables                               Assets
 ─────────── ────── ───────── ───────── ───────── ──────────────────────────────────────────────── ─────────────────────────────────────────────────────────────────────────────── ────────
  influx-db   pipe         0                       RUN:  sensu-influxdb-handler --db-name 'sensu'   INFLUXDB_ADDR=http://127.0.0.1:8086,INFLUXDB_USER=sensu,INFLUXDB_PASS=sandbox
```

I managed to get it working by the wget, tar, sudo cp steps I specified, but I would love for the asset method to work. Any tips on how to troubleshoot why the asset method isn't functioning for me?

**Comment by rgeniesse** [comment]
hello @spykermj, based on your handler output, it would appear a step was skipped over. For handlers to use assets, they need to have a `runtime_assets` attribute filled out. This tells Sensu that once the handler is invoked, that something needs to be downloaded prior to it running, in this case the InfluxDB asset.

Please try the following step, which is listed in the sandbox lesson plan, then re-run the creation of the handler to see if that gets data points into InfluxDB by looking at the Grafana dashboard.

Open the `influx-handler.json` handler definition provided with the sandbox, and edit the `runtime_assets` attribute to include the `sensu-influxdb-handler` asset.
```
"runtime_assets": ["sensu-influxdb-handler"]
```
Now you can use sensuctl to create the `influx-db` handler.
```
sensuctl create --file influx-handler.json
```

**Comment by spykermj** [comment]
Thanks @rgeniesse,

That has indeed worked.

I agree that now with the updated documentation, if you follow the instructions everything works as advertized. As a result, I'm closing this ticket.
