### ISSUE TITLE
Sidebar Menu not displaying under core/changelog

### ISSUE THREAD

**Issue by Blue0ctober** [sensu/sensu-docs#133]
How to replicate:

From the main sensu-docs-site, click on `Sensu Core`, then `CHANGELOG` on the sidebar menu.  The side bar will have just the `Sensu Docs Home` link.

What we should see:

The side bar should have the complete menu for `Sensu Core`

**Comment by dabria** [comment]
Looks like it just needs version added to the front matter :)

**Comment by Blue0ctober** [comment]
🤦‍♂️ not enough coffee
