### ISSUE TITLE
Update proxy entity example to be clear on use of subscriptions

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-docs#1350]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [X] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior
Examples are clear in their attribute usage.

## Current Behavior
For proxy entities:

https://docs.sensu.io/sensu-go/5.5/reference/entities/#proxy-entities-managed

The example given has the `subscriptions` attribute listed. While this is valid and has some use cases, it can lead to confusion that this is the place to for a proxy entity to subscribe to a check.

However, the `check` and `agent` running the check on behalf of the proxy entity need to have the matching `subscription` for the check to run, then the proxy entity to be created.

## Possible Solution
- [ ] Add a note that the subscription inside a proxy entity is not used to have the entity subscribe to the check.
- [ ] Possibly add use cases for that proxy entity subscription (silencing, dashboard filtering)

**Comment by hillaryfraley** [comment]
Closed by https://github.com/sensu/sensu-docs/pull/1876
