### ISSUE TITLE
Clarify supported types for tokens

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#1353]
Page: https://docs.sensu.io/sensu-go/5.5/reference/tokens

To do: Clarify supported types for token substitution

### References

- https://github.com/sensu/sensu-docs/pull/1082
- https://github.com/sensu/sensu-go/issues/2729

**Comment by cwjohnston** [comment]
I believe it is the case that

- [x] token substitution is only supported for the `command` attribute of a check definition. 
- [x] Only Entity attributes are available for substitution
- [x] Available attributes will always have string values, e.g. values from labels and annotations.

Need verify this with eng and update the reference doc accordingly.

**Comment by hillaryfraley** [comment]
@cwjohnston I confirmed w/Simon that the three things you listed are correct.

An aside that might be good to know -- Simon said "Users might be able to do token substitution for other fields than the command attribute but I’d prefer not to document it until we have a clear use case and some tests around that"
