### ISSUE TITLE
New anonymous binding and mutual TLS options for LDAP/AD auth providers

### ISSUE THREAD

**Issue by ccressent** [sensu/sensu-docs#1368]
I've added the ability to perform LDAP anonymous bindings and mutual TLS in this PR: https://github.com/sensu/sensu-enterprise-go/pull/362.

The documentation needs to be updated to mention how to perform anonymous bindings (basically leave the binder account name and/or password blank).

The documentation needs to be updated to mention 3 new fields for the AD and LDAP authentication providers: `server.trusted_ca_file`, `server.client_cert_file` and `server.client_key_file`. A description of each of these options can be seen in the doc strings [here](https://github.com/sensu/sensu-enterprise-go/pull/362/commits/ed39a9ca971f5b248861a9d78738e897e7aa0dd3#diff-1465e7312c84ac5900ea7c1bbfcb03e5R57).

## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [X] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

**Comment by palourde** [comment]
Because I got bitten by it: in Active Directory, the `ANONYMOUS LOGON` object needs read permissions on the users & groups to be able to authenticate users with anonymous binding.
