### ISSUE TITLE
Update example log content/output

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-docs#137]
Logging examples are very outdated, it would appear that they were created when Sensu < 0.9 was in use.

**Comment by calebhailey** [comment]
Heh, we don't have any documentation on logging. Let's schedule this for the 0.24 docs.

**Comment by cwjohnston** [comment]
I think we need more context here. I'm not even clear on which documentation we are talking about updating. @portertech can you provide a link to existing section in need of updating? Maybe this issue is stale? 😑

**Comment by cwjohnston** [comment]
I think this issue is stale. Closing.
