### ISSUE TITLE
Docs Feedback

### ISSUE THREAD

**Issue by mayankkhullar** [sensu/sensu-docs#1387]
Link to page: 

### Feedback

I have installed sensu-agent on one of my server , and i can see only keepalive check is being sent to Sensu-UI not all the checks being sent and we have already all the plugins in place , Somehow I managed to reinstal lthe agents and couldn't able to resolve that issue.

All the Namespaces and users being defined correctly as we can see all stats from different namespaces.

Can you please check and respond why its not responding.

**Comment by apaskulin** [comment]
Hi @mayankkhullar, Does your agent.yml configuration file contain a `subscriptions` attribute that matches the `subscriptions` attribute in the check definitions?

For example, an agent with the following agent.yml configuration:

```
# Sensu agent configuration

subscriptions:
  - server
```

would only run checks that include the same subscription (`"subscriptions": ["server"]`) in the check definition, for example:

```
{
  "type": "CheckConfig",
  "api_version": "core/v2",
  "metadata": {
    "namespace": "default",
    "name": "example_check"
  },
  "spec": {
    "command": "example command",
    "subscriptions": ["server"],
    "interval": 10,
    "publish": true
  }
}
```

**Comment by apaskulin** [comment]
Feel free to re-open if you have additional questions!
