### ISSUE TITLE
Filtering support in sensuctl

### ISSUE THREAD

**Issue by ccressent** [sensu/sensu-docs#1395]
`sensuctl` is getting filtering support in this PR: https://github.com/sensu/sensu-go/pull/2895

The documentation needs to be updated to include these new flags. In a nutshell, all the resource types that have a `list` verb now support two additional flags: `--field-selector` and `--label-selector`. Each of them take a string, which represents a field or label filter expression respectively.

Please note that while `sensuctl` is able to construct queries that include those selectors no matter what, a backend without a valid enterprise license will reply with an error instead of applying the filters.

## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [X] New content (guide wanted)
- [X] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

**Comment by apaskulin** [comment]
List entities with the proxy_type label:
```
sensuctl entity list --namespace default --format json --label-selector 'proxy_type == switch'
```

List entities with the subscriptions field:
```
sensuctl entity list --namespace default --format json --field-selector 'switches in entity.subscriptions'
```

List entities with the proxy_type label and name field
```
sensuctl entity list --namespace default --format json --label-selector 'proxy_type == switch' --field-selector 'entity.name != switch1'
```

**Comment by apaskulin** [comment]
Selectors:
`==` (`foo == bar`)
`!=` (`foo != bar`)
`in` (`foo in (foo,bar)`)
`notin` (`foo notin (foo,bar)`)
`&&` (`foo == bar && baz != qux`)

**Comment by ccressent** [comment]
I don't think all operators work across the 2 types of selectors. For example, I think `in` and `notin` only work for field selectors. @palourde can confirm/correct me.

**Comment by palourde** [comment]
All operators are supported in both field and label selectors. For example, you could create the label `"teams": "dev,ops"` and then use something like `ops in teams`. That being said, I do expect to see `in` & `notin` used more often in field selectors with fields like subscriptions and assets.
