### ISSUE TITLE
Call out the tables in the influx integration to elaborate on what tables are generated by the integration

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#1396]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior

Have a note about the tables that are automatically generated.

## Current Behavior

We don't currently call out what tables are automatically generated, or how new tables are generated. 

## Possible Solution

Update the content with more detail around tables created.

**Comment by apaskulin** [comment]
@asachs01 Can you add a comment with the content that needs to be added?

**Comment by asachs01** [comment]
There are generic tables that will be added for annotations. Only checks with the `metric` type will have tables created for them. PR incoming
