### ISSUE TITLE
Suggested correction for docs on API /results calls

### ISSUE THREAD

**Issue by kbuchsicf** [sensu/sensu-docs#1405]
## This is an issue with:
- [X] Update (Add missing or refresh existing content)

## Expected Behavior
/results POST request actually takes other arguments, such as handlers. My coworker found this to be the case by hacking around. 

In addition, saying source is for a proxy client is too limiting. It seems to be THE way to designate the client to which the check result belongs. 

## Current Behavior
For the API /results POST request, documented here: https://docs.sensu.io/sensu-core/1.7/api/results/#results-post  lists the available options in a Blue Note section: check name, output, status, and source (used to create a proxy client).

It also says: Please see the check definition specification documentation for more information. Going to that link, the content seems to make no sense for an API-created check. It is very confusing because the format and organization are different. 

## Context
I needed to create a Check via API with a specified handler, but it didn't appear to be possible.

**Comment by apaskulin** [comment]
Hi @kbuchsicf, Thanks for submitting this feedback! We'll confirm the attributes supported by the /results POST endpoint and update the API docs.
