### ISSUE TITLE
Filter examples are not possible, should be usable

### ISSUE THREAD

**Issue by nixwiz** [sensu/sensu-docs#1408]
The examples for certain filters are not possible to use.

## This is an issue with:

- [ ] Bug (site functionality or styling)
- [X] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior

Examples in documentation should be relevant and applicable.
## Current Behavior

In reviewing the examples for filters, I found that there are two examples that just wouldn't work, the [Handling production events](https://docs.sensu.io/sensu-go/5.5/reference/filters/#handling-production-events) and [Handling non-production events](https://docs.sensu.io/sensu-go/5.5/reference/filters/#handling-non-production-events).

The reason I say they won't work is because they are filtering on namespaces, while being created in the default namespace.  Since filters and handlers are namespace specific, a filter created in a namespace (such as default in the examples), would never be called upon to filter an event and therefore an entity from a different namespace.
## Possible Solution

Should those examples be using labels, possibly?
## Steps to Reproduce (for bugs)

1.
2.
3.

## Context

* Browser(s) and version(s): 
* OS:

**Comment by apaskulin** [comment]
Hi, @nixwiz. Thanks for calling this out! You're 100% correct about these filter examples. I've opened #1425 to use labels instead of namespaces.
