### ISSUE TITLE
Improved example filter needed for handling repeated events

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#1417]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior

Documentation includes filter examples which help operators avoid alert fatigue without burdening them with repetitious configuration.

## Current Behavior

The example filter offered for handling repeated events requires an instance of the filter for every unique check interval used on the system.

## Possible Solution

Implement a filter whose logic more closely follows the implementation used by [sensu-extensions-occurrences](https://github.com/sensu/sensu-extensions-occurrences).

## Context

A number of folks in the community have asked how to implement a filter which mimics the Sensu 1.x `occurrences` filter. It seems like all the pieces are there to do it, but we need some JavaScript expertise to help us close the gap.

**Comment by nikkictl** [comment]
Calling a stop-work on developing this javascript filter until we can iron out the implementation details of the occurrences rework: https://github.com/sensu/sensu-go/issues/1766

**Comment by apaskulin** [comment]
See docs here: https://docs.sensu.io/sensu-go/5.9/reference/events/#occurrences-and-occurrences-watermark

**Comment by cwjohnston** [comment]
Since we've shipped the occurrences rework in 5.9, I think we could resume work on this effort. 

After discussing with @portertech, we're thinking it would make sense to move this ahead by extending [nixwiz/sensu-go-fatigue-check-filter](https://github.com/nixwiz/sensu-go-fatigue-check-filter/) to cover the cases that the [Core occurrences filter](https://github.com/sensu/sensu-extensions-occurrences/blob/v1.2.0/lib/sensu/extensions/occurrences.rb) handles using occurrences_watermark.

@nikkiki would you be able to pick this back up, pairing with any of the CREs as needed for testing?

If we can get our desired changes merged into that community project, Customer Reliability will work with the maintainer to get the asset on Bonsai and provide some documentation examples for using it.

Tasks:

- [x] develop and contribute enhancements to [nixwiz/sensu-go-fatigue-check-filter](https://github.com/nixwiz/sensu-go-fatigue-check-filter/) filter asset
- [x] get the filter asset published on bonsai
- [ ] write the documentation needed to help folks understand how to use this filter asset to reduce alert fatigue (PR for these changes would close this issue)

**Comment by nixwiz** [comment]
@cwjohnston [this branch of my filter](https://github.com/nixwiz/sensu-go-fatigue-check-filter/tree/use_watermark) now uses occurrences_watermark.  Does this look like at least a portion of the changes you were considering?

**Comment by asachs01** [comment]
Will update the filters ref doc + guide w/ updated examples.

**Comment by asachs01** [comment]
Closed by #1589
