### ISSUE TITLE
Resolve security alert

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#1422]
Investigate and resolve jquery security alert https://github.com/sensu/sensu-docs/network/alert/package.json/jquery/open

**Comment by rgeniesse** [comment]
The `jquery` package was first added here:

https://github.com/sensu/sensu-docs/pull/769/files

That would mean that prior to this most likely nothing needed it, not sure if JS would silently fail if there was code that did, and that we should be looking for any further JS code that was added after that uses the `jquery` package.

After that is found, come up with a test plan to upgrade it and see if the JS code continues to work as expected/site builds correctly.

**Comment by rnevius** [comment]
The npm jQuery package isn't actually used by anything. That package should be able to be safely removed from the dependency list.

**Comment by apaskulin** [comment]
To do: Open a PR that updates https://github.com/sensu/sensu-docs/blob/master/package.json to `"jquery": ">=3.4.0"` and deploy to staging
