### ISSUE TITLE
Improve API response filtering docs

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#1424]
Following an excellent first version (https://docs.sensu.io/sensu-go/5.6/api/overview/#filtering), review and clarify API filtering docs.

To do:

- [x] Collect feedback
- [x] Review https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
- [ ] Add a note in individual endpoint reference tables where filtering is available and link to API overview
- [x] Clarify use of different array syntaxes: `linux in check.subscriptions` vs. `check.namespace in [dev,production]`

User story reference:

~1. As a User, I want to filter Events by one or more Object labels to construct an Aggregate for evaluation (e.g. are >= 70% web apps up?)~ (handled in Aggregates guide/asset https://github.com/sensu/sensu-docs/pull/2162)
2. As a User, I want to filter Events by Entity
3. As a User, I want to filter Events by Check
4. As a User, I want to filter Events by Silenced
5. As a User, I want to filter Events by Severity (ok, warning, critical, unknown
6. As a User, I want a list of Events that identify an incident (check state failing)
8. As a User, I want to filter Events, Entities, and Checks by one or more subscriptions

**Comment by hillaryfraley** [comment]
Next step: Determine whether this should be a guide or added to existing API overview documentation

**Comment by hillaryfraley** [comment]
I think this information should be added into the API overview document (rather than added as a separate new doc).

Next step: find out what "collect feedback" would entail -- does it just mean asking within Sensu? Asking on Discourse? Or did Alex have another means of collecting feedback?

**Comment by hillaryfraley** [comment]
Also, when we address this issue, we should develop the Katacoda scenario at the same time: https://github.com/sensu/katacoda-scenarios/issues/11

**Comment by hillaryfraley** [comment]
To clarify:

- Filtering section says "All resources support labels within the metadata object." Does this mean all resource API endpoints should say label filtering is available as a commercial feature?
- In Sensu, are aggregates groups of checks selected by a label? (rather than a group of checks to report the mean/average of)
