### ISSUE TITLE
Adjust Documentation

### ISSUE THREAD

**Issue by mbbroberg** [sensu/sensu-docs#144]
Right before launching, we will need to: 

- [x] Adjust the language of the README after #143 
- [x] Move all the Hugo administration how-to documentation from the README.md to a better place (TBD)

Might be resolved with #90 but possibly separate.

**Comment by cwjohnston** [comment]
Adding my two cents, we want to make sure this project's README refers to https://gohugo.io/getting-started/installing or similar for installation instructions, instead of duplicating that document here.

**Comment by cwjohnston** [comment]
@mbbroberg any updates on this? #143 is merged and we removed Hugo installation comments in #157.

We may be able to completely remove comments about publishing to Heroku as that is [done automatically by Travis whenever we merge to master](https://github.com/sensu/sensu-docs-site/blob/master/.travis.yml#L9-L15).

**Comment by cwjohnston** [comment]
I am going to move details related to Hugo formatting and layouts, Heroku configuration, etc into a Wiki on this repository.

**Comment by mbbroberg** [comment]
Regarding the first checkbox: 

- We're still in need of a status update section until we're fully migrated to the new site (and old is properly deprecated) 
- The "Why Change" is still valid and could even use a word or two more to organize it

**Comment by cwjohnston** [comment]
Marking the second check box as complete following #180

**Comment by cwjohnston** [comment]
@mbbroberg is this closed by #231 ?
