### ISSUE TITLE
Add entity limit attribute to license

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#1463]
To do:
- Update license object and instructions to include a backwards-compatible entity limit attribute with a grandfathered limit of 0
- [ ] Apply to all versions

Reference:
https://github.com/sensu/sensu-enterprise-go/pull/415

**Comment by nikkictl** [comment]
Thank you for filing this! I totally forget to file a docs issue as part of the epic. Will definitely do that next time 😄
