### ISSUE TITLE
Sensu Go Checks API: Delete doesn't list 204 response

### ISSUE THREAD

**Issue by jaredledvina** [sensu/sensu-docs#1476]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior
https://docs.sensu.io/sensu-go/5.7/api/checks/#checkscheck-delete is accurate

## Current Behavior
Currently the DELETE docs in https://docs.sensu.io/sensu-go/5.7/api/checks/#checkscheck-delete list 202, 404, and 500 but then the example has 204. 

## Context
I'm currently using the Checks API and it seems that I get a 204 reponse when deleteing but, in https://docs.sensu.io/sensu-go/5.7/api/checks/#checkscheck-delete that's not listed as a return value outside of the example. 

I'm actually curious what values I should be expecting, it seems like I can 204 but should I also expect a 202? 

* Browser(s) and version(s): 
* OS: Google Chrome Version 74.0.3729.131 (Official Build) (64-bit)

**Comment by apaskulin** [comment]
Hi, @jaredledvina. Thanks for calling this out! You are correct: 204 is the correct and only response code for all DELETE endpoint. I've opened #1487 to address this. Let me know if you have any questions!

**Comment by jaredledvina** [comment]
Sweet! Works for me, thanks for fixing that up @apaskulin!
