### ISSUE TITLE
Adding Licensing troubleshooting content

### ISSUE THREAD

**Issue by Blue0ctober** [sensu/sensu-docs#1485]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior

Adding content to the troubleshooting section regarding licensing.

## Steps to Reproduce (for bugs)

1.
2.
3.

## Context

* Browser(s) and version(s): 
* OS:

**Comment by asachs01** [comment]
Closing due to https://github.com/sensu/account-manager/pull/505
