### ISSUE TITLE
For some reason, when clicking the repos.sensuapp.org/index.html link, it doesn't redirect properly

### ISSUE THREAD

**Issue by paul42** [sensu/sensu-docs#150]
When I click the link at the bottom of the packages page, Step #1 - Download and install the MSI package,  for some reason my browsers (FF 32.0.3 and chrome 38.0.2125.111 m) redirects to http://repos.sensuapp.org/ which is a massive XML file and not http://repos.sensuapp.org/index.html. when I type in index.html after the redirect it works fine?

**Comment by calebhailey** [comment]
This was resolved a long time ago. Also, please note that new "Sensu on Windows" documentation has been release with the 0.22 documentation: https://sensuapp.org/docs/latest/sensu-on-microsoft-windows
