### ISSUE TITLE
Site code toggler moves the page up/down in some uses of it

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-docs#1504]
## This is an issue with:

- [X] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior
When toggling between code, in this case YML or JSON, the page should remain in same position.

Example of expected behavior:
https://docs.sensu.io/sensu-go/5.9/reference/filters/#built-in-filter-only-incidents

## Current Behavior
In some instances, using the code toggle is causing the page to scroll up or down, which can lead to a confusing user experience.

Example:
https://docs.sensu.io/sensu-go/5.9/reference/filters/#built-in-filter-allow-silencing

![2019-05-30 08 57 35](https://user-images.githubusercontent.com/19964713/58646189-be9c8480-82b9-11e9-9510-0df1ac5139b3.gif)

## Possible Solution
I have none to offer as front end is mostly a mystery to me.

## Steps to Reproduce (for bugs)
See gif above!

## Screenshots (if appropriate):
See gif above!

## Context

* Browser(s) and version(s): Chrome  74.0.3729.169.
* OS: OSX 10.14.5

**Comment by apaskulin** [comment]
This is likely due to to having multiple code samples on a page, so that when they are all switched between YML and JSON, they take up more or less space and the size of the content above the current place on the page increases or decreases. Possible solution: Make language toggle boxes the maximum size required by the largest code sample.

**Comment by apaskulin** [comment]
@rgeniesse I'd suggest closing this issue since we haven't had any complaints about this behavior.

**Comment by hillaryfraley** [comment]
Ask Ryan how much effort this might be to fix (if a fix is possible)

**Comment by hillaryfraley** [comment]
@rnevius looks like this happens because length can be substantially different for YAML and JSON, so switching back and forth can shorten or lengthen the page.

Is it possible to fix this? If so, can you estimate the effort it would require?

**Comment by rnevius** [comment]
@hillaryfraley yeah. While we could probably do what was mentioned above, I think it would be nicer to use JavaScript to immediately scroll the page to the proper position after clicking the toggle. I'm not sure if there would be a veeeery brief flash of content while this happened (there may not be)...but it would be easy to test.

**Comment by hillaryfraley** [comment]
@rnevius would the JS solution affect how the code appears in the PDFs of the docs?

**Comment by rnevius** [comment]
@hillaryfraley no, no JavaScript runs in the offline layouts.

**Comment by cwjohnston** [comment]
@hillaryfraley @rnevius if the JS solution is easy to test I say let's go for it. 👍

**Comment by rnevius** [comment]
Will test!
