### ISSUE TITLE
Address sshpk security alert

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#1513]
Context: https://github.com/sensu/sensu-docs/network/alert/yarn.lock/sshpk/open

sshpk seems to be a dependency of http-signature@~1.2.0" --> request@^2.60.0 --> hugo-cli@^0.5.4. Looks like `request` was replaced with `got` in hugo-cli v0.9.0 (https://github.com/nikku/hugo-cli/commit/7847091ac0c65dde25f9e4d3b5a401a5126e867b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2). Do you think it would be feasible to upgrade hugo-cli to 0.9.0 or even the latest, 0.10.0?

**Comment by cwjohnston** [comment]
Upon reviewing the hugo-cli changelog, this seems reasonable to me. If upgrading the module breaks anything, I expect we'll know right away via CI.
