### ISSUE TITLE
Docs Feedback

### ISSUE THREAD

**Issue by 1508amit** [sensu/sensu-docs#1524]
Error: unable to authenticate with error: Get http://localhost:8080/auth: dial tcp 127.0.0.1:8080: connect: connection refused

I am getting this  above error after running **sensuctl configure** 

$ sensuctl configure
? Sensu Backend URL: http://localhost:8080
? Username: admin
? Password: *********
? Namespace: default
? Preferred output format: tabular

Error: unable to authenticate with error: Get http://localhost:8080/auth: dial tcp 127.0.0.1:8080: connect: connection refused

**Comment by asachs01** [comment]
Hi @1508amit , 

Thanks for reaching out. While we'd love to help, the docs repo is generally for issues related to documentation and function of the site, not deployment issues. We advise either messaging in http://slack.sensu.io or on discourse.sensu.io
