### ISSUE TITLE
logging  sensu logs to /var/log/sensu not working on ubuntu [Sensu service logging with systemd]

### ISSUE THREAD

**Issue by kumareshan11** [sensu/sensu-docs#1533]
I have followed the below official document to redirect logs to /var/log/sensu directory 
https://docs.sensu.io/sensu-go/5.9/guides/systemd-logs/
but above step not working on my ubuntu nodes 

## This is an issue with:

logging with /var/log/sensu not wokring on ubuntu 

 
## Current Behavior
Logs still appearing on /var/log/syslog 

## Possible Solution
 sensu logs should be logging on /var/log/sensu/

## Steps to Reproduce (for bugs)
 
1.:~# cat  /etc/systemd/journald.conf 
[Journal]
ForwardToSyslog=yes

2.:~# cat /etc/rsyslog.d/99-sensu-agent.conf
if $programname == 'sensu-agent' then {
        /var/log/sensu/sensu-agent.log
        ~
}
3.
systemctl restart systemd-journald
systemctl restart rsyslog

/var/log/syslog filled with sensu logs 

* Browser(s) and version(s): 
* OS: "Ubuntu 18.04.1 LTS"
Sensu Version : ~# sensu-agent version
sensu-agent version 5.7.0#87a4066, build 87a4066ab68f5eabf666236c8dc2681563fa01c4, built 2019-05-08T19:11:52Z

**Comment by asachs01** [comment]
Hi @kumareshan11 thank you for opening this. 

From what I can tell in `/var/log/syslog`, this appears to be permissions related. 

```
# grep -i permission syslog
Jun 12 13:21:37 ubuntu-bionic rsyslogd: file '/var/log/sensu/sensu-backend.log': open error: Permission denied [v8.32.0 try http://www.rsyslog.com/e/2433 ]
Jun 12 13:26:56 ubuntu-bionic rsyslogd: file '/var/log/sensu/sensu-backend.log': open error: Permission denied [v8.32.0 try http://www.rsyslog.com/e/2433 ]
Jun 12 13:31:56 ubuntu-bionic rsyslogd: file '/var/log/sensu/sensu-backend.log': open error: Permission denied [v8.32.0 try http://www.rsyslog.com/e/2433 ]
```

Can provide the output of  `grep -i permission /var/log/syslog` to confirm that you're seeing the same? 

Can you also please provide the output of `ls -al /var/log`?

**Comment by asachs01** [comment]
@kumareshan11 fwiw, I've changed the permissions on `/var/log/sensu` to use `syslog:adm` as the user and now see that I have log files showing up.

**Comment by kumareshan11** [comment]
@asachs01 Thanks for pointing outing exact solution, you're right it was permission issue with /var/ log/sensu. it's totally working after i set permission to syslog.

**Comment by kumareshan11** [comment]
@asachs01  Following up on this, I see logs are getting updated on /var/log/sensu/sensu-agent.log but at the same time sensu logs still getting update in /var/log/syslog. seems i missed something

**Comment by hillaryfraley** [comment]
Next step: requires some more investigation.

**Comment by cwjohnston** [comment]
As I understand it, this issue was reopened because our suggested configuration results in log messages being written to both the intended service-specific log file and the more general system log file.

After a bit of searching around, I'm seeing solutions like [this one](https://askubuntu.com/questions/186592/how-do-i-configure-rsyslog-to-send-logs-from-a-specific-program-to-a-remote-sysl) suggest the use of an ampersand (`&`) between the log file path and the `~` directive. I suspect that the lack of an ampersand in our suggested configuration is causing logs to be written to both files.

**Comment by tannerwilliams** [comment]
For anyone else who comes across this, I worked around the logs being written to both locations by renaming the conf file to `00-sensu-agent.conf` to make sure it was loaded before the default file in `/etc/rsyslog.d/`. Using just the `~` after the log path worked fine like this as well.

**Comment by hillaryfraley** [comment]
We will revisit the suggestion from @tannerwilliams

**Comment by hillaryfraley** [comment]
See https://serverfault.com/questions/541362/rsyslog-relp-preventing-remote-logs-from-being-written-to-my-local-var-log/862045#862045 for info about adding the `&`

**Comment by hillaryfraley** [comment]
Change `~` to `& stop`

Make filename `40` and add note -- on Ubuntu 18.04, use a file name that will ensure the file is loaded before the default 50.

**Comment by hillaryfraley** [comment]
Docs are updated with the fix!

@kumareshan11 thank you for raising this issue. @tannerwilliams thank you for posting your solution.
