### ISSUE TITLE
Suggestion - Provide more detail and an example for filter assets in the docs. 

### ISSUE THREAD

**Issue by annaplotkin** [sensu/sensu-docs#1541]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [X ] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior
A contextual and detailed explanation of how filter assets are beneficial with an example of it solving a use case. 

## Current Behavior
Current filter asset paragraph:

Sensu filters can have assets that are included in their execution context. When valid assets are associated with a filter, Sensu evaluates any files it finds that have a “.js” extension before executing a filter. The result of evaluating the scripts is cached for a given asset set, for the sake of performance.

## Steps to Reproduce (for bugs)

1.
2.
3.

## Context

* Browser(s) and version(s): 
* OS:

**Comment by apaskulin** [comment]
Might be addressed by #1589

**Comment by asachs01** [comment]
Closing as we believe #1589 solves this. If not, let us know @annaplotkin
