### ISSUE TITLE
Clarify client `deregister` and `registration` are not mutually exclusive

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#155]
This issue was recorded by me in a Trello board but, as I didn't leave sufficient context there, I'm honestly not quite sure the specific problem this is trying to solve. 

Perhaps we just need a note indicating that clients may specify either `deregister` or `registration` attributes, both or neither.

**Comment by hillaryfraley** [comment]
Pending EOL: won't fix
