### ISSUE TITLE
Add Intercom chat to the Sensu Go sandbox page

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#1569]
The Sensu sales team has requested that we add Intercom chat functionality to only the Sensu Go sandbox page in the docs.

To do:

- [ ] Evaluate implementation complexity and impact to maintainability as a result of adding Intercom to a single page within the docs site.
- [ ] Confirm that we can implement Intercom in the least intrusive way, so that the chat window never pops up on its own and is only activated when a user clicks on it.
- [ ] Add Intercom to https://docs.sensu.io/sensu-go/x.x/getting-started/learn-sensu/ for all versions
- [ ] Test and validate

**Comment by hillaryfraley** [comment]
Next step: @cwjohnston will find out if this is still something Sales wants to add

**Comment by hillaryfraley** [comment]
Zoom w/Iryna re: Intercom setup. Here's the process:

1. Add code in body tags at the top of the page ([installation steps](https://developers.intercom.com/installing-intercom/docs/basic-javascript)).
2. Work w/Iryna to configure on-page placement and what the chat window should contain.
3. Test chat window configuration and adjust as needed.
