### ISSUE TITLE
Resolve security alerts

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#1586]
Context: https://github.com/sensu/sensu-docs/network/alerts

### To do

Investigate and resolve security alerts for:

- [underscore.string](https://github.com/sensu/sensu-docs/network/alert/yarn.lock/underscore.string/open)
- [js-yaml](https://github.com/sensu/sensu-docs/network/alert/yarn.lock/js-yaml/open)
- [lodash](https://github.com/sensu/sensu-docs/network/alert/yarn.lock/lodash/open)
- [string](https://github.com/sensu/sensu-docs/network/alert/yarn.lock/string/open)

**Comment by cwjohnston** [comment]
All alerts are now resolved ✅
