### ISSUE TITLE
EOL phase 1: 12/31/2019

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#1615]
On 12/13/2019:

- [x] 1 Remove Uchiwa and Sensu Core from the navigation page, replacing with Bonsai and Discourse. To do this, we'll need to rework the index.html layout to specify product tiles manually instead of pulling from the config: [drop-in example](https://gist.github.com/apaskulin/13ad6bfd1aafe8cf9093b0b4cd82abfe)
- [x] 2 Update landing pages (docs.sensu.io/sensu-core/x.x/ and docs.sensu.io/uchiwa/1.0/) and notification bar (layouts/partials/eolSection) to reflect official EOL status. 
- [x] 3 Verify that https://github.com/sensu/sensu/blob/master/README.md and https://github.com/sensu/uchiwa/blob/master/README.md are updated to reflect official EOL status.
- [x] 4 Remove Sensu Core from sensu.io/downloads
- [x] 5 Update installation documentation to use new host name listed in https://discourse.sensu.io/t/action-required-upcoming-changes-to-sensu-1-x-package-repository-configuration/1433

**Comment by hillaryfraley** [comment]
Jan 6 is the date for host changes described in https://discourse.sensu.io/t/action-required-upcoming-changes-to-sensu-1-x-package-repository-configuration/1433

**Comment by hillaryfraley** [comment]
5 - Installation documentation changed in https://github.com/sensu/sensu-docs/pull/1915
