### ISSUE TITLE
Update tar & zip artifact names

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#1620]
Reference: https://github.com/sensu/sensu-enterprise-go/pull/596

To do: Replace `sensu-enterprise-go` with `sensu-go` in all tar and zip artifact names

**Comment by Blue0ctober** [comment]
@amdprophet is this for only 5.12 and above or all versions of sensu-enterprise-go?

**Comment by amdprophet** [comment]
Only 5.12 and above.
