### ISSUE TITLE
Update events API docs

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#1621]
Reference: https://github.com/sensu/sensu-go/pull/3155

To do:

- [ ] Update events API docs
- [ ] Update all sandbox lessons and Katacoda scenarios

**Comment by hillaryfraley** [comment]
I think this is done via https://github.com/sensu/sensu-docs/issues/1680?

**Comment by hillaryfraley** [comment]
- [x] Test removal of namespace in required example under https://docs.sensu.io/sensu-go/5.15/api/events/#eventsentitycheck-put-parameters
- [x] If test returns as expected (example returns response that includes namespace 'default'), remove namespace in required example under https://docs.sensu.io/sensu-go/5.15/api/events/#eventsentitycheck-put-parameters
- [ ] If test returns as expected, remove namespace in step 2, 3, and 4 of sandbox Katacoda scenario and re-test scenario

**Comment by hillaryfraley** [comment]
See https://github.com/sensu/katacoda-scenarios/pull/56

**Comment by hillaryfraley** [comment]
PR in progress: https://github.com/sensu/sensu-docs/pull/1995
