### ISSUE TITLE
Document logging redaction changes

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-docs#1623]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Possible Solution
Add a note to the [redact flag](https://docs.sensu.io/sensu-go/5.11/reference/agent/#security-configuration-flags) for transparency. `Redacted secrets are sent via the websocket connection and are stored in etcd. They are not logged nor displayed via the Sensu API.`

> List of fields to redact when logging and sending keepalives

should become:

> List of fields to redact when displaying the entity

## Context
https://github.com/sensu/sensu-go/pull/3159

**Comment by cwjohnston** [comment]
@nikkixdev does this clarification apply to all versions of Sensu Go, or only 5.12 and later?

**Comment by nikkictl** [comment]
Only 5.12 and later where protobuf serialization is introduced.
