### ISSUE TITLE
EOL phase 2: 3/31/2020

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#1625]
On 3/31/2020:

- [x] 1 Remove Sensu Enterprise and Sensu Enterprise Dashboard from the navigation page, replacing with Interactive Tutorials and Resource Library. To do this, we'll need to rework the index.html layout to specify product tiles manually instead of pulling from the config: [drop-in example started here](https://gist.github.com/hillaryfraley/a98dd3e7ec3dd453cc1798b11ed14f66)
- [x] 2 Update landing pages (docs.sensu.io/sensu-enterprise/x.x/ and docs.sensu.io/sensu-enterprise-dashboard/x.x/) and notification bar (layouts/partials/eolSection) to reflect official EOL status. 
- [x] 3 Verify that https://github.com/sensu/sensu-enterprise/blob/master/README.md and https://github.com/sensu/sensu-enterprise-dashboard/blob/master/README.md are updated to reflect official EOL status.
~- [ ] 4 Update installation documentation to use new host name listed in https://discourse.sensu.io/t/action-required-upcoming-changes-to-sensu-1-x-package-repository-configuration/1433~

**Comment by hillaryfraley** [comment]
May need a separate ticket to track tasks for complete removal of Core and Enterprise docs from docs.sensu.io site. Include these tasks:

- [ ] Duplicate content from /sensu-enterprise/3.6/migration to /sensu-core/1.8/enterprise-eol. Include a note that historical docs for enterprise products can be found on GitHub in the docs repo.
- [ ] Redirect all Sensu Enterprise and Sensu Enterprise Dashboard content to /sensu-core/1.8/enterprise-eol using static.json.
- [ ] Remove Sensu Enterprise and Sensu Enterprise Dashboard from config.toml, static.json, and footer_js.html.
- [x] Remove Sensu Enterprise and Sensu Enterprise Dashboard from the index.html layout, replacing those tiles with important things we want to highlight.
- [x] Transfer https://docs.sensu.io/sensu-core/1.8/migration/ content from Core to Go docs.

**Comment by hillaryfraley** [comment]
Repo PRs:
- https://github.com/sensu/sensu-enterprise/pull/444
- https://github.com/sensu/sensu-enterprise-dashboard/pull/147

**Comment by hillaryfraley** [comment]
Other related issues:

- https://github.com/sensu/sensu-docs/issues/2338
