### ISSUE TITLE
Hyperlinked elements in SVG diagrams

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#1643]
### User story

As a reader of the docs, I would like to be able to click on individual elements within a diagram to navigate to a page with more information about that element.

### Context

In Lucidchart, you can assign a hyperlink to individual elements. These in-diagram links are persisted when the diagram is exported as an SVG. I've observed that in-diagram links work in the docs site when viewing the diagram by itself (docs.sensu.io/images/...), but not within a docs page.

### To do

- [ ] Create a diagram in Lucidchart that uses a hyperlinked element and export as an SVG
- [ ] Use the SVG in a docs page and get the link to works

**Comment by hillaryfraley** [comment]
We are no longer using SVGs in the docs.
