### ISSUE TITLE
Sensu Enterprise Dashboard "overview" page duplicates "index" and "configuration" content

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#165]
Figure out where this content should live and deduplicate it! 2⃣ ▶️1⃣

**Comment by asachs01** [comment]
@cwjohnston can you confirm that you're still seeing duplicated content? I'm not seeing it in the docs.

**Comment by cwjohnston** [comment]
I'm still seeing the duplication, specifically:

When I hit https://docs.sensu.io/sensu-enterprise-dashboard/latest/ I see:

* What is the Sensu Enterprise Dashboard?
* What is Uchiwa?
* What is the Sensu Enterprise Console?

These same headings and content are present at https://docs.sensu.io/sensu-enterprise-dashboard/latest/dashboard/, but this page includes a specification for number of configuration attributes as well. 

I think the attributes should move to https://docs.sensu.io/sensu-enterprise-dashboard/latest/configuration/ and the "/sensu-enterprise-dashboard/overview" (/latest/dashboard) section can be removed in favor of the remaining content living on the root or index page of /sensu-enterprise-dashboard/latest/
