### ISSUE TITLE
Document asset delete

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-docs#1658]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior
- [Asset API docs](https://docs.sensu.io/sensu-go/5.11/api/assets/) contains `/assets DELETE`.
- [Asset Reference](https://docs.sensu.io/sensu-go/5.11/reference/assets/) contains a subsection about deleting assets.
- **Notes to include in API and Reference docs:** Deleting an asset via the API or sensuctl will _only_ delete the asset resource within Sensu. Deleting an asset **will not** remove the tarball or downloaded files from disk. It is the operators responsibility to clear the asset cache if necessary. Deleting an asset **will not** remove references to said asset. It is the operators responsibility to remove the asset from the `runtime_assets` field of the check, hook, filter, mutator, or handler. These dependent resources will likely fail to run until the respective configs are updated (ex. `sh: asset.sh: command not found`). Check and hook failures will be surfaced in the event data, whereas mutator, handler and filter failures will only be surfaced in the backend logs.

## Context
https://github.com/sensu/sensu-go/pull/3185

**Comment by asachs01** [comment]
@nikkixdev just confirming here that the API endpoint is `/assets (DELETE)`, and not `/assets/:asset (DELETE)`

**Comment by nikkictl** [comment]
@asachs01 It's `/assets/:asset DELETE`.
