### ISSUE TITLE
Search indexing is not documented

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#166]
I've noticed that the search doesn't return as many results as I expect. The readme states

> Search was added through lunr js. The search code lives in /static/javascripts/application.js and the action of creating the index occurs in the /Gruntfile.

This leads me to believe we're storing a search index which should be regenerated periodically, if not with every deploy. I'm attempting to write up the process of rebuilding the index so we can figure out the automation but I am running into an error. 

Here's what I have so far:

```
$ brew install grunt-cli
...
$ npm install
...
$ grunt lunr-index
Running "lunr-index" task
Build pages index
Index pages -> process file -> process based on type
Inside indexPages function
Inside processFile function
Inside processMDFile function
Front matter failed: Cannot read property 'trim' of undefined
Warning: Cannot read property 'title' of undefined Use --force to continue.

Aborted due to warnings.
```

@dabria any ideas on this error or additional notes you can share that will help me along?

**Comment by cwjohnston** [comment]
Turns out this failure is related to the presence of `.DS_Store` files in my local copy. The `processMDFile` function defined in Gruntfile.js needs to do a better job of ignoring files that aren't markdown.

**Comment by grepory** [comment]
#182 partially addresses this. I'm looking into ways to automate generation of lunr-index now.
