### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by bananabele** [sensu/sensu-docs#1661]
Link to page: 
This is a 404: https://docs.sensu.io/sensu-go/5.11/guide/
referred from https://docs.sensu.io/sensu-go/5.11/guide/contact-routing
### Feedback

**Comment by apaskulin** [comment]
This is a bit of a mystery: https://docs.sensu.io/sensu-go/5.11/guide/contact-routing does not exist (correct URL has plural: "guides"). I've searched the docs for instances of URLs with the /guide (singular), but haven't found anything. I'm not sure how Moz is finding this URL, but I've confirmed that all the links in the contact routing guide work.

**Comment by apaskulin** [comment]
Closing for now, but feel free to reopen if this pops up again!

**Comment by apaskulin** [comment]
Found it!
