### ISSUE TITLE
Sidebar missing from local server

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#1663]
## Expected Behavior

Running `yarn run server` results in the site rendering correctly.

## Current Behavior

When running `yarn run server`, the sidebar is missing from the site. Using `yarn run server --disableFastRender` fixes this.

## Possible Solution

Either fix the bug so --disableFastRender is not required or update the contributing instructions.

## Context

Appeared following #1641

**Comment by rnevius** [comment]
This should be a one-time occurrence, following the recent Hugo upgrade. I think the best path forward will be to enable the `--disableFastRender` flag by default, in development.
