### ISSUE TITLE
Document API changes for Event and Entity creation

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#1680]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Context

https://github.com/sensu/sensu-go/pull/3155/ introduces the following changes

* Event and Entity resources can now be created without an explicit namespace; the system will refer to the namespace in the URL.
* Events and Entities can now be created with the POST verb.

The API reference should be updated to reflect them.

**Comment by asachs01** [comment]
per review w/ @cwjohnston , looks like I need to get rid of the change in the `entities` ref doc

**Comment by asachs01** [comment]
Need to add `/events (PUT)`
