### ISSUE TITLE
Add documentation for OIDC authentication provider

### ISSUE THREAD

**Issue by ccressent** [sensu/sensu-docs#1689]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [X] New content (guide wanted)
- [X] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

We can probably reuse a lot of the [relevant Sensu Enterprise Dashboard](https://docs.sensu.io/sensu-enterprise-dashboard/2.16/rbac/rbac-for-oidc/) documentation!

**Comment by asachs01** [comment]
Closed by #1694
