### ISSUE TITLE
Demo Site should be configured with TLS/SSL

### ISSUE THREAD

**Issue by majormoses** [sensu/sensu-docs#1699]
Link to page: https://docs.sensu.io/sensu-go/5.11/getting-started/demo/

### Feedback

While the username and password for the `guest` user are on the page and accessible to anyone it sets a bad precedence to have a site where you input credentials with platintext transmission. There are multiple options these days for free SSL certs with little to no overhead/cost:
- AWS ACM, pretty sure most major cloud providers have a similar service
- Letsencrypt
- Cloudflare (would still need a cert to allow CF and your origin to remain secure when communicating)

**Comment by rgeniesse** [comment]
@majormoses thanks for opening this. The demo site described on that page is actually something I work directly with so I'll get that addressed rather than @jspaleta.

I was leaning towards using Letsencrypt, but might take a peak at AWS ACM as well.
