### ISSUE TITLE
Update troubleshooting re: cluster issues

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#1702]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior

In our (Sensu's) troubleshooting efforts with multiple customers, we've run into the need to describe how to troubleshoot cluster issues (e.g., stopping cluster members and removing `/var/lib/sensu/etcd` and restarting). This should be present in the troubleshooting doc.

## Current Behavior

Currently, this isn't present and is a fairly common issue that folks run across. 

## Scoping

* Needs to ensure that we're following recommended best practices for etcd cluster troublshooting
* Ensure that we address that this is a destructive action
* Could also include the new `dump` feature and discuss reimporting data, though this may be a separate issue to track/write

**Comment by cwjohnston** [comment]
@asachs01 let's clarify the scope on this a bit: we should describe the conditions under which folks may need to reset their cluster, how to do it, and link to etcd cluster maintenance documentation for most other operations

**Comment by hillaryfraley** [comment]
@asachs01 to sketch an outline and add link here

**Comment by hillaryfraley** [comment]
If https://github.com/sensu/sensu-docs/pull/2805 does not already address this issue, we should update the PR so that it does.

edit: disregard - we decided to address the different troubleshooting issues in individual PRs.

**Comment by hillaryfraley** [comment]
Discussed with Cameron -- we can resolve this issue by adding "starting over" instructions to the troubleshooting guide. When you need to redeploy your Sensu instance from scratch, how should you go about it?
