### ISSUE TITLE
Aggregate checks

### ISSUE THREAD

**Issue by daharon** [sensu/sensu-docs#171]
I see aggregate checks mentioned [here](https://github.com/sensu/sensu-docs/blob/master/source/docs/0.16/api_aggregates.md) and [here](https://github.com/sensu/sensu-docs/blob/master/source/docs/0.16/checks.md#aggregate-checks-aggregate-checks).
However, the deffinition of an aggregate check is never given.
Why would I want to create an aggregate check?
How does an aggregate check differ from a standard check?

**Comment by calebhailey** [comment]
This has still never really been explained very well, unless you're willing to dig through the Sensu code. I'm tagging this for the 0.24 documentation.

**Comment by calebhailey** [comment]
This was resolved with the 0.24 release (along with a major overhaul of Sensu aggregates). See: https://sensuapp.org/docs/0.25/reference/aggregates.html
