### ISSUE TITLE
Add asset add and asset outdate to quickstart

### ISSUE THREAD

**Issue by Blue0ctober** [sensu/sensu-docs#1729]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior

Add a section in the sensuctl quickstart section on using `sensuctl asset add` to add a bonsai asset. 

This content might need to be placed in a different section or reference section. 

See https://github.com/sensu/sensu-docs/issues/1728
## Steps to Reproduce (for bugs)

1.
2.
3.

## Context

* Browser(s) and version(s): 
* OS:

**Comment by cwjohnston** [comment]
We have this documented in the [sensuctl reference](https://docs.sensu.io/sensu-go/5.14/sensuctl/reference/#interacting-with-bonsai), which might be sufficient for this need.

@Blue0ctober please review your notes and determine whether we can close this.

**Comment by hillaryfraley** [comment]
Closed in https://github.com/sensu/sensu-docs/pull/1734
