### ISSUE TITLE
Accessibility review of the docs site

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#173]
We should definitely ensure that the docs are more accessible to members of the community/customers who may be hearing/sight-impaired. This feels like a baseline sort of thing, but should also be incorporated into the new docs site.

**Comment by obfuscurity** [comment]
Discussed this with @apaskulin. This feels a bit vague; it could be _either_ a site issue (e.g. styling) or a content issue (e.g. alt text), so let's rescope this issue to be an *audit* of our accessibility features and needs.

**Comment by asachs01** [comment]
Of particular interest here:
* Ensuring that our colors are friendly to folks who might have some sort of color-blindness
* Ensuring alt text for images is accurate

**Comment by hillaryfraley** [comment]
Review complete: https://app.asana.com/0/1201099774497750/1203015383595657/f

Relevant issues:
- https://github.com/sensu/sensu-docs/issues/4089
- https://github.com/sensu/sensu-docs/issues/4092
- https://github.com/sensu/sensu-docs/issues/4098
- https://github.com/sensu/sensu-docs/issues/4107
- https://github.com/sensu/sensu-docs/issues/4108
- https://github.com/sensu/sensu-docs/issues/4121
