### ISSUE TITLE
Expand "Guides" content with more "How-to's"

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#174]
This is sort of a stop-gap measure in lieu of creating yet-another-site for KB-type articles. I see us splitting out the content by platform (e.g., API, Dashboard, Core, Enterprise) and expanding on the examples that we already have in the docs. The idea would be that the examples launch into something much more detailed, outlines possible use cases, etc.

**Comment by cwjohnston** [comment]
Closing this as it represents a current and ongoing effort that may never be "done" 😉
