### ISSUE TITLE
Document the Sensu Go transport? 

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-docs#1748]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior

It would be helpful to document how Sensu Go's built-in transport works (i.e. "TLS encrypted websockets"). 

In Sensu 1.x we had a dedicated reference document for this because the transport was external and had a dedicated configuration scope (`"transport": {}`). In Sensu Go the transport can still be configured (e.g. using self-signed certificates, etc), but it doesn't necessarily have a dedicated configuration scope, so it's unclear to me if it deserves its own reference documentation page. 

## Current Behavior

Information about the Sensu Go transport (e.g. what it is) and how to configure it already exists, but it's quite scattered around the documentation: 

- https://docs.sensu.io/sensu-go/5.13/installation/install-sensu/#architecture-overview
- https://docs.sensu.io/sensu-go/5.13/guides/securing-sensu/ 

...But there's no information about the transport mechanism in the reference documentation for the service that provides it (the backend): https://docs.sensu.io/sensu-go/5.13/reference/backend/ 

## Possible Solution

It would be helpful to pull all of this together somehow - either in the backend reference docs, or a new/dedicated transport reference document - including "here's what the Sensu transport mechanism is", and "here's how it works" (arch diagram), and "here's how it's configured by default" (minimal security), and "here's how to configure/secure it" (reference docs + link to guide(s)).  

## Steps to Reproduce (for bugs)

n/a

## Screenshots (if appropriate):

n/a

## Context

* Browser(s) and version(s): 
* OS:

**Comment by hillaryfraley** [comment]
Next step: Gather existing info in the docs here in a comment on this issue.
More: https://sensucommunity.slack.com/archives/C67TT2E6Q/p1575563273065700

**Comment by hillaryfraley** [comment]
This issue may be addressed by our [Generate Certificates guide](https://docs.sensu.io/sensu-go/latest/guides/generate-certificates/) and the [mTLS section of our Secure Sensu guide](https://docs.sensu.io/sensu-go/latest/guides/securing-sensu/#sensu-agent-mtls-authentication), although the issue comments indicate that we should consider having a single document to cover this.
This issue might also overlap with https://github.com/sensu/sensu-docs/issues/2272.

**Comment by hillaryfraley** [comment]
Sensu Go transport has little for users to configure or manage, so a separate document may not be necessary. This fits into the Secure Sensu document, as well as a "what is Sensu" overview (agent connects to backend but that's it; it's a websocket connection and it can be secured with TLS and mTLS). The Sensu Go transport technology may be more familiar to users today -- although there are a couple layers of protocols, the technology we're using in the Sensu Go transport is probably more familiar and less confusing to users today.

Perhaps a section in the agent reference?

**Comment by cwjohnston** [comment]
@hillaryfraley I think we should revisit this issue and at least add some content to the agent reference describing how the agent handles connection failures.

Given one or more working backends and an agent configured with a corresponding list of `backend-urls`, we assume the following behavior:

1. On startup, Sensu-agent shuffles the list of `backend-urls`
2. Agent attempts to connect to the first URL in the shuffled list
3. If a websocket connection is not established with the backend prior to the period specified via `backend-handshake-timeout`, the agent will abandon the current connection attempt and try the next URL in the list, retrying until successfully connected
5. Assuming a websocket connection is established before the `backend-handshake-timeout` is reached, the agent will send a heartbeat message to the backend at an interval configured via the `backend-heartbeat-interval`. 
6. For every heartbeat sent by the agent, the agent expects the backend to send a heartbeat response within the period configured via the `backend-heartbeat-timeout`. If the backend does not respond within this period, the agent will close the connection and attempt a connection to the next backend URL in the list
7. Agent will continue iterating over the list of backend URLs, attempting connections until successfully connected.

Above description does not account for other types of socket errors, e.g. unexpectedly closed connection, TLS handshake failures, etc. but the general expectation is that Sensu-agent will keep retrying connections to the configured backend-urls until it is successfully connected or the process is stopped.

Also note that websocket heartbeat and sensu-agent keepalive are two different things with a similar purpose. Per @echlebek:

> The heartbeat and heartbeat timeouts are configuration for the websocket connection keepalive.
> Sensu keepalive is more fluid and permits agents to reconnect any number of times within its timeout. As long as the agent can successfully send one event to any backend, the keepalive [watcher?] gets reset.
