### ISSUE TITLE
Add documentation for the platform selector

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#175]
It's unclear to me how the selector functions in the site as a whole. For example, we've introduced some 404's when removing the platform selector from the "client installation" page (see https://validator.w3.org/checklink?uri=sensu-docs-site.herokuapp.com&hide_redirects=on&hide_type=all&recursive=on&depth=3&check=Check ) There doesn't seem to be a way of bypassing it while we hammer out the issues with adding additional platform-specific content to the site. 

As a sidenote, the better documented this feature is, the better we'll be able to communicate requirements to contributing to guides that are platform specific.

**Comment by apaskulin** [comment]
This is partially documented here https://github.com/sensu/sensu-docs/wiki/Sensu-docs-style-guide#multi-platform-content, but we're still missing instructions for inter-page platform selectors as used in https://github.com/sensu/sensu-docs/blob/master/content/sensu-core/1.0/reference/ssl.md

**Comment by hillaryfraley** [comment]
Team has fixed this issue
