### ISSUE TITLE
Elaborate on being able to use golang regex for asset filters and filters

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#1750]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior

Have a section in our filters ref that calls out being able to use golang regex a la https://github.com/google/re2/wiki/Syntax

## Current Behavior

This currently doesn't exist

## Possible Solution

Write it ™️ (beautifully)

**Comment by cwjohnston** [comment]
Next steps
- [x] Set up a test environment to prove out this concept (using golang regex in asset filters)
- [ ] Determine the right place for this information
- [ ] Add content in the right place

**Comment by cwjohnston** [comment]
## Expected behavior

An EventFilter which specifies one or more expressions using `match(regex)`, where `regex` is a Go RE2-compatible expression, should function as a filter.

## Context

To test, I set up this Handler and EventFilter:

```
---
type: Handler
api_version: core/v2
metadata:
  name: debug
spec:
  type: pipe
  command: echo
  filters:
  - allow_foo
---
type: EventFilter
api_version: core/v2
metadata:
  name: allow_foo
  namespace: default
spec:
  action: allow
  expressions:
    - event.check.labels.filter_test.match(/foo.*/)
```

Now, post an event with a matching label to the Sensu API:

```
curl -sS -H 'Content-Type: application/json' -H "Authorization: Bearer $SENSU_ACCESS_TOKEN" -d '{
  "entity": {
    "entity_class": "proxy",
    "metadata": {
      "name": "server01",
      "namespace": "default"
    }
  },
  "check": {
    "metadata": {
      "name": "server-health",
      "labels": {
        "filter_test": "seafood"
      }
    },
    "output": "Hello, world!",
    "status": 0,
    "interval": 60,
    "handlers": ["debug"]
  }
}' http://localhost:8080/api/core/v2/namespaces/default/events
```

Now note that the event is allowed by the backend:

```
{"check_name":"server-health","check_namespace":"default","component":"pipelined","entity_name":"server01","entity_namespace":"default","hooks":null,"level":"debug","msg":"received event","silenced":[],"time":"2020-01-29T23:39:56Z","timestamp":1580341196}
{"assets":null,"check_name":"server-health","check_namespace":"default","component":"pipelined","entity_name":"server01","entity_namespace":"default","filter":"allow_foo","level":"debug","msg":"allowing event that matches filter","time":"2020-01-29T23:39:56Z"}
{"check_name":"server-health","check_namespace":"default","component":"pipelined","entity_name":"server01","entity_namespace":"default","filter":"allow_foo","handler":"debug","level":"debug","msg":"allowing event","time":"2020-01-29T23:39:56Z"}
{"check_name":"server-health","check_namespace":"default","component":"pipelined","entity_name":"server01","entity_namespace":"default","handler":"debug","level":"info","msg":"sending event to handler","time":"2020-01-29T23:39:56Z"}
{"assets":null,"component":"pipelined","handler":"debug","level":"info","msg":"event pipe handler executed","namespace":"default","output":"\n","status":0,"time":"2020-01-29T23:39:56Z"}
```

To test the negative case, I modified the label value in my request body to something that doesn't match the expression, e.g. `seafob` and sent a new event which was filtered as expected.

**Comment by cwjohnston** [comment]
> Determine the right place for this information

The event filter reference includes a section on [filter expression evaluation](https://docs.sensu.io/sensu-go/latest/reference/filters/#filter-expression-evaluation) which describes the use of javascript expressions as a feature, but offers no examples.

We should give this section a bit of attention and add examples such as the use of regular expression matching on a label.

**Comment by hillaryfraley** [comment]
@agoddard to think about a good example for filtering based on labels

**Comment by agoddard** [comment]
We need to test this using the check name instead of check label, and then assuming that works fine, we can use an example of a check name substring regex.

**Comment by hillaryfraley** [comment]
event.check.name
