### ISSUE TITLE
Troubleshooting `context deadline exceeded`

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#1752]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior

Have some instructions for troubleshooting and identifying etcd bottlenecks and how one might remediate those issues.

## Current Behavior

We don't really provide this.

**Comment by hillaryfraley** [comment]
Discussed as part of journald troubleshooting at one point
Also discussed as part of etcd process for recreating a cluster

Need some context for `context deadline exceeded` and when it's encountered. Cameron's understanding is some part of the code base hit a timeout, and this is the generic golang error.

Need more specific issues in which we see this message, describing what you were trying to do when you got this message.

This is an example of an error that could be improved by telling users what to do. For now, closing. As CREs or anyone else runs into specific cases of this message, we should figure out how to contextualize it for a docs issue and potentially Eng to make the message more informative.
