### ISSUE TITLE
Add list of available resources to sensuctl dump documentation

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-docs#1759]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior
The documentation should explicitly list all supported types, so that users have a reference to draw from.

## Current Behavior
No list exists.

## Possible Solution
Work with someone on the engineering team to draw up a list of the current resources that dump supports.

**Comment by hillaryfraley** [comment]
I think this list should be added at https://docs.sensu.io/sensu-go/5.13/sensuctl/reference/#exporting-resources

Edit: master list of resources https://docs.sensu.io/sensu-go/5.13/reference/rbac/#resources

Edit part 2: Eric is compiling a list of supported resources

**Comment by echlebek** [comment]
Here is the current list of supported resources:

authentication/v2.Provider
licensing/v2.LicenseFile
store/v1.PostgresConfig
federation/v1.Replicator
core/v2.Namespace
core/v2.ClusterRole
core/v2.ClusterRoleBinding
core/v2.User
core/v2.TessenConfig
core/v2.Asset
core/v2.CheckConfig
core/v2.Entity
core/v2.Event
core/v2.EventFilter
core/v2.Handler
core/v2.Hook
core/v2.Mutator
core/v2.Role
core/v2.RoleBinding
core/v2.Silenced

**Comment by echlebek** [comment]
In a future release of Sensu you will be able to list these types with:

```
sensuctl dump --types
```

This command won't require a running backend or agent.

**Comment by hillaryfraley** [comment]
https://github.com/sensu/sensu-go/pull/3292

**Comment by hillaryfraley** [comment]
To-dos:
- [ ] Add Eric's list to docs. I originally thought they should go in https://docs.sensu.io/sensu-go/5.13/sensuctl/reference/#exporting-resources, but are these Core resources?

- [x] Follow up with @cwjohnston re: necessary context for list of resources

- [x] Capture the future release info [in notes for release 5.next? Do we know that it be in the next release?]

**Comment by hillaryfraley** [comment]
Slack w/Eric; he will provide a list of synonyms for the supported resources. Eric thinks it makes sense to list both the fully qualified names and they synonyms.
