### ISSUE TITLE
Docs Feedback: reference/agent/enabling-on-boot

### ISSUE THREAD

**Issue by johannagnarsson** [sensu/sensu-docs#1764]
Link to page: 
https://docs.sensu.io/sensu-go/5.13/reference/agent/#enabling-on-boot
### Feedback
There is a note box that states:
`NOTE: On older distributions of Linux, use sudo chkconfig sensu-server on to enable the agent and sudo chkconfig sensu-server off to disable.`
This should probably state something like this:
`NOTE: On older distributions of Linux, use sudo chkconfig sensu-agent on to enable the agent and sudo chkconfig sensu-agent off to disable.`

**Comment by hillaryfraley** [comment]
Thank you, @johannagnarsson! We made this change and it's live: https://docs.sensu.io/sensu-go/5.13/reference/agent/#enabling-on-boot
