### ISSUE TITLE
Authentication providers API TOC links have incorrect refs

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#1767]
## This is an issue with:

- [x] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior
The authproviders API endpoints (licensed tier)
/authproviders (GET)
authproviders/:name (DELETE)

## Current Behavior
These TOC links have incorrect refs (so they don't work):
The authproviders/:name API endpoints (licensed tier)
authproviders/:name (GET)
authproviders/:name (PUT)

## Possible Solution
Fix link refs

## Steps to Reproduce (for bugs)
1. Open https://docs.sensu.io/sensu-go/5.13/api/authproviders/
2. Click links for The authproviders/:name API endpoints (licensed tier); authproviders/:name (GET); or authproviders/:name (PUT)
3. Refs for these links are incorrect, so links don't work

**Comment by hillaryfraley** [comment]
@cwjohnston This is a quick fix in a single doc, but a couple questions:
1. Should it be fixed in all Go docs versions? I'm guessing yes since it's functionality-related
2. Since we're aware of it here, should we audit every top-of-page TOC to see if there are other pages that need a similar fix?

**Comment by cwjohnston** [comment]
> @cwjohnston This is a quick fix in a single doc, but a couple questions:
> 
> 1. Should it be fixed in all Go docs versions? I'm guessing yes since it's functionality-related

Yes please!

> 2. Since we're aware of it here, should we audit every top-of-page TOC to see if there are other pages that need a similar fix?

Let's open an issue for a TOC audit (a one-time chore) which we can reprioritize if we become aware of other similar instances.
