### ISSUE TITLE
Document entity version

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-docs#1778]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior
https://docs.sensu.io/sensu-go/5.13/api/entities/ and https://docs.sensu.io/sensu-go/5.13/reference/entities/ contain information about the new string field `sensu_agent_version`, which reflects the Sensu semver version of the agent entity.

## Current Behavior
Field not present in 5.13.

## Possible Solution
Add the field to the api and reference docs.

## Context
https://github.com/sensu/sensu-go/pull/3295

**Comment by hillaryfraley** [comment]
I think this is a 5.13 issue, but I added it to the 5.14 milestone.

**Comment by hillaryfraley** [comment]
It seems like these might be the necessary changes:
- [ ] Add `sensu_agent_version` field in all examples for all endpoints at https://docs.sensu.io/sensu-go/5.13/api/entities/
- [ ] Add a `sensu_agent_version` entry under https://docs.sensu.io/sensu-go/5.13/reference/entities/#top-level-attributes
- [ ] Add `sensu_agent_version` field to https://docs.sensu.io/sensu-go/5.13/reference/entities/#examples

**Comment by nikkictl** [comment]
@hillaryfraley `sensu_agent_version` is a top level field in `Entity`. It doesn't belong in the object metadata.
