### ISSUE TITLE
Explore merging Uchiwa content into Docs Site

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#178]
Since Uchiwa uses Hugo and is already written in Markdown, it seems like a fairly simple thing for us to bring the content into the Docs site, and maybe do a redirect from the Uchiwa site to our docs.

**Comment by mbbroberg** [comment]
This aligns well with consolidation across other microsites (sensu-plugins.io).

**Comment by mbbroberg** [comment]
Note that Simon is open to it - we spoke about it today.

**Comment by asachs01** [comment]
#349 is the PR for this

**Comment by cwjohnston** [comment]
Closed by #349
