### ISSUE TITLE
Add documentation for cluster registration federation API

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-docs#1786]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

Add documentation describing the new federation API datatype `Cluster`.

Reference:
https://github.com/sensu/sensu-enterprise-go/issues/669
https://github.com/sensu/sensu-enterprise-go/pull/686

**Comment by hillaryfraley** [comment]
Looks like this should be done in sync with release 5.15
