### ISSUE TITLE
Add HTTP API documentation for federation/v1.Cluster

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-docs#1787]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

Add documentation describing the `federation/v1.Cluster` HTTP API.

Reference:
https://github.com/sensu/sensu-enterprise-go/issues/669
https://github.com/sensu/sensu-enterprise-go/pull/686

**Comment by hillaryfraley** [comment]
Also looks like a 5.15 issue
