### ISSUE TITLE
how to add storage's/switches manually to sensu ... 

### ISSUE THREAD

**Issue by mfinkelstine** [sensu/sensu-docs#179]
Im moving from nagios to sensu , 

and im trying to add my storage's to the sensu dashboard ,
where I need to configure the storage's ?
I cant install the sensu API on those storage's/switches etc ... 

it's possible to add them manually to sensu ?

Thanks 
Meir.

**Comment by calebhailey** [comment]
Closing in favor of https://github.com/sensu/sensu-docs/issues/180
