### ISSUE TITLE
Need to clarify occurrences differences in Classic v Go

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#1793]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior

@rgeniesse has noticed that there have been several occurrences of folks in the community thinking that `occurrences` is part of the check definition like it was in classic. This is no longer the case. We should make a note in the migration guide about this, and possible one in the check/events reference material

**Comment by cwjohnston** [comment]
I think we should also describe that [sensu-translator 1.0.1](https://github.com/sensu/sensu-translator/blob/master/CHANGELOG.md#101---2018-12-18) will translate occurrences and refresh attribute values to the annotations honored by the fatigue_check filter

**Comment by cwjohnston** [comment]
The translator doesn't automatically add fatigue_check asset nor filter configuration to run it, so we should describe those needed pieces in the migration doc as well.

**Comment by hillaryfraley** [comment]
@cwjohnston clarified during planning mtg today: sensu-translator now supports outputting the occurrence and refresh into a Sensu Go check definition with the correct annotations. Migration guide needs to tell people to install the right version of the sensu-translate tool.

We should also mention this in the filter reference (https://docs.sensu.io/sensu-go/5.15/reference/filters/) -- call out that Sensu Go does not include an occurrence-based filter (like the Core `occurrences` filter).

**Comment by hillaryfraley** [comment]
- [x] Migration guide: Explain that Sensu Go does not include an occurrence-based filter like the Core occurrences filter
- [x] Filter reference: Explain that Sensu Go does not include an occurrence-based filter like the Core occurrences filter (copy and paste the same sentence you add in the Migration guide for the first checkbox).
- [x] Migration guide: Explain that the latest version of the Sensu translator tool will get the occurrence and refresh values from the check and will translate those into the annotation values that are expected by the fatigue check
- [x] Migration guide: Add example of fatigue filter asset and filter resource so readers can see it will require a few extra steps to get the occurrence filtering
- [x] Check reference: Explain that occurrences is no longer part of the check definition in Go like it was in classic.

**Comment by hillaryfraley** [comment]
We should have an example in the filter reference that shows exactly how to add the fatigue check asset (`sensuctl asset add nixwiz/sensu-go-fatigue-check-filter`, use rename flag to fatigue-check-filter`) then a filter command that shows how to configure it (see examples in https://bonsai.sensu.io/assets/nixwiz/sensu-go-fatigue-check-filter).

The benefit is you define occurrences on the check level rather than having different versions of the filter with different thresholds. **dynamic**

In the check configuration, you would use the annotation to specify 10 occurrences, 7 occurrences, etc.
