### ISSUE TITLE
Refine offline docs support

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#1806]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [x] Enhancement (add new site functionality)

## Issues identified in initial offline docs PDF
- [x] ~PDF is not picking up bullet formatting or indention in lists and TOCs~ (fixed in https://github.com/sensu/sensu-docs/pull/2152)
- [x] ~Emojis are not printed in PDF~ https://github.com/sensu/sensu-docs/pull/1894
- [x] ~In the PDF bookmarks list, all doc page headings are nested under a "localhost" folder/heading~ Limitations of using this method with Acrobat are going to require manually renaming this bookmark after PDFs are generated
- [x] ~PDF bookmarks list includes "Sensu Docs" as part of each page title~ (fixed in https://github.com/sensu/sensu-docs/pull/2152)
- [x] ~PDF prints "Contents" after the heading~ (just before the TOC) on the first page of each docs article (fixed in https://github.com/sensu/sensu-docs/pull/2152)
- [ ] PDF ignores NOTE, WARNING, and PRO TIP formatting (except italics)

## Context
Refine results from initial PR, which allows us to generate offline copies of docs in PDF (#1779 )

See attached PDF, which includes comments noting instances of each issue listed above.
[Updated Review Copy - Sensu Go 5.13 - Sensu Docs.pdf](https://github.com/sensu/sensu-docs/files/3682899/Updated.Review.Copy.-.Sensu.Go.5.13.-.Sensu.Docs.pdf)

**Comment by cwjohnston** [comment]
Additional todos: 

- [x] Play-test the PDF on e-reader device, especially TOC @cwjohnston 
- [x] Provide alternative images for emojis @hillaryfraley

**Comment by cwjohnston** [comment]
I have tested the PDF on my Kindle via Amazon's email gateway. The TOC and other links I tried at random worked as expected. 🎉

**Comment by hillaryfraley** [comment]
Here are image versions (mac) for each of the two emojis we use in the docs
![cross-mark_274c](https://user-images.githubusercontent.com/19190208/66421575-1d93a800-e9d6-11e9-8fcd-cfe7729ae1f5.png)
![white-heavy-check-mark_2705](https://user-images.githubusercontent.com/19190208/66421583-208e9880-e9d6-11e9-9ff9-b2ac0ee0be2a.png)

**Comment by cwjohnston** [comment]
I've converted the list of issues to a checklist so we can better track what's been done on this epic. @rnevius any updates on the remaining items?

**Comment by rnevius** [comment]
I have created a new branch which adds `wkhtmltopdf` support for automating PDF export. `wkhtmltopdf` not only streamlines archival of product documentation, but it also eliminates many of the issues listed in the issue above. I expect this to be wrapped up and ready for review next week.

**Comment by cwjohnston** [comment]
@rnevius will you please provide an update on the status of the changes in progress?

**Comment by rnevius** [comment]
Regarding the last item in the checklist (_PDF ignores NOTE, WARNING, and PRO TIP formatting (except italics)_)... this formatting relies on post-processing on the frontend via JavaScript. 

Using JS in offline docs is not an option for us, so we can either (1) forego formatting these sections in offline docs, or (2) write new formatting template tags in Hugo to actually render this content properly via HTML/CSS – something like `{{< note >}}Some content{{< /note }}`. The second option will require refactoring existing content.

**Comment by hillaryfraley** [comment]
Re: info from Ryan about the Note/Warning/ProTip formatting in PDF...

Since we did the docs copy edit late last year, all of the Note/Warning/ProTip items have the first word in *bold face* (see image below), so they are a little more set off. I don't think the refactor Ryan suggests would take very long, especially if I just did the latest version and didn't worry about earlier versions.
![note-format-pdf](https://user-images.githubusercontent.com/19190208/73866726-354f3180-47fa-11ea-96b7-25e43de2902a.png)

**Comment by cwjohnston** [comment]
The second approach, using hugo template tags, seems to me like the correct solution, but I don't feel ready to spend much time on it. @hillaryfraley @rnevius do either of you believe your part will take more than two hours?

**Comment by hillaryfraley** [comment]
Since my earlier comment, I realized that the change to how formatting is handled in our template will probably require changing the `{{< note >}}Some content{{< /note }}` formatting throughout all content (otherwise we would have the old JS hanging around -- maybe that's not a big deal though?)

I think a find+replace throughout the content would take between 1 and 2 hours for all versions of the docs.

I would be happy to try to create the template changes, although I have no idea how long that would take me...I'm sure it would take me longer than it might take Ryan though.

**Comment by cwjohnston** [comment]
Sorry, I wasn't very clear in my last comment. I think this needs to be implemented in steps so we can avoid updates to every version of the docs, e.g. we add the new template tags, update one version of the docs to use them, and remove the frontend formatting implementation once the older versions have rolled off.

As the bulk of the work in this issue is done, I am going to open a new issue for the new formatting template tags.

**Comment by cwjohnston** [comment]
Closing in favor of #2158 for tracking the remaining work.
