### ISSUE TITLE
Default Handler missing in Getting Started guide

### ISSUE THREAD

**Issue by soupdiver** [sensu/sensu-docs#181]
I just followed the **Getting Started** guide to setup a sensu server and client.
I came until **adding_a_check** and there until **Testing the check**.
In the `sensu-server.log` I can see that the check is published.
But then I always get 
```
{"timestamp":"2015-02-01T08:32:21.762460+0100","level":"error","message":"unknown handler","handler_name":"default"}
```

So it seems a default handler is missing but was never mentioned before in the docs.

Where should it come from?

I'm not sure it this is related to #98 ?

**Comment by nadx969** [comment]
Hi folks.  I see this error a lot and I am not sure why.  

as an example, using the metric handler influxdb.  the influxdb-metrics.json file was modified and copied to /etc/sensu/conf.d/.  The plugin itself is copied to /etc/sensu/handlers/

    {
      "influxdb" : {
        "server": "localhost",
        "port": "8086",
        "username": "root",
        "password": "**********",
        "database": "sensudb"
      }
    }

after restart, we can see the error in the sensu-server.log related to unknown handler.

is there additional configuration requirements?  does this need to be in an "handler.json"?  is ruby file in the right directory?  what permissions/ownership should it have or does that matter?

any assistance would be extremely helpful.  we have seen the same issue with mailer and logevent

**Comment by calebhailey** [comment]
First off, I'm very sorry it's taken us this long to come back to this. We're planning on a major rewrite of the "getting started" documentation for the version 0.23 release, in which we'll try to finally answer this question. :D

**Comment by calebhailey** [comment]
Actually, I'm going to close this in favor of https://github.com/sensu/sensu-docs/issues/98
