### ISSUE TITLE
404 on sensuctl reference page

### ISSUE THREAD

**Issue by bananabele** [sensu/sensu-docs#1814]
Link to page:  https://docs.sensu.io/sensu-go/5.14/sensuctl/reference/

### Feedback
Bonsai (in the Bonsai section) of this page: https://docs.sensu.io/sensu-go/5.14/sensuctl/reference/ links to: https://docs.sensu.io/sensu-go/5.14/sensuctl/reference/34 where I'm guessing it should link to: https://bonsai.sensu.io/

**Comment by hillaryfraley** [comment]
PR to fix: https://github.com/sensu/sensu-docs/pull/1815
