### ISSUE TITLE
Document guides and overview for API Keys

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-docs#1834]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

In addition to https://github.com/sensu/sensu-docs/issues/1798 and https://github.com/sensu/sensu-docs/issues/1797, we should provide a guide for users on the new API Key feature, and update the [API Overview.](https://docs.sensu.io/sensu-go/5.14/api/overview/) `core/v2.APIKey` is a persistent UUID which maps to a _stored_ Sensu username (api keys are not supported for authentication providers, ex: ldap, oidc). It is a cluster wide resource, therefore only cluster admins can grant, view, and revoke them. The resource is intentionally not compatible with `sensuctl create`.

### API Key authentication

Similar to the `Bearer [token]` Authorization header, `Key [api-key]` will also be accepted as an Authorization header for authentication.

**JWT**
```
curl -H "Authorization: Bearer $SENSU_TOKEN" http://127.0.0.1:8080/api/core/v2/namespaces/default/checks
```

**API Key**
```
curl -H "Authorization: Key $SENSU_API_KEY" http://127.0.0.1:8080/api/core/v2/namespaces/default/checks
```
**ex.**
```
$ curl -H "Authorization: Key 7f63b5bc-41f4-4b3e-b59b-5431afd7e6a2" 

HTTP/1.1 200 OK
[
  {
    "command": "check-cpu.sh -w 75 -c 90",
    "handlers": [
      "slack"
    ],
    "interval": 60,
    "publish": true,
    "subscriptions": [
      "linux"
    ],
    "metadata": {
      "name": "check-cpu",
      "namespace": "default"
    }
  }
]
```

### Sensuctl management commands

**generate a new api key for the admin user:**
```
$ sensuctl api-key grant admin
Created: /api/core/v2/apikeys/7f63b5bc-41f4-4b3e-b59b-5431afd7e6a2
```

**get info about an api-key:**
```
$ sensuctl api-key info 7f63b5bc-41f4-4b3e-b59b-5431afd7e6a2 --format json
{
  "metadata": {
    "name": "7f63b5bc-41f4-4b3e-b59b-5431afd7e6a2"
  },
  "username": "admin",
  "created_at": 1570744117
}
```

**list all api-keys:**
```
$ sensuctl api-key list
                  Name                   Username            Created At            
 ────────────────────────────────────── ────────── ─────────────────────────────── 
  7f63b5bc-41f4-4b3e-b59b-5431afd7e6a2   admin      2019-10-10 14:48:37 -0700 PDT
```

**revoke an api key for the admin user:**
```
$ sensuctl api-key revoke 7f63b5bc-41f4-4b3e-b59b-5431afd7e6a2 --skip-confirm
Deleted
```

**Comment by hillaryfraley** [comment]
closed by https://github.com/sensu/sensu-docs/pull/1848
