### ISSUE TITLE
Sensu server on Windows

### ISSUE THREAD

**Issue by Gogeta094** [sensu/sensu-docs#184]
Hi. I can't find at docs the information if sensu server can be deployed on Windows? 
Thanks for answer!

**Comment by calebhailey** [comment]
We've addressed this via the version 0.22 installation docs rewrite; see here: https://sensuapp.org/docs/latest/install-sensu-server-api#sensu-core 

> _although Sensu Core packages are available for a variety of platforms – thus making it technically possible to run the sensu-server and sensu-api processes on non-Linux operating systems – we strongly recommended running the Sensu Server and API on a Linux-based platform. Sensu Core installer packages for non-Linux platforms are provided for the purpose of making the sensu-client available, and are not tested as extensively for running the sensu-server and sensu-api processes._

We've also updated the Windows docs, here: https://sensuapp.org/docs/latest/sensu-on-microsoft-windows 

I'm going to go ahead and close this, but please feel free to comment and/or open a new issue if you have any further questions. /cc @agoddard
