### ISSUE TITLE
Document Sensu environment variables

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#1840]
Caleb asked if we have documentation for Sensu environment variables. I couldn't find it (although I could be missing it).

Slack conversation starts here: https://sensu.slack.com/archives/C3MHLUP46/p1570819029042900

Simon suggested this may not be supported yet: https://github.com/sensu/sensu-go/issues/2680

## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

**Comment by cwjohnston** [comment]
#1724 will add environment variables to agent reference

**Comment by cwjohnston** [comment]
Following a release which closes https://github.com/sensu/sensu-go/issues/2680 we will need to document the backend environment variables before this can be closed out.

**Comment by hillaryfraley** [comment]
Note according to CR planning today: this issue requires PRs for agent and backend env vars.

- [x] Agent (addressed in https://github.com/sensu/sensu-docs/pull/1724)
- [x] Backend -- still needs to be addressed

**Comment by hillaryfraley** [comment]
Agent and backend both addressed in https://github.com/sensu/sensu-docs/pull/1724. Backend is part of 5.15.
