### ISSUE TITLE
Write up what happens when you rename or delete a check or client

### ISSUE THREAD

**Issue by majormoses** [sensu/sensu-docs#189]
Something that catches a lot of people by surprise is when they rename or remove a check and it still shows up in uchiwa. This is because unless the check has a TTL configured sensu keeps it around in redis and uchiwa aside from its functionality integrating into the api changing state is essentially a visual representation of the state. As such the check will remain even after removing the file and restarting api, server, and client. This can typically be solved via two methods:
1. clean out the keys for that check on the clients
2. delete the client and let it re-register

The basic steps as I understand them is to locate the keys in redis:
```
$ redis-cli
127.0.0.1:6379> keys '*:ip-10-38-152-75.us-west-2.compute.internal:disk'
1) "history:ip-10-38-152-75.us-west-2.compute.internal:disk"
2) "result:ip-10-38-152-75.us-west-2.compute.internal:disk"
```

Now that we know which keys to delete we can either delete them one by one or use several ways of dealing with looping over they keys and deleting them.

Nothing quite like good old reliable `xargs`:
```bash
$ redis-cli KEYS "prefix:*" | xargs redis-cli DEL
```
Another option if you have a new enough version of redis you can execute a lua script to do the same thing:
```
$ redis-cli
EVAL "return redis.call('del', unpack(redis.call('keys', ARGV[1])))" 0 prefix:*
```

In both of these cases update the prefix to match your check name and node name. You want to minimally remove the result and history keys.

For deleting a client:
- In Uchiwa there is an x in the top right corner of the client
- use the api

Example API request without auth:
```
curl -XDELETE --silent -L https://$SENU_API_HOST:4567/clients/$CLIENT_NAME
```

**Comment by mbbroberg** [comment]
@majormoses this is really important information to keep in mind. Thanks for sharing it! Hey @asachs01, in the current layout of information, where do you believe this fits best?

**Comment by majormoses** [comment]
It's worth noting that the same can be true for a client delete and/or rename if there is not another mechanism such as `aws-cleaner`, `handler`, or a shutdown script, to deregister clients`

**Comment by asachs01** [comment]
@mbbroberg not sure how I missed this. I'll get this added to next for our docs writeup

**Comment by mbbroberg** [comment]
Thanks @asachs01

**Comment by Shadowssong** [comment]
Ran into this same issue and was able to clear the history/checks using redis-cli but had failing alerts still showing up on the client page (but not when drilled down into the client page).  Turns out I needed to resolve all of the outstanding events for my alerts that had triggered, I did this via the events page in uchiwa but was unable to find the redis keys that corresponded to those events.

**Comment by majormoses** [comment]
@Shadowssong looks like there may have been something not cleaned up and https://github.com/sensu/sensu/pull/1892 should help with that in the future once its merged.
