### ISSUE TITLE
Add documentation for check extensions

### ISSUE THREAD

**Issue by rmc3** [sensu/sensu-docs#189]
The extensions page currently doesn't have anything under the Check Extensions heading other than ```TODO```. Documentation on how to configure check extensions should be added.

**Comment by rmc3** [comment]
I'm working on a PR for this.

**Comment by calebhailey** [comment]
This has still never really been addressed. I'm going to work on bringing this back in the 0.23 or 0.24 release.

**Comment by calebhailey** [comment]
This happened: https://sensuapp.org/docs/latest/reference/extensions.html \o/ 

There's a [lot more extension goodness coming in 0.26][0] as well... 

[0]: https://github.com/sensu/sensu/pull/1394
