### ISSUE TITLE
Feedback: What's a Sensu check plugin?

### ISSUE THREAD

**Issue by FredrikWendt** [sensu/sensu-docs#1912]
Link to page: https://docs.sensu.io/sensu-go/5.14/reference/checks/#check-commands

### Feedback

The introduction section is confusing for people new to Sensu Go, as:
- `executable commands which are executed by the Sensu agent` -- which agent? 
  Suggestion: change to `a Sensu agent`

- `Most Sensu check plugins provide support for command line arguments for reusability.` -- what's a Sensu check plugin, where can I find one? There's no `sensuctl plugins ...` equivalent. 
  Suggestion: change to `Many common checks are downloadable as Sensu assets, and provide support for command line arguments so many check definitions can use the same executable.`

**Comment by hillaryfraley** [comment]
Hi @FredrikWendt! Thank you for creating this issue. I submitted a PR to address the changes you suggest: https://github.com/sensu/sensu-docs/pull/1913. We appreciate you for taking the time to help improve Sensu Go docs!
