### ISSUE TITLE
New etcd discovery options: --etcd-discovery and --etcd-discovery-srv

### ISSUE THREAD

**Issue by ccressent** [sensu/sensu-docs#1956]
https://github.com/sensu/sensu-go/pull/3417 adds etcd and DNS SRV discovery options for the embedded etcd server we use in `sensu-backend`.

## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [X] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior

The 2 new options and what they do are described in our documentation. See PR above for links that should give a bit of context.

**Comment by hillaryfraley** [comment]
@hillaryfraley add flags to reference documentation. There may also be a guide that goes along with this -- reference etcd docs?
