### ISSUE TITLE
etcd replicator documentation has misleading port

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-docs#1957]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior

I'd expect port in https://docs.sensu.io/sensu-go/5.15/reference/etcdreplicators/ for `url` to match a real port used by sensu go.

## Current Behavior

Currently says `3379`

## Possible Solution

Change `3379` to `2379`

## Steps to Reproduce (for bugs)

https://docs.sensu.io/sensu-go/5.15/reference/etcdreplicators/

**Comment by hillaryfraley** [comment]
Thank you! I corrected the port in https://github.com/sensu/sensu-docs/pull/1958.
