### ISSUE TITLE
Docs for API auth using wrong URL path

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-docs#1967]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [x] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior

I'd expect API auth examples to use correct path.

## Current Behavior

I am working with the API and using path `/api/core/v2/auth` like the docs gives me 404 errors but using just `/auth` works.  I have found using `/api/core/v2/auth/test` like docs does work but I think the `/auth` and `/auth/token` examples are wrong and give me 404.

## Affected Docs Pages

https://docs.sensu.io/sensu-go/5.15/api/auth/

**Comment by hillaryfraley** [comment]
@treydock thank you for submitting this issue! I have submitted a PR to make the corrections you noted (https://github.com/sensu/sensu-docs/pull/1970). Thank you for helping us improve the Sensu docs!
