### ISSUE TITLE
Need to document the datastore API endpoint

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#1984]
We've not documented this, and it came up in a discussion w/ the Ansible collection folks. Waiting on some further input on https://github.com/sensu/sensu-go-ansible/issues/119 to see if the engineers have some input.

**Comment by hillaryfraley** [comment]
Need to add datastore endpoints to an API doc in API section. https://docs.sensu.io/sensu-go/5.15/reference/datastore/ is the bulk of the content we currently have in the docs.
