### ISSUE TITLE
Changelog section should be included in docs

### ISSUE THREAD

**Issue by johntdyer** [sensu/sensu-docs#200]
It would be great if there was a quick way to see what changed in each release on the [doc site](sensuapp.org/docs/).  This section should include fixed bugs, and perhaps links to the issue tickets.  For any new features there should be links to relevant doc sections, if they exist, as well as examples of how to use the new features.

**Comment by Akshaykapoor** [comment]
:+1:

**Comment by calebhailey** [comment]
I took a first stab at this in the 0.22 docs: https://sensuapp.org/docs/0.22/changelog 

I'd love any feedback! #monitoringlove

**Comment by calebhailey** [comment]
Added links to new documentation for new features in https://github.com/sensu/sensu-docs/pull/357/commits/10d440579c2df7580d664d6c33113a6c2a1ca63a which will get shipped along with #357. 

We have taken the first step in this direction, and we will continue to publish a changelog along with the documentation for future releases. Look for the 0.24 release to also include links to resolved github issues as well. :+1: 

Examples: 
- https://sensuapp.org/docs/0.22/changelog
- https://sensuapp.org/docs/0.23/changelog
