### ISSUE TITLE
Port forwarding in Sandbox lesson (was Docs Feedback)

### ISSUE THREAD

**Issue by mrpaulmanley** [sensu/sensu-docs#2002]
Link to page: https://docs.sensu.io/sensu-go/5.15/getting-started/learn-sensu/

### Feedback
Section 3 Start Vagrant
"ENABLE_SENSU_SANDBOX_PORT_FORWARDING=1 vagrant up"

Should be...
export ENABLE_SENSU_SANDBOX_PORT_FORWARDING=1
vagrant up

**Comment by asachs01** [comment]
Hi @mrpaulmanley , when running the command as part of starting up the sandbox, I'm not seeing an issue:

<img width="711" alt="Screen Shot 2019-12-10 at 5 16 15 PM" src="https://user-images.githubusercontent.com/898627/70573945-f04bad80-1b70-11ea-98ba-97f0aca1d343.png">

Can you tell us more about any error's you're encountering?

**Comment by hillaryfraley** [comment]
@asachs01 suggests setting port forwarding as part of the vagrant file (https://github.com/sensu/sandbox/blob/master/sensu-go/Vagrantfile). Aaron is going to submit a PR to make the required updates in the sandbox repo.

Edit: once this change is made to the vagrant file, the step in the sandbox lesson should be changed to just `vagrant up`

**Comment by hillaryfraley** [comment]
Closing pending further clarification about errors from reporter.
