### ISSUE TITLE
Audit and update sample-app.md

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#2027]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Expected Behavior

In https://docs.sensu.io/sensu-go/latest/getting-started/sample-app/:

- The step-by-step instructions work with no errors.
- The instructions are up-to-date with the current Kubernetes API versions and config requirements.

## Current Behavior

- There are gaps in the instructions that result in errors that users may not be able to solve.
- The instructions have not been updated to reflect current Kubernetes API versions and config requirements.

## Possible Solution
Audit the sample app instructions to complete any gaps and update repo files to incorporate Kubernetes changes.

## Affected Docs Pages
https://docs.sensu.io/sensu-go/latest/getting-started/sample-app/

## Context
I ran into an error at step 3 of the Set Up section when trying to walk through the sample app. Aaron and I worked on the instructions on a Zoom call, and he discovered issues like:

- https://docs.sensu.io/sensu-go/latest/getting-started/sample-app/#set-up Step 3: Need to change second command to `kubectl apply -f kube-state-metrics/examples/standard`
- https://docs.sensu.io/sensu-go/latest/getting-started/sample-app/#set-up Step 4: The IP addresses listed work if you are running minikube with `virtualbox` specified as the driver (see https://kubernetes.io/docs/tasks/tools/install-minikube/#confirm-installation). If you use hyperkit (which seems to be the minikube default), the IP addresses will be different. The instructions should make this clearer.
- Asset commands need to be changed to use `sensuctl asset add` throughout.
- In all `kubectl apply` commands for yaml files, the yaml files need to be updated to use the correct `api_version` (apps/v1) and to add `selector` in the spec. For example:
```
selector:
  matchLabels:
    app: sensu-backend
```

This sample app has many external dependencies that Sensu cannot control and is difficult to maintain as a docs walkthrough. Would it make more sense to recreate this as a Katacoda scenario? If we decide to maintain it outside the docs, would it be a Developer Advocate-maintained resource?

**Comment by hillaryfraley** [comment]
The `http://sensu.local` example seems fine because I think it's just a Sensu Backend URL placeholder, but should we update it to follow the placeholder format we've used in other docs (something like `http://127.0.0.1:8080`)?

I am less sure about the `http://webui.sensu.local/signin/` and `http://webui.sensu.local/events/` links. Based on our other docs, it seems like `http://localhost:3000/signin` and `http://localhost:3000/events` would be more appropriate.

I could not confirm any of this because I could not get past the "3. Deploy kube-state-metrics." step. I get this error:
`error: the path "kube-state-metrics/kubernetes" does not exist`

Not sure if it's a problem with the doc or something I'm doing wrong.

**Comment by asachs01** [comment]
@hillaryfraley I can pair with you on this.

**Comment by hillaryfraley** [comment]
We updated the docs so that they no longer link to sample-app.md (see #2133). Leaving this issue open pending further discussion about final dispensation.

**Comment by hillaryfraley** [comment]
Issues Aaron identified in 1/24/20 retro:

- Kubernetes extension apis have changed and have been deprecated
- Kube state metrics have changed how that app is deployed as well
- Minikube on OSX (maybe even on Windows) is now using hyperkit, which makes use of a different IP range than what Virtualbox uses
- Number of deployments inside of the sensu-kube-demo repo now contain deprecated references that make setup impossible

**Comment by hillaryfraley** [comment]
Text of issue #2270 from Edgar:
--------------------

### Description
Looks as though a while ago some changes where made to the repo causing our guide to no longer work at step 3. I believe it needs to be updated to `kubectl apply -f kube-state-metrics/examples/standard` but this needs to be tested. 

### Category

This is an issue with:

- [x] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/getting-started/sample-app/#set-up

### Expected behavior
Sample app should be deployed.

### Current behavior
Folder does not exist in the repo, deployment fails

### Corrections needed
App should be located in `metrics/examples/standard` but not sure if this is the same one as before.

**Comment by hillaryfraley** [comment]
Dev Advocates added to sprint and will take a look to see if they can help: https://sensu.slack.com/archives/CCBBAAZQW/p1591623677174900

**Comment by hillaryfraley** [comment]
See also https://github.com/sensu/sensu-docs/issues/2447. When we restore the sample-app.md page in the docs, we should make sure our docs search is picking it up as a result for a `sidecar` search.

**Comment by hillaryfraley** [comment]
Update from Jef: https://sumologic.slack.com/archives/C0250SG6Y03/p1626802296029100

**Comment by hillaryfraley** [comment]
Added to agenda for 1/13/2022 CR+DA sync

**Comment by hillaryfraley** [comment]
Discussed in 1/13/22 CR+DA sync meeting. Caleb thinks there will be a replacement for the deprecated repo and we will be able to rebuild this tutorial. Currently on hold pending Sensu Catalogs work.

**Comment by asachs01** [comment]
We've pretty well removed this from the docs. I'm going to close this issue.
