### ISSUE TITLE
Documentation for custom key values missing

### ISSUE THREAD

**Issue by vjanelle** [sensu/sensu-docs#205]
The documentation in 0.17 seems to be missing the custom key values in the client configuration page.

The documentation in question for 0.16 is at http://sensuapp.org/docs/0.16/clients#custom-key-values

**Comment by johntdyer** [comment]
I just ran into this myself.

**Comment by portertech** [comment]
https://github.com/sensu/sensu-docs/pull/235

**Comment by nabeken** [comment]
@portertech I also found that the doc is missing `command token substitution` since https://github.com/sensu/sensu-docs/commit/ec0866df3d70a19f1b0bee73bab4a18cc9ba1d31

**Comment by calebhailey** [comment]
This has been resolved in the 0.22 docs, along with a major rewrite of the client documentation: 

https://sensuapp.org/docs/latest/clients#custom-attributes
