### ISSUE TITLE
Default username/password not working in Web UI under Docker

### ISSUE THREAD

**Issue by exilemirror** [sensu/sensu-docs#2083]
Link to page: 
https://docs.sensu.io/sensu-go/latest/installation/install-sensu/#4-open-the-web-ui

### Feedback
Pulled the latest sensu/sensu docker image but the credentials admin and P@ssw0rd! is not working for this image. Getting Bad username or password.

Credentials are working fine for image sensu/sensu-rhel
Thank you.

![Screen Shot 2020-01-09 at 5 01 48 PM](https://user-images.githubusercontent.com/28727455/72053353-d1704080-3301-11ea-95fb-590cb8b3bea5.png)
![Screen Shot 2020-01-09 at 5 02 02 PM](https://user-images.githubusercontent.com/28727455/72053367-d59c5e00-3301-11ea-995c-4029abb19881.png)

**Comment by cwjohnston** [comment]
Hi @exilemirror, thanks for sharing your experience with the docker container and documentation. We are looking into what you've reported.

**Comment by cwjohnston** [comment]
@exilemirror I haven't been able to reproduce what you are seeing with either the sensu/sensu nor sensu/sensu-rhel images.

Can you please show us the output of `docker ps --no-trunc` so we can see more detail as to the command your container is running?

**Comment by exilemirror** [comment]
Hi @cwjohnston below output for docker ps --no-trunc
I'm running the container using docker-compose.

version: "3"
services:
  sensu-backend:
    image: sensu/sensu
    ports:
    - 3000:3000
    - 8080:8080
    - 8081:8081
    volumes:
    - "sensu-backend-data:/var/lib/sensu/etcd"
    command: "sensu-backend start --state-dir /var/lib/sensu/sensu-backend --log-level debug"

![Screen Shot 2020-01-10 at 9 49 43 AM](https://user-images.githubusercontent.com/28727455/72119233-b5ff4700-338e-11ea-8c81-ab6ea7a88e7b.png)

**Comment by cwjohnston** [comment]
Hi @exilemirror 👋 

Still haven't been able to reproduce the results you're seeing. Since you originally reported this behavior, we've released Sensu Go 5.17 with changes to the database initialization routines used by the Docker container.

Will you please retest your deployment with Sensu Go 5.17.2 and let us know if you are still seeing the same behavior?

**Comment by cwjohnston** [comment]
Since this issue was last updated we've revised [Docker initialization instructions](https://docs.sensu.io/sensu-go/latest/installation/install-sensu/#2-configure-and-start) to better describe the steps involved. Hope that helps!
