### ISSUE TITLE
Need confirmation: POST /entities/:entity 405 error

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#2097]
### Description
The Entities API doc is missing a POST /entities/:entity example, but when I try the call in Postman, I get a "405 Method Not Allowed" response.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/api/entities/#entitiesentity-post

### Corrections needed
I am hoping someone else can try a call to the POST http://hostname:8080/api/core/v2/namespaces/default/entities/entity endpoint to help confirm whether this is my mistake or an issue with this endpoint.

- If this is my mistake, I can add the missing example to the doc.
- If this is an issue with the endpoint, I can create a sensu/sensu-go issue.

**Comment by hillaryfraley** [comment]
See https://github.com/sensu/sensu-docs/pull/2052 for details

**Comment by rgeniesse** [comment]
@hillaryfraley I am get the same error as you using `curl`:

```
curl -v -X POST \
-H "Authorization: Bearer $SENSU_ACCESS_TOKEN" \
-H 'Content-Type: application/json' \
-d '{
  "entity_class": "proxy",
  "sensu_agent_version": "1.0.0",
  "subscriptions": [
    "web",
    "system2"
  ],
  "deregister": false,
  "deregistration": {},
  "metadata": {
    "name": "sensu-centos-proxy2",
    "namespace": "default",
    "labels": null,
    "annotations": null
  }
}' \
http://127.0.0.1:8080/api/core/v2/namespaces/default/entities/sensu-centos-proxy2
```

Error:

```
< HTTP/1.1 405 Method Not Allowed
```

We'll have to ask Engineering if the above usage is correct and if it is, we can then file a bug against sensu-go. I took a look at the code but its pretty well over my head on where to compare the entitys API for allowing PUT vs POST.

**Comment by hillaryfraley** [comment]
Thank you, @rgeniesse ! I will ask in Eng.
