### ISSUE TITLE
Document reference architectures

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#2111]
### Description

Document reference architectures for deploying Sensu Go to public cloud providers.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [x] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

This change could result a new doc or may be an update to the deployment guide.

### Expected behavior

As a Sensu implementor I can refer to the documentation for architecture diagrams and other content which help me to deploy Sensu in cloud environments while adhering to practices recommended by both my cloud provider and Sensu Inc.

### Current behavior

The [deploy Sensu guide](https://docs.sensu.io/sensu-go/latest/guides/deploying/) covers a lot of important considerations that are common to most every Sensu instance. The guide doesn't describe complete architectures in much detail, nor does it describe any considerations specific to cloud infrastructure.

### Additional context

This [internal proposal document](https://docs.google.com/document/d/1uiC4DiA5o1Ui2Ixu9lUx0qamJlWoE-6e288bwktTGZo/edit) describes our intent to develop reference architectures for Sensu deployment. 

This [LucidChart document](https://www.lucidchart.com/invitations/accept/7ce1871d-8c66-45e6-a710-2d75ded39c5a) contains infrastructure diagrams which engineering team have given an initial thumbs up on. 

For a first pass I think we should determine the best fit for sharing these diagrams on the docs site, and write up some descriptions to accompany them.

**Comment by hillaryfraley** [comment]
Create a draft PR with the architecture diagrams in the Deploy guide just to try it out (test how well they fit into the Deploy guide/whether they make the content too difficult to consume).
