### ISSUE TITLE
Add vault provider documentation

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-docs#2112]
### Description
The secrets/v1.VaultProvider needs to be documented.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [x] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

**Comment by hillaryfraley** [comment]
Documented in:

- https://github.com/sensu/sensu-docs/pull/2122
- https://github.com/sensu/sensu-docs/pull/2126
