### ISSUE TITLE
Bonsai troubleshooting guide?

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#2127]
This is more a prompt for discussion, but I was curious if we need to implement a troubleshooting guide for Bonsai. Things like

* When to recompile releases
* Troubleshooting the release process (there's a lot that could go into that)

The last bit could be split into a lot of different topics like dealing w/ ruby & travis, goreleaser, using other go packaging solutions. It's not really all that well-formed of an idea, but a thought/8:30pm musing.

**Comment by hillaryfraley** [comment]
We will address this issue as part of the IA project. See https://trello.com/c/coRcS5B7.

**Comment by hillaryfraley** [comment]
Moving back to hold for now status. We are not sure how catalogs will affect Bonsai or what troubleshooting might need to cover at this point.

**Comment by asachs01** [comment]
This is super old at this point and I'm not sure of its utility at this point.
