### ISSUE TITLE
Document RHEL/CentOS 8 support

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-docs#2151]
### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

https://docs.sensu.io/sensu-go/latest/installation/platforms/

### Expected behavior

Package cloud now has EL8 RPMs but the Sensu docs don't mention support for EL8 platforms.

### Current behavior

Only CentOS/RHEL 6 and 7 are listed as supported

### Corrections needed

Add CentOS / RedHat 8 to the list of supported platforms

**Comment by hillaryfraley** [comment]
@treydock thank you! We updated the Supported Platforms document in https://github.com/sensu/sensu-docs/pull/2161.
