### ISSUE TITLE
Broken role binding links on installation/auth page 

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#2156]
Link to page: https://docs.sensu.io/sensu-go/latest/installation/auth/#ad-groups-prefix

### Feedback

Broken links for `Sensu RBAC [role bindings][12] `

**Comment by cwjohnston** [comment]
![2020-02-06 at 4 37 PM](https://user-images.githubusercontent.com/148017/73988156-11c1df00-48ff-11ea-8214-4a086585029b.png)

**Comment by hillaryfraley** [comment]
Thank you for finding this
