### ISSUE TITLE
Static content should not be stylized via frontend JavaScript

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#2158]
### Description

Most documentation content is stylized by Hugo while rendering markdown as HTML, however 
some static content, i.e. `NOTE`, `PROTIP`, `IMPORTANT` and `WARNING` "callouts", are rendered using JavaScript instead.

### Category

This is an issue with:

- [ ] bug (bug in site build, layout, or functionality)
- [x] enhancement (add new or updated site functionality)

### Affected pages

Any page with `NOTE`, `PROTIP` or `WARNING` "callouts"

### Expected behavior

Static content is stylized by the static site build process, without dependency on JavaScript.

### Current behavior

As described in [this comment](https://github.com/sensu/sensu-docs/issues/1806#issuecomment-581578080), the special formatting applied to content inside a `_NOTE: _` or similar "callout" is being generated by Javascript instead of being rendered in the HTML generated by Hugo.

### Changes needed

As I have modeled this, we will be best served by implementing this in phases:

- [ ] Implement new formatting template tags, potentially one for each callout
- [ ] Update the latest version of the documentation to use these new tags

Once we've archived the last version using the old formatting:

- [ ] Remove the JavaScript styling implementation

### Additional context

Rendering `NOTE`, `PROTIP` or `WARNING` "callouts" using JavaScript prevents the content from being rendered properly in offline layout, i.e. when we generate a PDF.

* Browser(s) and version(s): 
* OS:

**Comment by hillaryfraley** [comment]
@cwjohnston I should have added this before, but we also have `IMPORTANT` callouts now -- I added them when we were making the Core EOL info more prominent.

**Comment by hillaryfraley** [comment]
I would like to take a swing at this, if it's ok by you @cwjohnston
