### ISSUE TITLE
Known limitations of authentication testing mechanisms should be documented

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#2159]
### Description

Documentation around users API and authentication credential testing touch points need clarification.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

https://docs.sensu.io/sensu-go/latest/api/auth/
https://docs.sensu.io/sensu-go/latest/api/users/
https://docs.sensu.io/sensu-go/latest/sensuctl/reference/

### Expected behavior

Documentation reflects known limitations so as to reduce confusion.

### Current behavior

The documentation for `/auth/test` GET API endpoint indicates it tests user credentials. This is true in so far as the provided credentials are valid for a "basic" user -- i.e. a User created via the `/users` API, as opposed to a user defined in an authentication provider such as LDAP or AD directories.

### Corrections needed

* The documentation for `/auth/test` GET API endpoint should clarify that authentication testing is only supported via "basic" authentication provider
* The documentation for `/users` API might need to better explain the relationship to the "basic" authentication provider
* Sensuctl reference documentation doesn't seem to cover `user test-creds`; that might be a useful addition.

### Screenshots

When testing known-working LDAP credentials via `/auth/test` GET API or `sensuctl user test-creds` the backend logs

```
{"component":"apid.routers","error":"basic provider is disabled","level":"info","msg":"invalid username and/or password","time":"2020-02-07T20:42:14Z","user":"dev"}
```

### Additional context

We don't have much if any documentation which indicates the existence of the built-in, non-configurable "basic" authentication provider, and I'm not sure where that might best fit.

* Browser(s) and version(s): 
* OS:

**Comment by hillaryfraley** [comment]
Closed by #2164
