### ISSUE TITLE
Securing Sensu guide issues

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#2169]
There are a couple of issues with this guide that came up during a recent customer migration effort, namely that we have a section on creating self signed certs that doesn't have any next steps after it. After chatting w/ @cwjohnston , we concluded that we should move that whole section to the clustering guide, and breadcrumb folks to it from Securing. The Clustering guide will also need an update to reflect the steps needed to secure a clustered set of backends.

**Comment by hillaryfraley** [comment]
This is the section to move into the Clustering guide: https://docs.sensu.io/sensu-go/latest/guides/securing-sensu/#create-self-signed-certificates

**Comment by hillaryfraley** [comment]
Aaron, Vikas forwarded a customer question and in looking over it, Cameron and I put together this issue: https://github.com/sensu/sensu-docs/issues/2210

We think that issue will address the things you pointed out in this issue. If you agree, I was thinking we could close this issue in favor of #2210 . Wdyt?

**Comment by asachs01** [comment]
👍 I agree @hillaryfraley

**Comment by asachs01** [comment]
Closing in deference to #2210
