### ISSUE TITLE
Sensu Go + etcd authentication (grant-permission)

### ISSUE THREAD

**Issue by tarcinil** [sensu/sensu-docs#2184]
As an engineer, 
I would like to ensure that my `backend-etcd` user has the correct permissions when `etcd` authentication is enabled.

## Feature Suggestion
Documentation on how to run Sensu Go while utilizing `etcd` authentication.  This will further enhance how to run Sensu Go securely.

## Possible Implementation
Add documentation to the follow page + h2
https://docs.sensu.io/sensu-go/latest/guides/securing-sensu/#etcd-user-role

## Context
Using etcd 3.4 with passwordless user account via mTLS with authentication enabled, I was unable to get Sensu Go `backend init` to run properly.

```
{"level":"warn","ts":"2020-02-13T15:31:24.552-0600","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-424eebe0-8294-4eb0-b146-7c456157de7c/REDACTED:2379","attempt":0,"error":"rpc error: code = PermissionDenied desc = etcdserver: permission denied"}
```

The concerning part is that I had scoped quite a bit into the user/role in etcd.

```
[root@REDACTED ~]# /opt/etcd/etcdctl user get REDACTED --detail
User: REDACTED

Role sensu_readwrite
KV Read:
	/
	[/, 0) (prefix /)
	[/sensu.io, /sensu.ip) (prefix /sensu.io)
	[/sensu.io/, /sensu.io0) (prefix /sensu.io/)
KV Write:
	/
	[/, 0) (prefix /)
	[/sensu.io, /sensu.ip) (prefix /sensu.io)
	[/sensu.io/, /sensu.io0) (prefix /sensu.io/)
```

As a test, I disabled etcd authentication and it was able to initialize the backend.  This means that this is definitely related to Sensu Go + permissions needed in etcd.  

I will continue working on getting them working in my environment and contribute as I can.

**Comment by echlebek** [comment]
Since this is a documentation issue, I've moved it to sensu-docs.

Now that the key named `.initialized` has been moved under `/sensu.io`, we can document that users will need to RW access to that key space.

```
User: REDACTED

Role sensu_readwrite
KV Read:
	[/sensu.io/, <open ended>
KV Write:
	[/sensu.io/, <open ended>
```

```
/opt/etcd/etcdctl role grant-permission sensu_readwrite readwrite --from-key '/sensu.io/'
```

**Comment by hillaryfraley** [comment]
Determine best fit: Secure Sensu or a doc that discusses external etcd.
Edit: I think it makes sense to put this information here: https://docs.sensu.io/sensu-go/5.18/guides/clustering/#use-an-external-etcd-cluster

Need to test before publishing.

**Comment by bitnik** [comment]
> Now that the key named .initialized has been moved under /sensu.io, we can document that users will need to RW access to that key space.

@echlebek is it so? Where is it documented? Using sensu 6.10.0 I still have to grant access to `.initialized` too.
