### ISSUE TITLE
Secrets management guide: Vault root token vs. Vault token

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#2199]
### Description
Because our secrets management guide uses the Vault dev server to make the example as straightforward as possible for readers, it relies on a Vault "root token." However, readers who use Vault in production would encounter a "Vault token" instead of a root token.

We were considering updating the guide language to just say "Vault token" (although the example would still require the root token from the Vault dev server). @nixwiz discovered though that non-root tokens (i.e. "Vault tokens") expire, whereas root tokens do not, and Engineering may prefer to recommend TLS auth instead. Until this issue is resolved, we should not change the language in the guide.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [x] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/guides/secrets-management/

### Corrections needed
Corrections will depend on how we decide to resolve the root token vs. Vault token vs. TLS auth question.

**Comment by hillaryfraley** [comment]
We need a better understanding from Engineering about what to document for now. If we show how to use a root token and teams cannot use a root token, we need to provide another example (mTLS?) that is compatible with our product but also reasonable for people to implement in production.

Is mTLS the next thing we should show that works with the current product? Is that what Engineering suggests for users who cannot get or use the root token?

**Comment by nixwiz** [comment]
Yes, we need to set up a mTLS example as it is the only other option.  Also, I have learned that when you configure VaultProvider with TLS, the token attribute is not required.  So we need to make sure that it's documented that you need to have either token or tls configured.
