### ISSUE TITLE
Reassess search scoping

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-docs#22]
After getting some content into the doc site project, determine how best to scope search results.

**Comment by asachs01** [comment]
@portertech since we have the Lunr search indices now, is this still an issue?

**Comment by apaskulin** [comment]
The search currently indexes page title, URL, and content. ([source](https://github.com/sensu/sensu-docs/blob/master/static/javascripts/application.js#L758-L760))

**Comment by obfuscurity** [comment]
I'm going to close this for now since there's no explicit request to expand the scope beyond the attributes @apaskulin listed. We can open a new issue if anyone has a specific attribute they'd like to see added.
