### ISSUE TITLE
Clarify the requirement of mTLS authentication when using sensu go secrets on agents

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-docs#2226]
### Description
When setting up Sensu secrets, language in at least the secrets reference may lead users to believe that only TLS is required for it to function:

https://docs.sensu.io/sensu-go/latest/reference/secrets/

```
Secrets are only transmitted over a TLS websocket connection. Unencrypted connections must not transmit privileged information. For agent-side resources, enable TLS/mTLS.
```

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [X] improvement (improve docs content or format)

### Affected pages
- At least the secrets reference.
- Any guide that mentions on how to setup secrets with agent examples.
- Maybe categorizing pre-5.14 TLS and mTLS.

### Expected behavior
Need more clear language that mTLS (mutual TLS) is required for agent resources. It is called out briefly on the reference page `For agent-side resources, enable TLS/mTLS`, but we should have links to exactly what it means to enable mTLS and that it does not include the TLS configuration that pre-dated 5.14.

### Current behavior
Before mTLS was added in 5.14, we have other ways to encrypt traffic between the agent and backend using wss. This can lead to confusion on exactly what is required for agent secrets to be transmitted by the backend to the agent requesting them.

### Corrections needed
Needs further discussion on each area that needs this due to previous use cases of wss prior to 5/14.

### Additional context

* Browser(s) and version(s): 
* OS:

**Comment by hillaryfraley** [comment]
Link to helpful discussion: https://sensu.slack.com/archives/C3MHLUP46/p1582843718092400
