### ISSUE TITLE
Add matches operator for api filtering

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-docs#2236]
### Description
In 5.19.0, a new operator for api filtering will be introduced called `matches`. 

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/api/overview/#response-filtering

### Expected behavior
- Add `matches` operator to the table
**operator:** `matches`
**description:** substring matching
**example:** `check.name matches "linux-"`
- Add subsection for string operators

### Additional context
- https://github.com/sensu/sensu-enterprise-go/issues/608
- https://github.com/sensu/sensu-enterprise-go/pull/881

* Browser(s) and version(s): Chrome
* OS: MacOS Catalina

**Comment by hillaryfraley** [comment]
Context: https://github.com/sensu/sensu-enterprise-go/issues/608#issuecomment-600638310

**Comment by palourde** [comment]
For reference, the `contains` operator has been renamed to `matches`: https://github.com/sensu/sensu-enterprise-go/pull/936

**Comment by palourde** [comment]
Some examples I've used for testing (obviously it's no longer `contains`): https://github.com/sensu/sensu-enterprise-go/pull/881#issuecomment-594605681
