### ISSUE TITLE
Update Sensu Go agent environment variable file documentation to match backend more closely

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-docs#2257]
### Description
The current section desribing how to use environment variables on disk with the Sensu Go agent is missing some critical details on requirements and behavior, which are present in the backend.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [X] improvement (improve docs content or format)

### Affected pages

https://docs.sensu.io/sensu-go/latest/reference/agent/#use-environment-variables-with-the-sensu-agent

Has some talk about how to get environment variables enabled, but the backend one has a lot more details on requirements and behavior.

### Expected behavior
Provide as much information as possible!

### Current behavior
Some important details are missing when using the agent to configure environment variables.

### Corrections needed
Ask @rgeniesse for them or I'll just take it.

### Screenshots
None.

### Additional context

* Browser(s) and version(s): 
* OS:

**Comment by hillaryfraley** [comment]
@rgeniesse I am missing something -- it looks to me like the agent reference has more info about env vars than the backend reference. I may not be looking at the right doc.

**Comment by rgeniesse** [comment]
@hillaryfraley  just saw your note. Let me track down what I meant here documentation wise.

**Comment by rgeniesse** [comment]
Yeah, looking back at:

https://docs.sensu.io/sensu-go/latest/reference/agent/#configuration-via-environment-variables

I am not sure what I wasn't seeing here. I think I thought the section I just linked was completely missing. But the agent and backend reference appear to have enough information. Let's sync up and see if that PR is needed at all.
