### ISSUE TITLE
Silenced API spec documentation needs to line up with Silenced Reference docs

### ISSUE THREAD

**Issue by mylesw42** [sensu/sensu-docs#2269]
### Description
The silencing spec given on the [Silencing API](https://docs.sensu.io/sensu-go/latest/api/silenced/#silenced-get-example) does not mention the "reason" attribute, even though it is available according to the reference docs.

### Category

This is an issue with:
- [x ] update (add missing or refresh existing content)

### Affected pages
https://docs.sensu.io/sensu-go/latest/api/silenced/

### Expected behavior
Expect to see a spec that lines up with the reference docs, specifically "reason" included.

### Current behavior
The docs currently don't show that "reason" is a vaild attribute returned from the Silenced API

### Corrections needed
Line up documentation to the spec on the [Silenced Reference](https://docs.sensu.io/sensu-go/latest/reference/silencing/#spec-attributes) page.

### Screenshots
N/A

### Additional context

Example including reason.

```json
{
  "metadata": {
    "name": "linux:check-cpu",
    "namespace": "default",
    "labels": null,
    "annotations": null
  },
  "expire": -1,
  "expire_on_resolve": false,
  "creator": "admin",
  "reason": "fix me",
  "subscription": "linux",
  "begin": 1542671205
}
```

* Browser(s) and version(s): 
Chrome 80.0.3987.132
* OS:
MacOS 10.14

**Comment by hillaryfraley** [comment]
@mylesw42 Thank you for submitting this issue! I have updated our silencing API docs to include the `reason` key-value pair.
