### ISSUE TITLE
An "Unreleased" version for Sensu Core

### ISSUE THREAD

**Issue by mbbroberg** [sensu/sensu-docs#227]
There are occasions when PRs are open to Core that will be waiting for the next release cycle of the project. It will be helpful to have an "Unreleased" version of the dropdown. Making some quick initial assumptions, it would: 

- Be a clone of the `latest` version so edits can be made
- Have a banner mentioning it's unreleased once #226 is resolved
- Be a place where CHANGELOG is maintained as the next release is prepped (which might help us given the multi-repo strategy we have for product)
- Bonus: When we cut early releases, we can point people to the Unreleased documentation to help test CHANGELOG entries. 

For an example of why this would be helpful, see https://github.com/sensu/sensu/pull/1800

**Comment by amdprophet** [comment]
Just as a note: I believe we will need to figure out how fixes against currently released versions can be brought forward to "unreleased" once the "unreleased" version has been cloned from the latest version.

**Comment by apaskulin** [comment]
This is currently in place!
