### ISSUE TITLE
Update Getting started sample app (K8s)

### ISSUE THREAD

**Issue by Blue0ctober** [sensu/sensu-docs#2270]
### Description

Looks as though a while ago some changes where made to the repo causing our guide to no longer work at step 3. I believe it needs to be updated to `kubectl apply -f kube-state-metrics/examples/standard` but this needs to be tested. 
### Category

This is an issue with:

- [x] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

https://docs.sensu.io/sensu-go/latest/getting-started/sample-app/#set-up
### Expected behavior

Sample app should be deployed.
### Current behavior

Folder does not exist in the repo, deployment fails
### Corrections needed

App should be located in `metrics/examples/standard` but not sure if this is the same one as before.
### Additional context

* Browser(s) and version(s): 
* OS:

**Comment by hillaryfraley** [comment]
@Blue0ctober do you have any objection to having me combine this issue with the other one about the sample app? https://github.com/sensu/sensu-docs/issues/2027

edit: hmmmm on second thought, I don't know when we will address https://github.com/sensu/sensu-docs/issues/2027 so maybe I should just test this command and make this change as an incremental improvement. Wdyt?

**Comment by hillaryfraley** [comment]
Moved issue text to https://github.com/sensu/sensu-docs/issues/2027. Closing in favor of https://github.com/sensu/sensu-docs/issues/2027 after discussion in today's planning mtg.
