### ISSUE TITLE
Guide Wanted: Securing Sensu

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#229]
We've been promising that a guide on securing Sensu is ["coming soon"](https://sensuapp.org/docs/latest/installation/summary.html#hardening-sensu) for a long time now. We should make good on this.

Some ideas about topics to be included:

* Generating SSL certificates for RabbitMQ
* Configuring RabbitMQ for certificate verification
* Configuring client and server specific credentials for RabbitMQ (See #104)
   * https://github.com/sensu/sensu/issues/696#issuecomment-191098780  
   * https://github.com/sensu/sensu/issues/1118#issuecomment-161650270
* Using [client signature](https://sensuapp.org/docs/latest/reference/clients.html#client-definition-specification) feature

**Comment by asachs01** [comment]
Fixed by #318, #327, #338
