### ISSUE TITLE
Document v1alpha prune API

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-docs#2297]
TODO(@palourde)

**Comment by palourde** [comment]
Endpoint: `http://localhost:8080/api/enterprise/prune/v1alpha`

Payload: Array of [`Metadata`](https://github.com/sensu/sensu-enterprise-go/blob/58a0a4e37825ae4af5ab1827454af2e47421a917/api/prune/v1alpha/prune.go#L65):
```
[
  {
    "type": "CheckConfig",
    "api_version": "core/v2",
    "name": "check-echo",
    "namespace": "default",
    "labels": {
      "region": "us-west-2",
      "sensu.io/managed_by": "sensuctl"
    },
    "created_by": "admin"
  }
]
```

Parameters:
- `?type=core/v2.CheckConfig`: corresponds to the arguments passed to `sensuctl prune`; does not support RBAC names (e.g. `checks`), must be the full qualified name as defined in https://docs.sensu.io/sensu-go/latest/sensuctl/reference/#sensuctl-prune-resource-types.
- `?allUsers=true`: corresponds to the `--all-users` flag
- `?users=admin`: corresponds to the `--users` flag
- `?labelSelector=[...]`: corresponds to the `--label-selector` flag
- `?dryRun=true`: corresponds to the `--dry-run` flag
- `?clusterWide=true`: corresponds to the `--cluster-wide` flag
- `?namespaces=dev`: corresponds to the `--namespace` flag

**N.B.** If you want to provide multiple value for query parameters that accept multiple values, you must specify the parameter multiple times and not pass a list, e.g.
- This works: `?users=admin&admin=foo`
- This won't work: `?users=admin,foo`

**Comment by hillaryfraley** [comment]
Clarification via slack: "Only POST. The response will be the same as the payload but include whatever gets pruned"

**Comment by hillaryfraley** [comment]
cURL command for testing:
```
curl -i -X POST -H "Content-Type: application/json" -d '[]' -H "Authorization: Key $SENSU_API_KEY" \
http://localhost:8080/api/enterprise/prune/v1alpha\?dryRun\=true\&types\=core/v2.CheckConfig&allUsers\=true\&namespaces\=default
```

**Comment by hillaryfraley** [comment]
@palourde when I use the testing command, I get:

```
http://127.0.0.1:8080/api/enterprise/prune/v1alpha\?dryRun\=true\&types\=core/v2.CheckConfig&allUsers\=true\&namespaces\=default
[1] 35005
zsh: command not found: allUsers=true&namespaces=default
hillaryfraley@Hillarys-Sensu-MacBook-Pro sensu-enterprise-go % HTTP/1.1 200 OK
Content-Type: application/json
Sensu-Entity-Count: 3
Sensu-Entity-Limit: 100
Sensu-Entity-Warning: 
Date: Fri, 03 Apr 2020 19:56:47 GMT
Content-Length: 2

[]
[1]  + done       curl -i -X POST -H "Content-Type: application/json" -d '[]' -H  
hillaryfraley@Hillarys-Sensu-MacBook-Pro sensu-enterprise-go % 
```

When I try it in Postman, I get 400 Bad Request.

edit: never mind -- I think it's because I don't actually have a resource that corresponds to the query parameters.

**Comment by palourde** [comment]
@hillaryfraley I believe you're missing a `\` before `&allUsers`; I think the right command would be:

```
curl -X POST -H "Content-Type: application/json" -d '[]' -H "Authorization: Key $SENSU_API_KEY" http://127.0.0.1:8080/api/enterprise/prune/v1alpha\?dryRun\=true\&types\=core/v2.CheckConfig\&allUsers\=true\&namespaces\=default
```
