### ISSUE TITLE
Re-add sensu client after delete

### ISSUE THREAD

**Issue by narcistesa** [sensu/sensu-docs#230]
Hi,

I'm not sure how to go about re-adding a client after deleting it (using Uchiwa).

Thanks,
Narcis

**Comment by portertech** [comment]
@ntesa Sensu clients automatically register with keepalives.

**Comment by calebhailey** [comment]
We'll make this more obvious in the 0.23 docs via an updated "getting started guide".

**Comment by calebhailey** [comment]
This will get fixed by #407.
