### ISSUE TITLE
Error in installation docker-compose docs?

### ISSUE THREAD

**Issue by audunsolemdal** [sensu/sensu-docs#2351]
I believe you have an issue here

https://docs.sensu.io/sensu-go/latest/installation/install-sensu/#2-configure-and-start

go to docker-compose tab

```
    volumes:
    - "sensu-backend-data:/var/lib/sensu/etcd"
    command: "sensu-backend start --state-dir /var/lib/sensu/sensu-backend --log-level debug"
```

while it should be 

```
    volumes:
    - "sensu-backend-data:/var/lib/sensu/sensu-backend/etcd"
    command: "sensu-backend start --state-dir /var/lib/sensu/sensu-backend --log-level debug"
```

My sensu-backend volume was empty until I changed this, the state kept resetting on each "docker-compose down" I did.

**Comment by hillaryfraley** [comment]
@solomson , thank you for reporting this issue. We'll check it out and get the doc updated.

**Comment by hillaryfraley** [comment]
@solomson thanks again for taking the time to help us improve the Sensu docs! We've merged the correction 🎉
