### ISSUE TITLE
Add processes field to system information, add --discover-processes flag

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-docs#2359]
### Description
https://github.com/sensu/sensu-enterprise-go/issues/956 introduces a new field to the system struct, but is only populated as a commercial agent feature. Update all documentation to reflect the new field. `--discover-processes` boolean flag has been added to commercial distributions of the sensu-agent.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
I'm not sure exactly which pages are affected, but assuming any references that document the system information such as entities and events and any entity/event payloads containing system information.

### Expected behavior
Processes field is documented, and each field of the struct is documented, for every system struct. Processes field is added to every system payload. `--discover-processes` is documented as a commercial agent flag to opt-in to service discovery.

### Current behavior
No docs, new field and flag shipping in 5.20.0

### Corrections needed
`Process`
- `Name string` name of the process
- `Pid int32` process id of the process
- `Ppid int32` parent process id of the process
- `Status string` status of the process (see [linux top manual](http://man7.org/linux/man-pages/man1/top.1.html) for examples)
- `Background bool` is it a background process
- `Running bool` is the process running
- `Created int64` when the process was created
- `MemoryPercent float32` memory % utilization of the process
- `CPUPercent float64` cpu % utilization of the process

`System`
- `Processes` list of processes on the local agent (see `Process` above)

**Commercial**
```
"processes": [
  {
    "name": "Slack",
    "pid": 89646,
    "ppid": 1,
    "status": "S",
    "background": true,
    "running": true,
    "created": 1586137792000,
    "memory_percent": 1.0215282,
    "cpu_percent": 0.34855995759805614
  },
  {
    "name": "Slack Helper",
    "pid": 89649,
    "ppid": 89646,
    "status": "S",
    "background": true,
    "running": true,
    "created": 1586137792000,
    "memory_percent": 0.15085936,
    "cpu_percent": 0.031070808975078856
  }
]
```
**OSS**
```
"processes": null
```

### Additional context
https://github.com/sensu/sensu-enterprise-go/issues/956

**Comment by hillaryfraley** [comment]
I looked through the /sensu-go issue (https://github.com/sensu/sensu-enterprise-go/issues/956) and PR (https://github.com/sensu/sensu-enterprise-go/pull/974) as well as all the docs, and I think these are the pages that will need to be updated:
- https://docs.sensu.io/sensu-go/5.20/reference/agent/#configuration
- https://docs.sensu.io/sensu-go/5.20/reference/entities/
- https://docs.sensu.io/sensu-go/5.20/reference/events/
- https://docs.sensu.io/sensu-go/5.20/reference/tokens/#examples (there's an example entity at the end)
- https://docs.sensu.io/sensu-go/5.20/api/entities/
- https://docs.sensu.io/sensu-go/5.20/api/events/

I switched to the `feature/discover-services` branch, but I couldn't start the agent with the `--discover-services` flag:
```
{"component":"agent","error":"unknown flag: --discover-services","level":"fatal","msg":"error executing sensu-agent","time":"2020-04-21T10:33:58-05:00"}
```

**Comment by hillaryfraley** [comment]
I looked through the /sensu-go issue (https://github.com/sensu/sensu-enterprise-go/issues/956) and PR (https://github.com/sensu/sensu-enterprise-go/pull/974) as well as all the docs, and I think these are the pages that will need to be updated:
- https://docs.sensu.io/sensu-go/5.20/reference/agent/#configuration
- https://docs.sensu.io/sensu-go/5.20/reference/entities/
- https://docs.sensu.io/sensu-go/5.20/reference/events/
- https://docs.sensu.io/sensu-go/5.20/reference/tokens/#examples (there's an example entity at the end)
- https://docs.sensu.io/sensu-go/5.20/api/entities/
- https://docs.sensu.io/sensu-go/5.20/api/events/

I switched to the `feature/discover-services` branch, but I couldn't start the agent with the `--discover-services` flag:
```
{"component":"agent","error":"unknown flag: --discover-services","level":"fatal","msg":"error executing sensu-agent","time":"2020-04-21T10:33:58-05:00"}
```

**Comment by hillaryfraley** [comment]
I looked through the /sensu-go issue (https://github.com/sensu/sensu-enterprise-go/issues/956) and PR (https://github.com/sensu/sensu-enterprise-go/pull/974) as well as all the docs, and I think these are the pages that will need to be updated:
- https://docs.sensu.io/sensu-go/5.20/reference/agent/#configuration
- https://docs.sensu.io/sensu-go/5.20/reference/entities/
- https://docs.sensu.io/sensu-go/5.20/reference/events/
- https://docs.sensu.io/sensu-go/5.20/reference/tokens/#examples (there's an example entity at the end)
- https://docs.sensu.io/sensu-go/5.20/api/entities/
- https://docs.sensu.io/sensu-go/5.20/api/events/

I switched to the `feature/discover-services` branch, but I couldn't start the agent with the `--discover-services` flag:
```
{"component":"agent","error":"unknown flag: --discover-services","level":"fatal","msg":"error executing sensu-agent","time":"2020-04-21T10:33:58-05:00"}
```

**Comment by hillaryfraley** [comment]
I looked through the /sensu-go issue (https://github.com/sensu/sensu-enterprise-go/issues/956) and PR (https://github.com/sensu/sensu-enterprise-go/pull/974) as well as all the docs, and I think these are the pages that will need to be updated:
- https://docs.sensu.io/sensu-go/5.20/reference/agent/#configuration
- https://docs.sensu.io/sensu-go/5.20/reference/entities/
- https://docs.sensu.io/sensu-go/5.20/reference/events/
- https://docs.sensu.io/sensu-go/5.20/reference/tokens/#examples (there's an example entity at the end)
- https://docs.sensu.io/sensu-go/5.20/api/entities/
- https://docs.sensu.io/sensu-go/5.20/api/events/

I switched to the `feature/discover-services` branch, but I couldn't start the agent with the `--discover-services` flag:
```
{"component":"agent","error":"unknown flag: --discover-services","level":"fatal","msg":"error executing sensu-agent","time":"2020-04-21T10:33:58-05:00"}
```

**Comment by hillaryfraley** [comment]
I looked through the /sensu-go issue (https://github.com/sensu/sensu-enterprise-go/issues/956) and PR (https://github.com/sensu/sensu-enterprise-go/pull/974) as well as all the docs, and I think these are the pages that will need to be updated:
- https://docs.sensu.io/sensu-go/5.20/reference/agent/#configuration
- https://docs.sensu.io/sensu-go/5.20/reference/entities/
- https://docs.sensu.io/sensu-go/5.20/reference/events/
- https://docs.sensu.io/sensu-go/5.20/reference/tokens/#examples (there's an example entity at the end)
- https://docs.sensu.io/sensu-go/5.20/api/entities/
- https://docs.sensu.io/sensu-go/5.20/api/events/

I switched to the `feature/discover-services` branch, but I couldn't start the agent with the `--discover-services` flag:
```
{"component":"agent","error":"unknown flag: --discover-services","level":"fatal","msg":"error executing sensu-agent","time":"2020-04-21T10:33:58-05:00"}
```

**Comment by hillaryfraley** [comment]
I looked through the /sensu-go issue (https://github.com/sensu/sensu-enterprise-go/issues/956) and PR (https://github.com/sensu/sensu-enterprise-go/pull/974) as well as all the docs, and I think these are the pages that will need to be updated:
- https://docs.sensu.io/sensu-go/5.20/reference/agent/#configuration
- https://docs.sensu.io/sensu-go/5.20/reference/entities/
- https://docs.sensu.io/sensu-go/5.20/reference/events/
- https://docs.sensu.io/sensu-go/5.20/reference/tokens/#examples (there's an example entity at the end)
- https://docs.sensu.io/sensu-go/5.20/api/entities/
- https://docs.sensu.io/sensu-go/5.20/api/events/

I switched to the `feature/discover-services` branch, but I couldn't start the agent with the `--discover-services` flag:
```
{"component":"agent","error":"unknown flag: --discover-services","level":"fatal","msg":"error executing sensu-agent","time":"2020-04-21T10:33:58-05:00"}
```

**Comment by nikkictl** [comment]
@hillaryfraley were you on the `feature/discover-services` branch in **sensu-enterprise-go**? You must build from the commercial repo to access the commercial flag. Let me know if you need help!

**Comment by hillaryfraley** [comment]
I looked through the /sensu-go issue (https://github.com/sensu/sensu-enterprise-go/issues/956) and PR (https://github.com/sensu/sensu-enterprise-go/pull/974) as well as all the docs, and I think these are the pages that will need to be updated:
- https://docs.sensu.io/sensu-go/5.20/reference/agent/#configuration
- https://docs.sensu.io/sensu-go/5.20/reference/entities/
- https://docs.sensu.io/sensu-go/5.20/reference/events/
- https://docs.sensu.io/sensu-go/5.20/reference/tokens/#examples (there's an example entity at the end)
- https://docs.sensu.io/sensu-go/5.20/api/entities/
- https://docs.sensu.io/sensu-go/5.20/api/events/

I switched to the `feature/discover-services` branch, but I couldn't start the agent with the `--discover-services` flag:
```
{"component":"agent","error":"unknown flag: --discover-services","level":"fatal","msg":"error executing sensu-agent","time":"2020-04-21T10:33:58-05:00"}
```

**Comment by hillaryfraley** [comment]
yeah, I am on that branch in that repo. but it looks like I'm somehow on 5.14.0 for the agent...

**Comment by nikkictl** [comment]
@hillaryfraley as part of review in https://github.com/sensu/sensu-enterprise-go/pull/974/, it was decided that `--discover-services` would be renamed to `--discover-processes`.
