### ISSUE TITLE
Retain search on all docs pages while improving 404 page with search

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#2372]
### Description
We would like to rework the 404 page as described in https://github.com/sensu/sensu-docs/issues/447 without affecting the search function on the rest of the docs pages.

The 404 page work completed in https://github.com/sensu/sensu-docs/pull/2352 worked very well for the 404 page, but it seemed to result in the search function not working anywhere except our 404 page.

### Category

This is an issue with:

- [x] bug (bug in site build, layout, or functionality)
- [x] enhancement (add new or updated site functionality)

### Affected pages
All

### Expected behavior
The search functions works on all pages of the docs in addition to being implemented to improve the 404 page as previously completed in https://github.com/sensu/sensu-docs/pull/2352

### Current behavior
The changes in https://github.com/sensu/sensu-docs/pull/2352 seemed to interfere with the search working anywhere else in the docs, so we reverted it. The search currently works on regular docs pages, but we no longer have the new and improved 404 page.

**Comment by hillaryfraley** [comment]
@rnevius , could you take a look at this and see if you know what might have caused the search in the rest of the docs to stop working after we merged https://github.com/sensu/sensu-docs/pull/2352?

**Comment by rnevius** [comment]
The TL;DR is that we were doing `document.getElementById('#selector')` instead of `document.querySelector('#selector')`.
