### ISSUE TITLE
Document backup and recovery recommendations

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#2382]
### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Expected behavior

As a Sensu operator I can find documentation on recommended operational practices including backup and restore processes.

### Current behavior

Documentation does not describe recommended backup and restore processes.

### Additional context

Potential approaches include use of `etcd snapshots` or `sensuctl dump`. 

Etcd snapshots are theoretically sound but users have reported problems and we need to test it ourselves before recommending it.

Sensuctl dump has known issues when restoring, as some resources are dumped without fields required for recreating those resources in a restore operation. See https://github.com/sensu/sensu-go/issues/3326

**Comment by hillaryfraley** [comment]
Requires CRE/Engineering exploration before we start to write the content.

Note from a customer about what they tried before `etcd snapshots` -- we do not have info about using this in the docs.

Need to describe how to restore from a dump. Consider starting an addition to https://docs.sensu.io/sensu-go/latest/reference/backend/#operation (although it may need to be included elsewhere in the docs too).

Sensuctl includes dump functionality by default, so might want to start developing those instructions first. https://docs.sensu.io/sensu-go/latest/sensuctl/reference/#export-resources

**Comment by hillaryfraley** [comment]
Prioritize for after 5.20 docs and Monitor Sensu with Sensu guide.

May intersect with some of Aaron's work.

**Comment by hillaryfraley** [comment]
Notes from Eng meeting: https://docs.google.com/document/d/1gmZiPCRPF4oyinKWOTHb4gWIptes18xknSIQvxVFXhg/edit

**Comment by cwjohnston** [comment]
My notes on exploration thus far:

* core/v2.APIKey resources should be omitted
	* they can't be recreated from a dumped record
* ~secrets/v1.provider resources can't be dumped and should be omitted~ I can't reproduce this anymore so let's ignore for ow.
	* ~dumping them results in an API error `Error: API error:`~ https://github.com/sensu/sensu-enterprise-go/issues/1193
* User resources can't be recreated from dump output without manual modification
  * user resources must have a `password_hash` or `password` added
  * Need to document or link to docs on use of `sensuctl user hash-password` to generate password_hash values

**Comment by calebhailey** [comment]
Here's the WIP "intro" / "beginner level" backup and restore instructions I'm using in the new Sensu Go Workshop. I haven't added any narrative yet, but these are the basic steps I'm going to recommend.  

1. **Create a backup folder.** 

   ```shell
   $ mkdir backup
   ```
   
2. **Backup pipeline resources only (stripping namespaces for portability/reuse)...** 
   
   ```shell
   $ sensuctl dump assets,checks,hooks,filters,mutators,handlers,silenced,secrets/v1.Secret \
     --format yaml | grep -v "^\s*namespace:" > backup/pipelines.yaml
   ```
   
3. **Make a namespaced backup of the entire cluster (sans entities, events, apikeys)...**
   
   ```shell 
   $ sensuctl dump all \
     --omit entities,events,apikeys \
     --format yaml > backup/config.yaml
   ```
   
4. **Backup RBAC resources only...** 
   
   ```shell
   $ sensuctl dump apikeys,users,roles,rolebindings,clusterroles,clusterrolebindings
     --format yaml > backup/system-rbac.yaml
   ```
   
5. **Optionally backup entity resources? (TBD)** 
     
   ```shell
   $ sensuctl dump entities \
     --format yaml | grep -v "^\s*namespace:" > backup/inventory.yaml
   ```
   
6. **Restore everything, or a subset of things:** 
   
   ```shell
   $ sensuctl create -r -f backup/
   $ sensuctl create -f backup/pipelines.yaml
   ```
