### ISSUE TITLE
Update: Example external check result input

### ISSUE THREAD

**Issue by sumit-sngpt** [sensu/sensu-docs#240]
In the example showing the use of  Sensu client socket to input External result to Sensu server, it should also contain the field "executed". The events following the example and without "executed" field would cause the Sensu API not fetch and return the check details due to following code in it.
https://github.com/sensu/sensu/blob/master/lib/sensu/api/process.rb#L373

Ref:
https://sensuapp.org/docs/latest/clients#example-external-check-result-input

So, please change the example to following:
echo '{"name": "app_01", "output": "could not connect to mysql", "status": 1, "executed": _timestamp_ }' > /dev/tcp/localhost/3030

**Comment by calebhailey** [comment]
Hi there, @sumit-sngpt. :)

Sorry for the radio silence on this! I'm going close this issue due to inactivity (mostly on our part), and because I can't reproduce this (and I vaguely recall that we fixed this a long time ago). Please feel free to open a new issue if this is still a problem.
