### ISSUE TITLE
Update Postgres SR content

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#2400]
### Description
We will need to update the Postgres SR content to reflect the clarifications Edgar identified during testing.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [x] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/guides/scale-event-storage/#configure-postgres-streaming-replication

### Corrections needed
Need to identify changes based on notes at https://docs.google.com/document/d/1ZN33pSWHfkhWKWwF55dCCpaw3DMvkmERfiHe2OpkVQo/edit

**Comment by hillaryfraley** [comment]
Needs further review and investigation (need to know version of Postgres used to develop this doc)

**Comment by cwjohnston** [comment]
@treydock Will you please comment on which version of Postgres you used for the work in #2342 ?

**Comment by treydock** [comment]
Looks like my VM test environment had 9.6.17 installed from PostgreSQL repos via YUM.

**Comment by hillaryfraley** [comment]
~In several places, `To exit the PostgreSQL prompt, type /q.` -- this should be `\q` (backslash rather than forward)~ fixed in https://github.com/sensu/sensu-docs/pull/3152

In testing with the [skunkworks repo](https://github.com/sensu/skunkworks/tree/master/dockerfiles/sensu-go-postgres), I could not get past the `sudo cp /var/lib/pgsql/data/pg_hba.conf /var/tmp/pg_hba.conf.bak` command.
Here's the error I get: `cp: /var/lib/pgsql/data/pg_hba.conf: No such file or directory`

**Comment by mgibson323** [comment]
> ~In several places, `To exit the PostgreSQL prompt, type /q.` -- this should be `\q` (backslash rather than forward)~ fixed in #3152
> 
> In testing with the [skunkworks repo](https://github.com/sensu/skunkworks/tree/master/dockerfiles/sensu-go-postgres), I could not get past the `sudo cp /var/lib/pgsql/data/pg_hba.conf /var/tmp/pg_hba.conf.bak` command.
> Here's the error I get: `cp: /var/lib/pgsql/data/pg_hba.conf: No such file or directory`

In the docker image we have in Skunkworks, the path differs a bit, so this command should work: 

```
cp /var/lib/postgresql/data/pg_hba.conf /var/tmp/pg_hba.conf.bak
```
However, to proceed with the rest of the instructions you will need at least 2 Postgres containers.

**Comment by mgibson323** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [create vagrant cluster w/2 postgres nodes to test SR](https://trello.com/c/yzIqoBGq/601-create-vagrant-cluster-w-2-postgres-nodes-to-test-sr)

**Comment by mgibson323** [comment]
@hillaryfraley I got this working, near as I can tell, and I've [opened a PR](https://github.com/sensu/skunkworks/pull/81) for a Skunkworks Vagrant Sensu Cluster w/SSL and PostgreSQL 9.6

Edit: Updated the Skunkworks Vagrant instance to use PostgreSQL 12, so it should be easier to run through these steps.
