### ISSUE TITLE
Document token substitution for assets

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-docs#2404]
### Description
We will ship in 5.20 support for token substitution in various runtime assets for the following resources:

- checks (agent entity)
- hooks (agent entity)
- handlers (backend entity)
- mutators (backend entity)

See [the issue](https://github.com/sensu/sensu-go/issues/3639) and [the PR](https://github.com/sensu/sensu-go/pull/3720).

The (only?) main use cases are using token substitution in the URL of an asset, so each backend and/or agent can download assets from the appropriate URL, or for customizing the headers. It's important to note that the SHA512 value does not accept token substitution, for security reasons. Also, token substitution cannot be used in the filters; the filters already have access to the entity so it's not a concern.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [X] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
- https://docs.sensu.io/sensu-go/latest/reference/assets/ ?
- https://docs.sensu.io/sensu-go/latest/reference/tokens/

### Additional context

* Browser(s) and version(s): 
* OS:

**Comment by hillaryfraley** [comment]
This will benefit users by surfacing the actual location where the asset is unpacked. Some checks and mutators need the full path to where the asset has been unpacked on disk. For example, users on Windows platforms may write plugins on PowerShell, but if you don't run the PowerShell script in a specific way, you will not get the correct exit codes. The specific way you are supposed to run them is using the specific path on disk for the asset. The token sub will allow you to sub in the specific path on disk. Part of the path is the checksum for that asset. If an asset changes, it will have a different checksum and therefore the path on disk for the current version of the plugin will change. The token sub in this case means that users will not have to manually update their check commands (among other resources listed in Simon's original message above).

**Comment by palourde** [comment]
@hillaryfraley This is actually true for the subsequent work which will be tackled via https://github.com/sensu/sensu-go/issues/3662. Token substitution was the required building block.
