### ISSUE TITLE
The prefix used for the environment variables of sensu-backend is wrong

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-docs#2437]
### Description
In https://docs.sensu.io/sensu-go/latest/reference/backend/#configuration-via-environment-variables, we mention that the environment variable must be prefixed with `SENSU_`, which is not true since at least 5.15.0: https://github.com/sensu/sensu-go/commit/555e94e1d097f40491b5f18b20627db557a2208b

### Category

This is an issue with:

- [x] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/reference/backend/#configuration-via-environment-variables

### Expected behavior
The actual prefix for environment variables of sensu-backend is `SENSU_BACKEND`. e.g.

```
SENSU_BACKEND_STATE_DIR=/data/sensu/state-dir
SENSU_BACKEND_CACHE_DIR=/data/sensu/cache
[...]
```

### Additional context

* Browser(s) and version(s): 
* OS:

**Comment by hillaryfraley** [comment]
Thank you @palourde -- is this true for the agent too? In other words, is the prefix `SENSU_AGENT` for agent env vars?

**Comment by palourde** [comment]
@hillaryfraley Unfortunately no haha, the agent uses the `SENSU_` prefix so no changes are required on this side.
