### ISSUE TITLE
Supported Platforms is missing OSX

### ISSUE THREAD

**Issue by Blue0ctober** [sensu/sensu-docs#2439]
### Description

Supported platforms page is missing OSX support for sensuctl and sensu-agent
### Category

This is an issue with:

- [x] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

https://docs.sensu.io/sensu-go/latest/installation/platforms/
### Expected behavior

should include info on osx support for sensu-agent and sensuctl
### Corrections needed

see https://sensu.io/downloads
### Additional context

* Browser(s) and version(s): 
* OS:

**Comment by hillaryfraley** [comment]
Closing b/c we don't have package support for macOS and it's already listed as a binary-only distribution.
