### ISSUE TITLE
Navigation enhancements needed

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#2443]
### Description
We would like to understand more about the capabilities of our current theme in context of some changes we want to make to the way our documentation is organized, nested, and displayed. 

With that in mind, we have these questions:

1. Can we add more nested levels in our left-nav menu? For example, could we nest more pages of content under a page like https://docs.sensu.io/sensu-go/latest/sensuctl/reference/?

2. Can we configure the docs site so that clicking a menu item opens a page with content? For example, could we turn the "Sensuctl CLI" menu item (in the left nav of our docs https://docs.sensu.io/sensu-go/latest/) into a page that opens in the main panel when clicked and displays content (but still includes nested content as well)?

3. Can we add a menu on the right side of each docs page that picks up and links the H2 and H3 headers on each page? Essentially, this would be an automatically generated table of contents for each individual page. See https://grafana.com/docs/grafana/latest/installation/requirements/ (right side, under "On this page:") for an example.

4. Can we add a global widget somewhere near the top on every page that would include our invitations to contribute (e.g. "Edit this page" and "Open a docs issue")? Again https://grafana.com/docs/grafana/latest/installation/requirements/ has a good example just above the "On this page:" menu.

Can we incorporate any of these changes and still keep our current docs theme?

### Category

This is an issue with:

- [ ] bug (bug in site build, layout, or functionality)
- [x] enhancement (add new or updated site functionality)

### Affected pages
All

### Additional context
If we can achieve these changes with our current docs theme, we can create individual issues to make PRs against. For now, we want to understand whether any of these changes are possible with our current docs theme.

**Comment by rnevius** [comment]
So Sensu isn't actually using much of the hugo-material-docs theme anymore. Specifically, the theme only contains 10 lines of HTML and 2 images that aren't covered by the custom layouts and styles in this app. There's so much custom functionality baked into sensu-docs now that nearly all original theme layouts, shortcodes, and partials have been overridden. In effect, Sensu has its own Hugo theme at this point. 

To demonstrate, I have created [a new branch](https://github.com/sensu/sensu-docs/compare/demo/no-theme) that shows how easy it would be to completely drop hugo-material-docs as a dependency (I recommend doing this anyway at this point). 

So, with this in mind, we should determine whether or not the features requested in this issue can be added to our custom theme components.

> 1. Can we add more nested levels in our left-nav menu? For example, could we nest more pages of content under a page like https://docs.sensu.io/sensu-go/latest/sensuctl/reference/?

Yes, Hugo supports [menus with unlimited depth](https://gohugo.io/content-management/menus/), so we'd just have to modify the menu layout partial to support additional levels.

> 2. Can we configure the docs site so that clicking a menu item opens a page with content? For example, could we turn the "Sensuctl CLI" menu item (in the left nav of our docs https://docs.sensu.io/sensu-go/latest/) into a page that opens in the main panel when clicked and displays content (but still includes nested content as well)?

Yes, this would require a change similar to the one mentioned above.

> 3. Can we add a menu on the right side of each docs page that picks up and links the H2 and H3 headers on each page? Essentially, this would be an automatically generated table of contents for each individual page. See https://grafana.com/docs/grafana/latest/installation/requirements/ (right side, under "On this page:") for an example.

Yep, Hugo now has "Table of Contents" support, so adding something like this would be as simple as adding a new layout partial that implements the [`{{ .TableOfContents }}`](https://gohugo.io/content-management/toc/) page variable, and add the [necessary markup](https://gohugo.io/getting-started/configuration-markup/#table-of-contents) meta to page front matter.

> 4. Can we add a global widget somewhere near the top on every page that would include our invitations to contribute (e.g. "Edit this page" and "Open a docs issue")? Again https://grafana.com/docs/grafana/latest/installation/requirements/ has a good example just above the "On this page:" menu.

Yep, we can use the `.File.Path` of each section/page in `content/` to point to the relevant .md file in this repo. This could be accomplished via another partial that would be added to the shared layouts.

**Comment by hillaryfraley** [comment]
@rnevius thank you! This is great news. I wasn't expecting the answer to be yes in every case :D 

Is there a way to make the changes for item 2 without affecting the way the docs site looks now? If not, I think that's the only one that would have some dependencies (e.g. we'd need to write or reorganize some content to avoid blank pages).

**Comment by rnevius** [comment]
@hillaryfraley yes, I believe so. Those items are already HTML link (`<a>`) elements, they just don't have the `href` attribute. If I'm understanding you correctly, this should be as simple as adding an attribute in the existing menu range/loop.

**Comment by cwjohnston** [comment]
Hi @rnevius, thanks for investigating these aspects of our navigation!

> Those items are already HTML link (`<a>`) elements, they just don't have the `href` attribute. 

Is this the only change that's needed in order to realize the second item (clicking a menu item opens a page with content)? I think this makes sense conceptually but want to be sure.

**Comment by rnevius** [comment]
@cwjohnston the click handler for those items will also need to be updated so that clicking a chevron icon expands the submenu, but clicking the words opens the link. But yes, those are the only things.

**Comment by cwjohnston** [comment]
Thanks @rnevius.

We'd like to move ahead with the changes, broken up into individual pull requests where possible so we can examine the impacts of each change. 

Ideally we'd like to take them on in this order:

- [x] right-hand side table-of-contents for current page (number 3)
- [x] additional nested levels in left-hand nav (number 1)
- [ ] global right-hand nav (number 4, completion depends on Sensu team determining what content belongs here)
- [ ] clickable categories in left-hand nav (number 2, completion depends on Sensu team developing content for top-level categories)

Please let me know if you want individual issues for these deliverables or see any issue with breaking them up into individual PRs as suggested?

**Comment by rnevius** [comment]
@cwjohnston thanks, I think it's fine to keep this issue open, perhaps with an updated title. Separate PRs for each line item is a good idea. 

To clarify number 2, these top-level items do currently have content/templates, but only render the child/directory contents. For example: https://docs.sensu.io/sensu-go/latest/sensuctl/ . As you have stated, updating the UI for item number 2 will require the template update mentioned above as well as additional content from Sensu.

**Comment by rnevius** [comment]
@hillaryfraley Is item number 3 going to be replacing the existing contents that are shown on many pages? For example, should I remove the top links on [this page](https://docs.sensu.io/sensu-go/latest/api/auth/) (also in the screenshot below) and replace them with the auto-generated table of contents?

<img width="386" alt="image" src="https://user-images.githubusercontent.com/4516305/81947134-7ed0c900-9600-11ea-9c52-0134df507875.png">

**Comment by hillaryfraley** [comment]
@rnevius good question. We want to keep the top-of-page TOCs for right now.
edit: will it cause any problems with your work to keep them?

Will the right-side TOC travel down the page as readers scroll down?

**Comment by rnevius** [comment]
@hillaryfraley it can do that, if that's desirable. My main reason for asking the question is that the content is pretty similar (or even identical) on some pages. I wasn't sure if this was going to replace or complement the content that's already there. 👍

**Comment by hillaryfraley** [comment]
@rnevius yes, I see what you mean. We talked about it a bit yesterday -- we do intend for the right-side TOC to be a replacement. But we were unsure how those right-side TOCs would look with the API docs (some of those headings are really long). So we decided to keep the top-of-page TOCs right now. I have an idea to rewrite the API doc headings into shorter, plain language versions, but I haven't run it by Cameron yet.

**Comment by rnevius** [comment]
Thanks! I'll proceed and we can evaluate things in staging 👍

**Comment by rnevius** [comment]
Item number 3 has been completed in #2544

**Comment by hillaryfraley** [comment]
@rnevius we would like to go ahead with the next item in our priority list: adding more nested levels in our left-nav menu. For example, nesting more pages of content under a page like https://docs.sensu.io/sensu-go/latest/sensuctl/reference/.

**Comment by rnevius** [comment]
> Can we add a global widget somewhere near the top on every page that would include our invitations to contribute (e.g. "Edit this page" and "Open a docs issue")? Again https://grafana.com/docs/grafana/latest/installation/requirements/ has a good example just above the "On this page:" menu.

@cwjohnston / @hillaryfraley – This item is next up. Has the Sensu team determined the content for this section?

**Comment by hillaryfraley** [comment]
@rnevius can we switch the priority and make item 2 the next up?

   2. Can we configure the docs site so that clicking a menu item opens a page with content? For example, could we turn the "Sensuctl CLI" menu item (in the left nav of our docs https://docs.sensu.io/sensu-go/latest/) into a page that opens in the main panel when clicked and displays content (but still includes nested content as well)?

If so, we'd like to go ahead with this change. Thank you for checking.

**Comment by hillaryfraley** [comment]
@rnevius just checking in on this -- do you know when you expect to have a PR ready for review?

**Comment by hillaryfraley** [comment]
All four enhancements identified in this issue are complete! 🎉
