### ISSUE TITLE
Improve site indexing

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#2447]
### Description

From @sensu/growth-marketing team:

```
Looks like this page doesn't show up in the search results in the Docs: https://docs.sensu.io/sensu-go/latest/getting-started/sample-app/#deploy-sensu-agents-and-influxdb 

We are trying to get it to show when someone searches for "sidecar" on the website.
```

### Category

This is an issue with:

- [x] bug (bug in site build, layout, or functionality)
- [ ] enhancement (add new or updated site functionality)

### Expected behavior

Search should surface pages where "sidecar" is mentioned.

### Current behavior

Currently the search box doesn't surface any pages where "sidecar" is mentioned.

### Changes needed

Unsure of what changes need to be made. This might need @rnevius's expertise.

**Comment by hillaryfraley** [comment]
I think it doesn't show up because we removed all links to ../../sample-app in favor of linking directly to https://github.com/sensu/sensu-k8s-quick-start in this PR: https://github.com/sensu/sensu-docs/pull/2133.

We left the ../../sample-app file in the docs repo though because the idea was to fix the problems and restore it: https://github.com/sensu/sensu-docs/issues/2027

**Comment by rnevius** [comment]
@hillaryfraley that's correct. DocSearch simply crawls the Sensu Docs site via its internal links. If it's not linked somewhere, it won't show up in the search.

**Comment by hillaryfraley** [comment]
I followed up with the Growth team to ask if DA can help us resolve the issues in the sample app: https://sensu.slack.com/archives/C6AF34L6R/p1589486930074400

**Comment by hillaryfraley** [comment]
I followed up with the dev advocates (I should have contacted them directly to begin with): https://sensu.slack.com/archives/CCBBAAZQW/p1591623677174900

**Comment by hillaryfraley** [comment]
Closing this issue in favor of https://github.com/sensu/sensu-docs/issues/2027

Dev Advocates will take a look at the issues in the sample-app.md doc. When those issues are resolved, we can restore this page in our docs and a search for `sidecar` should surface the sample-app.md doc.
