### ISSUE TITLE
Document creating a service account for checks 

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#2454]
### Description

While we have RBAC well documented, I believe there's a piece that's missing, namely creating a service account for resources like the aggregate check and remediation handler.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

Probably should live in RBAC, though could move to a 'best practices' guide .

### Expected behavior

Have a clear section that outlines service accounts in Sensu Go.

The alternative would be to update the plugin readmes to include the permissions that a plugin needs.

**Comment by hillaryfraley** [comment]
Resolve by adding an example for the EC2 handler. We could do this by repurposing the "Create a read-only user" guide to cover more examples. Or we could create a separate guide like "Create a limited service account" using the EC2 handler as a use case.
