### ISSUE TITLE
POST & PUT requests to events API won't return a response body

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-docs#2459]
### Description
Context: https://sensucommunity.slack.com/archives/C9BB9AW7K/p1589487879288700

These requests will not return a response body, which is the intended behavior.

### Category

This is an issue with:

- [x] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
- https://docs.sensu.io/sensu-go/latest/api/events/#eventsentitycheck-post
- https://docs.sensu.io/sensu-go/latest/api/events/#eventsentitycheck-put
- ???

### Corrections needed
Only a 204 response code is returned, with an empty body.

### Additional context

* Browser(s) and version(s): 
* OS:

**Comment by tadeboro** [comment]
Just a small correction: PUT returns 201, not 204.
