### ISSUE TITLE
Proxy entities do not (and should not?) need subscriptions?

### ISSUE THREAD

**Issue by ichilton** [sensu/sensu-docs#2475]
### Description

On this page: https://docs.sensu.io/sensu-go/latest/reference/entities/

It includes the following:

> NOTE: The proxy entity definition must include the same subscriptions as the sensu-agent to work with round robin scheduling and proxy requests attributes. If more than one sensu-agent will execute a proxy check and you did not configure the proxy entity with the same subscriptions as the sensu-agent, the sensu-backend will log an error and the proxy check will not be scheduled for agents to run.

I don't find this to be true.

I've not set any subscriptions on the proxy entity (as I don't understand why you'd want/need to?) and the checks appear to be executed fine.

### Category

This is an issue with:

- [x] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

https://docs.sensu.io/sensu-go/latest/reference/entities/

### Expected behavior

I think the behaviour of sensu-go seems to be correct and this should be removed from the documentation.

### Current behavior

I think the behaviour is correct.

### Corrections needed

I think the quoted section should be removed.

**Comment by echlebek** [comment]
Confirmed! The docs appear to be lying.

**Comment by hillaryfraley** [comment]
@cwjohnston to re-test

**Comment by cwjohnston** [comment]
@hillaryfraley I've retested with both 5.14.2 and latest, and found that checks are executed on behalf of a proxy entity even when that proxy entity does not have subscriptions matching the check's subscriptions. 

As I understand it, the behavior I am seeing is the desired behavior. Therefore, we should remove the callout in question from all current versions of the docs.

**Comment by hillaryfraley** [comment]
@ichilton thank you for finding and reporting this issue. @echlebek and @cwjohnston thank you for testing and confirming. I removed the notes from the current docs in https://github.com/sensu/sensu-docs/pull/2579.

**Comment by ichilton** [comment]
That's great news! - as I rely on that functionality! :)

Thanks all!

Ian
