### ISSUE TITLE
Add links for FIPS-supported tarballs

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-docs#2505]
### Description
With the release of 5.21 we will be shipping two new tarballs (and zips) for `linux/amd64`.

These are the links for the tarballs that will be released:

#### OpenSSL 1.0 with FIPS support
* https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/5.21.0/sensu-go-openssl-1.0_5.21.0_linux_amd64.tar.gz
* https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/5.21.0/sensu-go-openssl-1.0_5.21.0_linux_amd64.zip

#### OpenSSL 1.1 with FIPS support
* https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/5.21.0/sensu-go-openssl-1.1_5.21.0_linux_amd64.tar.gz
* https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/5.21.0/sensu-go-openssl-1.1_5.21.0_linux_amd64.zip

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

**Comment by cwjohnston** [comment]
per internal conversations, we’re not going to document the download links for FIPS builds at this time. Instead, we’ll provide the download links upon request.

**Comment by hillaryfraley** [comment]
Closing for now ^
