### ISSUE TITLE
Document new `--require-openssl` and `--require-fips` flags

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-docs#2506]
### Description
With the release of 5.21, two new flags will be supported in both the agent & backend.

**NOTE:** These flags only exist within the new OpenSSL-linked binaries. See https://github.com/sensu/sensu-docs/issues/2505 for more information.

`--require-openssl` will ensure that OpenSSL is being used instead of Go's standard cryptography library.
`--require-fips` will ensure that OpenSSL is operating in FIPS mode.

### Category
This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/reference/agent/
https://docs.sensu.io/sensu-go/latest/reference/backend/

**Comment by hillaryfraley** [comment]
@amdprophet I will need the text displayed for each flag in the response for `sensu-backend start -h` and `sensu-agent start -h` to complete the PR.
Edit: PR is https://github.com/sensu/sensu-docs/pull/2511

**Comment by cwjohnston** [comment]
When we document these flags we should call out that these builds are available by contacting us via https://sensu.io/contact
