### ISSUE TITLE
Floating TOC broke embedded Katacoda scenario pages

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#2531]
### Description
Merging the floating TOC PR (#2466) seems to have squished our pages with embedded Katacoda scenarios. I added our `toc: false` indicator to the top of each page (https://github.com/sensu/sensu-docs/pull/2530), but this does not seem to fix the problem.

### Category

This is an issue with:

- [x] bug (bug in site build, layout, or functionality)
- [ ] enhancement (add new or updated site functionality)

### Affected pages
- https://docs.sensu.io/sensu-go/latest/learn/learn-in-15/
- https://docs.sensu.io/sensu-go/latest/learn/up-and-running/
- https://docs.sensu.io/sensu-go/latest/learn/sensu-pagerduty/

### Expected behavior
These pages should display the scenario across the normal width of the page (similar to the scenarios as hosted on the Katacoda site at https://www.katacoda.com/sensu)

### Current behavior
![embedded-scenarios](https://user-images.githubusercontent.com/19190208/84678297-d747fe80-aefd-11ea-833b-5aef437cddee.gif)

### Changes needed
The Katacoda scenarios should display properly on our docs pages that include embedded scenarios.

### Additional context
If this is not a quick fix, I can revert #2466

**Comment by rnevius** [comment]
Should be a quick style change. I'll submit a PR ASAP.
