### ISSUE TITLE
Floating TOC broke platform switcher

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#2536]
### Description
I reverted https://github.com/sensu/sensu-docs/pull/2466 and https://github.com/sensu/sensu-docs/pull/2532 because I found another issue after they were merged: the platform switcher didn't seem to work.
![platform-switcher](https://user-images.githubusercontent.com/19190208/84690991-63afec80-af11-11ea-8cc1-699311d2d87e.gif)

I restored the feature/navigation-enhancements branch in hopes that the issue can be fixed there.

### Category

This is an issue with:

- [x] bug (bug in site build, layout, or functionality)
- [ ] enhancement (add new or updated site functionality)

### Affected pages
Pages that include the platform switcher, like https://docs.sensu.io/sensu-go/latest/installation/install-sensu/#install-the-sensu-backend

### Expected behavior
When a reader clicks one of the platform tabs, the page should display the corresponding code for that platform.

### Current behavior
When a reader clicks any of the platform tabs except the first, the place where the corresponding code should be displayed is blank.

Note that I reverted the floating TOC change in https://github.com/sensu/sensu-docs/pull/2533, so the published docs site currently works as expected. The behavior described here is shown in the gif above.

### Changes needed
(if possible) update branch feature/navigation-enhancements so the change to add the floating TOC does not break the platform switcher

**Comment by rnevius** [comment]
Just a heads up that this is the upgrade to Hugo 0.72.0 causing the issue. This upgrade happened in the same PR as the floating ToC.

**Comment by hillaryfraley** [comment]
Thanks @rnevius . So this is something we can resolve by sticking with Hugo version 0.56.1? Or will that ruin the work in feature/navigation-enhancements?

**Comment by rnevius** [comment]
@hillaryfraley the latter. We need newer versions of Hugo, because goldmark and the Table of Contents feature were added relatively recently. 👍
