### ISSUE TITLE
Document the SAML authentication provider

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-docs#2540]
### Description
This is a placeholder for the upcoming work that will performed under this epic: https://github.com/sensu/sensu-enterprise-go/issues/93.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [x] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/installation/auth/ ?

### Expected behavior

We will probably need to provide similar documentation to the OIDC provider.

### Additional context

* Browser(s) and version(s): 
* OS:

**Comment by hillaryfraley** [comment]
The SAML auth epic (https://github.com/sensu/sensu-enterprise-go/issues/93) is closed (stale)
