### ISSUE TITLE
Adjust the users password & reset_password API endpoints

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-docs#2563]
### Description

Following the changes made in 5.21 via https://github.com/sensu/sensu-go/pull/3753, the `/users/:user/password` endpoint payload had to be modified, and a new `/users/:user/reset_password` endpoint was added.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/api/users/

### Expected behavior

1. We should document the new `/users/:user/reset_password` endpoint. It requires explicit permissions on `users`, but compared to `/users/:user/password`, it does not require the current password, only the new password hashed via bcrypt:

```
$ curl -X PUT \
-H "Authorization: Key $SENSU_API_KEY" \
-H 'Content-Type: application/json' \
-d '{
  "username": "alice",
  "password_hash": "$2a$10$KVI0qsoHHLh9eE8xkEeO7uLkSq./3UfYuL0BdfE9G14TIevjsY/B6"
}' \
http://127.0.0.1:8080/api/core/v2/users/alice/reset_password
```

2. We should update `/users/:user/password` to reflect the new payload; `password` is the current password, in cleartext & `password_hash` is the new hashed password via bcrypt. The difference here is that a simple user, without any permissions, is able to use this API to change its own password, whereas `reset_password` requires some explicit permissions.

```
$ curl -X PUT \
-H "Authorization: Key $SENSU_API_KEY" \
-H 'Content-Type: application/json' \
-d '{
  "username": "alice",
  "password": "P@ssw0rd!",
  "password_hash": "$2a$10$KVI0qsoHHLh9eE8xkEeO7uLkSq./3UfYuL0BdfE9G14TIevjsY/B6"
}' \
http://127.0.0.1:8080/api/core/v2/users/alice/password
```

3. We should update the example given in https://docs.sensu.io/sensu-go/latest/api/users/#usersuser-put so we don't suggest that for resetting a password, but instead for adjusting the groups for example.

### Additional context

* Browser(s) and version(s): 
* OS:

**Comment by hillaryfraley** [comment]
@palourde does #2 mean a user now needs the password_hash to change their own password? I'm trying to use the `/users/:user/password` endpoint to change my own password with no hash and getting `400 Bad Request {"message":"a password or its hash is required","code":1}`

**Comment by palourde** [comment]
@hillaryfraley That's right; you need to provide both the current password in cleartext via `password` and the new hashed password via `password_hash`.

**Comment by hillaryfraley** [comment]
@palourde Is the 400 message incorrect then? The "or" makes me think I can provide one or the other.

Are the notes in the `password` and `password_hash` description tables incorrect then? http://localhost:1313/sensu-go/5.21/reference/rbac/#password
http://localhost:1313/sensu-go/5.21/reference/rbac/#password_hash

The notes say you only need password or hash but not both. I am fixing the formatting in that doc btw

**Comment by palourde** [comment]
@hillaryfraley Yeah, the message is a bit misleading, but the application is different; the `password` & `password_hash` fields are both only required for the `/users/:user/password` endpoint. Creating/updating users via `sensuctl create/edit` is different and does not require the same payload.

**Comment by hillaryfraley** [comment]
OK. So if you use the API you *do* need both for *both* endpoints? I think I should be as clear as possible about that in the reference notes.

**Comment by palourde** [comment]
For `/users/:user/reset_password`, you only provide the new password via `password_hash`.

For `/users/:user/password`, you need to provide both the current cleartext password (`password`) and the new hashed password (`password_hash`).

For POST `/users` or PUT `/users/:user`, you should only provide one of them; the payload is the actual user resource as referenced in https://docs.sensu.io/sensu-go/latest/reference/rbac/#user-specification.

Makes more sense?

**Comment by hillaryfraley** [comment]
Yep, it does, thank you
