### ISSUE TITLE
Asset Reference documentation missing useful information

### ISSUE THREAD

**Issue by rst-ack** [sensu/sensu-docs#2588]
### Description
The [asset reference documentation for Sensu Go](https://docs.sensu.io/sensu-go/latest/reference/assets/) doesn't explain that any registered assets aren't downloaded/fetched until a check that references the asset is executed. This can be confusing for new users that are expecting to find the downloaded asset files as soon as they asset is registered via `sensuctl asset add`.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [x] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/reference/assets/

### Expected behavior
Explain that registered assets won't be downloaded until a check that references the asset in their definition is executed.

### Current behavior
There is currently nothing that explains anything about the expected behavior.

**Comment by hillaryfraley** [comment]
@llamalump thank you for opening this issue. I will work on a PR to address it.

**Comment by jspaleta** [comment]
Hey @llamalump 
It seems to me like there is an attempt made to communicate this information here:
https://docs.sensu.io/sensu-go/latest/reference/assets/#asset-build-installation

Maybe its just a matter of reorganizing this section and highlight a couple of important pieces of information as highlighted notes.

### Possible textual change to consider:
https://docs.sensu.io/sensu-go/latest/reference/assets/#asset-build-installation


Sensu will download an asset build on the host system where the asset contents are needed to execute the requested command.
For example, when an asset is referenced as part of a check definition, the Sensu agent executing the check will download the asset the first time the check requesting the asset is executed. Which asset build an agent downloads will depend on the filter rules associated with each build defined for the asset.   A similar process occurs for Sensu backends when pipeline elements (filter, mutator, and handler) request an runtime asset be installed as part of operation. 

```
Note: Asset builds are not downloaded until they are needed for command execution
```

When Sensu finds a matching build, it downloads the build artifact from the specified URL. If the asset definition includes headers, they are passed along as part of the HTTP request. If the downloaded artifact’s SHA512 checksum matches the checksum provided by the build, it is unpacked into the Sensu service’s local cache directory.

Set the backend or agent’s local cache path with the --cache-dir flag. Disable assets for an agent with the agent --disable-assets configuration flag.

```
Note: Asset builds are unpacked into cache directory configured using --cache-dir flag
```

Use the --assets-rate-limit and --assets-burst-limit flags for the agent and backend to configure a global rate limit for fetching assets.

**Comment by rst-ack** [comment]
To me, the way the section reads as is currently published doesn't attempt to communicate that information, @jspaleta.

But the revised paragraph you wrote in your reply is very nice - it calls it out very explicitly, with specific caveats and provisions, what happens (or doesn't happen) when an asset is registered. 

A big +1 from me to your proposed revision.

**Comment by jspaleta** [comment]
lgtm

**Comment by hillaryfraley** [comment]
@llamalump thanks again! We've updated the documentation: https://docs.sensu.io/sensu-go/latest/reference/assets/#asset-build-download
