### ISSUE TITLE
Document breaking database schema for 6.0 entity store

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-docs#2598]
### Description
See https://github.com/sensu/sensu-go/blob/master/CHANGELOG.md#breaking:
> The database schema for entities has changed. After upgrading, users will not
be able to use their database with older versions of Sensu.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
I'm not sure what the entire scope is, but we'll probably need ~API and reference docs for `EntityConfig` and `EntityState` with~ notes about backwards compatibility and migration tooling.

_Edit:_ Eric informs me that API and reference docs for `EntityConfig` and `EntityState` probably aren't necessary yet since the user won't interact with these types.

### Additional context
- https://github.com/sensu/sensu-go/commit/7fce7eb37c92108e71904596286d6dc5d6a917b2
- [Proposal: core/v3.Entity API](https://docs.google.com/document/d/1p43VdkuSU4_lndiVZ_K-5cQryEpNCAOBmVeaqmAaubk/edit#heading=h.letafivq6wet)

cc @echlebek

**Comment by hillaryfraley** [comment]
@nikkictl and @echlebek Similar question as in https://github.com/sensu/sensu-docs/issues/2597#issuecomment-660312741, although it sounds like this might be mainly for people upgrading from 5.x. Even so, I imagine some parts of the 6.0 docs need to be rewritten to accurately reflect how things work in 6.0...

**Comment by echlebek** [comment]
New users will not need to know about this. Existing users will need to understand that once they upgrade their database to 6.0 (`sensu-backend upgrade`), they will not be able to downgrade to the 5.x series.

The `sensu-backend` command will warn them about this, and remind them that it would be a good idea to create a backup.

**Comment by hillaryfraley** [comment]
Thank you, @echlebek! I added a note to the upgrade instructions in https://github.com/sensu/sensu-docs/pull/2622 to address this.
