### ISSUE TITLE
Add context about runtime assets to guide

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-docs#2599]
### Description
https://github.com/sensu/sensu-go/issues/3885 was sparked by a [Reddit thread](https://www.reddit.com/r/sysadmin/comments/hl2xiu/is_sensu_go_broken_or_am_i_incompetent/) to improve messaging and context around runtime assets, how/when/where they are downloaded, and how they relate to other Sensu resources.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/guides/monitor-server-resources/

### Expected behavior
Documentation of `sensuctl asset add` should summarize the new help usage. 
```
$ sensuctl asset add sensu/monitoring-plugins
no version specified, using latest: 2.5.2
fetching bonsai asset: sensu/monitoring-plugins:2.5.2
added asset: sensu/monitoring-plugins:2.5.2

You have successfully added the Sensu asset resource, but the asset will not get downloaded until
it's invoked by another Sensu resource (ex. check). To add this runtime asset to the appropriate
resource, populate the "runtime_assets" field with ["sensu/monitoring-plugins"].
```

### Current behavior
No mention of when/where/how assets are downloaded or how the connect to other Sensu resources. 

### Corrections needed
Add summary of help usage for additional context around `sensuctl asset add`.

### Additional context
- https://github.com/sensu/sensu-go/pull/3893
- https://github.com/sensu/sensu-go/issues/3885
- [Reddit thread](https://www.reddit.com/r/sysadmin/comments/hl2xiu/is_sensu_go_broken_or_am_i_incompetent/)

**Comment by hillaryfraley** [comment]
@nikkictl is this part of 6.0? It looks like it based on https://github.com/sensu/sensu-go/pull/3893 so I added it to that milestone but thought I should make sure.

**Comment by hillaryfraley** [comment]
Tracking other docs where we should probably add this:

- https://docs.sensu.io/sensu-go/latest/sensuctl/sensuctl-bonsai/
- https://docs.sensu.io/sensu-go/latest/guides/monitor-external-resources/#register-assets
- https://docs.sensu.io/sensu-go/latest/guides/influx-db-metric-handler/#register-the-asset
- https://docs.sensu.io/sensu-go/latest/guides/send-slack-alerts/#register-the-asset
- https://docs.sensu.io/sensu-go/latest/guides/email-handler/#add-the-email-handler-asset
- https://docs.sensu.io/sensu-go/latest/guides/install-check-executables-with-assets/#register-the-sensu-pagerduty-handler-asset
- https://docs.sensu.io/sensu-go/latest/guides/reduce-alert-fatigue/#approach-2-use-an-event-filter-asset
- https://docs.sensu.io/sensu-go/latest/guides/contact-routing/#1-register-the-has-contact-filter-asset
