### ISSUE TITLE
Document new package architectures

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-docs#2611]
### Description
We're shipping deb & rpm packages for additional Linux architectures with the 6.0 release. See https://github.com/sensu/sensu-enterprise-go/pull/1147 for a list of the new architectures and the list of repositories we'll be publishing each package to.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [x] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
* Downloads page
* Supported Platforms https://docs.sensu.io/sensu-go/latest/platforms/

**Comment by hillaryfraley** [comment]
@amdprophet it looks like the only packages listed in your PR https://github.com/sensu/sensu-enterprise-go/pull/1147 that are not included at https://docs.sensu.io/sensu-go/latest/platforms/#supported-packages are the Raspbian ones. For packages, we list distribution and version but not architectures in the docs.

Are the Raspbian packages new for 6.0? Or do they need to be added at https://docs.sensu.io/sensu-go/latest/platforms/#supported-packages for earlier Sensu versions?
