### ISSUE TITLE
Note on system information gathering by agents

### ISSUE THREAD

**Issue by ccressent** [sensu/sensu-docs#2614]
### Description

We've decided that the best course of action in order to resolve https://github.com/sensu/sensu-go/issues/2027 might be to have a note somewhere in the documentation, or at least in our internal knowledge base.

None of our [supported packages](https://docs.sensu.io/sensu-go/latest/platforms/) are affected, so maybe it doesn't belong in the public documentation.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [x] improvement (improve docs content or format)

### Corrections needed

Decide if the note about `lsb_release` belongs in the public documentation. If it does, we need to find where to add a small paragraph about potentially having to install `lsb_release` on agents that report some empty system information.

**Comment by hillaryfraley** [comment]
@ccressent even though our packages aren't affected, are our binary distributions?

I'm trying to figure out if our users would ever encounter this or need to be aware of it for any reason. If they would not, then I'm not sure I would put it in our docs.

**Comment by ccressent** [comment]
Binaries are not affected in themselves; what matters is where one ends up running those binaries.
If it ends up on an agent running a less known Linux Distribution, it _could_ fail to report some of that system information. That's not very likely, but it could happen.

I too have mixed feelings about including this in the docs, especially given that it's rarer and rarer as the library we use, `gopsutil`, is updated to provide explicit support to more and more distributions.

Maybe this should just be a "note to ourselves" to help support a customer if they ever run into this (unlikely).

**Comment by hillaryfraley** [comment]
@ccressent thank you for the clarification.

Maybe this note to ourselves would be appropriate in https://github.com/sensu/reliability/wiki? Or is there a place that Eng keeps track of this kind of thing?

**Comment by ccressent** [comment]
That wiki seems appropriate; I can't think of a place where Engineering keeps track of such notes. Maybe scattered across our documents in our company Google Drive.

**Comment by hillaryfraley** [comment]
asked about a good place to document this in https://sensu.slack.com/archives/C3MHLUP46/p1595942335115500

**Comment by hillaryfraley** [comment]
Cameron's suggestion is to add this in Troubleshooting: if you're running the agent on a platform that isn't specifically supported, the tools might fail to properly identify the version of Linux you're running and therefore download the wrong asset version.

Add in section about assets: Filters might not match when you expect them to is the agent cannot correctly determine your version of Linux.

**Comment by ccressent** [comment]
That seems very appropriate to me!
