### ISSUE TITLE
Add API documentation for Javascript filter execution environment

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-docs#2632]
### Description
We are adding two new functions to the javascript event filter execution environment, per https://github.com/sensu/sensu-enterprise-go/pull/1151#pullrequestreview-450269815.

The Javascript execution environment will now provide the functions:
```
sensu.FetchEvent(entity, check)
sensu.ListEvents()
```

We need to document how these functions work, and their error cases.

It's unclear to me if this fits well within the existing event filtering documentation.

**Comment by hillaryfraley** [comment]
@echlebek Are these Sensu query expressions? https://docs.sensu.io/sensu-go/latest/reference/sensu-query-expressions/

**Comment by echlebek** [comment]
@hillaryfraley yes! I forgot we called them that.

**Comment by echlebek** [comment]
The thing is, these, by themselves, do not constitute Sensu Query Expressions. Sensu Query Expressions are expressions that return a boolean value. These functions return complex data.

**Comment by hillaryfraley** [comment]
There are actually 4 of these in 6.0.0:
```
sensu.CheckDependencies
sensu.EventStatus
sensu.ListEvents
sensu.FetchEvent
```

See https://gist.github.com/echlebek/7453391056b158cd44776b95d021c8dc
