### ISSUE TITLE
Update secrets docs to clarify secrets paths

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#2636]
### Description
Sensu currently requires the Vault secret path `secret/`, but this will be fixed in a future version.

When we fix this requirement so Vault secrets can have any path, we must also update the docs.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Expected behavior
Docs should reflect Sensu's requirements w/r/t Vault secret paths.

Restore in the note under https://docs.sensu.io/sensu-go/latest/operations/manage-secrets/secrets-management/#use-hashicorp-vault-for-secrets-management:

In addition, this guide uses the [Vault KV secrets engine](https://www.vaultproject.io/api/secret/kv/kv-v2.html) with the path `"secret/"`.

Restore in the note under https://docs.sensu.io/sensu-go/latest/operations/manage-secrets/secrets-management/#create-your-vault-secret:

The Vault dev server is preconfigured with the `secret` keyspace already set up, so we recommend using the `secret/` path for the `id` value while you are learning and getting started with Vault secrets management.

Replace the last paragraph of https://docs.sensu.io/sensu-go/latest/reference/secrets/#secret-examples with:

The `id` value for secrets that target a HashiCorp Vault must start with the name of the secret's path in Vault.
The [Vault dev server][10] is preconfigured with the `secret` keyspace already set up.
This is convenient for learning and getting started with Vault secrets management, so this example and our guide to [Secrets management][11] use the `secret/` path for the `id` value.
In this example, the name of the secret is `database`.
The `database` secret contains a key called `password`, and its value is the password to our database.

### Additional context
https://github.com/sensu/sensu-enterprise-go/issues/1152

**Comment by hillaryfraley** [comment]
@palourde does this issue cover the same ground as https://github.com/sensu/sensu-docs/issues/2682?

**Comment by palourde** [comment]
@hillaryfraley Ah yes, never realized we already had an issue for that, my bad! Feel free to close mine

**Comment by hillaryfraley** [comment]
@palourde np -- I think your issue includes better detail so I'll just keep them both open and close them both with the same PR when the time comes. Thank you!
