### ISSUE TITLE
Okta OIDC instructions need update

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#2647]
### Description

It seems Okta UI has changed, so our instructions don't help as much as we'd like.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

https://docs.sensu.io/sensu-go/latest/operations/control-access/auth/

### Expected behavior

Documented instructions are usable.

### Current behavior

Documented instructions reference settings/sections no longer present in Okta UI.

### Screenshots

![2020-07-24 at 2 00 PM](https://user-images.githubusercontent.com/148017/88578582-0629b800-d006-11ea-958b-1f935a7ae2d1.png)

### Additional context

Ideally we'd figure out how to reduce coupling with Okta or any other provider such that users have enough context from us to follow their provider's instructions.

* Browser(s) and version(s): 
* OS:

**Comment by hillaryfraley** [comment]
We may need to remove these instructions and replace them with specific setups users need to work with Okta support to implement depending on the application they need.

**Comment by hillaryfraley** [comment]
@cwjohnston is this issue related to https://github.com/sensu/sensu-docs/issues/2700?

**Comment by cwjohnston** [comment]
@hillaryfraley yep, it looks like 2700 describes the changes needed to update the content I've singled out here.
