### ISSUE TITLE
Add Prometheus check output format

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-docs#2650]
See https://github.com/sensu/sensu-go/pull/3945 for updates on `output_metric_format`.

**Comment by hillaryfraley** [comment]
@nikkictl it looks like this is not part of 6.0, is that right?

**Comment by nikkictl** [comment]
As of now, it doesn't look like the Prometheus metric transformer will be in 6.0. The PR is targeting master.

**Comment by hillaryfraley** [comment]
@nikkictl any idea if this is going in 6.1? I am not sure if this ended up going in 6.0 or not.

**Comment by nikkictl** [comment]
@hillaryfraley the respective PR has been merged to master, so I expect this to ship for 6.1!
