### ISSUE TITLE
Monitor Sensu with Sensu: Add examples of inspecting JSON response body

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#2658]
### Description
The Monitor Sensu with Sensu guide should include examples of inspecting JSON response body.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [x] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/operations/monitor-sensu/monitor-sensu-with-sensu/

### Expected behavior
The guide includes examples of checks that inspect the JSON response body.

### Current behavior
The checks in the guide are only looking for a 200 instead of looking for content.

### Corrections needed
Add examples of inspecting the JSON response body.

### Additional context
Original PR to merge the guide: https://github.com/sensu/sensu-docs/pull/2568

Slack discussion w/Aaron re: feedback about checks in guide: https://sensu.slack.com/archives/DN2HUT999/p1595971107001100

**Comment by hillaryfraley** [comment]
@asachs01 does https://github.com/sensu/sensu-docs/pull/2706 close this issue?

**Comment by asachs01** [comment]
Yup! This closes it.
