### ISSUE TITLE
Invalid authorization header in the example

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-docs#2663]
### Description

The authorization header is case sensitive, so the `curl` example with the header `-H "Authorization: KEY $SENSU_API_KEY"` will always return `{"Code": 5, "Message": "bad credentials"}`. 

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

See: https://docs.sensu.io/sensu-go/latest/api/apikeys/#apikeys-get-example

### Expected behavior

It works with the correct case header `-H "Authorization: Key $SENSU_API_KEY"`. 

### Current behavior

Using the header `-H "Authorization: KEY $SENSU_API_KEY"` will always return `{"Code": 5, "Message": "bad credentials"}`. 

### Corrections needed

`s/KEY/Key/` 😄 

### Screenshots

n/a

### Additional context

* Browser(s) and version(s): n/a
* OS: Debian 10.x

**Comment by hillaryfraley** [comment]
Gah-- thank you. Fixing now.
