### ISSUE TITLE
Add a redirect for RBAC guide

### ISSUE THREAD

**Issue by bananabele** [sensu/sensu-docs#2685]
Link to page: 
Old link: https://docs.sensu.io/sensu-go/latest/guides/create-read-only-user/
new link: https://docs.sensu.io/sensu-go/latest/operations/control-access/create-read-only-user/

### Feedback

The email course links to the first link on creating a read-only user in RBAC, and we have yet to do an audit of other broken links (and other pages on our site that may link to the old page), so a redirect would be great when you have a chance!

**Comment by hillaryfraley** [comment]
Argh sorry about that. I had the redirects up but for some reason I redirected "create-a-read-only-user" instead of "create-read-only-user"

Fixing it now...
