### ISSUE TITLE
Docs Feedback: entity & events response codes not clear/correct

### ISSUE THREAD

**Issue by mkobel** [sensu/sensu-docs#2693]
Create a new entity: https://docs.sensu.io/sensu-go/latest/api/entities/#create-a-new-entity

* Example text says `201` on success
* Example shows `201` on success
* API Specification says `200` on success

Create or update an entity: https://docs.sensu.io/sensu-go/latest/api/entities/#entitiesentity-put

* Example text says `201` on success
* Example shows `201` on success
* API Specification says `201` on success
* API returns 200 on success (sensu-go-backend 6.0.0-3003, debian buster amd64: sensu-backend version 6.0.0+ee, enterprise edition, build 98694fcc4ee5552bcdd4f394aa39e4f0466cbaf2, built 2020-08-07T19:06:58Z, built with go1.13.15)

Create a new event: https://docs.sensu.io/sensu-go/latest/api/events/#create-a-new-event

* Example text says `200` on success
* Example shows `201` on success
* API Specification says `201` on success

**Comment by hillaryfraley** [comment]
@mkobel , thank you for creating this issue. I will get these response codes corrected ~this week~ in two weeks 😅
