### ISSUE TITLE
Document Azure AD setup steps

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#2694]
### Description
Add steps for setting up Sensu Go with Azure AD.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/operations/control-access/auth/

### Expected behavior
Documentation includes steps required to set up Sensu Go with Azure AD

### Current behavior
Docs do not explain setup with Azure AD

### Corrections needed
Add steps required to set up Sensu Go with Azure AD

### Additional context
https://sensu.slack.com/archives/CCBBAAZQW/p1598466119135500
https://sensu.slack.com/archives/CCBBAAZQW/p1598648481192500

**Comment by cwjohnston** [comment]
We can likely crib some steps from https://www.influxdata.com/blog/securing-chronograf-with-oauth-2-0-in-microsoft-azure-active-directory/

**Comment by hillaryfraley** [comment]
@cwjohnston a couple questions:
1. does this belong within the existing AD section? Or in a separate (standalone) section like LDAP, AD, and OIDC?
2. is the Azure AD process more like the OIDC application setup? The tutorial Jef followed (https://docs.microsoft.com/en-us/azure/active-directory-domain-services/tutorial-configure-ldaps) seems like all the steps are done in your Azure account.

**Comment by hillaryfraley** [comment]
1. Yes -- in AD
2. Add comment/note "If you want to set up for Azure AD, follow this tutorial" (link to https://docs.microsoft.com/en-us/azure/active-directory-domain-services/tutorial-configure-ldaps)

**Comment by hillaryfraley** [comment]
https://github.com/sensu/sensu-enterprise-go/issues/1915
