### ISSUE TITLE
Add types query parameter to polymorphic APIs

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-docs#2698]
### Description
For polymorphic resources (ex. secrets providers and authentication providers), the API now supports listing specific types of each resource via a query parameter called `types`.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
- https://docs.sensu.io/sensu-go/latest/api/authproviders/
- https://docs.sensu.io/sensu-go/latest/api/secrets/

### Expected behavior
The `types` query parameter is documented and there are relevant examples for how to apply the param to the API endpoint.

### Current behavior
No docs/notes exist for this new use case.

### Corrections needed
- GET **/api/enterprise/secrets/v1/providers** lists all secrets providers (ex. `Env` and `VaultProvider`)
- GET **/api/enterprise/secrets/v1/providers?types=VaultProvider** lists all vault secrets providers
- GET **/api/enterprise/secrets/v1/providers?types=Env** lists all env secrets providers
- GET **/api/enterprise/authentication/v2/authproviders** lists all authentication providers (ex. `AD`, `LDAP`, and `OIDC`)
- GET **/api/enterprise/authentication/v2/authproviders?types=AD** lists all AD auth providers
- GET **/api/enterprise/authentication/v2/authproviders?types=LDAP** lists all LDAP auth providers
- GET **/api/enterprise/authentication/v2/authproviders?types=OIDC** lists all OIDC auth providers
- `types` can be used for multiple types, ex **?types=LDAP&types=OIDC**

### Additional context
https://github.com/sensu/sensu-enterprise-go/pull/1253

**Comment by hillaryfraley** [comment]
@nikkictl is this part of 6.1?

**Comment by nikkictl** [comment]
@hillaryfraley Yup, https://github.com/sensu/sensu-enterprise-go/pull/1253 is merged to master so this will go out in the next minor release (which is 6.1)!
