### ISSUE TITLE
Update 404 page to explain some pages in 6.x docs are not present in 5.x docs

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#2708]
### Description
We are planning to reorganize some content in the 6.0 docs but *not* in the previous versions (i.e., not 5.21, 5.20, or 5.19). The reorganization will involve a new section called “Observability Pipeline,” so although much of the content exists in the docs now, it will be moved to a new section in 6.0. The planned changes are in https://github.com/sensu/sensu-docs/pull/2709

When we publish this change, if a user browses to any sub-page of docs.sensu.io/sensu-go/6.0/observability-pipeline and then changes to docs version 5.21, 5.20, or 5.19, they will see a 404 page. Here’s a screenshot so you can see what I mean:

![obs-pipeline-404](https://user-images.githubusercontent.com/19190208/92158187-21e86100-edf1-11ea-8e97-6d33881ab192.gif)

We want to replace text on the 404 page to explain that there have been some docs changes in 6.0 that could cause a 404 when navigating from newer 6.x docs to 5.x versions.

### Category

This is an issue with:

- [ ] bug (bug in site build, layout, or functionality)
- [x] enhancement (add new or updated site functionality)

### Affected pages
https://github.com/sensu/sensu-docs/blob/master/layouts/404.html

### Expected behavior
If a user is viewing a page in the observability pipeline section and selects a pre-6.0 docs version from the dropdown, they will see a message on the 404 page (along with the current 404 page content) that explains why the page does not exist for that version.

### Current behavior
If a user is viewing a page in the observability pipeline section and selects a pre-6.0 docs version from the dropdown, they will see a 404 page with no indication that the page does not exist for the previous version or why.

### Changes needed

On the 404 page, replace the text
`Try searching the docs below, or visit the site directory.`
With
`We made some improvements in the 6.x docs that aren’t reflected in earlier versions. Try the main Sensu Go 5.21 page if you need to use pre-6.0 docs. You can also search the docs below or visit the site directory.`

The text “5.21” and the link (https://docs.sensu.io/sensu-go/5.21/) should reflect whatever version the user attempted to navigate to (e.g. selected from the dropdown menu).

### Additional context
We are targeting next Wednesday (September 9) for publishing the reorganized 6.0 docs with the observability pipeline section. I hope to have a PR ready by Tuesday morning (September 8). This could be tricky since the changes to the 404 page will depend on a section in the docs that we haven’t published yet.

A couple questions:
1. If this change is possible, can it be done by Wednesday, September 9?
2. Can you target the branch in my PR https://github.com/sensu/sensu-docs/pull/2709 with your PR to update the 404 page?

**Comment by hillaryfraley** [comment]
[Note Sept 9 -- ignore this; I'll handle it with redirects] 
This will affect some other pages in the Operations and Web UI sections. For example:
https://sensu-docs-observabilit-euggrk.herokuapp.com/sensu-go/latest/operations/control-access/apikeys/
https://sensu-docs-observabilit-euggrk.herokuapp.com/sensu-go/latest/web-ui/webconfig-reference/

**Comment by rnevius** [comment]
@hillaryfraley just seeing this one. Wouldn't this be better handled via some [custom redirect rules](https://github.com/sensu/sensu-docs/blob/master/static.json#L5) for 5.x versions, until the 5.x versions are eventually archived? I'll start working on the 404 update in case the redirect isn't an option.

**Comment by hillaryfraley** [comment]
@rnevius thank you. I can handle some of the content with redirects, but all of the _index.md pages in the observability pipeline section are totally new, so they won't exist for pre-6.0 docs. Rather than just redirecting to the main docs page, we thought it would be better to have a 404 with explanation.

**Comment by hillaryfraley** [comment]
Closed in https://github.com/sensu/sensu-docs/pull/2711
