### ISSUE TITLE
SensuGo Log By Severity

### ISSUE THREAD

**Issue by mrstrozy** [sensu/sensu-docs#2747]
Link to page: https://docs.sensu.io/sensu-go/latest/operations/monitor-sensu/log-sensu-systemd/

Hi - I was wondering if further examples could be provided for splitting out different severities into separate logs? Perhaps having a <service>.log & <service>.err?

Any examples would be greatly appreciated.

Thanks!

**Comment by hillaryfraley** [comment]
We need to establish whether this is possible -- we will start by investigating how [Sensu log levels](https://docs.sensu.io/sensu-go/latest/operations/maintain-sensu/troubleshoot/#log-levels) map to syslog severity codes when [forwarded via journald](https://docs.sensu.io/sensu-go/latest/operations/monitor-sensu/log-sensu-systemd/#configure-journald).

**Comment by hillaryfraley** [comment]
Discussed w/Eng -- this is something users would configure in syslog or a tool like Splunk or Logstash (after forwarding the Sensu log to syslog, for example). Separating logs based on severity depends on the tool's processing capabilities. Also, Sensu's [log levels](https://docs.sensu.io/sensu-go/latest/operations/maintain-sensu/troubleshoot/#log-levels) may not map 1:1 to another tool's log or severity levels.

To be discussed: how should we cover this in the docs?

**Comment by hillaryfraley** [comment]
First step: Test what it looks like when you send these logs based on their severity. Does this give you log files that are useful? If so, we can document how that works. But if it requires looking in several log files to discover the behavior of one event, this may not be something we can resolve with documentation. CR will discuss during office hours.

**Comment by hillaryfraley** [comment]
@mrstrozy Thank you for opening this issue. We've confirmed that splitting logs based on level is not currently built into Sensu. We think it should be possible to extract the level from log messages for processing with rsyslog, but doing so requires some expertise with rsyslog and it's outside the scope of our docs. We will add a note in the docs to address this. Thanks again for taking the time to ask this question.
