### ISSUE TITLE
Docs Feedback - Update info in Migration Guide

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#2752]
Link to page: https://docs.sensu.io/sensu-go/latest/operations/maintain-sensu/migrate/#2-translate-checks

### Feedback

In the table here: https://docs.sensu.io/sensu-go/latest/operations/maintain-sensu/migrate/#2-translate-checks, we note that dependencies are not available. However, I believe that we've come out with dependency filtering. If this is correct, we should make and adjustment and update the doc.

**Comment by hillaryfraley** [comment]
Discussion at https://sensu.slack.com/archives/C60EEQFH8/p1603719429160000
