### ISSUE TITLE
Document known caveats for prune API

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#2753]
### Description
We need to document tribal knowledge that is developing around the use of Prune API, and make sure any related defects or enhancements are being tracked.

Sync w/ Sensu Flow project when beginning this work.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/sensuctl/create-manage-resources/#sensuctl-prune
https://docs.sensu.io/sensu-go/latest/api/prune/

### Expected behavior
The docs include information about all known caveats with regard to how prune works.

### Current behavior
The docs may be missing some information about how prune works.

### Corrections needed
Add any missing information about prune-related caveats and limitations.

### Additional context
https://sensu.slack.com/archives/CCBBAAZQW/p1593635824046700

* Browser(s) and version(s): 
* OS:

**Comment by cwjohnston** [comment]
https://github.com/sensu/sensu-enterprise-go/issues/1278 describes a known limitation, namely that cluster-level privileges are required to use prune API, even when all resources belong to the same namespace.
