### ISSUE TITLE
[ON HOLD] Reproduce readme content from individual plugin repos within Supported Integrations sub-category

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#2757]
### Description
We want to add a Supported Integrations sub-category in the Sensu Go docs that contains individual pages for each supported Sensu handler plugin.

Each page in the Supported Integrations sub-category should correspond to a Sensu plugin. We'd like the content on the page to be an exact reproduction of that plugin's readme, with the sensu-docs formatting applied.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [x] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [x] improvement (improve docs content or format)

### Affected pages
All individual pages within the Supported Integrations section (review app for PR in progress: https://sensu-docs-plugins-sect-rxplct.herokuapp.com/sensu-go/latest/plugins/supported-integrations/).

### Expected behavior
The content on the individual pages in the Supported Integrations sub-category is programmatically reproduced from the corresponding plugin's readme.
For example, on the page https://sensu-docs-plugins-sect-rxplct.herokuapp.com/sensu-go/latest/plugins/supported-integrations/pagerduty/, the content is programmatically reproduced from https://github.com/sensu/sensu-pagerduty-handler/blob/master/README.md.

Any time https://github.com/sensu/sensu-pagerduty-handler/blob/master/README.md is updated, the changes are also automatically reflected on the page at  https://sensu-docs-plugins-sect-rxplct.herokuapp.com/sensu-go/latest/plugins/supported-integrations/pagerduty/.

Also, the readme content pulled in the Sensu Go docs is available and included when we create an offline PDF of the docs using the offline layout (https://github.com/sensu/sensu-docs/wiki/Release-related-docs-updates#create-an-offline-pdf-copy-of-docs).

### Current behavior
We add pages in our docs by creating new .md files and manually adding content in Markdown on the page.

### Corrections needed
Programmatically reproduce the plugin repo readme on the corresponding page in the Supported Integrations sub-category in the Sensu Go docs.

### Additional context
I created a WIP PR with the Supported Integrations sub-category: https://github.com/sensu/sensu-docs/pull/2756. The pages within the sub-category include a link to the readme we'd like to reproduce on the page.

**Comment by rnevius** [comment]
@hillaryfraley since at least some of these repositories are private, this may be complicated (unless I'm over-complicating things). One way would be to generate an [OAuth token](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/authorizing-oauth-apps) that could be used to gain access to private repo content during the build process. Are these README.md files in any public repos? 

Another challenge is ensuring the content is up to date. Because Sensu Docs is a static site, the markdown will need to be injected into a file during the build process. We could set up some kind of scheduled job to run every 24 hours to poll a list of repos and check whether or not the README content. If there is new content, a PR could be opened with the new README content.

Please let me know if I'm way off base. Both issues seem like pretty significant hurdles to surmount.

**Comment by hillaryfraley** [comment]
@rnevius thank you!
edit: to answer your first question, the readmes in public repos are:
https://github.com/sensu/sensu-chef-handler/blob/master/README.md
https://github.com/sensu/sensu-ec2-handler/blob/master/README.md
https://github.com/sensu/sensu-email-handler/blob/master/README.md
https://github.com/sensu/sensu-influxdb-handler/blob/master/README.md
https://github.com/sensu/sensu-opentsdb-handler/blob/master/README.md
https://github.com/sensu/sensu-pagerduty-handler/blob/master/README.md
https://github.com/sensu/sensu-puppet-handler/blob/master/README.md
https://github.com/sensu/sensu-relay-handler/blob/master/README.md
https://github.com/sensu/sensu-slack-handler/blob/master/README.md
https://github.com/sensu/sensu-snmp-trap-handler/blob/master/README.md
https://github.com/sensu/sensu-wavefront-handler/blob/master/README.md

The others are in private repos:
https://github.com/sensu/sensu-ansible-handler/blob/master/README.md
https://github.com/sensu/sensu-jira-handler/blob/master/README.md
https://github.com/sensu/sensu-maintenance-mode-handler/blob/master/README.md
https://github.com/sensu/sensu-servicenow-handler/blob/master/README.md


A couple alternative possibilities here...what do you think?

For the readme pulls issue, would it work to pull the content from Bonsai instead? Here's one public and one enterprise (private) example:
- Public repo: https://bonsai.sensu.io/assets/sensu/sensu-pagerduty-handler
- Private repo: https://bonsai.sensu.io/assets/sensu/sensu-jira-handler

For the issue with keeping content up-to-date, would it work to create a script in the sensu-docs repo (instead of a scheduled job) that we could run manually to update the integrations pages as part of the release process (for all integrations) or on an ad hoc basis when we know there's been a new release of a specific plugin (for individual integrations)?

**Comment by hillaryfraley** [comment]
@rnevius we are thinking about another way to present integrations in the docs, so the request in this issue is on hold. Thank you for describing the challenges in your comment above.

**Comment by hillaryfraley** [comment]
Closing this issue -- we are going to approach this by focusing on supported integrations and describing features in the docs with links to get the plugins and templates and other resources. See https://github.com/sensu/sensu-docs/pull/2833.
