### ISSUE TITLE
Sensu 6.1 - Sensu go Agent URL outdated or broken

### ISSUE THREAD

**Issue by goorallab** [sensu/sensu-docs#2782]
### Description
Sensu 6.1 - Sensu go Agent URL outdated or broken

### Category

This is an issue with:

- [ ] errata (error in doc content)

### Affected pages
https://docs.sensu.io/sensu-go/latest/operations/deploy-sensu/install-sensu/

### Expected behavior
URL to Windows MSI installation files should be correct. 

### Current behavior
URL to Windows MSI installation files are either broken or outdated.

### Screenshots
![image](https://user-images.githubusercontent.com/41610384/95306253-7450ed80-0887-11eb-825b-e1e2a73903e6.png)
![image](https://user-images.githubusercontent.com/41610384/95306693-0527c900-0888-11eb-9c6c-abff17751550.png)

**Comment by hillaryfraley** [comment]
@goorallab thank you for opening this issue. I apologize -- I am fixing the links now. In the meantime, the correct links are:

Sensu agent for Windows amd64
Invoke-WebRequest https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/6.1.0/sensu-go-agent_6.1.0.3465_en-US.x64.msi  -OutFile "$env:userprofile\sensu-go-agent_6.1.0.3465_en-US.x64.msi"

Sensu agent for Windows 386
Invoke-WebRequest https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/6.1.0/sensu-go-agent_6.1.0.3465_en-US.x86.msi  -OutFile "$env:userprofile\sensu-go-agent_6.1.0.3465_en-US.x86.msi"
