### ISSUE TITLE
Please switch RabbitMQ TLS setting guide to use new style (rabbitmq.conf) configuration

### ISSUE THREAD

**Issue by michaelklishin** [sensu/sensu-docs#2791]
### Description

Sensu TLS docs for RabbitMQ use a legacy configuration format that is now only recommended for advanced use cases.
All TLS settings are exposed via [`rabbitmq.conf`]() which is easier to read, generate, offers additional validation
and is superior in every way (for this particular use case at least).

This format has been available since November 2017.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

 * https://docs.sensu.io/sensu-core/latest/reference/ssl/

### Expected behavior

RabbitMQ TLS settings use [`rabbitmq.conf` examples](https://www.rabbitmq.com/ssl.html#enabling-tls) from the [RabbitMQ TLS guide](https://www.rabbitmq.com/ssl.html) are used, since the [new style format](https://www.rabbitmq.com/configure.html#config-file) is significantly easier to read and generate.

### Current behavior

[Classic config format](https://www.rabbitmq.com/configure.html#advanced-config-file) syntax is used in the examples.

**Comment by hillaryfraley** [comment]
Hi @michaelklishin -- thank you for taking the time to open this issue. Sensu Core reached end-of-life in December 2019, and we are no longer testing changes or updating the documentation for Sensu Core.

Closing -- Core documentation updates discontinued.
