### ISSUE TITLE
Write up what's special about Extensions (when compared to Plugins)

### ISSUE THREAD

**Issue by mbbroberg** [sensu/sensu-docs#281]
Extensions are special and we'd like to acknowledge how. A new page, under the Plugins areas of this repository, that outlines the differences between Plugins and Extensions would be great. Once we have that artifact, it can be turned into a brief 2-liner to add to the top of ever Extension repo in order to give a better understanding of the nuances.

**Comment by apaskulin** [comment]
Closing for now since extensions are not currently available for Sensu Go
