### ISSUE TITLE
Remove incorrect env vars for agent and backend config-file settings

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#2813]
### Description

Backend and agent references erroneously indicate that config-file setting can be set via environment variables

### Category

This is an issue with:

- [x] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

Backend and agent references

### Corrections needed

Remove from 6.1 and earlier.

### Screenshots

![2020-10-26 at 11 49 AM](https://user-images.githubusercontent.com/148017/97208946-550bf880-1781-11eb-8b82-728dd4fd3722.png)

![2020-10-26 at 11 47 AM](https://user-images.githubusercontent.com/148017/97208827-2db52b80-1781-11eb-9a8b-ed2a31c80fb5.png)

### Additional context

Expected to be implemented in a future release. Watch https://github.com/sensu/sensu-go/issues/4069

* Browser(s) and version(s): 
* OS:

**Comment by treydock** [comment]
Might also want to remove reference to setting these via YAML since I would image can't set config path inside the config, at least that seems like a chick and the egg type situation if you try to define the past to the config in the config.
