### ISSUE TITLE
Document new `/health` API available in the backend websocket API

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-docs#2818]
### Description
Document the new `/health` endpoint which will become available with https://github.com/sensu/sensu-go/pull/4075. This provides the same functionality as https://docs.sensu.io/sensu-go/latest/api/health/ but is accessible via the backend websocket API (a.k.a. the agent port, `8081` by default).

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [x] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
We may be able to add a snippet that says it's available on both the HTTP API and weboscket API to https://docs.sensu.io/sensu-go/latest/api/health/.

**Comment by hillaryfraley** [comment]
I think we should cover this in https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-schedule/agent/. We should probably also add it in https://docs.sensu.io/sensu-go/latest/operations/monitor-sensu/monitor-sensu-with-sensu/
