### ISSUE TITLE
SNMP Integration Docs - Corrections Needed

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#282]
When comparing the documentation in the site with what's present in the code on [Github](https://github.com/sensu-extensions/sensu-extensions-snmp-trap/blob/master/lib/sensu/extensions/snmp-trap.rb#L52-L61), we state that there is a `host` attribute, which I'm assuming should actually be `bind`. We should also add the examples from the trap extension into the integration doc.

**Comment by cwjohnston** [comment]
I'm not sure a change is needed here but maybe I misunderstand. 

The Enterprise integration sends traps to an SNMP agent, whose DNS name or IP address is specified via the`host` attribute. 

Conversely, the snmp-trap extension acts as an agent for receiving traps and thus has a `bind` attribute for specifying an IP address to listen on.

**Comment by asachs01** [comment]
Ah! Ok. Yeah, I'd misunderstood and conflated the integration & the extension.
