### ISSUE TITLE
Silencing API needs more information regarding silencing checks

### ISSUE THREAD

**Issue by nixwiz** [sensu/sensu-docs#2840]
### Description

Per this [Discourse thread](https://discourse.sensu.io/t/api-silence-check-without-subscription/2088), the docs are missing information on using the API to silence checks.
### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [X] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

https://docs.sensu.io/sensu-go/latest/api/silenced/#silencedsilenced-delete-specification
### Expected behavior

The docs should include information on how to silence a check without a subscription and also detail the attributes required for this API operation.
### Current behavior

The docs lack this information.
### Corrections needed

My answer to the Discourse question includes an example of how to accomplish what the requestor was asking.  Docs need to include a similar example and explain any missing attributes from the example.
### Additional context

* Browser(s) and version(s): 
* OS:

**Comment by sensu-discourse** [comment]
This issue has been mentioned on **Sensu Community**. There might be relevant details there:

https://discourse.sensu.io/t/api-silence-check-without-subscription/2088/4

**Comment by hillaryfraley** [comment]
I think I have enough info to add the example, but I may be misunderstanding what is missing from the attributes. I see all of the possible spec attributes listed here: https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-process/silencing/#spec-attributes

**Comment by nixwiz** [comment]
Ah, okay.  Even I missed that on my cursory review of the attributes.  I've linked that into the discourse reply as well.
