### ISSUE TITLE
Standardize checks in Monitor Sensu with Sensu

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#2854]
### Description
In Monitor Sensu with Sensu, the [backend checks](https://docs.sensu.io/sensu-go/latest/operations/monitor-sensu/monitor-sensu-with-sensu/#monitor-your-sensu-backend-instances) and [Postgres checks](https://docs.sensu.io/sensu-go/latest/operations/monitor-sensu/monitor-sensu-with-sensu/#monitor-postgres) use a plugin from the [Sensu HTTP Plugins](https://bonsai.sensu.io/assets/sensu-plugins/sensu-plugins-http) asset. The [etcd checks](https://docs.sensu.io/sensu-go/latest/operations/monitor-sensu/monitor-sensu-with-sensu/#monitor-external-etcd) use a plugin from the [Monitoring Plugins](https://bonsai.sensu.io/assets/sensu/monitoring-plugins) asset.

Two potential issues:

1. The latest iteration of Monitor Sensu with Sensu replaced the Monitoring Plugins plugin with the Sensu HTTP Plugins plugin in the backend checks because the Monitoring Plugins check resulted in a 200 no matter the actual health of the backend. The Postgres checks also use the Sensu HTTP Plugins plugin. However, the etcd checks still use the Monitoring Plugins plugins. If the Monitoring Plugins plugin didn't work in the backend checks, does it work in the etcd checks? Or should it be replaced?
2. If possible, can we update all the checks in Monitor Sensu with Sensu to use a Monitoring Plugins plugin? This asset does not require Ruby runtime.

### Category

This is an issue with:

- [x] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/operations/monitor-sensu/monitor-sensu-with-sensu/

### Expected behavior
All of the check examples in Monitor Sensu with Sensu work to produce the result described in the doc. In addition, the checks all standardize on plugins from a single Sensu asset (preferably, one that does not require a Ruby runtime).

### Current behavior
The check examples use plugins from two different assets and it's not clear whether the etcd examples work with the plugin from Monitoring Plugins (that plugin previously did not work in the backend checks).

### Corrections needed
- Test and confirm that the existing checks work.
- Figure out whether we can use a Monitoring Plugins plugin for the backend and Postgres checks to standardize (test and confirm), and then update the backend and Postgres checks if so.

### Additional context

History of work on this doc:
- We originally wrote the backend checks to use a plugin from Monitoring Plugins: https://github.com/sensu/sensu-docs/pull/2568
- A customer reported that the backend checks didn't work as expected: https://github.com/sensu/sensu-docs/pull/2568#issuecomment-656287502
- We revised the backend checks to use a plugin from Sensu HTTP Plugins instead: https://github.com/sensu/sensu-docs/pull/2706

**Comment by hillaryfraley** [comment]
1. Review Monitor Sensu with Sensu to make sure all checks use the correct plugin
2. Hillary to add explanation re: two backends required to "monitor" each other; commands for installing assets, etc.

**Comment by mgibson323** [comment]
I tested this out in Skunkworks. I think using the [`monitoring-plugins`](https://bonsai.sensu.io/assets/sensu/monitoring-plugins) asset is a more elegant and simple solution as it would only require users to install a single asset they can then use for multiple checks for the components described in the Doc. 

This reported errors if the backend being monitored was down:
```
connect to address sensu-beta and port 8080: Connection refused
HTTP CRITICAL - Unable to open TCP socket
```

But reports 200 if the backend is up:
```
HTTP OK: HTTP/1.1 200 OK - 371 bytes in 0.004 second response time |time=0.004337s;;;0.000000;10.000000 size=371B;;;0
```

One small note on the instructions: when adding the asset with sensuctl, the user should use the `-r` flag to rename the asset to match the specification in the yaml files, otherwise the check will fail with `command not found`.

Example:
`sensuctl asset add sensu/monitoring-plugins -r monitoring-plugins`

YML Backend Alpha
```
---
type: CheckConfig
api_version: core/v2
metadata:
  namespace: default
  name: check_beta_backend_health
spec:
  command: check_http -H sensu-beta -p 8080 -u /health
  subscriptions:
    - backend_alpha
  interval: 10
  publish: true
  timeout: 10
  runtime_assets:
    - monitoring-plugins
 
```

**Comment by hillaryfraley** [comment]
I can clean up the explanation in the guide with regard to commands to install plugins, but I think there are outstanding questions to answer before I can update all the checks to use monitoring-plugins:

1. Did something change in the monitoring-plugins asset between July 2020 and today?
    - Until July 2020, the checks in this guide did use monitoring-plugins, but a customer reported that the checks did not work (see [comment](https://github.com/sensu/sensu-docs/pull/2568#issuecomment-656287502)) and that's why we reverted to using the Ruby-based check in https://github.com/sensu/sensu-docs/pull/2706.
    - I see that the [monitoring-plugins asset](https://bonsai.sensu.io/assets/sensu/monitoring-plugins) has not been updated since August 2020, which is *before* the September 2020 PR to revert to the Ruby-based check. That makes me think the monitoring-plugins asset still won't work in these checks to monitor Sensu with Sensu.

2. Why does the [external etcd check](https://docs.sensu.io/sensu-go/latest/operations/monitor-sensu/monitor-sensu-with-sensu/#monitor-external-etcd) still use monitoring-plugins?
    - We reverted the other two checks to use the Ruby-based plugin.
    - Is there something about external etcd that means monitoring-plugins works in that check when it doesn't in the other two?

**Comment by mgibson323** [comment]
I redid my test using the ruby-based assets for the backend checks and the outputs for my test weren't all that different from the outputs I got above using the monitoring-plugins asset: 

Healthy: 
```
CheckHttp OK: 200, did not find /false/ in 234 bytes
```
Unhealthy:
```
CheckHttp CRITICAL: Request error: Failed to open TCP connection to sensu-beta:8080 (Connection refused - connect(2) for "172.21.0.3" port 8080)
```
---
I also tested the [postgres instructions](https://docs.sensu.io/sensu-go/latest/operations/monitor-sensu/monitor-sensu-with-sensu/#monitor-postgres). 
Using the Ruby-based asset and the `check-http-json.rb` command seems to be the best way to monitor postgres for now, until and unless the [`monitoring-plugins`](https://bonsai.sensu.io/assets/sensu/monitoring-plugins) asset has the [`check_pgsql`](https://www.monitoring-plugins.org/doc/man/check_pgsql.html) command added to it. 

(edit: Asked about this in [slack here](https://sumologic.slack.com/archives/C0254420A1Y/p1626381575395500).)

**Comment by mgibson323** [comment]
I spun up a skunkworks [Sensu Go w/external etcd](https://github.com/sensu/skunkworks/pull/80) and confirmed it's working: 

```
❯ sensuctl cluster health
=== Etcd Cluster ID: e228d933c3e5ad54
         ID           Name    Error   Healthy
 ────────────────── ──────── ─────── ─────────
  a39066e1c9ca5dba   etcd-0           true
  b1731c25383873f4   etcd-1           true
  351f818efbfa3a6b   etcd-2           true
```

But, when I try to use the example check from the docs:
```
---
type: CheckConfig
api_version: core/v2
metadata:
  namespace: default
  name: check_etcd_health
spec:
  command: check_http -H etcd-0 -p 2379 -u /health
  subscriptions:
    - linux
  interval: 10
  publish: true
  timeout: 10
  runtime_assets:
    - monitoring-plugins
 ```

I always get a failure: 

```
❯ sensuctl event info agent-01 check_etcd_health
=== agent-01 - check_etcd_health
Entity:    agent-01
Check:     check_etcd_health
Output:    HTTP CRITICAL - No data received from host
Status:    2
History:   2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Silenced:  false
Timestamp: 2021-07-16 16:32:16 -0700 PDT
UUID:      8021cc0b-923a-4214-8ce0-aaf1461f5065
```

I've tried using the container's IP address instead of its hostname but the same thing happens. It seems that this check doesn't work with the `check_http` command from the `monitoring-plugins` asset. It might be better to run a check using `etcdctl` although that would require installing and configuring the tool, which I briefly go over [how to do here](https://github.com/sensu/skunkworks/tree/master/dockerfiles/etcd-cluster-tls).

**Comment by hillaryfraley** [comment]
@mgibson323 do you know if a check that uses Sensu Plugins HTTP and Ruby runtime assets (like the [backend](https://docs.sensu.io/sensu-go/latest/operations/monitor-sensu/monitor-sensu-with-sensu/#monitor-your-sensu-backend-instances) check) works for external etcd? I tried to test this myself using the [skunkworks scenario](https://github.com/sensu/skunkworks/pull/80) you put together for external etcd but I couldn't get sensuctl running.

**Comment by mgibson323** [comment]
I tested using curl to hit the etcd health endpoint and it returns the following:
```
$ curl http://10.0.10.6:2379/health 
{"health":"true","reason":""}/
```

**Comment by mgibson323** [comment]
I opened this issue in the repo for the monitoring-plugins asset: https://github.com/sensu/monitoring-plugins/issues/26
