### ISSUE TITLE
Backend deregistration-handler doc is confusing

### ISSUE THREAD

**Issue by anatolijd** [sensu/sensu-docs#2904]
### Description

Backend deregistration-handler doc is confusing:

https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-schedule/backend/

deregistration-handler |  
-- | --
description | Default event handler to use when processing agent deregistration events.
type | String
default | ""
environment variable | SENSU_BACKEND_DEREGISTRATION_HANDLER
example | 

```
# Command line example 
sensu-backend start --deregistration-handler /path/to/handler.sh  

# /etc/sensu/backend.yml example 
deregistration-handler: "/path/to/handler.sh"
```

Description says it should be just a handler name.
But example demostrates it should be full path to the executable.

If deregistration handler is deployed with dynamic runtime asset, then it is not possible to predict a full path to the executable.

What is the proper way of defining deregistration handler ?

**Comment by hillaryfraley** [comment]
@anatolijd thank you for bringing this to our attention. It should indeed be an event handler name. We are updating the documentation now.
