### ISSUE TITLE
New docs.sensu.io landing page

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#2915]
### Description

As Sensu Core and Enterprise reached EOL, we changed the text and links on the tiles at our landing page, docs.sensu.io (/layouts/_index.html), but haven't changed the page itself. We should make better use of the docs landing page to help people find Sensu Go docs and represent the full range of documentation we provide.

### Category

This is an issue with:

- [ ] bug (bug in site build, layout, or functionality)
- [x] enhancement (add new or updated site functionality)

### Affected pages
https://docs.sensu.io/

### Changes requested
- Overhaul `/layouts/index.html` to reproduce to the [wireframe design](https://github.com/sensu/sensu-docs/files/5718352/12-15-20_docs.sensu.io_wireframe.pdf), using new partial templates where appropriate to reduce clutter and repetitive HTML.
- Each element on the landing page should have a mouseover effect of some kind to help users navigate and orient themselves on the page.
- We should be able to link each element on the landing page to a corresponding page in the docs.
   - Here is a [map of the current link plan](https://github.com/sensu/sensu-docs/files/5851995/Wireframe-to-docs.mapping.xlsx) in case you need it for any reason, but please use link placeholders in your PR -- I can add the links when I'm testing the PR.
   - In one case (the blue "Need help with a question?" element), we will need to link the text in the element rather than the element itself because the element includes two different links.
   - In another case (the green "New to Sensu?" element), we will need to link to a section on the landing page itself (in other words, we want to link the "New to Sensu?" element to the "Learn Sensu" section at the bottom of the page).
- Where the wireframe shows the simplified observability pipeline image, use this image instead:
![observability-pipeline](https://user-images.githubusercontent.com/19190208/105406656-56b75200-5bf2-11eb-93bb-207cb9449094.png)
   - We plan to replace the PNG image with the SVG inline code for the same image. We're going to use our existing image for now while we think through ideas for a redesigned version.
- Logos for each integration should appear more or less evenly in the "Sensu Integrations" section.
   - I'm not sure how you will approach this --  here's a [zip folder of the logos](https://github.com/sensu/sensu-docs/files/5851944/logos.zip) in case you do something like use CSS to resize them, but placeholders are also fine.
   - If needed, I can alter the logo dimensions to fit your design -- just give me the specs.
- For ongoing updates and maintenance, we should be able to change the text and links on the page, add and remove elements as we add new features in Sensu, and move elements and sections to different locations on the page if needed.

### Additional context

The improved docs landing page:
- Gives users a fuller picture of the information they will find in the Sensu docs: communicates the breadth and depth of the Sensu documentation
- Provides an at-a-glance view of Sensu Go features and concepts
- Includes sections that respond to every level of familiarity with Sensu, so brand new users and experienced operators alike will find information appropriate for their needs
- Links directly to individual docs pages and offers lots of entry points, both within the docs and to other Sensu resources like Discourse

**Comment by rnevius** [comment]
@hillaryfraley will the products in the "integrations" section contain links? If so, will these links be internal to the docs site, or will they link to external resources?

**Comment by hillaryfraley** [comment]
@rnevius yes -- links internal to the docs site. I'm hoping to link those logos to the pages in our Supported Integrations sub-category (https://docs.sensu.io/sensu-go/latest/plugins/supported-integrations/)

**Comment by hillaryfraley** [comment]
Hi @rnevius, just checking in to see how it's going and whether you've run into any problems with the way we *think* this should work!

**Comment by rnevius** [comment]
@hillaryfraley so far so good. Are we targeting a specific date to ship this? Either way, I'll prioritize this to have something ready for your review next week.

**Comment by hillaryfraley** [comment]
Hi @rnevius great! No specific date to ship. It's just on my follow-up list this week. Thank you!
