### ISSUE TITLE
Document etcd sensitivity to disk latency

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#2917]
### Description

Add content to our docs which help to highlight the importance of understanding sensitivity to disk latency and other etcd scaling challenges

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

Hardware requirements
Etcd external cluster guide
Troubleshooting doc

### Expected behavior

As an evaluator or implementor of Sensu I readily find documentation which helps me understand:

* How to plan a Sensu deployment with regard to etcd performance
* How to identify behaviors which are symptomatic of etcd performance issues
* Available commercial features to scale Sensu and reduce dependency on etcd  (i.e. use pg datastore with `enable_round_robin: true`)

### Current behavior

Hardware requirements documentation indicates that sustained IOPS matter
Troubleshooting documentation doesn't describe etcd performance pains

### Additional context

Because etcd performance has emerged as a recurring theme for Sensu users, it seems to me that our existing messaging on hardware requirements isn't effectively communicating the importance of disk latency. For this reason I think we need to make this point more clear in prose and obvious on the page. 

At the same time, I'd like to be able to respond to conversations like https://github.com/sensu/sensu-go/issues/4139 and [this one on discourse](https://discourse.sensu.io/t/sensu-webui-offline-restarting-service-solves-the-problem/2352) with a link to documentation which helps users work through the issue from where they are already, having already deployed Sensu in some capacity. Right now I am imagining this as new section of the troubleshooting documentation.

**Comment by cwjohnston** [comment]
This page on tuning etcd seems to be new in the 3.4.0 documentation: https://etcd.io/docs/v3.4.0/tuning/

**Comment by cwjohnston** [comment]
An example of Github issues that have been opened against etcd related to this: https://github.com/etcd-io/etcd/issues/10860

**Comment by cwjohnston** [comment]
This blog post provides some context on planning for etcd workloads that might also be helpful: https://www.ibm.com/cloud/blog/using-fio-to-tell-whether-your-storage-is-fast-enough-for-etcd

**Comment by hillaryfraley** [comment]
Has most of this issue been addressed? Looks like the latency and tuning information might be covered in https://docs.sensu.io/sensu-go/latest/operations/maintain-sensu/troubleshoot/#datastore-performance.

I think only the item about commercial features like enable_round_robin is outstanding.

How we will proceed: after 6.2.2 patch release and confirmation that the PostgreSQL round robin fixes are working as expected, we can add that suggestion to the troubleshooting doc and close this issue.
