### ISSUE TITLE
Update check examples for cross-platform usability

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#2919]
### Description

Update guide content to use cross-platform plugins wherever possible.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-schedule/monitor-server-resources/

### Expected behavior

Wherever possible, check config examples in the docs are usable for agents on both Linux and Windows.

### Current behavior

Many example checks depend on sensu-ruby-runtime, which has no Windows equivalent.

### Additional context

The following check plugins are expected to work equally well on both Linux and Windows platforms:

https://bonsai.sensu.io/assets/sensu/sensu-processes-check
https://bonsai.sensu.io/assets/sensu/sensu-check-log
https://bonsai.sensu.io/assets/ncr-devops-platform/nagiosfoundation
https://bonsai.sensu.io/assets/nixwiz/http-checks

**Comment by hillaryfraley** [comment]
Hillary to compile a list of the plugins we suggest in the docs right now. Then we can see if there are any that lend themselves to adding a Windows example.

**Comment by hillaryfraley** [comment]
Hillary added this to the agenda for the next DA/CR mtg. [List of plugins used in docs](https://docs.google.com/spreadsheets/d/1hJQ2ZZFf2VzBBBkxlJZTyC_qoYLbrkXC4mvixxXkxTU/edit#gid=0)

**Comment by hillaryfraley** [comment]
Update from DA/CR mtg:
Documentation examples using ruby plugins
- Review [this document](https://docs.google.com/spreadsheets/d/1hJQ2ZZFf2VzBBBkxlJZTyC_qoYLbrkXC4mvixxXkxTU/edit#gid=0) and prioritize replacing these example w/ Go-based plugins
- Starting with the [proxy request example(s)](https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-entities/monitor-external-resources/)

**Comment by hillaryfraley** [comment]
PRs that resolve this issue:
- https://github.com/sensu/sensu-docs/pull/3384
- https://github.com/sensu/sensu-docs/pull/3389
