### ISSUE TITLE
Document authentication options for email integration

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#294]

**Comment by asachs01** [comment]
Better described, flesh out better examples in the email integration docs.
* O365
* Gsuite
* SES

**Comment by asachs01** [comment]
Add:

- [ ] [AWS SES](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-smtp.html)
- [ ]  [Mailgun](https://documentation.mailgun.com/en/latest/user_manual.html#smtp-relay)
- [ ]  [Office 365](https://support.office.com/en-us/article/How-to-set-up-a-multifunction-device-or-application-to-send-email-using-Office-365-69f58e99-c550-4274-ad18-c805d654b4c4?ui=en-US&rs=en-US&ad=US)
- [ ] [Gmail/Gsuite](https://support.google.com/a/answer/176600?hl=en)

To https://docs.sensu.io/sensu-enterprise/$/integrations/email/

**Comment by asachs01** [comment]
It's worth noting that there are some differences in authentication options as to what each provider will accept.

**Comment by hillaryfraley** [comment]
Pending EOL: won't fix
