### ISSUE TITLE
Document wait flag for sensu-backend init

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-docs#2942]
### Description

Document the new `--wait` flag added to `sensu-backend init`. When specified, the wait flag will enable waiting indefinitely for etcd to become available.

Implemented in https://github.com/sensu/sensu-go/pull/4170.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-schedule/backend/

**Comment by hillaryfraley** [comment]
@amdprophet I have a question about this flag. I don't see it listed in the output for `sensu-backend init --help`. I rebuilt my local version (which is devel) and still don't see the wait flag. When I run `git rev-parse HEAD` the version is 3431c7a88625496ebae39e431c113ecb7b1af6d7 if that helps.

edit: also, in the --help output, `timeout` is listed as a string. Should it be an integer?

**Comment by amdprophet** [comment]
@hillaryfraley we pulled the wait flag work that was supposed to go out with 6.3.0. This can be put on hold for now.

Timeout would make more sense as an integer. I will have to look into whether or not we intentionally used the string type.

**Comment by hillaryfraley** [comment]
@amdprophet any idea if this is coming in 6.4.0?

**Comment by amdprophet** [comment]
@hillaryfraley likely, but still TBD.

**Comment by hillaryfraley** [comment]
@amdprophet roger that, thanks! I'll hold on moving the PR over to 6.4 docs then.
