### ISSUE TITLE
Changing the version on a page takes you to the root

### ISSUE THREAD

**Issue by majormoses** [sensu/sensu-docs#296]
When on a page [for example](https://docs.sensu.io/sensu-core/1.2/reference/ssl/#generate-self-signed-openssl-certificates-and-ca)

![image](https://user-images.githubusercontent.com/3145127/37866392-7d93bfa6-2f47-11e8-8ae8-9274a25b45e4.png)
 When changing to a different version it does not leave you on the documentation on that page for the new version but instead takes you to the root.

Selecting 1.1 takes you [to](https://docs.sensu.io/sensu-core/1.1/)

![image](https://user-images.githubusercontent.com/3145127/37866427-e13d8082-2f47-11e8-8341-a349b76e9e91.png)

What I'd like to see is to take me to [here](https://docs.sensu.io/sensu-core/1.1/reference/ssl/)

**Comment by rgeniesse** [comment]
Close on this one. All products for 1.x appear to be working on spot checking.

Just need to get the navigation back from `2.0` pages to `1.x` resolved, as the change in product means we'll never have pages that align like the `1.x` versions do.

**Comment by majormoses** [comment]
I spot checked this one as well and it LGTM

**Comment by rgeniesse** [comment]
@majormoses was that on the branch I pushed or on the live site? I hadn't opened a PR on it yet as I wanted to take a stab at filtering `2.0` content from being broken in the other direction.

**Comment by majormoses** [comment]
This was on the live site, I had misread and assumed that if it was fixed in a couple locations it was fixed everywhere. Feel free to close this out when you have confirmed that it is fixed everywhere.

**Comment by rgeniesse** [comment]
Thanks! Yea, my comment was misleading. Sorry about that. Thanks for re-opening it until then.
