### ISSUE TITLE
Add a Namespace reference documentation page? 

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-docs#2966]
### Description

We don't have any reference documentation for what a Namespace is. 

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [x] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Expected behavior

The Sensu equivalent of https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/

### Additional context

We have not yet published any "best practices" around namespaces, so the initial implementation here can be a little bit light on "why" and "when" advice, and focus more on the "what" and "how"... if that makes sense?

**Comment by calebhailey** [comment]
@hillaryfraley LMK if you have any questions on this one. :+1:

**Comment by hillaryfraley** [comment]
@calebhailey we cover namespaces in the RBAC reference (https://docs.sensu.io/sensu-go/latest/operations/control-access/rbac/#namespaces)

In the docs IA project, we talked about pulling them (edit: pulling namespaces out) separately. I believe we were thinking they'd be part of the observability pipeline, but we didn't end up doing that.

I could pull the namespace content out of the RBAC reference and put it a separate reference doc in the Control Access subcategory. The [namepaces spec table](https://docs.sensu.io/sensu-go/latest/operations/control-access/rbac/#namespace-specification) is missing the ~metadata~ type and API version too, so I could fill that in.

**Comment by calebhailey** [comment]
@hillaryfraley let's discuss on our next messaging/docs call and see if/how we want to prioritize this. 

Thanks!
