### ISSUE TITLE
OIDC configuration (docs) needs fixing

### ISSUE THREAD

**Issue by mjiderhamn** [sensu/sensu-docs#2968]
## Expected Behavior

The documentation on how to configure OIDC authentication at https://docs.sensu.io/sensu-go/latest/operations/control-access/oidc-auth/, and/or the implementation itself, leaves quite a bit to ask.

## Current Behavior

What is called `redirect_uri` in the Sensu config seems to be what for example Grafana calls `auth_url` and `oauth2-proxy` calls `login-url`. It is the URL that the Sign-in button leads to. *However* Sensu doesn't seem to construct the URL correctly. Sensu will add a single `callback` URL parameter, containing the (unescaped) URL to return to after authentication (i.e. reply URL). This URL parameter is normally called `redirect_uri`. The URL on the Sign-in button is lacking `client_id`, `scope` and `response_type` (and in the case of Azure, `resource`) URL parameters.
If parameters are added to the `redirect_uri` or the Sensu config, they are stripped from the Sign-in button URL.

It is unclear what should be entered into the `server` attribute, or what it is used for. Using Grafana and `oauth2-proxy` as examples again, they want a `token_url` or `redeem-url` respectively, in addition to a `api_url` or `profile-url`.

## Context

Specifically we want the OIDC provider to work with Azure AD.

Example Grafana snippet:
```
auth_url = https://login.microsoftonline.com/TENANT-ID/oauth2/authorize
token_url = https://login.microsoftonline.com/TENANT-ID/oauth2/token
api_url = https://graph.microsoft.com/v1.0/me
```
Example `oauth2-proxy` snippet
```
--oidc-issuer-url=https://sts.windows.net/TENANT-ID/
--login-url=https://login.windows.net/TENANT-ID/oauth2/authorize?resource=https%3A%2F%2Fgraph.microsoft.com
--redeem-url=https://login.windows.net/TENANT-ID/oauth2/token
--oidc-jwks-url=https://login.windows.net/common/discovery/keys
--profile-url=https://graph.microsoft.com/v1.0/me
```

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 6.2.2
* Installation method (packages, binaries, docker etc.): Docker
* Operating System and version (e.g. Ubuntu 14.04): n/a

**Comment by hillaryfraley** [comment]
Hillary to follow up with developer advocates or engineering. See https://sensu.slack.com/archives/C60EEQFH8/p1592257584455500 for context.

**Comment by hillaryfraley** [comment]
Potentially relevant [Discourse discussion](https://discourse.sensu.io/t/using-azure-ad-openid-connect-oidc-for-authentication/1819)

**Comment by sensu-discourse** [comment]
This issue has been mentioned on **Sensu Community**. There might be relevant details there:

https://discourse.sensu.io/t/using-azure-ad-openid-connect-oidc-for-authentication/1819/29

**Comment by mjiderhamn** [comment]
@hillaryfraley , while [the discussion](https://discourse.sensu.io/t/using-azure-ad-openid-connect-oidc-for-authentication/1819) relates to this issue, no one in the thread has confirmed they got it working, so a clarification from the Sensu team would be greatly appreciated.

**Comment by hillaryfraley** [comment]
@mjiderhamn thank you for your message. We are still looking into this, so I don't have an update as yet.

**Comment by mjiderhamn** [comment]
Any new on this, @hillaryfraley ?

**Comment by hillaryfraley** [comment]
@mjiderhamn thank you for following up. I'm trying to determine whether this is something we just haven't documented completely or something that will require engineering work. I'm sorry I don't have an update for you right now.

**Comment by hillaryfraley** [comment]
Follow up: https://sumologic.slack.com/archives/C0254420A1Y/p1637090205057300

**Comment by hillaryfraley** [comment]
@mjiderhamn Thanks again for opening this issue. I opened a feature request in sensu-enterprise-go for supporting Azure AD OIDC (and a companion issue in our sensu-go repo so that you can follow it if desired: https://github.com/sensu/sensu-go/issues/4495).

I am closing this issue in the meantime -- I will open a new docs issue to cover any changes that result from the feature request issue in sensu-enterprise-go.
