### ISSUE TITLE
Both dropdown options are initially shown for platform

### ISSUE THREAD

**Issue by majormoses** [sensu/sensu-docs#297]
On [this page](https://docs.sensu.io/sensu-core/1.2/reference/ssl/#generate-self-signed-openssl-certificates-and-ca) you have a dropdown to switch the platform but it initially shows up n times where n is the number of platforms.

![image](https://user-images.githubusercontent.com/3145127/37866471-59c65bb4-2f48-11e8-8d05-5cef67b3db7b.png)

After selecting a platform the others go away and default to the platform you have previously suggested (had to go incognito to replicate to avoid cache). If its not a bug it's certainly an odd quirk.

![image](https://user-images.githubusercontent.com/3145127/37866497-9c317632-2f48-11e8-8d97-7f6f03fe4142.png)

**Comment by majormoses** [comment]
While its clearly not an issue with a small number of platforms it could get very annoying if we had a half dozen or more.

**Comment by hillaryfraley** [comment]
Team has fixed this

**Comment by majormoses** [comment]
am still able to replicate this it initially shows both versions as per the screenshot, after selecting one it works fine. I would suggest testing this in an incognito window as I was able to reproduce but then hitting the page again I was not able to reproduce without an incognito window.

**Comment by hillaryfraley** [comment]
@majormoses I believe this is now fixed via https://github.com/sensu/sensu-docs/pull/3047, but can you confirm whether you are still seeing the problem?
