### ISSUE TITLE
Issue SSL certificate directly for docs.sensu.io

### ISSUE THREAD

**Issue by jaredledvina** [sensu/sensu-docs#298]
Hi!

I'm attempting to work around an issue with Python 2.7.6 and it's lack of built in SNI support over on https://github.com/sensu/sensu-ansible/pull/151. Before I continue to smash my face against this, I was wondering if we could instead issue the SSL certificate for the new docs site directly for docs.sensu.io instead of the current docs-preview.sensu.io. If you're using `certbot` for getting the Let's Encrypt certificate that's currently issued for the domain. I believe all that would be required is to pass `--cert-name docs.sensu.io` and then `-d docs-preview.sensu.io`. Looking at the current certificate, you'd probably want the following:
```
certbot certonly ----cert-name docs.sensu.io -d docs-preview.sensu.io,docs-preview.sensuapp.com, docs-preview.sensuapp.org,docs.sensuapp.com,docs.sensuapp.org
```

https://certbot.eff.org/docs/using.html#changing-a-certificate-s-domains has some more detail as well. 

Context:
Any version of Python before 2.7.9 doesn't have complete SSL SNI support. As such, there's a complex set of Python dependancies that need to get installed on a system to support validating a certificate via SNI. Currently the `sensu-ansible` repo attempts to fetch the `ssl_tools` tarball directly for the site and fails because of the lack of SNI validation for Ubuntu 14.04 (more generally, any operating system that doesn't ship with Python 2.7.9 or higher by default).

**Comment by majormoses** [comment]
Ya the issued cert should either be with a `*` which they now support (I am super excited about that) or issue it for the actual domain its intended to run out of.

**Comment by cwjohnston** [comment]
Hey @jaredledvina, sorry this has been left so long. I understand this is impacting some folks in a very obtuse way.

We are using Let's Encrypt via Heroku's automated certificate management, but we don't have the ability to directly influence the arrangement of common names or subject alternate names in the certificate. I want to help solve this issue for Ansible + Sensu users, but we also want to avoid taking on maintenance tasks to periodically regenerate certificates and update them in Heroku.

Despite our having duplicated the tarball artifact under each version of the Sensu documentation, the tool hasn't changed in a very long time. Would it be idiomatic for the Ansible module to vendor it's own copy of the SSL tool? 

If this artifact is a dependency of the automation, it seems to me that including it with the code is the right thing to do. This could also open up some opportunities for improvement, e.g. perhaps there is an Ansible module for certificate generation that would better fill this gap?

**Comment by jaredledvina** [comment]
Ah yeah, totally understood. I definitely don't wont you (or anyone) to manually be managing the certificates, was hoping that it was a trivial configuration change. 

I'll look into other options. Personally, I'm not a fan of having this single Ansible role also manage the self signed certificates but, since it's there, I won't take it out.

**Comment by jaredledvina** [comment]
https://github.com/sensu/sensu-ansible/pull/151 is the first swing at simply porting the ssl_tools logic to Ansible, such that we maintain support for generating the self signed CA, server, client keys but, avoid the core issue here. All of the configs, commands, etc are the exact same as well (i.e. I'm not forking the code). We should be good to close this from the Ansible side as I've simply side-stepped the problem.

**Comment by jaredledvina** [comment]
Lagging follow up but the Ansible role no longer depends on the ssl_tools bundle, so we can close this as I've worked around the issue entirely with the above PR.
