### ISSUE TITLE
Document how and when Sensu checks certificate revocation

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#2986]
### Description

As a Sensu evaluator, I can learn more about Sensu's use of OCSP and CRL to check the revocation status of certificates.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [x] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Expected behavior

Evaluators can find documentation which explains how revocation data provided in X509 certificates used for Sensu's various TLS-capable network listeners. 

### Current behavior

The backend reference covers a relevant configuration flag, but not with sufficient detail.

### Additional context

I believe the backend will check CRL and OCSP endpoints for any mTLS connection where the remote side presents a certificate providing such details. I think this means sensu-agent mTLS and both etcd client and peer certificate authentication.

We also have a backend config flag for `agent-auth-crl-urls` but it's not clear from the description whether this list of, CRL endpoints is queried for every sensu-agent mTLS certificate.

This content would be helpful in answering some of the questions commonly raised in security audits. 

I didn't find anything on this in the Securing Sensu guide. As an aside, I suspect the content in that guide would make more sense if presented as a reference. Would that make it easier to incorporate details like this?

* Browser(s) and version(s): 
* OS:

**Comment by hillaryfraley** [comment]
The SSL reference in Core (https://docs.sensu.io/sensu-core/latest/reference/ssl/) is a good model for converting Secure Sensu to a reference-style doc

**Comment by hillaryfraley** [comment]
Revocation checking info could be added in the agent and backend references until we develop a more robust Secure Sensu doc.

Open question: when you use sensuctl and the API url is an https URL, does sensuctl check the certificate presented by the API for revocation? If we only do revocation check for mTLS, OCSP and/or CRL checking would be limited to agent transport and etcd client and peer transports.
edit: [answer in Slack](https://sensu.slack.com/archives/C60EEQFH8/p1613158497305100)

**Comment by hillaryfraley** [comment]
I created a new issue to address the Secure Sensu --> reference suggestion: https://github.com/sensu/sensu-docs/issues/3004
