### ISSUE TITLE
Installation guide rewrite

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-docs#30]
Rewrite the Sensu installation guides, utilizing the new features, i.e. drop down selectors.

**Comment by asachs01** [comment]
@portertech I think @palourde has #307 where we can do this on a as-needed basis, depending on the doc. I'm also not sure if this is still an issue, or if we want to scope this out on a per-doc basis, or maybe add them as items to this issue?

**Comment by apaskulin** [comment]
Closing due to upcoming EOL for Sensu Core
