### ISSUE TITLE
document "auto_resolve" & "force_resolve" check definition attributes 

### ISSUE THREAD

**Issue by agoddard** [sensu/sensu-docs#303]
This feature exists, but is not yet documented
https://github.com/sensu/sensu/blob/master/lib/sensu/server/process.rb#L354

ref: https://github.com/sensu/sensu/issues/1127

**Comment by calebhailey** [comment]
Oh, good catch! Let's try to get this into the 0.23 docs.

**Comment by calebhailey** [comment]
Looks like this has moved to https://github.com/sensu/sensu/blob/master/lib/sensu/server/process.rb#L420-L474 (https://github.com/sensu/sensu/blob/master/lib/sensu/server/process.rb#L464)

...and it looks like there's another attributed called `force_resolve` that I don't think is documented.

**Comment by calebhailey** [comment]
...these attributes have moved to https://github.com/sensu/sensu/blob/master/lib/sensu/server/process.rb#L440. 

The `auto_resolve` attribute has been documented via #406, but we still need docs for `force_resolve`.
