### ISSUE TITLE
Add reasonable values for low_flap_threshold, high_flap_threshold

### ISSUE THREAD

**Issue by nstielau** [sensu/sensu-docs#305]
The [docs](https://sensuapp.org/docs/latest/checks) on `low_flap_threshold`, `high_flap_threshold` would be more helpful if they mentioned reasonable defaults.  Perhaps something like:

```
The flap detection low threshold (% state change) for the check. Sensu uses the same flap detection algorithm as Nagios.  Events that were tagged as flapping will be untagged once the % of the last 21 occurrences drops below this percentage.  Typical values are in the 10%-30% range.
``
```

**Comment by calebhailey** [comment]
@nstielau thanks for this suggestion! I'll get this into the upcoming 0.23 docs.

**Comment by calebhailey** [comment]
Related: https://github.com/sensu/sensu/issues/1124

**Comment by cwjohnston** [comment]
Closing as this issue has migrated to https://github.com/sensu/sensu-docs-site/issues/103
