### ISSUE TITLE
Update dynamic runtime asset path docs

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#3065]
### Description

The Windows execution environment uses different envvar expansion syntax compared to other agents. We hardcode the shell environments for command execution. This is not currently documented.

See https://github.com/sensu/sensu-go/issues/4184.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/plugins/assets/#dynamic-runtime-asset-path

### Additional context
The existing docs content was added in https://github.com/sensu/sensu-docs/pull/2494.

Discussion at https://sensu.slack.com/archives/C60EEQFH8/p1617822874033400

**Comment by hillaryfraley** [comment]
Discussed w/Jef -- still testing existing Windows examples.

**Comment by jspaleta** [comment]
I'm running up a new PR with changes to the documented check that I've tested.

here's the underlying issue:
sensu agent is using the standard windows console to run commands so any calling arguments to that command will need to use windows console syntax for env vars '%whatever%'    We arent actually in powershell environment yet that `-f` needs to be treated in a windows console syntax.

Its a little complcated to explain.

Once powershell.exe is running we'd use powershell syntax from inside a power shell script, but the -File argument is being processed by windows console to build the full powershell.exe call.

**Comment by jspaleta** [comment]
Opened PR #3102

**Comment by jspaleta** [comment]
One more comment,

We probably need to document which execution environments are used on which platforms.   
This impacts sensu-backend, sensu-agent, and sensu-agent

Basically anything that might want to run a executable provided by an asset
Not sure where that would be best documented.

**Comment by hillaryfraley** [comment]
> One more comment,
> 
> We probably need to document which execution environments are used on which platforms.
> This impacts sensu-backend, sensu-agent, and sensu-agent
> 
> Basically anything that might want to run a executable provided by an asset
> Not sure where that would be best documented.

@jspaleta maybe at https://docs.sensu.io/sensu-go/latest/platforms/?

Also, is it just `cmd.exe` for everything Windows and `bash.exe` for everything Linux?

edit: [Eric clarified](https://sensu.slack.com/archives/C60EEQFH8/p1617909627283100) "For shells, it's always the bourne shell (sh) unless the OS is Windows, then it's cmd.exe"
