### ISSUE TITLE
Outdated link

### ISSUE THREAD

**Issue by danielhoherd** [sensu/sensu-docs#309]
This link claims to be outdated and points to a newer location - https://github.com/sensu/sensu-docs/blame/master/source/docs/0.21/overview.md#L28

The target of the link is https://github.com/sensu/sensu-community-plugins

**Comment by calebhailey** [comment]
If something links to that repo, that definitely needs to be update, but I'm not seeing where it's being used via that blame link. Please advise.

**Comment by calebhailey** [comment]
Ah, I found it: https://github.com/sensu/sensu-docs/blame/e642259ec6660766b737b92edd1860da76b9a44d/source/docs/0.21/overview.md#L28 

We've rewritten the overview page such that this reference has been removed. I'm going to go ahead and close this.
