### ISSUE TITLE
Document the new --api-key sensuctl option 

### ISSUE THREAD

**Issue by fguimond** [sensu/sensu-docs#3103]
### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [X] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

https://docs.sensu.io/sensu-go/latest/sensuctl/

### Expected behavior

Using sensuctl with the new `--api-key` command-line option allows the user to authenticate using an API key instead of the username/password provided when running `sensuctl configure`.

`sensuctl` can now be executed without having been previously configured, using `--api-key` and `--api-url`.

When configured the provided username/password will be bypassed if `--api-key` is used, in which case the user associated with the key will be used.

Ref. https://github.com/sensu/sensu-go/pull/4256

**Comment by hillaryfraley** [comment]
Sorry, I overlooked this b/c I saw the 6.4.0 milestone! The change was merged into 6.3 so it's in the 6.3 docs: https://github.com/sensu/sensu-docs/pull/3174
