### ISSUE TITLE
Document truststore and keystore creation for Puppet integration

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#312]
The Sensu Enterprise documentation for Puppet integration does not describe how to create a keystore or a truststore for PuppetDB API calls. We need to document this, possibly by duplicating the instructions from the [Enterprise API](https://docs.sensu.io/sensu-enterprise/2.8/api/#create-an-ssl-keystore) documentation.

**Comment by hillaryfraley** [comment]
Pending EOL: won't fix
