### ISSUE TITLE
Links to docs unfurl poorly in Slack

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#314]
When someone posts a link to our documentation into Slack, the page is crawled for metadata which is used to "unfurl" or provide a synopsis of the linked content. Right now it looks like this: 

![2018-03-30 at 5 57 pm](https://user-images.githubusercontent.com/148017/38157406-df03458a-3443-11e8-9227-5d2d991402f5.png)

The unfurled message is the same for every page on our site, which makes these synopses obnoxiously repetitive. We should follow [the instructions provided by Slack](https://api.slack.com/docs/message-link-unfurling) to make them useful.

**Comment by apaskulin** [comment]
https://github.com/sensu/sensu-docs/commit/b477814164dc906b9b24648ae06ccd5689e38437 produces https://gist.github.com/apaskulin/428ceec6805dbea20b2610401c760430

Working under a theory that a smaller image will render in-line with the text instead of expanding below (see unfurl for slack.com), but still looking for a way to test this.

**Comment by cwjohnston** [comment]
@apaskulin On the face of it your commit looks 💯 to me! If it proves too difficult to test, perhaps we just roll with it and revert if needed?

**Comment by obfuscurity** [comment]
I agree with Cameron, let's :shipit: and see how it goes. I can also run it by Emerson Stone if you'd like a 3rd opinion from our design consultants.

**Comment by apaskulin** [comment]
PR is ready (#515) for a first try at this. As a sidenote, Hugo offers a wealth of [page-specific variables](https://gohugo.io/variables/page/) for this type of use case, including page summary (the first 70 words on the page), reading time, and word count. I left these out of #515 in an effort to keep unfurls brief and reduce noise, but I'm open to feedback if there's something more you'd like to see in an unfurl.

**Comment by cwjohnston** [comment]
The end result of Alex’s first pass in #515 looks great when unfurled in slack, so I think we’re done here. If we need to iterate on this further, let’s open a new issue.

**Comment by obfuscurity** [comment]
<3
