### ISSUE TITLE
Document process for renewing self-generated certificates

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#3175]
### Description
The Generate certificates page should explain how users will know their self-generated certificates have expired and the step-by-step process for renewing expired certificates.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/operations/deploy-sensu/generate-certificates/

### Expected behavior
Generate certificates doc describes how users will know their self-generated certs are expired and how to renew expired certs.

### Current behavior
Generate certificates doc does not include info about identifying or renewing expired self-generated certs.

### Corrections needed
Describe how users will know their self-generated certs are expired and list the step-by-step process for renewing expired certs.

### Additional context
https://trello.com/c/rYh5DATc

**Comment by mgibson323** [comment]
I made some notes on the [trello card](https://trello.com/c/rYh5DATc/579-test-self-generated-tls-cert-expiry-document-renewal) that show what a user can expect to see when their SSL certificates are expired for: 

- a single backend
- all backends
- agents

**Comment by mgibson323** [comment]
One more comment: 

There doesn't seem to be a way to renew an SSL using [`cfssl`](https://github.com/cloudflare/cfssl) but I've had no issues with simply generating a new one that overwrites the old one. I believe we can suggest this method for renewal. 

As for configuring a check in Sensu Go to verify SSL validity we can have the check run a command like the following, perhaps? 

```openssl x509 -noout -enddate -in cert.pem```
