### ISSUE TITLE
Pagination feature gone after new styles implemented

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#319]
Prior to the new ES styles, articles could have `next` and `previous` specified in them for articles that are next/previous in a series. The feature no longer appears to be present (as of #286 ), so we'll need to add it back.

**Comment by inghamemerson** [comment]
@asachs01 rectified in https://github.com/sensu/sensu-docs/pull/325.

**Comment by asachs01** [comment]
<3 @inghamemerson
