### ISSUE TITLE
Incorrect link on Create and manage resources with sensuctl

### ISSUE THREAD

**Issue by mgibson323** [sensu/sensu-docs#3200]
### Description

At https://docs.sensu.io/sensu-go/latest/sensuctl/create-manage-resources/#manage-resources when I click on `sensuctl namespace` the link takes me to https://docs.sensu.io/sensu-go/latest/operations/control-access/rbac/ - but I think the correct location for this link should be  https://docs.sensu.io/sensu-go/latest/operations/control-access/namespaces/

### Category

This is an issue with:

- [x] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

https://docs.sensu.io/sensu-go/latest/sensuctl/create-manage-resources/#manage-resources

### Expected behavior

Link `sensuctl namespace` goes to https://docs.sensu.io/sensu-go/latest/operations/control-access/namespaces/

### Current behavior

Link `sensuctl namespace` goes to https://docs.sensu.io/sensu-go/latest/operations/control-access/rbac/ 

### Corrections needed

The link should be corrected. 

### Additional context

* Browser(s) and version(s): 
* OS:

**Comment by hillaryfraley** [comment]
@mgibson323 thank you! fixing it now.
