### ISSUE TITLE
Add new custom query functions in docs

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-docs#3207]
### Description
Need updated documentation for newly merged  filter functions:
https://github.com/sensu/sensu-go/pull/4314
### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [X] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-filter/sensu-query-expressions/#custom-functions

https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-filter/filters/#filter-for-events-during-office-hours-only

### Corrections needed
Need to document new time-based custom-functions
minute()
second()
seconds_since()

Here's a good summary for each of the new functions
https://github.com/sensu/sensu-go/pull/4314/files#r649442100

### Additional context

* Browser(s) and version(s): 
* OS:

**Comment by hillaryfraley** [comment]
Many thanks, @jspaleta ! Is this for 6.4.0?

edit: answer is yes https://sensu.slack.com/archives/C60EEQFH8/p1623708231425800
