### ISSUE TITLE
Document ignore-already-initialized flag in sensu-backend init

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-docs#3246]
### Description

We're adding a new `--ignore-already-initialized` flag to the sensu-backend init command. See https://github.com/sensu/sensu-go/pull/4347 for additional information.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-schedule/backend/

**Comment by calebhailey** [comment]
Closed by #4347

**Comment by amdprophet** [comment]
Oops - this shouldn't have been closed. This is a docs issue, not Sensu Go.
