### ISSUE TITLE
Document Pipelines

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-docs#3354]
### Description
We're adding Pipelines to 6.5.0 and several components will have to be documented.

#### Description
A ResourceReference is used to reference another resource within Sensu. For example, a PipelineWorkflow may refer to a `core/v2.Handler` or a `pipeline/v1.TCPStreamHandler`.

#### Fields
* `api_version` -- the api_version of the referenced resource (e.g. `core/v2`)
* `type` -- the type of the referenced resource (e.g. `Handler`)
* `name` -- the name of the referenced resource (e.g. `email-handler`)

#### Description
A Pipeline defines one or more pipeline workflows for handling events. The `core/v2.CheckConfig`, `core/v2.Check` and `core/v2.Event` types all have a new `pipelines` field that contains a list of ResourceReferences to a Pipeline.

#### Fields
* `metadata` -- the metadata for the pipeline (name, namespace, labels, annotations, created_by)
* `workflows` -- one or more ResourceReferences to a `core/v2.Pipeline`.

#### Description
A PipelineWorkflow defines a single handler path within a Pipeline for an event.

#### Fields
* `name` -- a descriptive name for the workflow, not checked for uniqueness
* `filters` -- zero or more ResourceReferences to types that can filter the event
* `mutator` -- zero or one ResourceReferences to a type that can mutate the event
* `handler` -- one ResourceReference to a type that can handle the event

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Additional context
PR for the changes: https://github.com/sensu/sensu-go/pull/4408
Additional information in the proposal: https://docs.google.com/document/d/1rWDJoSFhpXRe9PUB8i7SVNA_eggJ6v5L8nJB7UaEkKc/edit

**Comment by amdprophet** [comment]
@hillaryfraley we'll also want to document the `sensuctl pipeline` commands from https://github.com/sensu/sensu-go/pull/4417. Let me know if you'd like me to open a separate issue for that or if it can be covered under this issue.

**Comment by hillaryfraley** [comment]
Thank you @amdprophet -- I was already looking at just documenting it in the PR that goes with this issue, so if that works for you, no need to create a new issue.
