### ISSUE TITLE
Disaster Recovery instructions aren't working as expected

### ISSUE THREAD

**Issue by mgibson323** [sensu/sensu-docs#3369]
### Description

The [Disaster Recovery instructions](https://docs.sensu.io/sensu-go/latest/operations/deploy-sensu/cluster-sensu/#disaster-recovery) don't specify whether they should work on embedded etcd or only on external etcd. I ran a test with embedded etcd and ran into problems - etcd would not return to a healthy state after restoring the snapshot. Details below. 

### Category

This is an issue with:

- [x] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

https://docs.sensu.io/sensu-go/latest/operations/deploy-sensu/cluster-sensu/#disaster-recovery

### Expected behavior

Users should be able to restore from an etcd snapshot with both embedded etcd or external etcd.

### Current behavior

The Docs link to [etcd's docs on snapshot/restore](https://etcd.io/docs/v3.5/op-guide/recovery/). The commands on that page require modification for embedded etcd as we can't restart etcd using their instructions - rather, the `sensu-backend` must be restarted after pointing at the directories created by the restore process. However, doing so causes etcd to start in an unhealthy state and won't allow the user to access `sensuctl` or the Web UI. 

I ran a test using [this docker-based 3 backend node deployment](https://github.com/sensu/skunkworks/tree/master/dockerfiles/sensu-go-cluster):
- Created the Sensu Go deployment using `docker-compose up -d`
- Added some entities, checks, etc. Allowed to run for a few minutes to generate some events. 
- Ran the etcd snapshot command against one node: `etcdctl --endpoints localhost:2379 snapshot save snapshot.db`
- Destroyed the Sensu Go deployment using `docker-compose down`, then recreated it with `docker-compose up -d` and verified that the entities, checks, and events created above were not there. 
- Ran the `etcdctl snapshot restore` command 3 times, one time for each node to be restored: 
```
etcdctl snapshot restore snapshot.db \
  --name sensu-backend-01 \
  --initial-cluster sensu-backend-01=http://localhost:2380,sensu-backend-02=http://localhost:12380,sensu-backend-03=http://localhost:22380 \
  --initial-cluster-token sensu-backend-cluster-1 \
  --initial-advertise-peer-urls http://localhost:2380

etcdctl snapshot restore snapshot.db \
  --name sensu-backend-02 \
  --initial-cluster sensu-backend-01=http://localhost:2380,sensu-backend-02=http://localhost:12380,sensu-backend-03=http://localhost:22380 \
  --initial-cluster-token sensu-backend-cluster-1 \
  --initial-advertise-peer-urls http://localhost:12380

etcdctl snapshot restore snapshot.db \
  --name sensu-backend-03 \
  --initial-cluster sensu-backend-01=http://localhost:2380,sensu-backend-02=http://localhost:12380,sensu-backend-03=http://localhost:22380 \
  --initial-cluster-token sensu-backend-cluster-1 \
  --initial-advertise-peer-urls http://localhost:22380
```
- This created directories for each restored node: 
![Screen Shot 2021-09-24 at 2 40 27 PM](https://user-images.githubusercontent.com/4676632/134742568-e0c22846-e856-49c3-abf8-d25aaf53148e.png)
- I modified the `docker-compose.yaml` to mount those directories at the `--state-dir` path used by Sensu Go for etcd, then reloaded with `docker-compose up -d`, which reported that the containers were recreated. 
- Attempted to access Web UI and reconfigure `sensuctl` but was not able to do either - docker logs showed that etcd was unhealthy. 

### Corrections needed

This may not be solely a docs issue, but the main correction needed for docs is for instructions to be added that will work for embedded etcd, and perhaps a warning/caveat that etcd's instructions may only work for external etcd. 

### Additional context

Initially reported by a customer, internal Sensu ref here: https://secure.helpscout.net/conversation/1602930238/26783?folderId=1211661

**Comment by hillaryfraley** [comment]
@mgibson323 do the instructions at https://docs.sensu.io/sensu-go/latest/operations/maintain-sensu/troubleshoot/#remove-and-redeploy-a-cluster work for either embedded or external etcd?

**Comment by mgibson323** [comment]
@hillaryfraley I attempted to use an etcd snapshot to restore the single node cluster in [this Vagrant-based skunkworks](https://github.com/sensu/skunkworks/tree/master/sensu-go-standalone) using those instructions and the restoration failed - none of the entities, checks, or events that I created were restored. 

```
[vagrant@sensu-centos ~]$ etcdctl snapshot restore snapshot.db \
>   --name sensu-centos \
>   --initial-cluster sensu-centos=http://localhost:2380 \
>   --initial-cluster-token sensu-centos \
>   --initial-advertise-peer-urls http://localhost:2380
2021-09-27 18:01:43.124577 I | mvcc: restore compact to 628
2021-09-27 18:01:43.127558 I | etcdserver/membership: added member d3eed0da8fee390b [http://localhost:2380] to cluster e8097a760d0562b6
```

**Comment by mgibson323** [comment]
The backup/restore steps using `sensuctl` [here](https://docs.sensu.io/sensu-go/latest/sensuctl/back-up-recover/) work - the assets and checks were restored. 

It's my opinion that we should point to those for disaster recovery for embedded etcd as well, and perhaps save the etcd-specific restoration instructions for external etcd clusters *only*

**Comment by mgibson323** [comment]
@hillaryfraley I had a conversation with @echlebek about this in Slack and his recommendations are in [this thread](https://sumologic.slack.com/archives/C024XK35Z3Q/p1633463822289100). 
I think at this point we should talk to Product about how to proceed.

**Comment by hillaryfraley** [comment]
@mgibson323 thank you! I'll follow up in Product

**Comment by calebhailey** [comment]
I think this issue might require a closer look. I don't see any reference to embedded etcd errors reported in the sensu-backend log in the original post here.  

While working through a customer support issue this week we discovered two `etcdctl snapshot restore` flags that may be useful here: `--data-dir` and `--wal-dir`. 

Some incantation like the following gets us pretty close to a working solution: 

```
etcdctl snapshot restore snapshot.db \
  --name <same as "--etcd-name" provided at sensu-backend start> \
  --initial-cluster <same as --etcd-initial-cluster provided at sensu-backend start> \
  --initial-advertise-peer-urls <same as --etcd-advertise-peer-urls provided at sensu-backend start> \
  --data-dir <default: /var/lib/sensu/sensu-backend/etcd/data > \
  --wal-dir <default: /var/lib/sensu/sensu-backend/etcd/wal >
```

Example: 

```
/ # tree /var/lib/sensu/sensu-backend/etcd/
/var/lib/sensu/sensu-backend/etcd/
├── data
│   └── member
│       └── snap
│           └── db
└── wal
    ├── 0.tmp
    └── 0000000000000000-0000000000000000.wal

4 directories, 3 files
/ # export ETCDCTL_API=3
/ # etcdctl snapshot --endpoints sensu-backend:2379 save snapshot.db                                                                    
Snapshot saved at snapshot.db
/ # rm -rf /var/lib/sensu/sensu-backend/etcd
/ # etcdctl snapshot restore snapshot.db --name default --initial-cluster "default=http://sensu-backend:2380" --initial-advertise-peer-ur
ls http://sensu-backend:2380 --data-dir /var/lib/sensu/sensu-backend/etcd/data --wal-dir /var/lib/sensu/sensu-backend/etcd/wal          
2021-12-07 05:53:06.499712 I | pkg/netutil: resolving sensu-backend:2380 to 172.19.0.9:2380                                             
2021-12-07 05:53:06.499928 I | pkg/netutil: resolving sensu-backend:2380 to 172.19.0.9:2380                                             
2021-12-07 05:53:06.512972 I | etcdserver/membership: added member 639eb35c86bb8aaa [http://sensu-backend:2380] to cluster 3de03ddcbc5cd6c9
/ # tree /var/lib/sensu/sensu-backend/etcd/
/var/lib/sensu/sensu-backend/etcd/
├── data
│   └── member
│       └── snap
│           ├── 0000000000000001-0000000000000001.snap
│           └── db
└── wal
    └── 0000000000000000-0000000000000000.wal

4 directories, 3 files
/ # 
```

_Note: the `rm -rf /var/lib/sensu/sensu-backend/etcd` command is necessary because the `snapshot restore` command expect empty directories..._

When I take these steps in a single-node deployment w/ embedded etcd the backend crashes with the following error: `failed to update; member unknown`. 

Will provide more details when I can come back to this...

**Comment by hillaryfraley** [comment]
Reopening this issue based on @calebhailey comment above.

**Comment by hillaryfraley** [comment]
Closed via https://github.com/sensu/sensu-docs/pull/3982
