### ISSUE TITLE
RabbitMQ link points to Redis on Transport page

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#342]
Both the RabbitMQ and Redis links at the bottom of https://sensuapp.org/docs/latest/transport point to the Redis config page.

**Comment by calebhailey** [comment]
Resolved in https://github.com/sensu/sensu-docs/pull/357/commits/3381d6364e0361f84066048ec9a71b3bd5f45d2b and will be shipped along with #357
