### ISSUE TITLE
Document "localhost" configuration disclaimer

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-docs#347]
Sensu _does_ support IPv6, however if the services it is connecting to (e.g. Redis and/or RabbitMQ) don't support IPv6 and/or aren't configured to listen on an IPv6 port, errors like https://github.com/sensu/sensu/issues/1209 will happen. The recommendation will be to use `127.0.0.1` instead of `localhost` for Sensu configuration.

**Comment by RiRa12621** [comment]
shouldn't this be handled a little more elegant so that if IPv6 fails, try IPv4 ?

**Comment by calebhailey** [comment]
Resolved in https://github.com/sensu/sensu-docs/pull/357/commits/10c4bd3c275677dd6ffd278aedc487d0153398a8 and https://github.com/sensu/sensu-docs/pull/357/commits/fd8ed9a99b43160489b729cb302cad52cf9d3da7 and will be shipped with #357. 

@RiRa12621 perhaps. Please feel free to submit an issue on https://github.com/sensu/sensu/issues with the suggestion.
