### ISSUE TITLE
Explain that clients created via the /clients API are "proxy clients"

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-docs#348]
See: https://github.com/sensu/sensu/issues/1203 

We need to explain that, by design, it's not possible to tell Sensu about a client that hasn't registered itself yet, and then expect keepalive messages from that client. Clients created via the API are actually proxy clients https://sensuapp.org/docs/latest/clients#proxy-clients

**Comment by Blue0ctober** [comment]
Migrating to https://github.com/sensu/sensu-docs-site/issues/105
