### ISSUE TITLE
Sensu without internet access

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-docs#349]
There are a number of frequently asked questions about how to do X with Sensu without internet access that we could help answer with some documentation. 

Example: https://github.com/sensu/sensu/issues/1199 

These aren't necessarily Sensu issues, but we can provide some suggestions on how to overcome these industry standard challenges.

**Comment by Blue0ctober** [comment]
migrated to https://github.com/sensu/sensu-docs-site/issues/106
