### ISSUE TITLE
Add NTP warning to keepalive documentation.

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-docs#351]
We need a warning similar to https://sensuapp.org/faq#do-system-clocks-need-to-be-synchronized in the keepalive documentation.

**Comment by wbrodie** [comment]
+1

**Comment by Blue0ctober** [comment]
https://sensuapp.org/docs/latest/reference/clients.html#client-keepalives 

Client-keepalives has been updated with NTP and time synchronization warning.
