### ISSUE TITLE
Improve documentation for sensu-install

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-docs#352]
Related: 
- https://github.com/sensu/sensu/issues/1156
- https://github.com/sensu/sensu/issues/1145 
- https://github.com/sensu/sensu/issues/1490

**Comment by portertech** [comment]
I plan to add uninstall support in 0.27 https://github.com/sensu/sensu/issues/1490

**Comment by cwjohnston** [comment]
We're adding proxy support in 0.29 https://github.com/sensu/sensu/pull/1629/commits/ac1dd78bce151aeb677423e89e239bf27d6cf73e

**Comment by cwjohnston** [comment]
I think we need a new page to describe sensu-install and its capabilities, as its mostly a footnote in the places we currently mention it.

**Comment by cwjohnston** [comment]
Relates to #529.

**Comment by cwjohnston** [comment]
Closed by #563
