### ISSUE TITLE
Improve configuration reload documentation 

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-docs#353]
We need to provide a better explanation to help users understand that the server/client/api processes need to be restarted to load configuration changes.

**Comment by calebhailey** [comment]
Related: https://github.com/sensu/sensu/issues/1138

**Comment by calebhailey** [comment]
Related: https://github.com/sensu/uchiwa/issues/230

**Comment by cwjohnston** [comment]
This issue was moved to sensu/sensu-docs-site#107
