### ISSUE TITLE
Discuss agent rate limiting behavior in tuning doc

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#3548]
### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

[Tuning Sensu](https://docs.sensu.io/sensu-go/latest/operations/maintain-sensu/tune/#backdrop)

### Content to be added

One aspect of Sensu's operations that has come up recently is the behavior around leases and agent rate limiting. The tuning doc should discuss (at length) the considerations for when operators would want to implement or adjust agent rate limiting. I'll note that there should be some improvements around this behavior in 6.6.3, but given that at a sufficiently large enough scale, agent leases can become somewhat problematic, it's worth us being prescriptive in our recommendations around agent rate limiting. 

I'll also note that it might be worth us adjusting our example configuration file within the docs to include this parameter.

**Comment by hillaryfraley** [comment]
I created an Asana task to gather recommendations: https://app.asana.com/0/1201099774497750/1201520675433595/f

**Comment by hillaryfraley** [comment]
When backends restart, agents lag in reconnecting -- rate-limit the agent reconnections to reduce the time required for all agents to reconnect. Ask Eng how many agents could reasonably be expected to connect per second. That is the tuning value we should suggest. And maybe it should be the default for agent-rate-limit.

edit: question in Eng https://sumologic.slack.com/archives/C024XK35Z3Q/p1642712156381700
