### ISSUE TITLE
Footer hides sidebar content

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#355]
Footer is hiding sidebar content and making the site un-navigable. See the below screenshots.

![image](https://user-images.githubusercontent.com/898627/38749260-98b5a0ea-3f16-11e8-9c63-7929c926d248.png)

![image](https://user-images.githubusercontent.com/898627/38749251-91de51fe-3f16-11e8-9d6a-013c0792c397.png)

**Comment by cwjohnston** [comment]
Closed by #360
