### ISSUE TITLE
Document new --etcd-client-log-level flag / config option

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-docs#3552]
### Description
We're adding a new `--etcd-client-log-level` flag in the 6.6.3 release which controls the log level of the internal Etcd client used within sensu-backend. We've also updated the description of the `--etcd-log-level`  flag to specify that it controls the Etcd server log level.

The output of `sensu-backend start --help` will show:
```
--etcd-client-log-level string               etcd client logging level [panic, fatal, error, warn, info, debug] (default "error")
--etcd-log-level string                          etcd server logging level [panic, fatal, error, warn, info, debug]
```

The default Etcd client log level is `error`.

Implemented in PR: https://github.com/sensu/sensu-go/pull/4560

### Category
This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-schedule/backend/

**Comment by hillaryfraley** [comment]
https://sumologic.slack.com/archives/C024PCF29KR/p1639605207035500
etcd-client-log-level will not have any effect when using embedded etcd.
