### ISSUE TITLE
Update Cloud Hardware Requirements to include other cloud providers

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#3574]
### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

https://docs.sensu.io/sensu-go/latest/operations/deploy-sensu/hardware-requirements/#cloud-recommendations

### Expected behavior

When making cloud recommendations, we should have more comprehensive recommendations that include other cloud providers. 

### Corrections needed

Doing some rough Googling, I've found the following info:

* [AWS M5d.xl to Azure](https://kinsta.com/blog/aws-vs-azure/)
* [AWS m5d.lx to Google](https://www.cloudhealthtech.com/blog/aws-reserved-instances-vs-google-committed-use-discounts)

We'll need to do some additional verification with other cloud providers, but we should definitely have this information as part of our docs.

**Comment by hillaryfraley** [comment]
Related issue: https://github.com/sensu/sensu-docs/issues/1099

**Comment by hillaryfraley** [comment]
To do:
- [x] Find out what's the difference between M5d.xl and M5.xl
- [x] For Google, find out the corresponding difference w/r/t n1-standard-4
- [x] For Azure, find out if D2ds v4 – D64ds v4, D2s v4 – D64s v4, or D2 v3 – D64 v3 encompasses M5d.xl
- [x] Look for comparable info for Digital Ocean

**Comment by asachs01** [comment]
@hillaryfraley DO: 
![CleanShot 2022-01-20 at 16 55 21](https://user-images.githubusercontent.com/898627/150428489-a184f1fc-f67b-42ad-9ebf-02cd54f85a40.png)

**Comment by hillaryfraley** [comment]
@asachs01 thank you!
