### ISSUE TITLE
Sensu logs critical event against backend entity when secrets provider returns an access error

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#3667]
### Description
As of Sensu Go 6.7.0, when the secrets provider returns an access error, Sensu will log a critical event against the backend entity (created automatically at backend startup).

When the secrets provider is accessible again, Sensu will log an ok event against the entity.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [x] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
Unsure -- need to sync w/ @fguimond 

Probably:
https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-entities/entities/
https://docs.sensu.io/sensu-go/latest/operations/manage-secrets/secrets-management/#use-hashicorp-vault-for-secrets-management
https://docs.sensu.io/sensu-go/latest/operations/manage-secrets/secrets-providers/

### Corrections needed
Unsure -- need to sync w/ @fguimond 

### Additional context
Issue: https://github.com/sensu/sensu-go/issues/4261
PR: https://github.com/sensu/sensu-go/pull/4624

**Comment by calebhailey** [comment]
I think the actual enhancement we're making here is that we're going to generate a Sensu Event in a reserved namespace (`sensu-system`), thus making the event visible in Sensu (no need to go to the logs).

**Comment by hillaryfraley** [comment]
Closed in https://github.com/sensu/sensu-docs/pull/3778
