### ISSUE TITLE
Update check hook reference docs to include better examples

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#367]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [x] Errata (fix needed for doc content)
- [ ] New content (guide wanted)

## Expected Behavior
The current docs provide the following example for check hooks:
```
{
  "checks": {
    "nginx_process": {
      "command": "check-process.rb -p nginx",
      "subscribers": [
        "proxy"
      ],
      "interval": 60,
      "hooks": {
        "critical": {"command": "sudo systemctl start nginx"}
      }
    }
  }
}
```

While yes, hooks do allow for doing rudimentary remediation, constantly restarting nginx in this case wouldn't be the best use case for hooks.

## Current Behavior
We should update the docs to include a more useful example (like the previous hook example in the docs) where hooks are being used to add context, rather than restart a process.

## Possible Solution
```
{
  "checks": {
    "nginx_process": {
      "command": "check-process.rb -p nginx",
      "subscribers": [
        "proxy"
      ],
      "interval": 60,
      "hooks": {
        "critical": {"command": "tail -n 100 /var/log/nginx/error.log"}
      }
    }
  }
}
```

**Comment by majormoses** [comment]
If you want to take a look I have several examples here: https://gist.github.com/majormoses/6b670730551bf59c60165b19a3afdefe
