### ISSUE TITLE
Check "notification" attribute is missing from latest docs

### ISSUE THREAD

**Issue by johntdyer** [sensu/sensu-docs#369]
Sensu has the concept of "notification" for a check which is supposed to allow you to override the output of the actual check with something more meaningful.  It appears this is no longer present in the latest docs.  

It was here in [v0.21](https://sensuapp.org/docs/0.21/checks) but is missing in [v0.22](https://sensuapp.org/docs/0.22/checks)

Is this no longer supported ?

**Comment by calebhailey** [comment]
@johntdyer this was moved to the plugins documentation, as this is one of a handful of attributes which are essential [custom check definition attributes][1] which are not supported by Sensu directly, but are supported by plugins that use the sensu-plugin gem Handler class. 

See here: https://sensuapp.org/docs/latest/plugins#sensu-plugin-definition-specification 

[1]: https://sensuapp.org/docs/latest/checks#custom-attributes
