### ISSUE TITLE
Minor issue: typo, first sentance, last word keepalives#overriding-configuration

### ISSUE THREAD

**Issue by AirCombat** [sensu/sensu-docs#371]
https://sensuapp.org/docs/0.16/keepalives#overriding-configuration

Basic instead of basis.

:)

**Comment by calebhailey** [comment]
@AirCombat nice catch! Thanks for the issue. :)

**Comment by calebhailey** [comment]
@AirCombat oh, but I see this is for a _very_ old version of Sensu. If possible, we strongly recommend running the latest version of Sensu, and referring to the documentation for the latest version: https://sensuapp.org/docs/latest/clients#client-keepalives

**Comment by AirCombat** [comment]
My bad. I often find google biases the indexing of your old documentation. A rel canonical to the new docs might help this althouth I have been told rel canonical should not beused this way.
