### ISSUE TITLE
No documentation on keepalive configuration options or location of script to see arguments

### ISSUE THREAD

**Issue by AirCombat** [sensu/sensu-docs#372]
The documentation on the website explains what the keepalive is and a high level view of how it works as well as an example configuration but does not give a list of options to configure and their default settings.

I have yet to come across a check that has any documentation at all (I sadly have to look inside the script to find out what arguments they accept), I don't expect keepalive to be any better but theres not even any dcumentation on its location.

It does not appear to be in the embedded folder with all the other checks. 

This is incredibly unintuitive.

**Comment by calebhailey** [comment]
@AirCombat keepalive configuration documentation has been improved in the latest version of the docs. Keepalive configuration is now documented in great detail. Please note the following reference and specification(s): 

- https://sensuapp.org/docs/latest/clients#client-keepalives
- https://sensuapp.org/docs/latest/clients#client-attributes (see the `keepalive` attribute)
- https://sensuapp.org/docs/latest/clients#keepalive-attributes (including the `thresholds` attribute)
- https://sensuapp.org/docs/latest/clients#thresholds-attributes

Here's an example: 

```
{
  "client": {
    "name": "i-424242",
    "address": "10.0.1.2",
    "subscriptions": [
      "webserver"
    ],
    "keepalive": {
      "handler": "keepalive",
      "thresholds": {
        "warning": 40,
        "critical": 60
      }
    }
  }
}
```

Let me know if this helps answer your question. :)

**Comment by AirCombat** [comment]
Cheers! I assumed it would be documented seperately from clients
