### ISSUE TITLE
No documentation on where to find checks for sensu

### ISSUE THREAD

**Issue by AirCombat** [sensu/sensu-docs#373]
There is no documentation on how to find checks.

It is mentioned on the plugins page but not the checks page. I wrongly assumed some checks would be built in rather than be a separate plugin.

The documentation mentions sensu-install only briefly.

I found this very unintuitive

**Comment by calebhailey** [comment]
@AirCombat thank you for this feedback! This was just recently improved in the latest release of the documentation; see here for more information: https://sensuapp.org/docs/latest/plugins#where-to-find-sensu-plugins
