### ISSUE TITLE
No documentation on how to find arguments for checks

### ISSUE THREAD

**Issue by AirCombat** [sensu/sensu-docs#374]
Most plugins have no documentation other than an unhelpful generic sensu-plugins.io page.

Plugins seem to default to documenting themselves within the script itself. I'm not a developer and do not assume that I could read and understand a script in a foreign programming language such as ruby so normally do not look inside scripts coming from trusted sources.

Documentation should mention to look inside the script for documentation on a check - eg what arguments it takes.

Although I would prefer if everyone just created a readme.md

Is there any way I can contribute towards this?

**Comment by calebhailey** [comment]
@AirCombat we are having some internal discussions about how to promote better documentation for the plugins, potentially including a bounty program to incentivize the community. In the interim, you are welcome to contribute to plugins by submitting pull requests to any repo in https://github.com/sensu-plugins 

#monitoringlove

**Comment by calebhailey** [comment]
...also, as far as Sensu is concerned, check `command`s and their corresponding arguments are documented in fairly comprehensive detail, here: https://sensuapp.org/docs/latest/checks#check-commands

**Comment by cwjohnston** [comment]
I suggest that anyone who wants to help improve plugins project documentation have a look at the work Sensu community contributor @ghostlyrics done [here](https://github.com/GhostLyrics/sensu-plugin-doc-draft). 👍
