### ISSUE TITLE
Guide Wanted: Using built-in occurrences filter

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#374]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)

## Expected Behavior
There should be a doc on using the built-in occurrences filter.

## Current Behavior
The current filters reference doc seems to have outdated content, as noted in #311 which could lead to confusion regarding occurrences and how the built-in filter works.

## Possible Solution
New doc to discuss how to use this filter.

**Comment by asachs01** [comment]
Proposed title: "Understanding Occurrence Filtering"

**Comment by Blue0ctober** [comment]
Would #498 satisfy this issue?

**Comment by cwjohnston** [comment]
Let’s treat #498 as a starting point for a guide that stands alone. I propose the title be more along the lines of “How to limit the number of alerts for an ongoing incident”

**Comment by apaskulin** [comment]
Closing due to upcoming EOL
