### ISSUE TITLE
[Doc]: Need Improvement for De registration of Proxy Entities details

### ISSUE THREAD

**Issue by aaggarwal-sumo** [sensu/sensu-docs#3740]
[Doc]: Need Improvement for De registration of Proxy Entities details

More details: https://github.com/sensu/sensu-go/issues/4657

## Expected Behavior
Currently information of how de registration will work with proxy entity is missing from documentation

**Comment by aaggarwal-sumo** [comment]
@hillaryfraley  Raised doc jira. Please let me know if anything is required

**Comment by hillaryfraley** [comment]
@aaggarwal-sumo thank you! I'm going to transfer this issue to the sensu-docs repo.

**Comment by hillaryfraley** [comment]
See also: https://github.com/sensu/sensu-go/issues/4657
