### ISSUE TITLE
Update documentation to provide systemctl commands for service management

### ISSUE THREAD

**Issue by AirCombat** [sensu/sensu-docs#376]
The documentation uses sysVinit and not systemd commands. 

systemctl enable sensu-client
systemctl start sensu-client
etc...

**Comment by cwjohnston** [comment]
Ubuntu docs will need similar updates as we'll be [installing unit files automatically in 0.27](https://github.com/sensu/sensu-omnibus/issues/34).

**Comment by cwjohnston** [comment]
As described in https://github.com/sensu/sensu-omnibus/issues/34, the omnibus packages will apply the following logic:

> * If sysv scripts are present, the package will update them to use the new sensu-service binstub
> * If no sysv scripts are present and systemd is the running init, systemd unit files will be installed in /etc/systemd/system

As a result, I think the docs should describe how to determine whether your system is using init scripts or systemd unit files to manage Sensu services.

**Comment by amdprophet** [comment]
We've updated the 0.26 documentation to be agnostic to the service manager in place. See https://github.com/sensu/sensu-docs/commit/626234698ede4d661db47841ab85e3cf4a6ef5ef for the changes.
