### ISSUE TITLE
Document Redis master name configuration

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-docs#380]
See: https://github.com/sensu/sensu/issues/1245

**Comment by RiRa12621** [comment]
for this in addition: it does not get 100% clear to me which regular redis options like DB can also be combined with sentinels config

**Comment by eklein** [comment]
Is there a reason this hasn't been added into the 0.23 docs? I burned several hours on this today until I found this issue. If I submit a PR to add the missing `"master": "mymaster"` line to the 2 entries in the doc, will you guys merge it?

**Comment by calebhailey** [comment]
@eklein hi there! 👋  

I'm going to fix this right now. Sorry for the lost time!

**Comment by eklein** [comment]
Awesome! I'm happy to submit a PR if it helps. It should be a quick change. Thank you!

**Comment by calebhailey** [comment]
@eklein fixed! https://sensuapp.org/docs/0.23/reference/redis.html#redis-attributes :)

**Comment by eklein** [comment]
Thanks @calebhailey. Long time no talk by the way :) Happy no one else will hit this problem!!

**Comment by eklein** [comment]
FYI, down below under the heading "Configuring Sensu for Redis Sentinel" - possibly the second heading, there's another configuration block that's missing the "master" line.
