### ISSUE TITLE
Misleading example RabbitMQ config

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-docs#385]
One of our example configurations shows both port 5672 (non-SSL) and ssl cert configurations. By default, RabbitMQ expects SSL connections to happen on port 5671, so this could be confusing for new users. 

See: https://sensuapp.org/docs/latest/rabbitmq#sensu-rabbitmq-configuration-examples-distributed

**Comment by agoddard** [comment]
👍 good catch
