### ISSUE TITLE
[Sensu 2.0] Guides cleanup

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-docs#385]
There's currently few inconsistencies/bugs/false statements in our 2.0 guides.

For example:
- https://docs.sensu.io/sensu-core/2.0/guides/reduce-alert-fatigue/#creating-the-filter
  - This filter doesn't work for event with status `0`, since these events are now also handled in 2.0, compared to 1.0, and the `occurrences` count is always set to `1` as long the check is successful.
- https://docs.sensu.io/sensu-core/2.0/guides/reduce-alert-fatigue/#assigning-the-filter-to-a-handler
  - The `sensuctl handler set-filters` subcommand does not exist

We should make sure to test again all guides and make sure they do work as expected!

**Comment by grepory** [comment]
Please audit the guides by running through with the latest nightly build and ensuring that each example works.

**Comment by palourde** [comment]
Closed by https://github.com/sensu/sensu-docs/pull/389
