### ISSUE TITLE
Reduce Heroku slug size

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#3862]
### Description
During app deployment, Heroku compiles a [slug](https://devcenter.heroku.com/articles/slug-compiler), essentially a compressed and optimized copy of the app.

Heroku enforces [slug size](https://devcenter.heroku.com/articles/slug-compiler#slug-size) limits (300 MB soft and 500 MG hard).
When the slug size exceeds 300 MB, the Heroku deployment log includes this message:

```
Warning: Your slug size (308 MB) exceeds our soft limit (300 MB) which may affect boot time.
```

We are not near the 500-MB hard limit right now, but we will approach it as we add docs (especially when the web UI diverges among Sensu versions).
We can also request a higher hard limit directly from Heroku support, but perhaps it would be better to minimize the slug size and avoid the problem altogether if we can.

I tried [purging the build cache](https://github.com/heroku/heroku-builds#purge-build-cache), which did not reduce the slug size at all.

I deleted an image from the sensu-docs/static/images directory to see if it would affect the slug size, and it does. For this reason, I believe image sizes are the main culprit in our slug size.

I created a .slugignore file, which we should be able to use to list any files, folders, or directories that are not needed for building the sensu-docs-site app. To test this, I added `node_modules/` in the .slugignore file, exactly as listed in our .gitignore file (https://github.com/sensu/sensu-docs/pull/3860). This did not work; the list of slug contents still included node_modules. I also tried with `/node_modules`, which did not work either.

Here is the list of our current slug contents:

```
12K	CONTRIBUTING.md
4.0K	DCO
8.0K	Gruntfile.js
4.0K	LICENSE
4.0K	Procfile
8.0K	README.md
4.0K	app.json
32K	archetypes
55M	archived
19M	bin
8.0K	config
4.0K	config.toml
16M	content
4.0K	insertFrontMatter.py
256K	layouts
4.0K	logs
8.3M	node_modules
128K	offline
4.0K	package.json
245M	public
16K	resources
12K	scripts
4.0K	sensu-docs.code-workspace
146M	static
16K	static.json
8.0K	tests
160K	yarn.lock
```

The `archived` item is the directory where we store docs for Sensu Core, Enterprise, and Go versions that are no longer supported. We do not need `archived` to build the sensu-docs-site app, so I think we can add it to the .slugignore file.

To prevent this problem altogether, we can also move the images we use in the docs site to S3/cloudfront.

### Category

This is an issue with:

- [ ] bug (bug in site build, layout, or functionality)
- [x] enhancement (add new or updated site functionality)

### Additional context
PR to add .slugignore file and test `node_modules/`: https://github.com/sensu/sensu-docs/pull/3860
PR to test `/node_modules` instead: https://github.com/sensu/sensu-docs/pull/3861

**Comment by hillaryfraley** [comment]
I added `/archived` to the .slugignore file in https://github.com/sensu/sensu-docs/pull/3863 and it worked to prevent the slug from containing `/archived`. Current slug contents:

```
12K	CONTRIBUTING.md
4.0K	DCO
8.0K	Gruntfile.js
4.0K	LICENSE
4.0K	Procfile
8.0K	README.md
4.0K	app.json
32K	archetypes
19M	bin
8.0K	config
4.0K	config.toml
16M	content
4.0K	insertFrontMatter.py
256K	layouts
4.0K	logs
8.3M	node_modules
128K	offline
4.0K	package.json
245M	public
16K	resources
12K	scripts
4.0K	sensu-docs.code-workspace
146M	static
16K	static.json
8.0K	tests
160K	yarn.lock
```

The previous slug that included the `/archived` folder listed its size at 55 MB, yet removing it via .slugignore only reduced the size of the slug by 10 MB (from 308 MB to 298.7 MB).

**Comment by agoddard** [comment]
@hillaryfraley can we experiment w/ apng files (or potentially webm) to replace some animated gifs and see if it makes a big enough difference to those?

**Comment by hillaryfraley** [comment]
I used [Ezgif converter](https://ezgif.com/gif-to-apng) to change an animated gif to apng. The converter increased the size of the image by 2.5 MB.

I also converted an animated gif to webm, and the converter reduced the size of the image by 3 MB.

I tested both apng and webm with our offline docs process. The apng displays properly in the offline docs (as a still image). The webm does not display at all (there is a small empty rectangle where the still image should be).

**Comment by hillaryfraley** [comment]
Tried [gif2apng](https://sourceforge.net/projects/gif2apng/).

At default compression (7ZIP with 15 iterations), the apng was 2 GB larger than the GIF.

Using the ZOPFLI compression option (also 15 iterations), the apng was about 1.7 GB larger than the GIF. This option also took a really long time.

**Comment by hillaryfraley** [comment]
I tested [Gifsicle](https://www.lcdf.org/gifsicle/) on a few images. It increased the size of one image and very slightly reduced the size of another (from ~12.1 to 11.7 MB).

**Comment by hillaryfraley** [comment]
[ImageMagick](https://imagemagick.org/script/index.php) does reduce the size of animated GIFs! Testing results:

`magick mogrify -layers 'optimize' -fuzz 7% create-service-component.gif`
Reduced image size from 12.5 MB to ~5 MB. The fuzz setting is too high though -- the blended colors affected the image quality.

`magick mogrify -layers 'optimize' -fuzz 3% create-service-component.gif`
Reduced image size from 12.5 MB to ~7 MB. Fuzz setting is OK -- color blending is noticeable to me but might not be obvious to readers.

`magick mogrify -layers 'optimize' create-service-component.gif`
Reduced image size from 12.5 MB to ~10.7 MB, even with no fuzz setting. Image quality is slightly affected but it's not too noticeable.

**Comment by hillaryfraley** [comment]
Slug size reduced from ~320MB to 197.2MB with these changes:

- Run every still png image through Image Magick:
     `magick mogrify -layers 'optimize' <PNG_NAME>.png`
- Run every animated gif image through Image Magick:
     `magick mogrify -layers 'optimize' -fuzz 3% <GIF_NAME>.gif`
- When a docs version is archived, move images that appear only in that version to the `archived_version_images` directory, which is listed in the .slugignore file and therefore does not count toward the slug size.
