### ISSUE TITLE
[Sensu 2.0] Document Agent <-> Backend TLS configuration

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-docs#390]
We need to document how to secure Agent <-> Backend communication with TLS, CA and peer certificate creation, management, and Sensu service configuration.

**Comment by calebhailey** [comment]
Related: https://github.com/sensu/sensu-go/issues/1078

**Comment by apaskulin** [comment]
Closing this for now until this feature is implemented in Sensu Go.
