### ISSUE TITLE
Strip networks flag

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#3901]
### Description
The probable solution for a network discovery issue that CE uncovered is a ~`--disable-network-discovery`~ `--strip-networks` backend flag. When the flag or other solution is implemented, we will need to document it.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
- List flag at https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-schedule/backend/#configuration-summary
- Add description table for flag at https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-schedule/backend/#general-configuration-flags

### Additional context
New issue: https://github.com/sensu/sensu-go/issues/4787
Former issue, now closed: https://github.com/sensu/sensu-enterprise-go/issues/2324
https://sumologic.slack.com/archives/C024XK35Z3Q/p1655217834791619

**Comment by asachs01** [comment]
Addressed in the 6.10 release. Closing as fixed by #4162
