### ISSUE TITLE
Clarify deregister behavior for ephemeral entities

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#3910]
In a [recent community conversation](https://sensucommunity.slack.com/archives/C6ARWHC2W/p1655796587926039), there was a discussion around expected behavior when it comes to ephemeral entities and deregistration. It seems that in order for ephemeral entities to successfully deregister, they must have both `deregister: true` and `agent-managed-entity: true`. However, it's unclear from the doc as to whether or not this is expected behavior. Can we clarify with product/eng as to how we envision ephemeral entities to be configured/operate?

Link to page: 
https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-entities/entities/#manage-agent-entities-via-the-agent
### Feedback

**Comment by hillaryfraley** [comment]
Question in eng slack: https://sumologic.slack.com/archives/C024XK35Z3Q/p1655834562695169

**Comment by hillaryfraley** [comment]
@asachs01 seems they only need `deregister: true` (Eng answered in https://sumologic.slack.com/archives/C024XK35Z3Q/p1655834562695169) -- I am not sure if that means something else is causing the community user's issue or if something isn't working the way it should. At this point it seems to be documented correctly...wdyt?

**Comment by hillaryfraley** [comment]
Closing after discussion in docs inbox cleanup mtg.
