### ISSUE TITLE
`&` symbols rendered to ` \u0026`

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#3918]
### Category

This is an issue with:

- [x] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-schedule/business-service-monitoring/

### Expected behavior

` \u0026` should be `&`

**Comment by hillaryfraley** [comment]
Thank you for finding this @asachs01 !
