### ISSUE TITLE
entity reference missing fields in system section of the specificaiton

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-docs#3921]
### Category

This is an issue with:

- [X] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-entities/entities/

### Current behavior
Missing some entity `system` attributes that are useful for asset build filters

### Corrections needed
Need to validate documented system attributes matches what is currently supported:
https://github.com/sensu/sensu-go/blob/974418e1fca5a2fe242ccca29fc0ccc95bf036ed/api/core/v2/entity.proto#L43

At a minimum the `arm_version` field is missing, but there may be more.

**Comment by hillaryfraley** [comment]
Looks like arm_version and float_type are the two missing attributes.
https://github.com/sensu/sensu-go/pull/3206
https://github.com/sensu/sensu-go/pull/3620
