### ISSUE TITLE
Documentation on Scalability of sensu

### ISSUE THREAD

**Issue by RiRa12621** [sensu/sensu-docs#394]
I think there is a big need for a real documentation on how to properly scale sense horizontally.

I saw that there is a “coming soon”. Is there an expected date to complete this?

**Comment by cwjohnston** [comment]
Scaling section may also be a good place to also talk about configuration uniformity concerns suggested in #256.

**Comment by cwjohnston** [comment]
This issue was moved to sensu/sensu-docs-site#110
