### ISSUE TITLE
Sidebar spacing issues at small screen widths

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-docs#395]
## This is an issue with:

- [X] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)

## Current Behavior
When using the GNOME Shell feature that allows me to throw a window to the left or right side of a display... for quick split screen window viewing... the navigation bar menu fails to collapse..and spills over into the sidebar nav.
Tested with both firefox and chrome.

But if I manually resize the window to roughly the same size, the navigation layout collapses like I would expect to avoid poor rendering due to text spill over.

I think osX has a similar feature, probably a good idea to try to test there as well.

## Expected Behavior
The nav menu should collapse when I throw the window to left/right split screeen like it does when I manually resize.

## Possible Solution
There's some sort of window width check that isn't firing to collapse the nav menu. I'm not familiar enough with the rendering code...yet... to suggest a fix. It's weird though.. manual resize of the window works.

## Steps to Reproduce (for bugs)

1. Gnome Shell linux desktop
2. grab browser window with sensu-core landing page open and throw to left side of display using display edge split screen feature
3. watch nav menu spill over into sidebar instead of collapsing.

## Screenshots (if appropriate):
Dual Screen setup:
Right screen has firefox and chrome side by side using Gnome Shell split window feature.

![screenshot from 2018-05-04 09-19-19](https://user-images.githubusercontent.com/39937/39641889-4ac36356-4f7c-11e8-8444-d6b80f798ae4.png)

## Context
The rendering spill over makes it impossible to use the sidebar nav.

* Browser(s) and version(s): 
firefox 54.0 Fedora build
chrome Version 64.0.3282.186 (Official Build) (64-bit)
* OS: 
Fedora 24 (I really need to upgrade)

I need to re-test with latest to make sure this isn't a bug in GNOME Shell interaction with browsers.

**Comment by jspaleta** [comment]
I got it to happen on manual resize.. 
its just a couple of pixels width that causing the problem.
Bad Manual Window Width: 960-970  -> nave menu renders with spill over into sidebar
Below 960 -> nav/sidebnar menu collapse
Above 970 -> nav menu renders without spill over

**Comment by apaskulin** [comment]
Also seeing lack of left-side padding at around 1100px width

![image](https://user-images.githubusercontent.com/11339965/46485481-9737fb00-c7b0-11e8-876a-1b989d75f0ce.png)

**Comment by rnevius** [comment]
The current style overrides should ideally be completely refactored, as they're a source of major technical debt. These styles are split between multiple files, and are riddled with bad practices (e.g. negative margins, mixed units, no mobile-first or desktop-first strategy, single-use classnames, etc), duplicate/conflicting declarations, and a brittle HTML markup. 

IMO, this is an epic that would require all partials to be properly (re)structured via HTML, all current style overrides to be deleted, and new styles rewritten (properly) from scratch. Bonus points for adding an autoprefixer to the build process.

**Comment by rnevius** [comment]
This will be resolved by #1528
