### ISSUE TITLE
2.0 statsd documentation features an incorrect example

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-docs#406]
When I try to use the example in the statsd documentation, I get an error.

## This is an issue with:

- [x] Errata (fix needed for doc content)

## Expected Behavior
```
echo "foo:1|c" | nc -u -w0 127.0.0.1 8125  # works, creates metrics
```

## Current Behavior
Doesn't work.

## Steps to Reproduce (for bugs)
```
$ echo "foo:1|c" | nc -u -w0 127.0.0.1 8125
Ncat: Invalid -w timeout (must be greater than 0). QUITTING.
```

## Context
Discovered while doing beta QA.

* OS: Fedora 26

**Comment by nikkictl** [comment]
Good catch! The example [here](https://github.com/atlassian/gostatsd#sending-metrics) is more appropriate than [this one](https://github.com/etsy/statsd#usage).

**Comment by apaskulin** [comment]
Page: https://docs.sensu.io/sensu-core/2.0/guides/aggregate-metrics-statsd/#how-does-sensu-implement-statsd
