### ISSUE TITLE
Add error fetching asset issue to Troubleshooting

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-docs#4066]
### Description
Add `error fetching asset` to the Troubleshooting page:
```
error getting assets for check: error fetching asset: Get "https://assets.bonsai.sensu.io/2940de675113d07710c0f896efa8b43b7c301c5c/sensu-plugins-process-checks_4.0.0_centos_linux_amd64.tar.gz": x509: certificate signed by unknown authority
```

Unsure of how to resolve - based on the HS ticket, it seems to be something like:

1. Confirm you can download the asset from one of the agent hosts using the link quoted in the error message
2. If the download does not work, the issue may be due to a proxy between the agent and the internet (or proxy settings)
3. If there are no proxies or proxy settings of concern, you may need to update the trust store on agent hosts

Another wrinkle: It looks like if you're using PowerShell, it's possible to get this error if TLS on Powershell is trying TLS 1.0 (Bonsai site requires TLS 1.2). -- see HS #27144

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
https://docs.sensu.io/sensu-go/latest/operations/maintain-sensu/troubleshoot/

### Additional context
HS #27188 and #27144

**Comment by jhenderson-pro** [comment]
I tested the powershell issue with a Windows Server 2019 box.  

I ran the command to force tls 1.2 in powershell:

`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`

I invoked a web request to download an asset (successfully):

`Invoke-WebRequest https://assets.bonsai.sensu.io/b4c5875e8d272d096f4bf0f69d2598b1755fe4a3/sensu-windows-powershell-checks.tar.gz -OutFile $env:userprofile/sensu-windows-powershell-checks.tar.gz`

![image](https://user-images.githubusercontent.com/100726636/195948314-fc9ac13e-d1a1-49ef-adc0-16406141a382.png)
