### ISSUE TITLE
404 Error when attempting to redirect to previous documentation versions

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-docs#407]
404 error is encouraged with popup suggestion.

## This is an issue with:

- [x] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)

## Expected Behavior
"Click here for the latest" popup (below) shouldn't attempt to redirect to earlier versions of docs if those docs do not exist:
<img width="1412" alt="screen shot 2018-05-07 at 5 16 20 pm" src="https://user-images.githubusercontent.com/10634078/39725656-99fbabea-521a-11e8-8660-1f7a523bf6c0.png">

## Current Behavior
404:
<img width="542" alt="screen shot 2018-05-07 at 5 16 28 pm" src="https://user-images.githubusercontent.com/10634078/39725725-c99d4340-521a-11e8-82af-3d14d0225d31.png">

## Possible Solution
Only show that popup if the doc exists in the earlier version it is attempting to redirect to, or redirect to the general landing page for earlier version docs.

## Steps to Reproduce (for bugs)
1. Go to a 2.0 doc page that is a new feature or guide, ex: https://docs.sensu.io/sensu-core/2.0/guides/extract-metrics-with-checks/#what-are-sensu-checks
2. Click "You're viewing documentation for an older or pre-release version of Sensu Core. Click here for the latest" popup.

## Context
404 error, redirecting users to non-existent pages.

* Browser(s) and version(s): Safari
* OS: Mac

**Comment by apaskulin** [comment]
No longer an issue following #875
