### ISSUE TITLE
Add how-to for Saving Sensu-Enterprise-Dashboard Collections

### ISSUE THREAD

**Issue by Blue0ctober** [sensu/sensu-docs#410]
Under Sensu-Enterprise-Dashboard -> Collections there is currently no documentation on how to save and recall collections. 

## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)

## Expected Behavior
Guide should include:

- How to save a collection
- How to recall a collection

**Comment by apaskulin** [comment]
Closing due to upcoming EOL
