### ISSUE TITLE
Broken reference links (unversioned paths) in platforms

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-docs#411]
Broken reference links in transport config section under multiple platforms
Links need to be versioned.
Bad Link Ex:
https://docs.sensu.io/sensu-core/reference/redis/#sensu-redis-configuration
Corrected Link Ex:
https://docs.sensu.io/sensu-core/1.4/reference/redis/#sensu-redis-configuration

Bad Link Usage Ex:
https://docs.sensu.io/sensu-core/1.4/platforms/sensu-on-ubuntu-debian/#example-transport-configuration
https://docs.sensu.io/sensu-core/1.3/platforms/sensu-on-ubuntu-debian/#example-transport-configuration
https://docs.sensu.io/sensu-core/1.3/platforms/sensu-on-rhel-centos/#sensu-on-rhel-centos

## This is an issue with:

- [ ] Bug (site functionality or styling)
- [X] Errata (fix needed for doc content)
- [ ] New content (guide wanted)

## Expected Behavior
Reference links should use versioned content path.

## Current Behavior
Reference links using unversioned content path == 404 status.

## Steps to Reproduce (for bugs)

1.
2.
3.

## Context

* Browser(s) and version(s): 
* OS:

**Comment by apaskulin** [comment]
Thanks, @jspaleta! Fixed by #437
