### ISSUE TITLE
Document the current benchmark process and results

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-docs#414]
Document the current Sensu 2.0 benchmarking process and the latest results.

Cover:

- [ ] The tooling
- [ ] How to stand up a benchmark environment
- [ ] How to run a benchmark
- [ ] Latest benchmark results for a given hardware setup, e.g. how many Agent connections and Events per second on a system with 8 cores and 8GB of RAM?

**Comment by hillaryfraley** [comment]
Done by perf
