### ISSUE TITLE
0.26 Changelog

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#414]
As with any release, we need to update the changelog as part of releasing 0.26. Please add known changes to this list:

* [x] New: `/silenced` API
* [x] New: automatic per-client subscriptions
* [x] New: Support for Redis Sentinel configuration via environment variables
* [x] New: Checks now support multiple named aggregates
* [x] New: Events now track the high water mark for occurrences at the current status
* [x] Changed: Client now attempts to set reasonable defaults for `name` and `address` attributes 
* [x] Changed: Subdue 2.0 API (breaking change)
* [x] Changed: Standalone checks no longer scheduled if `publish` is `false` or `interval` is not specified

**Comment by calebhailey** [comment]
Thanks for this list! I knocked off just over half of these in my first draft of #415... but on coming here I see I'm still missing three items (sentinel env vars, occurrences_watermark, and automatic name/address attributes). I'll work on those now...

**Comment by calebhailey** [comment]
OK, #415 isn't done yet (needs links), but it at least covers all of the bases in terms of the changelog.

**Comment by cwjohnston** [comment]
Closed by #415
