### ISSUE TITLE
Update PostgreSQL Datastore documentation for Postgre-15 compatibility

### ISSUE THREAD

**Issue by lspxxv** [sensu/sensu-docs#4163]
### Description

We need to update postgres documentation [here](https://docs.sensu.io/sensu-go/latest/operations/deploy-sensu/scale-event-storage/) to include running the command below that will grant all privileges to the `sensu` user for the `sensu_events` db 
### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

https://docs.sensu.io/sensu-go/latest/operations/deploy-sensu/scale-event-storage/

### Expected behavior

Docs should include the command - `GRANT ALL ON SCHEMA public TO sensu` - for PostgreSQL-15 compatibility.

### Current behavior

The current installation/configuration steps would only work for earlier versions of postgres

### Corrections needed

Add `GRANT ALL ON SCHEMA public TO sensu` while interacting with the sensu_events db.

Error when necessary privileges are not applied.
```
"component":"ent-store","error":"error migrating database to latest version: Could not get DB version: ERROR: permission denied for schema public (SQLSTATE 42501)","level":"error","msg":"error opening postgres store, retrying..
```

**Comment by jhenderson-pro** [comment]
Confirmed the same behavior and the fix.
