### ISSUE TITLE
New Configuration Flag: log-millisecond-timestamps

### ISSUE THREAD

**Issue by c-kruse** [sensu/sensu-docs#4171]
### Description
We'll need to document the --log-millisecond-timestamps backend configuration flag.
https://github.com/sensu/sensu-go/pull/4961

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [X] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Additional context

* Browser(s) and version(s): 
* OS:

**Comment by asachs01** [comment]
@jhenderson-pro since this was a request in https://secure.helpscout.net/conversation/2021733689/29981?folderId=6841159, are you able to run with this?

**Comment by jhenderson-pro** [comment]
This will require a new docset before the release.  I'll open that up tomorrow and do the two PRs.  I've got most of the text completed in a local branch already.

**Comment by asachs01** [comment]
Closing this as fixed by #4196
