### ISSUE TITLE
Guide for labels and annotations

### ISSUE THREAD

**Issue by mercul3s** [sensu/sensu-docs#420]
We need a basic how-to guide for labels and annotations. _I_ keep forgetting how to use them, so I'm guessing new users will also be confused without a guide.

To do:

- [ ] Create a guide to using labels and annotations
- [ ] Update label and annotation examples throughout the docs

## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [X] New content (guide wanted)

**Comment by hillaryfraley** [comment]
Team has documented this
