### ISSUE TITLE
Link to Enterprise Contact Routing Broken in sensu-core/x.y/reference/checks

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-docs#424]
Dead link to https://docs.sensu.io/sensu-enterprise/1.0/contact-routing
as found in: https://docs.sensu.io/sensu-core/1.4/reference/checks/#check-attributes
in the contact attribute description

## This is an issue with:

- [ ] Bug (site functionality or styling)
- [X] Errata (fix needed for doc content)
- [ ] New content (guide wanted)

## Expected Behavior

Links should take you to latest contact routing info
https://docs.sensu.io/sensu-enterprise/latest/contact-routing/

## Current Behavior
Following link results in 404

## Possible Solution
use "latest" for enterprise versioning in url.

## Steps to Reproduce (for bugs)
1.https://docs.sensu.io/sensu-core/1.4/reference/checks/#check-attributes
2. use reference link to Contact Routing
3. enjoy the very earnestly frowny 404 page, and take a moment to re-think the life decisions that brought you to this point. 

## Context
Found while dogfooding on-ramp learning from Core to Enterprise to configure contact routing
Looks like it needs to be fixed in all Core versioned content directory stubs.

**Comment by apaskulin** [comment]
Thanks, @jspaleta! Fixed by #437
