### ISSUE TITLE
Issues with Initial install per Sensu 2.0 docs

### ISSUE THREAD

**Issue by justizin** [sensu/sensu-docs#426]
Following the documentation at https://docs.sensu.io/sensu-core/2.0/getting-started/installation-and-configuration/, I had issues getting the backend and agent to run, talking on localhost, on a single system running Amazon Linux, installed via RPMs from Packagecloud.

## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ X ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)

## Expected Behavior
It feels like the agent expects to talk over SSL to the backend, which isn't directly described, though some stub configuration exists.

## Current Behavior
Backend starts up complaining that it is listening insecurely, agent manages to connect, but logs a large volume of repeat messages about UDP failures.

## Possible Solution
Basic self-signed SSL setup in the docs would help this, I suspect that isn't in place because it isn't recommended for production.  Working example of backend/agent config with no SSL might be better.

## Steps to Reproduce (for bugs)
1. Add packagecloud.io repository to fresh Amazon Linux machine.
2. Install sensu-backend + sensu-agent
3. Follow instructions about copying example configs into place
4. Start sensu-backend
5. Start sensu-agent
6. Check logs of backend and agent

sensu-backend.log on startup:
```
{"component":"etcd","level":"warning","msg":"simple token is not cryptographically signed","pkg":"auth","time":"2018-05-14T23:11:27Z"}
{"component":"etcd","level":"warning","msg":"set the initial cluster version to 3.3","pkg":"etcdserver/membership","time":"2018-05-14T23:11:27Z"}
{"component":"etcd","level":"warning","msg":"serving insecure client requests on 127.0.0.1:2379, this is strongly discouraged!","pkg":"embed","time":"2018-05-14T23:11:28Z"}
```

The agent log prints usage, shows an initial failure connecting to 127.0.0.1:8081

```
Error: dial tcp 127.0.0.1:8081: connect: connection refused
Usage:
  sensu-agent start [flags]

Flags:
      --api-host string                     address to bind the Sensu client HTTP API to (default "127.0.0.1")
      --api-port int                        port the Sensu client HTTP API listens on (default 3031)
      --backend-url stringSlice             ws/wss URL of Sensu backend server (to specify multiple backends use this flag multiple times) (default [ws://127.0.0.1:8081]
)
      --cache-dir string                    path to store cached data (default "/var/cache/sensu/sensu-agent")
  -c, --config-file string                  path to sensu-agent config file
      --custom-attributes string            custom attributes to include in the agent entity
      --deregister                          ephemeral agent
      --deregistration-handler string       deregistration handler that should process the entity deregistration event.
      --disable-api                         disable the Agent HTTP API
      --disable-sockets                     disable the Agent TCP and UDP event sockets
      --environment string                  agent environment (default "default")
  -h, --help                                help for start
      --id string                           agent ID (defaults to hostname) (default "ip-10-127-16-116")
      --keepalive-interval int              number of seconds to send between keepalive events (default 20)
      --keepalive-timeout uint32            number of seconds until agent is considered dead by backend (default 120)
      --log-level string                    logging level [panic, fatal, error, warn, info, debug] (default "warn")
      --organization string                 agent organization (default "default")
      --password string                     agent password (default "P@ssw0rd!")
      --redact string                       comma-delimited customized list of fields to redact
      --socket-host string                  address to bind the Sensu client socket to (default "127.0.0.1")
      --socket-port int                     port the Sensu client socket listens on (default 3030)
      --statsd-disable                      disables the statsd listener and metrics server
      --statsd-event-handlers stringSlice   comma-delimited list of event handlers for statsd metrics
      --statsd-flush-interval int           number of seconds between statsd flush (default 10)
      --statsd-metrics-host string          address used for the statsd metrics server (default "127.0.0.1")
      --statsd-metrics-port int             port used for the statsd metrics server (default 8125)
      --subscriptions string                comma-delimited list of agent subscriptions
      --user string                         agent user (default "agent")

{"component":"cmd","level":"fatal","msg":"dial tcp 127.0.0.1:8081: connect: connection refused","time":"2018-05-14T21:02:30Z"}
{"component":"agent","error":"Connection error: websocket: close 1006 (abnormal closure): unexpected EOF","level":"error","msg":"transport receive error","time":"2018-05
-14T21:11:05Z"}
{"component":"agent","error":"dial tcp 127.0.0.1:8081: connect: connection refused","level":"error","msg":"reconnection attempt failed","time":"2018-05-14T21:11:05Z"}
```

... then scrolls hundreds of lines of udp errors:

```
{"level":"warning","msg":"Error reading from socket: read udp 127.0.0.1:8125: raw-read udp 127.0.0.1:8125: use of closed network connection","time":"2018-05-14T23:01:19Z
"}
```

Eventually, giving up:

```
{"level":"warning","msg":"Error closing socket: close udp 127.0.0.1:8125: use of closed network connection","time":"2018-05-14T23:01:19Z"}
```

I tried uncommenting agent-port in backend.yml:

```
##
# agent configuration
##
#agent-host: "[::]" # listen on all IPv4 and IPv6 addresses
agent-port: 8081
```

Restarted the agent, I get connection refused:

```
{"component":"agent","error":"Connection error: websocket: close 1006 (abnormal closure): unexpected EOF","level":"error","msg":"transport receive error","time":"2018-05-16T15:51:38Z"}
{"component":"agent","error":"dial tcp 127.0.0.1:8081: connect: connection refused","level":"error","msg":"reconnection attempt failed","time":"2018-05-16T15:51:38Z"}
{"component":"agent","error":"dial tcp 127.0.0.1:8081: connect: connection refused","level":"error","msg":"reconnection attempt failed","time":"2018-05-16T15:51:39Z"}
{"level":"warning","msg":"Error reading from socket: read udp 127.0.0.1:8125: raw-read udp 127.0.0.1:8125: use of closed network connection","time":"2018-05-16T15:54:24Z"}
```

Port 8081 is open, I can telnet to it.

I tried some other combinations of uncommenting defaults to no avail, couldn't find any reference to the configuration in documentation aside from this one page.  I'd be happy to contribute to the docs, but this is kinda leaving me at a roadblock before I even get started. :)

## Context
Just trying to get started, I know we wouldn't expect to launch production on these default configs, but I didn't really find other documentation to supplement this.

* OS: Amazon Linux

**Comment by mercul3s** [comment]
@bitmonk Sorry you had some difficulties getting started!

The backend error you're seeing about insecure requests is an expected warning from etcd. It is recommended to configure TLS, but isn't required - we provide the config options as a reference. We might improve the docs with a link to [etcd's security documentation](https://coreos.com/etcd/docs/latest/op-guide/security.html).

The UDP errors sound related to statsd as it is operating on port 8125. I'm also seeing a ton of udp errors in the agent logs after restarting the backend when the agent disconnects and goes into a retry connection loop, so I'll open an issue to investigate that.

I'm not sure what might block a local network connection from the agent to the backend. Can you try with an updated nightly build with logging enabled in debug mode and report back? That should give a little more detailed feedback.

Regarding config defaults - I was able to get an agent and backend up and running on Amazon linux using the default configs, only setting the backend-url and log level on the agent:
```yaml
backend-url:
  - "ws://127.0.0.1:8081"

log-level: "debug"
```
And adding debug to the backend config:
```yaml
---
##
# general configuration
##
state-dir: "/var/lib/sensu"
log-level: "debug"
```
We don't have every config option listed in the default backend or agent config, and that may be a bit confusing.

**Comment by apaskulin** [comment]
I think we can solve this with #390 and a note in the install instructions about the etcd warnings in the backend logs.

**Comment by apaskulin** [comment]
I received the following errors when starting up a Sensu backend. I believe these are expected with a default configuration.

```
Apr 08 16:07:24 sensu-centos sensu-backend[3918]: {"component":"etcd","level":"warning","msg":"simple token is not cryptographically signed","pkg...07:24Z"}
Apr 08 16:07:25 sensu-centos sensu-backend[3918]: {"component":"etcd","level":"warning","msg":"set the initial cluster version to 3.3","pkg":"etc...07:25Z"}
Apr 08 16:07:25 sensu-centos sensu-backend[3918]: {"component":"etcd","level":"warning","msg":"serving insecure client requests on 127.0.0.1:2379...07:25Z"}
```

To do: Decide where to include this information in the docs.

**Comment by hillaryfraley** [comment]
Document the expected errors when starting up a Sensu backend ^
Sensu Go, maybe in troubleshooting doc? Backend reference?
