### ISSUE TITLE
Check TTL does not work when Round-Robin

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-docs#440]
Document the fact that Check TTL does not work when the Check is Round-Robin.

See the Sensu 2.0 eventd code for the conditional and some code documentation: https://github.com/sensu/sensu-go/blob/fe473a9ee28b25e106b8004a404f6e3522485ec1/backend/eventd/eventd.go#L208-L212

This limitation is not ideal, it should eventually be addressed/removed, documenting the current behaviour is important.

**Comment by apaskulin** [comment]
Fixed by https://github.com/sensu/sensu-go/pull/1780
