### ISSUE TITLE
Silencing reference document should note that regex is not supported

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#441]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [x] Errata (fix needed for doc content)
- [ ] New content (guide wanted)

## Expected Behavior

The silencing reference documentation should help users understand any supported special characters and use of wildcard operators.

## Current Behavior

Our silencing implementation supports a wildcard `*` for check or subscription element of `id` which may lead some to believe that these IDs can use globbing or regular expression syntax. This is not the case.

## Possible Solution

The reference documentation should indicate clearly that only the wildcard `*` operator is supported.

## Context

This periodically shows up as a question or point of confusion in training and support requests.

**Comment by apaskulin** [comment]
In the current doc, I see examples where the response includes `"id": "*:mysql_status"`. Is it also possible to use a wildcard in a request, for example, to silence all checks with names that start with `mysql`?

Example:

```
$ curl -s -i -X POST \
-H 'Content-Type: application/json' \
-d '{"check": "mysql*"}' \
http://127.0.0.1:4567/silenced

HTTP/1.1 201 Created
```

**Comment by cwjohnston** [comment]
It is not possible to use a wildcard as part of a string (e.g. `mysql*`)  it must stand alone.

**Comment by apaskulin** [comment]
Since wildcards are not a tool that users can add to their API requests (wildcards only appear in API responses, like [this one](https://docs.sensu.io/sensu-core/1.4/reference/silencing/#silence-all-checks-on-a-specific-client)), I don't think we need to call out that RegEx is not supported. Unless I am misunderstanding this, I'd recommend closing this issue.

**Comment by cwjohnston** [comment]
You’re right, the wildcard is mostly seen in /silenced API responses and isn’t valid for initial creation of silencing entries.

I originally opened this issue because it is a question we hear frequently from users, so it seems like a well-placed note to this effect could help answer that question upfront.
