### ISSUE TITLE
Add feedback flows

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#445]
The docs should provide clear channels for users to provide feedback.

## This is an issue with:
Bug (site functionality or styling)

## Expected Behavior
Users should be encouraged to submit feedback while using the docs.

## Current Behavior
Feedback process is implied by GitHub repo but not super clear from the docs site.

## Possible Solution
- Site-wide, generally positive feedback: [GitHub stars](https://buttons.github.io/)
- Page-specific, long-form feedback: Ideally, a "Was this page helpful: Yes / No" field with comment box, but a link to open a GitHub issue could be a serviceable, short-term solution.

**Comment by apaskulin** [comment]
Request for feedback on this design:
![screen shot 2018-07-20 at 1 26 45 pm](https://user-images.githubusercontent.com/11339965/43023702-a615e6a8-8c20-11e8-9078-d15cd0b925d7.png)

**Comment by rgeniesse** [comment]
Adding my thoughts here so others can view them:
- Sidebar area is a great place as not everyone is going to read to the bottom of the doc.
- The github issue is a great short term solution as we already have defined templates for opening issues.

Eventual form would be better, as you state as a goal, as it would allow users to provide feedback without a github account.
