### ISSUE TITLE
More helpful 404 page

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#447]
Help users get back on track when they get to the 404 page.

## This is an issue with:

Bug (site functionality or styling)

## Expected Behavior
404 page should be consistent with the rest of the site and help users find what they're looking for.

## Current Behavior
Current 404 page links to the docs homepage.

## Possible Solution
- Add page styling and branding
- Add helpful links
- Add search bar

## Screenshots
![screen shot 2018-05-31 at 11 17 38 am](https://user-images.githubusercontent.com/11339965/40800108-48c394f6-64c4-11e8-8525-055eafe84da5.png)

**Comment by hillaryfraley** [comment]
Develop clearer scope and hand off to Ryan

**Comment by hillaryfraley** [comment]
@rnevius We would like for the docs.sensu.io page to be able to use the requested URL that resulted in a 404 and offer a possible search result to correspond.

Would it be possible to do this with a JS script that turns the 404 URL into a search query?

**Comment by rnevius** [comment]
@hillaryfraley unfortunately, the Algolia DocSearch only supports their live/dropdown search box/results. There's no documented way to trigger these results via JS without human interaction, but I dug through their source code and found a way that should work for us. Essentially, what we could do is:

1. Embed Docsearch in the 404 page
2. Parse the URL to grab the parts and parse it into words
3. Populate the Docsearch input with some or all of these words
4. Trigger the popup to display

I'm envisioning this search being front and center, right below some 404/not found text.

If that sounds good to you, I'll give it a shot!

**Comment by cwjohnston** [comment]
@hillaryfraley @rnevius sounds like a step in the right direction, lets give it a shot. 👍
