### ISSUE TITLE
Configuration reference doc does not discuss custom attributes

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#449]
A number of plugins managed by the Sensu Plugins project, particularly handler plugins, depend on  custom attributes defined in Sensu configuration, but the Configuration reference doc doesn't seem to describe how this works. 

I think we should describe custom configuration attributes just as we have done with custom client and check attributes.

**Comment by majormoses** [comment]
not sure how true this is anymore I know that we do this for the occurrences and refresh settings. 

Relates to #640 I agree that there probably should be more, that being said I think they should be defined as custom to indicate that this still not something directly supported through the sensu framework but are common things that people consider.

**Comment by cwjohnston** [comment]
This issue was moved to sensu/sensu-docs-site#114
