### ISSUE TITLE
Remove RPM references from RMQ install docs

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#450]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [X] Errata (fix needed for doc content)
- [ ] New content (guide wanted)

## Expected Behavior
Have documentation that is using most recent versions of RMQ/Erlang. 

## Current Behavior
We're currently describing the installation process using [RPM](https://github.com/sensu/sensu-docs/blob/master/content/sensu-core/1.4/installation/install-rabbitmq-on-rhel-centos.md#download-and-install-rabbitmq-using-rpm), which is pointing to an earlier version of RMQ. The problem is that this leads to expecting a dependency for a SUPER old version of Erlang (R16B03). We should be directing people to use the RPMs published by RMQ solely, IMO. 

## Possible Solution
Remove the RPM section.

## Context
https://sensucommunity.slack.com/archives/C6YL8C4Q2/p1527794218000391 in which one of the community members ran into this exact issue.

**Comment by apaskulin** [comment]
Instead of linking to `3.6.9` [here](https://docs.sensu.io/sensu-core/1.4/installation/install-rabbitmq-on-rhel-centos/#download-and-install-rabbitmq-using-rpm), we should link to the RabbitMQ page here http://www.rabbitmq.com/install-rpm.html
