### ISSUE TITLE
Windows platform page should describe supported versions

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#450]
Platform page for Sensu on Windows does not describe which Windows versions are supported.

**Comment by cwjohnston** [comment]
@amdprophet @portertech can you please comment with supported Windows versions?

**Comment by amdprophet** [comment]
Windows Server 2012

**Comment by cwjohnston** [comment]
Whats the EOL status of Windows 2008? Should we try to test our latest Omnibus builds against it so we can know with some certainty if we can even suggest it as an option?

**Comment by cwjohnston** [comment]
As the downloads page has been updated to provide platform-version specific links, I think we can close this issue.
