### ISSUE TITLE
Enterprise installation guide needs update for Java 1.8 on Centos 6

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#451]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [x] Errata (fix needed for doc content)
- [ ] New content (guide wanted)

## Expected Behavior

Enterprise installation guide should document prerequisites for installation.

## Current Behavior

Currently the Enterprise installation guide does not recommend installing EPEL repository. This will be a requirement for users wishing to install Enterprise 3.0 or later on RHEL/Centos 6 and similar platforms.

## Possible Solution

Add steps for installing/enabling EPEL package repository and note that this is required for RHEL/Centos 6 and similar platforms.

## Context

With the upcoming release of Sensu Enterprise 3.0 our packaging dependency for Java, currently `java-1.7.0-openjdk`, will change to `java-1.8.0-openjdk`. Users installing Sensu Enterprise on RHEL/Centos 6 and similar platforms will need to install the EPEL package repository to provide `java-1.8.0-openjdk`. 

See https://github.com/sensu/sensu-enterprise/issues/344/ for details.

* OS:  RHEL/Centos 6

**Comment by asachs01** [comment]
Depends on #452 and should only be scoped to the 3.0 release

**Comment by cwjohnston** [comment]
I think we also need to figure out how this affects supported Debian/Ubuntu versions.
