### ISSUE TITLE
Use WinSW to manage sensu-client service on Windows

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-docs#457]
Sensu docs currently details how to use the `sc` command to manage the sensu-client Windows service. Our packages bundle in a `sensu-client.exe` WinSW stub that can be used to manage the service more efficiently. This stub should be used instead of `sc` so long as it's been tested & works on Windows Server 2008, 2012, and 2016.

**Comment by cwjohnston** [comment]
This issue was moved to sensu/sensu-docs-site#112
