### ISSUE TITLE
Add note about token substitution using values with special characters

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-docs#489]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [X] Update (Add missing or refresh existing content)

## Expected Behavior
Token substitution does not call out the need for single quotes around flag parameter values that may get interrupted by the shell (like $, !, etc). 

## Current Behavior
No call out here:
https://docs.sensu.io/sensu-core/1.4/reference/checks/#what-is-check-token-substitution

## Possible Solution
Add a note or warning about using single quotes if the parameter you are passing contains special characters:

https://docs.sensu.io/sensu-core/1.4/reference/checks/#what-is-check-token-substitution

**Comment by hillaryfraley** [comment]
Pending EOL: won't fix
