### ISSUE TITLE
Update 0.27 documentation to reflect new package repository layout

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#500]
To accommodate per-platform-version packages build with sensu-omnibus, the package repository layout is changing. Any users who wish to install Sensu 0.27 or newer will need to use the new repository layout, and the docs need to describe this.

**Comment by cwjohnston** [comment]
We're going to implement minimum viable instructions for 0.27 release, followed by improvements like those suggested in #501

**Comment by portertech** [comment]
Done!

**Comment by cwjohnston** [comment]
Closed by #502
