### ISSUE TITLE
Occurences And Refresh explination

### ISSUE THREAD

**Issue by itamarshpak** [sensu/sensu-docs#507]
Hey, 
I tried to figure out how the occurrences and refresh check parameters works but unsuccessfully.
there is no place in the internet with satisfying explanation and the docs also dont explain it well.

I configured a check with:
      "interval": 120,
      "occurrences": 10,
      "refresh": 1200,
with handler of pagerduty.

once the check handled by the pagerduty handler i noticed the history - 
      "history": [
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "2"
      ],

it means 2 things, 
first of all it didnt refreshed after 1200 sec (because it ran 21 times.)
second, the occurences parameter dont suppose to count 10 times of error\warning and it reach the counter its sending it to the handler ? 
help plz ASAP !

**Comment by asachs01** [comment]
Hi @itamarshpak , 

Thanks for reaching out about the issue. In order for the built-in occurrences filter to work, you'll need to have `"filters": ["occurrences"]` added inside of your pagerduty handler config. Also, we generally recommend using our community Slack channel ([slack.sensu.io](https://slack.sensu.io)) if you need support for an issue, or clarification regarding any Sensu components.
