### ISSUE TITLE
Documented Yum repository URL is broken under RHEL

### ISSUE THREAD

**Issue by flowerysong** [sensu/sensu-docs#508]
de584b0cf5cc0c33c36f77501cae1f94fcfdbd45 and 6b383a703136aad6d31ebb936a45aa98fa4166cd document the addition of `$releasever` to the repository URL. RHEL's `$releasever` is the [major release number plus the variant](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Deployment_Guide/sec-Using_Yum_Variables.html), so a RHEL 7 server will try (and fail) to find a repo at http://sensu.global.ssl.fastly.net/yum/7Server/x86_64

**Comment by amdprophet** [comment]
@flowerysong we've just added some rewrite rules that should forward requests from `/yum/(5|6|7)(Server|Client)` to `/yum/(5|6|7)`. Let me know if it works for you.
