### ISSUE TITLE
InfluxDB Integration Doesn't Reflect Required Attributes

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#508]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [x] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior
Tags, DB are required to send data to newer versions of IDB.

## Current Behavior
Current docs don't reflect this.

**Comment by cwjohnston** [comment]
We need to verify this is accurate. If so, document it.

**Comment by asachs01** [comment]
Did some testing today and all seems to be accurate.
