### ISSUE TITLE
Add some notes about graphite configuration to the getting started guide

### ISSUE THREAD

**Issue by jkugler** [sensu/sensu-docs#509]
While reading the the (so far, informative) getting started guide, I hit a bit of a roadblock when I got to this part: https://sensuapp.org/docs/0.27/guides/getting-started/intro-to-checks.html#create-a-metric-analysis-check It uses a plugin that access graphite, but up to that point, there was never any discussion of graphite.

Maybe a link to a graphite getting started guide would be good.
Also: a small discussion of how to configure Sensu to *put* the metrics it receives into graphite. This would include creating the graphite handler, like so:
```
Place the following contents in /etc/sensu/conf.d/graphite_handler.json

{
  "handlers": {
    "graphite": {
      "type": "tcp",
      "timeout": 30,
      "socket": {
        "host": "127.0.0.1",
        "port": 2003
      },
      "mutator": "only_check_output"
    }
  }
}
```
and then a brief discussion of adding "graphite" to the list of handlers for a check.

**Comment by cwjohnston** [comment]
This issue was moved to sensu/sensu-docs-site#115
