### ISSUE TITLE
Sensu 2.0 check reference missing several attributes

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-docs#522]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

## Expected Behavior

I would expect the Sensu 2.0 check reference page to reference all possible attributes.  Currently missing the following

* metric_format
* metric_handlers
* output_metric_format
* output_metric_handlers

## Current Behavior

The check reference page should reference the following attributes

* metric_format
* metric_handlers
* output_metric_format
* output_metric_handlers

## Steps to Reproduce (for bugs)

1. https://docs.sensu.io/sensu-core/2.0/reference/checks/

## Context

I am working with @ghoneycutt to support Sensu 2.0 with sensu-puppet and would like our custom types descriptions to match the official documentation as we map Puppet type properties to sensu resource attributes.

**Comment by apaskulin** [comment]
Page: https://docs.sensu.io/sensu-core/2.0/reference/checks/
To do: Add documentation for attributes `output_metric_format` and `output_metric_handlers` (`metric_format` and `metric_handlers` were removed in https://github.com/sensu/sensu-go/pull/1454.)
Reference: https://docs.sensu.io/sensu-core/2.0/guides/extract-metrics-with-checks
