### ISSUE TITLE
Whitespacing on H1's is excessive

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#524]
## This is an issue with:

- [x} Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior

![happy_whitespce](https://user-images.githubusercontent.com/898627/42000626-dbeea230-7a26-11e8-83db-c78941a1baea.png)

## Current Behavior

![nothappywhitespace](https://user-images.githubusercontent.com/898627/42000705-28118f38-7a27-11e8-995b-4b201352688b.png)

## Possible Solution

https://github.com/sensu/sensu-docs/blob/master/static/stylesheets/override.css#L390-L395

^  eliminate `padding-top: 50px;`

https://github.com/sensu/sensu-docs/blob/master/static/stylesheets/docs-overrides.css#L729-L731

^ eliminate those lines

**Comment by rgeniesse** [comment]
Possible this would resolve #465 or maybe is a duplicate. If so, I'd go with this one as it has the solution documented.

**Comment by asachs01** [comment]
Haderp. Dupe.
