### ISSUE TITLE
Deprecate OpsGenie API v1

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#525]
On June 30, OpsGenie will deprecate their version 1 API that is used by Sensu Enterprise prior to version 3.0. The docs for versions <3.0 should be updated to specify that the OpsGenie integration is no longer supported after that date and direct users to the upgrading guide.

## This is an issue with:
- Update (Add missing or refresh existing content)

**Comment by cwjohnston** [comment]
We've discussed this and decided to remove the OpsGenie v1 content and replace it with links to upgrade instructions.
