### ISSUE TITLE
Reference doc needed for proxy check requests

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#528]
We have basic documentation for the new [`proxy_requests` check attribute](https://sensuapp.org/docs/latest/reference/checks.html#proxy-requests-attributes), but I think we need a document to describe usage more holistically.

**Comment by portertech** [comment]
Should include examples using eval attributes, i.e. https://github.com/sensu/sensu/issues/1631

**Comment by cwjohnston** [comment]
Direct link to eval example https://github.com/sensu/sensu/issues/1585#issuecomment-283509407
