### ISSUE TITLE
Community Trello board link no longer goes to a valid board

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-docs#529]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [X] Update (Add missing or refresh existing content)

## Expected Behavior
Link to community Trello board works.

## Current Behavior
Link to Trello board gives a board not found error.

## Possible Solution
Remove link or update link with new location of community Trello board.

## Steps to Reproduce (for bugs)

Link is in this section:
https://docs.sensu.io/plugins/1.0/getting-started/#trello

Direct link is here:
https://trello.com/b/QjkJ8CS3/sensu-community-plugins

**Comment by rgeniesse** [comment]
Per Matt in Slack, it would appear the proper board is https://trello.com/b/gxVPgTOH/community. Thanks @mbbroberg!

**Comment by mbbroberg** [comment]
@rgeniesse not quite! The Contributors to Sensu Plugins no longer use Trello. We do use the Community repo at https://github.com/sensu-plugins/community for project tracking. I recommend linking there in any updates 👌 

Thanks for finding this!
