### ISSUE TITLE
$releasever use on Scientific Linux

### ISSUE THREAD

**Issue by kmkramer** [sensu/sensu-docs#534]
What are you recommending for users of SL wrt the repo changes? ie, salt-formulas for instance

**Comment by cwjohnston** [comment]
@kmkramer my apologies for the tardiness in responding to this question. In #608 we updated the [RHEL/Centos platform pages](https://sensuapp.org/docs/latest/platforms/sensu-on-rhel-centos.html#install-sensu-core-repository) in an effort to better describe installation on RHEL derivatives like Scientific Linux. Specifically, you should use RHEL 6 packages on versions of Scientific Linux which use sysv init:

```
[sensu]
name=sensu
baseurl=https://sensu.global.ssl.fastly.net/yum/$releasever/$basearch/
gpgcheck=0
enabled=1
```

... and use RHEL 7 packages on versions of Scientific Linux which use systemd as init:
```
[sensu]
name=sensu
baseurl=https://sensu.global.ssl.fastly.net/yum/7/$basearch/
gpgcheck=0
enabled=1
```
