### ISSUE TITLE
Edit README to reflect that Uchiwa docs have been merged

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#535]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [x] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior
Uchiwa docs live on the docs site.

## Current Behavior
Readme says otherwise.

## Possible Solution
Quick change to Readme

**Comment by apaskulin** [comment]
Closed by #546
