### ISSUE TITLE
Sensu Ubuntu install should include extra details for enabling services on boot

### ISSUE THREAD

**Issue by Blue0ctober** [sensu/sensu-docs#550]
The current iteration of sensu install docs assumes that you are running version of Ubuntu older than 16.04. The command for enabling the sensu services changes from update-rc.d to systemctl and should reflect that in the documentation. 

Currently there is a single sentence informing the reader of the change. 

A couple options:

1.  It might be best to add a drop down or selection for specific version of Ubuntu eg pre 16.04 and anything newer than 16.04.  Same can be done for other OS version such as CentOS/RHEL
2. Change the current commands to what is the new way of enabling the services and adding a note for pre 16.04 users. 

As 14.04LTS is reaching EOL and 16.04LTS is nearing midlife cycle it may be best to make the changes now especially since 18.04 LTS is now out.

## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

## Context
Makes life easier for users who want to copy/pasta the commands into the shell. 

* Browser(s) and version(s): 
* OS: Ubuntu 16.04+

**Comment by hillaryfraley** [comment]
@Blue0ctober is this still an issue we need to address?

**Comment by hillaryfraley** [comment]
@cwjohnston , Richie and Edgar suggested that to resolve this issue, we might need to change the https://docs.sensu.io/sensu-go/latest/installation/install-sensu/#2-configure-and-start instructions:

- Ubuntu/Debian, add another tab with code for `systemd` and `init` to cover 18.04 and newer

What do you think?

**Comment by hillaryfraley** [comment]
Need to reproduce the issue (need to test that the existing instructions will/will not work for 18.04 and newer platforms).

Consider adding a sysconfig command in the RHEL instructions to enable service at boot.

**Comment by hillaryfraley** [comment]
Closing -- 1.x issue (Go docs do not include `update-rc.d`)
