### ISSUE TITLE
Search results for index pages 404

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#552]
Index pages that appear in search results 404 due to malformed URL.

To reproduce: Search for “platforms” and select the first result. You can see that the result tries to take you to https://docs.sensu.io/sensu-core/1.0/platforms/_index instead of https://docs.sensu.io/sensu-core/1.0/platforms. This is due to the way the “location” field for the page is created.

## This is an issue with:

- Bug (site functionality or styling)

**Comment by hillaryfraley** [comment]
@cwjohnston I was going to combine this into #447, but I think this issue might be resolved. When I search the Core docs for "platforms," none of the available results take me to https://docs.sensu.io/sensu-core/1.0/platforms/_index. Maybe this is resolved by Ryan's work -- are you able to reproduce this bug?

**Comment by cwjohnston** [comment]
@hillaryfraley thanks! this issue does appear to be distinct from #447 and I agree that it doesn't seem to be valid any longer. Closing.
