### ISSUE TITLE
Guide Wanted: Setting up RBAC for SED

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#554]
While the reference docs are great, they don't exactly perform the function of walking customers through setting up RBAC for the dashboard. We should add a guide for this. 

- [ ] LDAP
- [ ]  Github
- [ ] Gitlab
- [ ] OIDC

**Comment by asachs01** [comment]
Added check boxes to split out the guides

**Comment by hillaryfraley** [comment]
Pending EOL: won't fix
