### ISSUE TITLE
Document API DELETE client invalidation

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-docs#558]
Added support for invalidating a Sensu client when deleting it via the
Sensu API DELETE /clients/:name endpoint, disallowing further client
keepalives and check results until the client is either successfully
removed from the client registry or for a specified duration of time. To
invalidate a Sensu client until it is deleted, the query parameter
invalidate must be set to true, e.g.
/clients/app01.example.com?invalidate=true. To invalidate the client for
a certain amount of time (in seconds), the query parameter
invalidate_expire must be set as well, e.g.
/clients/app01.example.com?invalidate=true&invalidate_expire=300.

**Comment by cwjohnston** [comment]
Closed by #567
