### ISSUE TITLE
Document Sensu Enterprise Console API

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#561]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior
A reference doc that describes the SE API

## Current Behavior
Currently not present.

## Possible Solution
Write it.

**Comment by asachs01** [comment]
@cwjohnston you've got the full list for this, yeah?

**Comment by cwjohnston** [comment]
Sensu Enterprise Console supports the following API endpoints:

/aggregates (GET)
/aggregates/:aggregate (GET, DELETE)
/checks (GET)
/checks/:check (GET, DELETE)
/checks/:check (GET, DELETE)
/clients (GET)
/clients/:client (GET, DELETE)
/clients/:client/history (GET)
/config (GET)
/datacenters (GET)
/datacenters/ (GET)
/events (GET)
/events/:client/:check (DELETE)
/request (POST)
/results/:client/:check (DELETE)
/silenced (GET, POST)
/silenced/clear (POST)
/stashes/:path (DELETE)
/stashes (GET, POST)
/subscriptions (GET)
/subscriptions/:subscription (GET)
