### ISSUE TITLE
Feature Request: show example of minimum required attributes

### ISSUE THREAD

**Issue by Blue0ctober** [sensu/sensu-docs#568]
There needs to be a way to list required attributes quickly in our docs. 

## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

## Possible Solution
 An example configuration with the minimum required attributes

## Context
Looking up required attributes can be a time consuming pain when trying to troubleshoot quickly. 
Having an example that shows the minimum requirements for both testing and verification is useful.

**Comment by asachs01** [comment]
Is this for each building block? If so, we should probably split this out.

**Comment by apaskulin** [comment]
Choose a page:
- https://docs.sensu.io/sensu-core/1.4/reference/clients/#client-configuration
- https://docs.sensu.io/sensu-core/1.4/reference/checks/#check-configuration
- https://docs.sensu.io/sensu-core/1.4/reference/filters/#example-filter-definition

To do: Add a minimum required attributes example based on which attributes are marked as required on that page.

**Comment by apaskulin** [comment]
Closed by #1168
