### ISSUE TITLE
"Why Sensu?" Doc

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#569]
Similar to https://prometheus.io/docs/introduction/comparison/, it would be super awesome for us to have a comparison doc that outlines the key differences between Sensu and other monitoring products.

**Comment by hillaryfraley** [comment]
Hillary will bring this up with Anna during next 1:1 at the end of March.

edit: Hillary will bring this up with Anna during next 1:1 at the end of November

**Comment by hillaryfraley** [comment]
Discussed with Anna and she agrees this is probably more aligned with a marketing site page. Anna is adding it to the Growth team's backlog.

**Comment by hillaryfraley** [comment]
Cameron agrees with Anna and me that this is something more at home in the marketing site. Closing.
