### ISSUE TITLE
Prototype new version switcher design

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#579]
To provide users with more context about the version they're viewing and to support the upcoming differentiation between Sensu Core 1.x and 2.0, prototype a version switcher that can support:

1. `(latest)` appended to the latest version number
2. links to changelogs
~3. an ad-hoc term appended to some version numbers~

**Comment by apaskulin** [comment]
Updates after some experimentation:

The version switcher lives at [partials/productVersionDropdown.html](https://github.com/sensu/sensu-docs/blob/master/layouts/partials/productVersionDropdown.html), which currently generates version switchers for all products using the same loop.

1. Possible using `$product_info.latest`
2. Possible using `$currentversion`
3. Not possible with the current way the loop works. Would require a more manual method of generating the version switcher.

While I do think that changes 1 and 2 listed above are worth implementing, they require a significant refactoring of the partial that would require adding multiple conditionals. This would substantially increase the complexity of the partial and make it more difficult to maintain.

Related to #296

**Comment by rnevius** [comment]
@hillaryfraley I think this may have been closed by #2015

**Comment by hillaryfraley** [comment]
@rnevius yes, you're correct! Thank you for catching that.
