### ISSUE TITLE
Review sidebar ordering

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#581]
Ordering of links in the navigation sidebar is controlled by the `weight` parameter in the page frontmatter.

To do:
- Review page weights so that sections and pages are ordered logically
- Check for erroneous sidebar items (ex: https://docs.sensu.io/sensu-core/1.4/quick-start/)
- Check for conflicting or duplicated weight values

**Comment by richburroughs** [comment]
Taking the bug label off. This sounds like a content issue. @apaskulin is this something you can handle. Or do you need help?

**Comment by apaskulin** [comment]
Thanks, I can take care of this, @richburroughs.

**Comment by apaskulin** [comment]
Closed by #1121, #670, and #648
