### ISSUE TITLE
Update windows platform page

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-docs#601]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

## Expected Behavior
Windows platform page needs a few updates to make it easier to at least get up and running:
- [x] Call out file extensions based on your editor saving `.json` files as some other file type.
- [x] Move _DANGER to _WARNING
- [ ] Distinguish when to use `PowerShell` or `cmd` (or just use `cmd` if possible)

## Current Behavior

While seasoned windows users might be able to get through the platform guide without issue, the listed items should at least be called out to cover newer users.

## Possible Solution
Add some updates.

## Screenshots (if appropriate):

<img width="1429" alt="screen shot 2018-07-24 at 9 24 37 pm" src="https://user-images.githubusercontent.com/19964713/43179477-045ca034-8f88-11e8-8c4e-fe81c4d81aa9.png">

**Comment by apaskulin** [comment]
I'm hesitant to add another callout type. I think WARNING would work for that example.

![](http://78.media.tumblr.com/cb8e92ab455bf7239d58b690e81fadcc/tumblr_mt7kq10AbO1qg5iluo1_250.gif)

**Comment by rgeniesse** [comment]
I've moved this issue to be a Windows platform update ticket instead, after running through the entirety of the document and getting a working windows client.
