### ISSUE TITLE
Include details of Stash Deprecation in stash-related docs

### ISSUE THREAD

**Issue by slime-man** [sensu/sensu-docs#602]
I found out today that Stashing is deprecated in favor of Silencing, in a quiet footnote at the bottom of the Silencing Docs page.

This should be a louder addition to the Stashing docs. Somewhere up top, clearly saying something about recommending Silencing, rather than stashing. I suggest on the [Stashes Reference Page](https://sensuapp.org/docs/latest/reference/stashes.html) as well as the [Stash API Page](https://sensuapp.org/docs/latest/api/stashes-api.html). Anywhere else it would be relevant, too.

---
unless there is some other use of Stashing that I am not aware of, I thought it was just left in for backwards compatibility.

**Comment by cwjohnston** [comment]
Hi @slime-man, thanks for bringing this to our attention. I've opened #614 to include a note in the stash reference documentation describing the deprecation of stash-based silencing. Stashes themselves are not deprecated, and are expected to remain a feature of Sensu's API for the foreseeable future.
