### ISSUE TITLE
Automate page table of contents

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#603]
Currently, we create a table of contents for each page manually. Hugo offers a [table of contents feature](https://gohugo.io/content-management/toc/) to generate this automatically. We should add an automated table of contents and styling to the single page template.

Design referemces:
- https://developers.google.com/maps/documentation/javascript/adding-a-google-map
- https://docs.microsoft.com/en-us/dotnet/visual-basic/getting-started/index
- https://gohugo.io/templates/introduction/

**Comment by hillaryfraley** [comment]
Next steps: Hillary to investigate

**Comment by hillaryfraley** [comment]
Closed in favor of https://github.com/sensu/sensu-docs/pull/2466
