### ISSUE TITLE
Update Troubleshooting Docs openssl command to add `-cert`

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#605]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

## Expected Behavior
Should have `-cert $PATHTOCERT` 

## Current Behavior
Above is missing.

## Possible Solution
Add it

**Comment by hillaryfraley** [comment]
@asachs01 I'm trying to figure out where this would belong -- is it at https://docs.sensu.io/sensu-go/latest/guides/troubleshooting/? I can't find "openssl" there.

**Comment by hillaryfraley** [comment]
@asachs01  suggests closing for now; can reopen if this issue arises again.
