### ISSUE TITLE
Guide - Using Elasticache

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#607]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Current Behavior

- Call out modes for Elasticache (clustered Redis vs Redis)
- SSL configuration?

**Comment by hillaryfraley** [comment]
Pending EOL: won't fix
