### ISSUE TITLE
Clarify systemd / initd change in 0.29/1.0

### ISSUE THREAD

**Issue by mbbroberg** [sensu/sensu-docs#609]
The change from systemd to init.d seems to be missing documentation. We should have a solid how-to or updates to existing docs to address it. Sorry that I don't know the specific spots to do that. 

Found on HangOps: 

<img width="684" alt="screen shot 2017-07-19 at 9 00 18 am" src="https://user-images.githubusercontent.com/1744971/28377212-f2d95366-6c60-11e7-9877-93831c7a4e81.png">

**Comment by cwjohnston** [comment]
I'll attempt to unpack this a little bit.

The systemd / init change originates in 0.27, we have [upgrading notes](https://sensuapp.org/docs/latest/installation/upgrading.html#upgrading-from-sensu--027) describing the need to manually stop processes running under sysv when upgrading to systemd

Despite the change from sysv to systemd, we continue to load environment variables from `/etc/default/sensu`, but, as described in https://github.com/sensu/sensu-omnibus/issues/216#issuecomment-315157356, we did change the environment variable used to specify the directory path Sensu will load configuration from (`CONF_DIR` -> `CONFD_DIR`).

**Comment by cwjohnston** [comment]
In #610 the upgrade notes have been updated to describe the CONFIG_DIR -> CONF_D change.
