### ISSUE TITLE
Update EC2 guide to describe IAM roles and policies for cross-account usage.

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#622]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

## Expected Behavior
Include instruction on how to configure EC2 for cross-account useage.

## Current Behavior
Current instruction is missing.

## Possible Solution
Update additional content.

Will fix #614

**Comment by asachs01** [comment]
Will fix #614

**Comment by Blue0ctober** [comment]
Closed by #632
