### ISSUE TITLE
Update contact routing reference to include array of `"severities"`

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#623]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

## Expected Behavior
Reference shows:

```
{
  "contact": {
    "foo": {
      "integration" : { 
        "severities" : ["warning", "critical"]
      }
    }
  }
}
```

## Current Behavior
Current reference is missing.

## Possible Solution
Add it.

Will fix sensu/sensu-enterprise/issues/315

**Comment by asachs01** [comment]
Need to check to see if this is at the contact level, or integration w/in the contact.

**Comment by cwjohnston** [comment]
@asachs01 the code comments and unit test in 
https://github.com/sensu/sensu-enterprise/pull/378/ indicate that the severities may be inside integration options for each contact.
