### ISSUE TITLE
Guide Wanted: Configuring the Dashboard

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#630]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior
Guide doing a walkthrough of configuring the dashboard.

## Current Behavior
Guide is not present.

## Possible Solution
Write it.

**Comment by asachs01** [comment]
Full list of cipher suites that are supported can be found here https://golang.org/src/crypto/tls/cipher_suites.go

**Comment by asachs01** [comment]
"As a Sensu user, I want to secure the dashboard SSL/TLS"
"As a Sensu user, I'd like have a guide that walks me through how to do ^"

**Comment by rgeniesse** [comment]
@asachs01 is the scope of this guide only to setup SSL/TLS for the Sensu Enterprise Dashboard? Would it also be safe to say that a prerequisite would be to have the Sensu Enterprise Dashboard installed and configured without SSL/TLS before doing this guide? 

We do go over that a bit here: https://docs.sensu.io/sensu-core/1.5/platforms/sensu-on-rhel-centos/#dashboard-standalone-configuration

And I can link back to those if needed.

Thanks!

**Comment by apaskulin** [comment]
Closing since this is covered in https://docs.sensu.io/sensu-core/1.5/platforms/sensu-on-rhel-centos/#dashboard-standalone-configuration
