### ISSUE TITLE
Shell syntax error on 5 min install

### ISSUE THREAD

**Issue by mbbroberg** [sensu/sensu-docs#636]
Looks like one of the shell commands isn't rendering quite right. I can't put my finger on what the problem is. Seems like either a spacing issue on when `~~~ shell` is aligned or how the numbering pushes the rest of the text over. I tried manipulating both and found it broke further down the text instead of where it's currently broken, so I'm backing away slowly now... 

Current issue is seen on https://sensuapp.org/docs/1.0/quick-start/the-five-minute-install.html

<img width="788" alt="screen shot 2017-10-06 at 10 49 49 am" src="https://user-images.githubusercontent.com/1744971/31291784-c09f98a2-aa85-11e7-8c18-85900eafc431.png">

**Comment by mbbroberg** [comment]
FOUND IT! It's a Tab to Spaces issue.

**Comment by mbbroberg** [comment]
Tab problem AND requires a single character for the list. A play in two acts: 

<img width="400" alt="screen shot 2017-10-06 at 11 06 50 am" src="https://user-images.githubusercontent.com/1744971/31291993-918118d8-aa86-11e7-9207-a44a9bcabc90.png">

Results in: 
<img width="400" alt="screen shot 2017-10-06 at 11 06 45 am" src="https://user-images.githubusercontent.com/1744971/31292007-9f44d52c-aa86-11e7-8bb6-72fa504257ce.png">

And the fix: 
<img width="400" alt="screen shot 2017-10-06 at 11 02 11 am" src="https://user-images.githubusercontent.com/1744971/31292019-acc79b58-aa86-11e7-98a0-b12757431078.png">

<img width="400" alt="screen shot 2017-10-06 at 11 07 00 am" src="https://user-images.githubusercontent.com/1744971/31292032-b57b6d4c-aa86-11e7-8a7d-dc3fd46d7077.png">

**Comment by calebhailey** [comment]
Nice find!
