### ISSUE TITLE
curl | bash installer for downloads page

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-docs#639]
We should provide a `curl | bash` one liner for Sensu 1.x installation that we can provide on the Downloads page (https://sensuapp.org/downloads) and the Sensu installation guide.

**Comment by asachs01** [comment]
@portertech @cwjohnston has a gist that he's used for training that might be of use here. I've got one (based off of his) for SE.

**Comment by cwjohnston** [comment]
Closing as a duplicate of #501
