### ISSUE TITLE
Guide Wanted: Proxy Clients

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#639]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior
Expanded content/walkthrough on creating proxy clients in Sensu 1.X is present.

## Current Behavior
Content doesn't yet exist.

## Possible Solution
Write the content

**Comment by asachs01** [comment]
"As a user, I want to be able to monitor [infra, APIs, sites] that I can't install Sensu on."
"As a user, I'd like to have a guide that shows me how I can accomplish ^"

**Comment by apaskulin** [comment]
Let's start this off with a support experience outline: main use cases, points of potential misunderstanding, key features

**Comment by rgeniesse** [comment]
A few thoughts as users have come to us with proxy client issues:
- Use proxy clients following a pub/sub model
- Use proxy clients following a standalone check model

I feel #1095 is related here, so the questions I have there may better define the purpose of this guide.

**Comment by hillaryfraley** [comment]
Pending EOL: won't fix
