### ISSUE TITLE
Guide Wanted: Create monitor Sensu Enterprise with Sensu Enterprise

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-docs#641]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [X] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior
Create a document for SE as we did with Sensu Core.

Scope:
1.) Monitoring Sensu Enterprise
     - Sensu API inside of it
     - Sensu health points to monitor the server or possible network port.
2.) Sensu Enterprise Dashboard
     -  Process running
     - Ability to get to dashboard port

**Comment by hillaryfraley** [comment]
Pending EOL: won't fix
