### ISSUE TITLE
External drivers for Sensu 2.x RBAC will be Enterprise only

### ISSUE THREAD

**Issue by obfuscurity** [sensu/sensu-docs#642]
https://docs.sensu.io/sensu-core/2.0/reference/rbac/ incorrectly claims that `Support for external directories (such as LDAP) is planned for future releases`. This is incorrect, as support for external RBAC directories will only be supported in future releases of Enterprise (not Core).

## This is an issue with:

- [ ] Bug (site functionality or styling)
- [x] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Possible Solution
A solution might be to rewrite it as `Support for external directories (such as LDAP) will be included in the Enterprise edition`.

## Context
We want to be transparent with our users about which products will support this functionality.

**Comment by obfuscurity** [comment]
@apaskulin I'm curious why we went with removing the mention completely. I'm not against it per se but I wonder if this is going to raise more questions than it answers.

**Comment by apaskulin** [comment]
@obfuscurity I don't think the reference docs are the right place for this kind of information while the feature is still unreleased.
