### ISSUE TITLE
Guide Wanted: Using Check Aggregates

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#643]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior
Guide describing use of check aggregates is present.

## Current Behavior
Guide isn't present.

## Possible Solution
Write the guide

## Context
"As a Sensu user, I want to know how to monitor the overall health of a service or application, not just an individual check."
"As a Sensu user, it'd be helpful to have a guide describing how I can monitor the overall health of a service or application."

**Comment by hillaryfraley** [comment]
Add as a Discourse post for Sensu Go

**Comment by hillaryfraley** [comment]
Aaron is testing some changes from Todd and then should be able to publish.

Aaron and Edgar to voltron on this issue.

**Comment by asachs01** [comment]
Closed by #2162
