### ISSUE TITLE
Installing Sensu via gem packages requires some documentation

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#644]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

## Expected Behavior

We should describe installing Sensu from gem packages for some edge cases

## Current Behavior

We don't describe installing Sensu from gem packages

## Possible Solution

Document this process, consider https://github.com/sensu/sensu/issues/1865 as a possible edge case

## Context

See https://github.com/sensu/sensu/issues/1865 for example of issues encountered when installing Sensu from gem packages

**Comment by hillaryfraley** [comment]
Pending EOL: won't fix
