### ISSUE TITLE
Reference Other Mail Platforms in SE Email Doc

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#647]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

## Expected Behavior
Point to major mail services' SMTP gateway docs. 

## Current Behavior
References to other mail platforms are not present. 

## Possible Solution
Add:

* [AWS SES](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-smtp.html)
* [Mailgun](https://documentation.mailgun.com/en/latest/user_manual.html#smtp-relay)
* [Office 365](https://support.office.com/en-us/article/How-to-set-up-a-multifunction-device-or-application-to-send-email-using-Office-365-69f58e99-c550-4274-ad18-c805d654b4c4?ui=en-US&rs=en-US&ad=US)
* [Gmail/Gsuite](https://support.google.com/a/answer/176600?hl=en)

To https://docs.sensu.io/sensu-enterprise/$/integrations/email/

**Comment by rgeniesse** [comment]
@asachs01 , is this a duplicate of #294?

**Comment by asachs01** [comment]
@rgeniesse yup. I was thinking there were some differences, but they're pretty much the same.
