### ISSUE TITLE
Guide Wanted: Add TLS/SSL to 2.x sensu-backend

### ISSUE THREAD

**Issue by teekennedy** [sensu/sensu-docs#649]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior
Create a guide for Sensu 2.x to generate TLS certs and configure sensu-backend instances to use them for peer, API, and dashboard communication.

A reference implementation can be found in https://github.com/sensu/sensu-staging

**Comment by jaredledvina** [comment]
Is this similar to https://github.com/sensu/sensu-docs/issues/390?

**Comment by teekennedy** [comment]
Ah why yes it is! Closing this in favor of existing issue.

Duplicates #390
