### ISSUE TITLE
/checks API doc should describe exclusion of standalone checks

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#654]
As described in https://github.com/sensu/sensu/issues/1775, the /checks API documentation does not explicitly indicate that `standalone` checks are excluded from the results returned by this endpoint.

We should explicitly document that standalone checks are not returned by /checks endpoint.

**Comment by mbbroberg** [comment]
@cwjohnston can you confirm this is resolved by https://github.com/sensu/sensu-docs/pull/673/commits/c8e0c434df8bee6fb812c5c196b38323a1403f60 which is pulled into #675? ThanksQ!

**Comment by cwjohnston** [comment]
This issue was moved to sensu/sensu-docs-site#123
