### ISSUE TITLE
Scheduled maintenance event silencing is undocumented

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#654]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

## Expected Behavior

Documentation reflects features implemented in released versions of Sensu

## Current Behavior

Scheduled maintenance silencing implemented in https://github.com/sensu/sensu/pull/1790 is undocumented in the silencing reference documentation

## Possible Solution

Update silencing reference documentation to describe `begin` attribute.

**Comment by apaskulin** [comment]
@rgeniesse to review

**Comment by apaskulin** [comment]
For Sensu Core 1.2 and later
