### ISSUE TITLE
How do I install Sensu Plugins?

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#665]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior
Have a guide that tells our users how they can install Sensu plugins.

## Current Behavior
We currently have commands scattered around the docs, as well as some of the plugin repos, but we have nothing that explicitly tells users "install plugins via `sensu-install -p $NAMEOFPLUGIN`. 

## Possible Solution
Add an article to the `installation` section.

## Context
This is one of the most commonly asked questions, and can be a source of confusion for new users. By explicitly calling this out in the docs, we deflect any support requests, whether in the community channel, or via the enterprise helpdesk.

**Comment by cwjohnston** [comment]
I think we should both write this guide connect it to content in https://docs.sensu.io/plugins/1.0/installation/ which describes config management approaches etc.
