### ISSUE TITLE
Firm up language about how Redis is NOT recommended as a transport

### ISSUE THREAD

**Issue by mbbroberg** [sensu/sensu-docs#668]
Multiple conversations in our Community Slack ([this one](https://sensucommunity.slack.com/archives/C3C1D874M/p1511896980000779) & [another starting here](https://sensucommunity.slack.com/archives/C68LV5M9U/p1511893439000219)) show that people are using Redis as a replacement for RabbitMQ without knowing the ramifications of doing so. It is important to both: 

* Clarify that Redis is not recommended 
* Warn how it is not supported in any significant way by the maintainers

So far we've found it needs to be added to: 

- [ ] 1. [This doc on Using Redis as a transport](https://sensuapp.org/docs/1.1/installation/install-redis-on-ubuntu-debian.html#using-redis-as-the-sensu-transport)
- [ ] 2. [Transport reference documentation](https://sensuapp.org/docs/1.1/reference/transport#the-redis-transport)

But I'm sure there are others. Please add them or address in a PR. 

I know @majormoses is interested in resolving this ASAP so feel free to take a whack and I'll do a PR review and release.

**Comment by majormoses** [comment]
Will get to this today hopefully.

**Comment by majormoses** [comment]
:tada:
