### ISSUE TITLE
Rename layouts in the interest of clarity

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#67]
The current layout names, e.g. index, index-2, index-3 are somewhat unintuitive and we might consider renaming them to resemble their function. Here's the current intended usage per @dabria 

> `single` is what the default layout is for content. 
> Index is for a landing page to a project
`project/index`
> Index-2 is the landing page for if you’ve picked a version. 
`project/1.0/index`
> Index-3 is the landing page for a subfolder from the version.
`project/1.0/reference/index`
> Generally the first index is never seen because we take you directly to the latest version of a project and you can select a version from any page in the project, but it’s there to not break stuff.

**Comment by dabria** [comment]
I believe `single.html` is the only one which can't be renamed due to some Hugo defaults. The others can be renamed and will need their respective file's `layout` front matter value changed to the new name.

**Comment by asachs01** [comment]
@cwjohnston @dabria did this get addressed, or is this still ongoing?

**Comment by dabria** [comment]
@asachs01 I just looked at it appears I renamed these, I think I just forgot to link this ticket in my PR.

**Comment by dabria** [comment]
#141 fixed this
