### ISSUE TITLE
Re-order `installation` docs for more logical flow

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#670]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

## Expected Behavior
Ideally, each doc inside of the installation section should build on the previous docs. For example:

1. Install/configure Sensu server/api
2. Install/configure Sensu client
3. Install/configure RabbitMQ
4. Install/configure Redis

#484 provides some more detail on what should be expected.

## Current Behavior
Currently, things are a bit out of order when it comes to installation (hence #484), and with #666 incoming, installation has the potential to be more out of whack.

## Possible Solution
Reorder the content so that it makes sense. This should solve #484.

**Comment by apaskulin** [comment]
Closed by #809
