### ISSUE TITLE
Create documentation for 2.x clustering

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-docs#671]
We need to add some documentation around 2.x clustering. While sensu clustering works similarly to etcd clustering, we should have our own documentation instead of relying on etcd's.

Things the documentation should cover:

* the sensuctl cluster commands, and how they work
* clustering operations pitfalls
* how to go from a 1-node cluster to a 3-node cluster

The documentation should contain both reference material and a guide for clustering.

**Comment by asachs01** [comment]
Linking to the Notion doc: https://www.notion.so/Clustering-WIP-22093c565a7247e7b48938fc476068a7

**Comment by asachs01** [comment]
@echlebek for clustering, do we have any clarification on how to BYO cert (a la letsencrypt) and use that with SSL for the backend?

**Comment by apaskulin** [comment]
Closed by #818, #766, and #884
