### ISSUE TITLE
2.x check reference should not say handler is required 

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-docs#679]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [x] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior

The examples for adding checks with sensu 2.x do no assign a handler and I'd expect the reference to match this behavior.

## Current Behavior

Currently the sensu check reference says handler is required.

## Possible Solution

Change handler reference to be not required.

## Steps to Reproduce (for bugs)

Page with example without defining handler - https://docs.sensu.io/sensu-core/2.0/guides/monitor-server-resources/
Page with reference that shows handler required - https://docs.sensu.io/sensu-core/2.0/reference/checks/

## Context

I'm working with @ghoneycutt to automate with Puppet and basing our Puppet code on reference docs.

**Comment by apaskulin** [comment]
Page: https://docs.sensu.io/sensu-core/2.0/reference/checks/#check-attributes
To do: Change `required | true` to `required | false` under "handlers".
