### ISSUE TITLE
Support adding documentation that is merged but not released

### ISSUE THREAD

**Issue by majormoses** [sensu/sensu-docs#680]
Currently there is no "next" or "unreleased" place to put documentation for features that have been accepted but have not been assigned to a particular release version.

The following issues and PRs illustrate this lack of solution:
- https://github.com/sensu/sensu-docs/pull/678
- https://github.com/sensu/sensu-docs/pull/679
- https://github.com/sensu/sensu/issues/1799
- https://github.com/sensu/sensu/pull/1800

Ideally documentation should be coming in as new features are developed with a `[WIP]` prefix on the PRs.

This should be considered while designing the new documentation system.

**Comment by mbbroberg** [comment]
Great news! With the new docs site released, this is a built-in functionality as show by the 2.0 Release: https://docs.sensu.io/sensu-core/2.0/

<img width="758" alt="screen shot 2018-03-20 at 3 45 52 pm" src="https://user-images.githubusercontent.com/1744971/37686701-cbe9e72e-2c55-11e8-8edb-e1d2f72e2cba.png">

I'm closing in favor of this being available. If there's further documentation on how to prep a new release that isn't yet [in the wiki](https://github.com/sensu/sensu-docs-site/wiki/Hugo-Formatting-and-Layouts), please open an issue on that repo or add to the wiki. Thanks!

**Comment by majormoses** [comment]
Not sure I agree they are the same thing, we need a `2.x-unreleased` and a `1.x-unreleased` respectively.

**Comment by mbbroberg** [comment]
My mistake here - there is still a need to _have_ the versions. The functionality will be much easier than previously. I have an existing issue on the project to cover it: https://github.com/sensu/sensu-docs-site/issues/227

**Comment by majormoses** [comment]
Sounds good, am fine with it being moved over to the new project just wanted to make sure that it was clear that the need has not been fulfilled yet and that someone will work on it.
