### ISSUE TITLE
Add links for windows/386 builds of sensu-agent

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-docs#687]
We've added support for `windows/386` to sensu-agent and https://docs.sensu.io/sensu-core/2.0/getting-started/installation-and-configuration/ will need to be updated to reflect the next releases once they've been built.

The URL path for `windows/386` will use `windows/386` rather than `windows/amd64`.

e.g. https://storage.googleapis.com/sensu-binaries/2.0.0-beta.4-1/windows/386/sensu-agent

**Comment by apaskulin** [comment]
@amdprophet It seems like https://storage.googleapis.com/sensu-binaries/2.0.0-beta.7-1/windows/386/sensu-agent isn't working for me

**Comment by apaskulin** [comment]
Closing for now based on currently supported platforms
