### ISSUE TITLE
Add a Windows section to the Configure sensuctl page

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-docs#688]
The `windows/amd64` sensuctl releases are already being built with `windows/386` sensuctl releases coming with the next release. The `Configure sensuctl` page should be updated to include links to the Windows sensuctl releases https://docs.sensu.io/sensu-core/2.0/getting-started/configuring-sensuctl/.

e.g. http://storage.googleapis.com/sensu-binaries/2.0.0-beta.4-1/windows/amd64/sensuctl (64-bit builds)

**Comment by apaskulin** [comment]
Closed by #771
