### ISSUE TITLE
The menus on the sidebar only go a directory deep after version

### ISSUE THREAD

**Issue by dabria** [sensu/sensu-docs#69]
There may need to be additional code written to support deep directories.

`project/version/folder1/item` will appear on the list. However `project/version/folder1/folder2/item` will not.

The logic for displaying these items will probably have to be reworked at some point.

**Comment by asachs01** [comment]
@dabria 👋 was curious if this was still lingering, or something we can close out.

**Comment by dabria** [comment]
It's currently not a problem, however it's something we need to be mindful of in the future. We can either close it and reopen it when it becomes an issue, or let it hang around, preemptively fixing it down the road when there's time.

**Comment by asachs01** [comment]
Howdy @dabria , is this something we can implement? We're seeing the need to have additional subdirectories (e.g., project/version/folder1/folder2).

**Comment by dabria** [comment]
Fell behind a bit on my notifications, sorry!

We can definitely implement it. As for when, is this currently blocking work needing to take place? I can look into getting this worked into our next sprint.

**Comment by asachs01** [comment]
Ach, this is what I get for having my GH notifications filtered. I think the change might actually be pretty simple (https://discourse.gohugo.io/t/hierarchical-menus/2406/3). If that link is correct, it could just be something that I might be able to make changes myself and do a PR.

**Comment by hillaryfraley** [comment]
This will be resolved in tasks 1 and 2 in https://github.com/sensu/sensu-docs/issues/2443
