### ISSUE TITLE
Repo link for RHEL/CentOS is outdated. 

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#703]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

## Expected Behavior
```
[sensu]
name=sensu
baseurl=https://repositories.sensuapp.org/yum/$releasever/$basearch/
gpgcheck=0
enabled=1
```

## Current Behavior
```
[sensu]
name=sensu
baseurl=https://sensu.global.ssl.fastly.net/yum/$releasever/$basearch/
gpgcheck=0
enabled=1
```

## Possible Solution
Update the link to what's under "Expected Behavior"

**Comment by apaskulin** [comment]
Does this apply to all links to fastly or just the one on this page?

**Comment by asachs01** [comment]
So this needs to be reworked. Essentially, we need to find where in the docs we're referencing 
```
[sensu]
name=sensu
baseurl=https://sensu.global.ssl.fastly.net/yum/$basearch/
gpgcheck=0
enabled=1
```
From our convo in sprint, the repo definition above seems to be responsible for problematic issue of customers only getting up to version .26. It could also older Sensu puppet/chef versions. Going to try and track this down this week.

**Comment by asachs01** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Track down SE .26 repo references](https://trello.com/c/l8oLqYHO/1-track-down-se-26-repo-references)

**Comment by hillaryfraley** [comment]
@asachs01 I think the https://repositories.sensuapp.org/yum/$releasever/$basearch/ is a 404. Does this still need to be fixed?

**Comment by cwjohnston** [comment]
@hillaryfraley a 404 is expected for that URL; `$releasever` and `$basearch` are variables which get interpolated with local values when fed through the yum package manager. The result of the interpolation would be something like https://repositories.sensuapp.org/yum/7/x86_64/

**Comment by hillaryfraley** [comment]
Closed by https://github.com/sensu/sensu-docs/pull/1915
