### ISSUE TITLE
Sensu Go Epic: Reference

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#709]
This is a tracking ticket for all planned docs within the Getting Started section. Notes below should be moved to individual tickets once created.

### Reference
Existing:
- [ ] Assets
- [ ] Checks #678 #522 #440
- [ ] Entities #420
- [ ] Events
- [ ] Filters #409 #822
- [ ] Handlers #658
- [ ] Hooks #401
- [ ] Mutators
- [ ] RBAC
- [ ] Sensu Query Expressions
- [ ] Sensuctl
- [ ] Silencing
- [ ] Tokens

To write:
- [ ] ~~Aggregates #527~~
- [x] Backend #364 #528 #390
- [x] Agent #364 #390 #658
- [ ] Benchmark? #414

**Comment by jspaleta** [comment]
Is there a plan to add API reference doc for Agent api endpoint and control api endpoints under the Reference section?

**Comment by apaskulin** [comment]
Tracked as individual issues
