### ISSUE TITLE
Refactor Quick Start to use Sandbox Instead of Alternate Installation Instructions

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#710]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [x] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

## Possible Solution
Refactor the 5 Minute Install to point to sensu/sandbox.

## Context
We've recently noticed quite a bit of confusion around what configuration files are actually needed for a working Sensu instance. The idea here is to:

* Keep things as simple as possible
* Ensure that instructions are consistent across platform, guide, and quick start sections
* Ensure that our examples are crystal clear

**Comment by apaskulin** [comment]
Closed by #809 and #718
