### ISSUE TITLE
Fold In Community Best Practices Docs into Docs Project

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#712]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior
docs.sensu.io should be the canonical place for best practices, whether it be around deployment, version pinning, etc. The docs linked below should live there.

## Current Behavior
Currently, community has a set of docs living https://github.com/sensu-plugins/community/tree/master/best_practices. 

## Possible Solution
Fold the docs into the docs site.

**Comment by hillaryfraley** [comment]
@asachs01 how much of this is relevant for Go docs?
Do you mean for these best practices to live only in the docs? Or also in the community repo perhaps?

**Comment by hillaryfraley** [comment]
This is a topic we will cover during our team onsite w/CR and Dev Advocates.

**Comment by asachs01** [comment]
@hillaryfraley did we ever discuss this during the offsite? I don't recall if we ever did. Also, those best practices seem WAAAAAY out of date to me. I mean, there are some things here, but overall we probably need to figure out what the "Sensu Go best practices" look like.

**Comment by hillaryfraley** [comment]
@asachs01 I don't think we did discuss it -- I don't see it on the agenda. In any case, one of our community Slack members suggested adding best practices in the docs last week. I agree it would be excellent to figure this out and add it in the docs.

**Comment by hillaryfraley** [comment]
Document reason for specifying an asset version when using sensuctl asset add in https://docs.sensu.io/sensu-go/latest/plugins/use-assets-to-install-plugins/ and https://docs.sensu.io/sensu-go/latest/plugins/install-plugins/

"To install the latest version of the plugin, use [no version command]. But if you're doing any kind of automation with assets, Sensu will automatically pull the latest version unless you've specified a version when you add the asset or plugin."

Read https://github.com/sensu-plugins/community/blob/master/best_practices/production_deployments/plugins/PINNING_VERSIONS.md for insights about versioning to figure out how to phrase this version pinning info.
