### ISSUE TITLE
Add configuration file matrix

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#716]
Dropping this in quick, but it seems like it might be helpful for us (in lieu of getting another ticket about configuration) to have a matrix indicating what config files are needed on what component (e.g., on the client, on the server).

**Comment by cwjohnston** [comment]
This seems like it might make sense as an entry in the FAQ

**Comment by cwjohnston** [comment]
Once we have the content written we can also identify places in the install instructions to put notes related to this.
