### ISSUE TITLE
Add SSL troubleshooting step to guide regarding get_private error

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-docs#719]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [X] Update (Add missing or refresh existing content)

## Expected Behavior
Add additional step in troubleshooting SSL issues to:
https://docs.sensu.io/sensu-core/1.5/guides/troubleshooting/

Step:
openssl rsa -in your-current-key.key -out new-key.pem

For error mentioned in:
https://secure.helpscout.net/conversation/380597415/1748/

## Current Behavior
Missing step!

## Possible Solution
Add that step!

**Comment by cwjohnston** [comment]
Maybe this goes in the troubleshooting guide?

**Comment by cwjohnston** [comment]
Closed by https://github.com/sensu/sensu-docs/pull/790
