### ISSUE TITLE
Add SSL troubleshooting step to guide regarding Unknown CA

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#720]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

## Expected Behavior
Step re: adding full chain to `client` certs (e.g., sensu-server/enterprise RMQ config)

## Current Behavior
MIssing

## Possible Solution
Add it

**Comment by cwjohnston** [comment]
Maybe this goes in the troubleshooting guide
