### ISSUE TITLE
Update SSL reference re: RMQ and SSL depth

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#721]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

## Expected Behavior
Content describing https://www.rabbitmq.com/ssl.html#peer-verification-depth

## Current Behavior
MIssing

## Possible Solution
Add it

**Comment by cwjohnston** [comment]
Perhaps this belongs in the RMQ configuration reference
