### ISSUE TITLE
Add end-to-end testing doc/troubleshooting guide

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#725]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior
Instructions describing doing an end to end test with Sensu

## Current Behavior
Not present

## Possible Solution
Add it.

**Comment by apaskulin** [comment]
@asachs01 Can you add some requirements for an end-to-end test?
