### ISSUE TITLE
Typo on https://docs.sensu.io/plugins/1.0/developer-guidelines/#issue-and-pull-request-submissions

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#728]
Under the URL mentioned in the title, there is the following:
```
The CHANGELOG follows the standard conventions laid out here. Every PR has to include an updated CHANGELOG and README (if needed), this makes our lives eaiser
```
`Eaiser` should be `easier`

**Comment by rgeniesse** [comment]
Also:

```- the minor version is for the addition of **any* new scripts.  Even though this is generally non-breaking, it is a major change to the gem and should be indicitated as such```

`indicitated` should be `indicated` (maybe, google leaves me with no confidence here)

and

```- the major version should only be bumped by a core contributor.  This is for major breaking or non-breaking changes that affect widespreadspread functionality.  Examples of this would be a wholesale refactor of the repo or a switch away from an established method such as going from SOAP to REST across multiple checks.```

`widespreadspread` should be `widespread` (?).
