### ISSUE TITLE
Moving from unique 2.0 page to any 1.x version using latest bar at top results in 404

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-docs#733]
## This is an issue with:

- [X] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior
Should bring you to the home page for the latest version of sensu core.

## Current Behavior
Results in 404:

## Steps to Reproduce (for bugs)
1. Got to https://docs.sensu.io/sensu-core/2.0/getting-started/installation-and-configuration/
2. Click the bar at top "You're viewing documentation for an older or pre-release version of Sensu Core. Click here for the latest."

## Screenshots (if appropriate):
![screen shot 2018-09-12 at 2 34 01 pm](https://user-images.githubusercontent.com/19964713/45454478-e9e23380-b698-11e8-828b-c701b457c5d3.png)

**Comment by rgeniesse** [comment]
Possibly caused by changes in #591.

**Comment by obfuscurity** [comment]
@rgeniesse This looks like a dupe of #407, would you agree?

**Comment by rgeniesse** [comment]
Agreed. Closing. Thanks!
