### ISSUE TITLE
Server task election mechanism should be described in docs

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#736]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

## Expected Behavior

As a Sensu implementor I would like to understand the technical mechanism used to implement server task election so I can reason about how it works. 

## Current Behavior

Task election is described in broad strokes but the technical details are not present. As a result folks may try to make sense of task election by reading the source code, which is not trivial.

## Possible Solution

Expand on the [existing server task documentation](https://docs.sensu.io/sensu-core/1.5/reference/server/#server-tasks) with a technical explanation

## Context

Folks in the Community Slack are looking for this kind of information and find it lacking in our docs.

![2018-09-13 at 10 52 am](https://user-images.githubusercontent.com/148017/45504517-53b91680-b747-11e8-86d3-529482449074.png)

**Comment by hillaryfraley** [comment]
Pending EOL: won't fix
