### ISSUE TITLE
Limit search results to specific version

### ISSUE THREAD

**Issue by obfuscurity** [sensu/sensu-docs#740]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [x] Enhancement (site functionality)

## Expected Behavior

We should provide a way for users to limit their search results to a specific version. If this scope is active, it should intuit that we also want to limit search results to the current product. I propose that the keyword for this feature is `version`.

For example, if I'm browsing the Sensu Core docs and search for `handlers version:1.5`, it should only return results pertaining to Sensu Core 1.5.

## Current Behavior

The current behavior is to return any matching documents across the entire documentation site. There appears to be no way to scope matching results to a particular product or version.

## Possible Solution

No known solution at this time. AIUI we're using lunarjs for our search capability, which AFAICT has no support for this sort of scoping.

**Comment by apaskulin** [comment]
#1370 scopes the search to the currently selected version without the need to specify the version in the search terms.
