### ISSUE TITLE
Order search results according to product version

### ISSUE THREAD

**Issue by obfuscurity** [sensu/sensu-docs#742]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [x] Enhancement (site functionality)

## Expected Behavior

We should return match results in an intuitive fashion. If the user is in docs for Sensu Core version 1.5, we should return search results with an affinity for that product and version, followed by all other versions of that product (newest to oldest), followed by other products and versions (newest to oldest).

For example, if the user is browsing docs for Sensu Core version 1.5, a search for `silencing` should return the following results first:

- https://docs.sensu.io/sensu-core/1.5/reference/silencing (current version)
- https://docs.sensu.io/sensu-core/2.0/reference/silencing (highest version number of current product)
- https://docs.sensu.io/sensu-core/1.4/reference/silencing
- https://docs.sensu.io/sensu-core/1.3/reference/silencing
- https://docs.sensu.io/sensu-core/1.2/reference/silencing
- https://docs.sensu.io/sensu-core/1.1/reference/silencing
- https://docs.sensu.io/sensu-core/1.0/reference/silencing
- https://docs.sensu.io/sensu-core/0.29/reference/silencing
- https://docs.sensu.io/sensu-enterprise/3.0/filters/silence-stashes (different product, highest version)
- https://docs.sensu.io/sensu-enterprise/2.8/filters/silence-stashes

## Current Behavior

Current results are unpredictable and unintuitive. There is no discernible pattern for the order of the returned set of results.

## Possible Solution

No known solution at this time. AIUI we're using lunarjs for our search capability, which AFAICT has no support for this sort of predictable results ordering.

**Comment by apaskulin** [comment]
#1370 scopes the search to the currently selected version.
