### ISSUE TITLE
Navigate search results with keyboard

### ISSUE THREAD

**Issue by obfuscurity** [sensu/sensu-docs#744]
@apaskulin suggested that we add support for keyboard-driven search results navigation. This feels like a nice addition with accessibility benefits.

## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [x] Enhancement (site functionality)

## Expected Behavior

A user should be able to perform a new search, navigate through the results, and select a final choice using only keyboard inputs. Example workflow:

- User enters a keyboard shortcut to activate the search bar (e.g. `ctrl+shift+s` or `command+shift+s`).
- Search bar opens and grabs input
- User enters search string (e.g. `handlers`).
- Search results populate interactively.
- User navigates to the 3rd result with the down arrow. Each item is highlighted as the cursor enters its selection box.
- User selects the desired result by pressing `enter`.

## Current Behavior

Users are required to click on the Search icon (🔍) and select the desired result with their mouse. There is no keyboard-driven analog to this series of actions.

**Comment by apaskulin** [comment]
Closed by #1312
