### ISSUE TITLE
Sensu 2.0 Document agent.yml options

### ISSUE THREAD

**Issue by majormoses** [sensu/sensu-docs#753]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

## Expected Behavior

Documentation should be available

## Current Behavior

It is not

## Possible Solution

Document it

## Context

Not obvious what you can/can't configure via agent config

**Comment by majormoses** [comment]
From a slack question:
> Is it possible to set extended attributes in the agent.yml file and then see them in all events from the agents I have set it on?

> ...and if it is possible can someone please show me how it's supposed to look like in agent.yml?

**Comment by asachs01** [comment]
Good question! @majormoses there are some docs in the works from the SWE's that should be released soon. I think @nikkiki and @echlebek were working on getting those pushed out.
