### ISSUE TITLE
Adding Dashboard Docs?

### ISSUE THREAD

**Issue by solarkennedy** [sensu/sensu-docs#76]
I have been setting up a lot of Sensu in production, which involved putting the Sensu dashboard behind a proxy, ssl, etc.

There isn't much docs on the dashboard at all. Would a PR be accepted if I added these entries and content, after maybe the API section?

* **Dashboard
  * [Basic Usage]
  * [Configuration]
  * [Proxy Howto]

If so, are there additional sections you would like to see? If not, where would you like these docs to be and what content would you like to see?

**Comment by agoddard** [comment]
Hi @solarkennedy, we now have Enterprise Dashboard docs on the docs page, and uchiwa docs are now maintained separately from the Sensu project. I'll close this, however please feel free to re-open if there's any additional documentation you would like to see on the Enterprise Dashboard
