### ISSUE TITLE
Guide Wanted: Monitor Unifi networking equipment

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#760]
Late night, and this isn't fully fleshed out, but here goes:

Guide for using Sensu to monitor Unifi networking equipment via the Unifi API. This probably won't be worth too much, as it's a very specific subset of networking equipment, but this _could_ be a cool thing to do. Ideas for what to monitor are your standard network metrics, but then you could be shipping this off to influx, graphite, whathaveyou.

**Comment by agoddard** [comment]
https://github.com/sensu-plugins/sensu-plugins-ubiquiti/blob/master/bin/metrics-unifi.rb

**Comment by asachs01** [comment]
Emmmm, I don't know why the hell I opened this. This categorically doesn't belong on the docs and should be in a plugin readme or discourse post.
