### ISSUE TITLE
Site hanging due to Fontawesome.js unavailability

### ISSUE THREAD

**Issue by richburroughs** [sensu/sensu-docs#764]
## This is an issue with:

- [X] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior

Site should be loading.

## Current Behavior

Site is hanging due to fontawesome's CDN being unavailable. https://twitter.com/fontawesome/status/1045070553734950912

## Possible Solution

We could possibly host the file locally, or come up with a different solution.

## Steps to Reproduce (for bugs)

1.
2.
3.

## Context

* Browser(s) and version(s): 
* OS:

**Comment by mercul3s** [comment]
This needs a fallback to a locally hosted fontawesome.js if the cdn is unavailable.

**Comment by mercul3s** [comment]
A quick and dirty fix has been deployed with this pr: https://github.com/sensu/sensu-docs/pull/765
I still need to ensure the actual fallback mechanism works, will do that later this week.

**Comment by mercul3s** [comment]
I have a working mechanism to do fallback, so I'm going to go ahead and vendor any other cdn sourced assets as well.

**Comment by richburroughs** [comment]
@mercul3s Please do. Thank you :)
