### ISSUE TITLE
Update Sensu 2.0 clustering document to only use configuration on disk

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-docs#794]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

## Expected Behavior
Clustering guide provides exact steps to get a working cluster or when other options are provided (in this case config file vs command line arguments), those are called out as needed or not needed depending on your situtation.

## Current Behavior
The page:

https://docs.sensu.io/sensu-core/2.0/guides/clustering/#peer-communication-authentication-with-https-client-certificates

Shows starting the sensu-backend with command line options, when previously it had gone over setting up the configuration in `/etc/sensu/backend.xml`. Configuration shouldn't be needed in both places and should be called out.

## Possible Solution
Update the document as described above.

**Comment by cwjohnston** [comment]
Please note that `sensuctl cluster` subcommand may be removed. Guide should focus on using `etcd` prefixed command line flags or configuration directives (yaml) to configure cluster. If you find that there are aspects which cannot be configured without `sensuctl cluster` subcommand, please document them.
