### ISSUE TITLE
Add to Documentation

### ISSUE THREAD

**Issue by bdennis** [sensu/sensu-docs#81]
Sensu's built in keepalive (https://github.com/sensu/sensu/blob/master/lib/sensu/client.rb#L69)

is set to 20 hard-coded. This has caused me a lot of work a rounds with keepalive storms. After talking with Portertech i think we should add into the documentation that if you attempt to set the thresholds's for keepalives near 20 seconds it will cause a mass amount of false positives. This is an issue iv been dealing with for a while and i believe we should document this so in the future someone does not spend a month looking for an answer. Some company's like mine do not wish to wait 60 seconds to tell if a host is not responding or down. We want something around 15 seconds but with this 20 seconds hard-coded it cannot happen as of the current release. Please add this to this versions documentation.

**Comment by calebhailey** [comment]
Looks like this was never documented. We'll get this resolved in the upcoming 0.23 docs.

**Comment by calebhailey** [comment]
Added in https://github.com/sensu/sensu-docs/pull/346/commits/b56f632181921b4151bc7f229d206ea85817ac84 and will be committed in #346. \o/
