### ISSUE TITLE
Update sensu 2.0 entity reference documentation for attributes organization and environment

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-docs#810]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [x] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior
Reference documentation is correct in indicating when an attribute is required.

## Current Behavior
`environment` and `organization` attributes for an entity are said to be required by `sensuctl`.

## Possible Solution
Update the documentation to show that they are required.

## Steps to Reproduce (for bugs)
In a Sensu 2.x setup with `sensuctl`, create a file named `my_entity.json` with the following:

```
{
  "type": "Entity",
  "spec": {
    "class": "proxy",
    "id": "sensu-doc-site",
    "url": "https://docs.sensu.io"
  }
}
```

Run `sensuctl create -f my_entity.json`

See the following error:
```
error validating resource 0 (/entities/sensu-doc-site): environment must be set
Error: resource validation failed
```

Edit `my_entity.json` and add an environment. Re-run `sensuctl create -f my_entity.json` and see the following error:
```
error validating resource 0 (/entities/sensu-doc-site): organization must be set
Error: resource validation failed
```

## Context
Possible this is a bug in sensu-go.

**Comment by apaskulin** [comment]
Closing this issue since these attributes are being replaced by namespaces (https://github.com/sensu/sensu-go/pull/2175)
