### ISSUE TITLE
sensu-go docs are missing information for filter set-when and filter remove-when

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-docs#822]
There is no documentation on using filter set-when. This command expects a blob of JSON to be present in STDIN. We need to specifically show how to do this in the docs.

## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

**Comment by apaskulin** [comment]
Related: https://github.com/sensu/sensu-go/issues/2202 and https://github.com/sensu/sensu-go/pull/1337/files

**Comment by apaskulin** [comment]
Closing this for now until this feature is implemented in Sensu Go.
