### ISSUE TITLE
Replace Travis CI service with GitHub app

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#826]
Currently the docs site uses Travis CI as a GitHub Service, however GitHub will remove this feature on January 31, 2019. ([reference](https://developer.github.com/changes/2018-04-25-github-services-deprecation/)). We need to switch Travis over to a GitHub app before the shutoff date.

**Comment by cwjohnston** [comment]
Closing as I think this is now complete:

![image](https://user-images.githubusercontent.com/148017/49763819-f1f74280-fc8a-11e8-87d2-cdd3d0d05fc4.png)

**Comment by cwjohnston** [comment]
Narrator:
> But it wasn't complete

Turns out this change requires migrating the CI project from travis-ci.org to travis-ci.com. Travis support team have added us to their beta program and the migration process, [described here](https://docs.travis-ci.com/user/open-source-repository-migration/), is _now_ complete.
