### ISSUE TITLE
Implement copy-to-clipboard button

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#832]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [x] Feature request

#Comments 
It would save users a bit of time if we had a copy to clipboard button on our code samples. This should be easy enough to implement using something like https://themes.gohugo.io/theme/bulma/posts/clipboard/ .

**Comment by asachs01** [comment]
Pushed up a branch for this last night. I don't currently have it working, but would love some extra 👀 on it. https://github.com/sensu/sensu-docs/tree/add-copy-to-clipboard

**Comment by rgeniesse** [comment]
Swapped `/js/clipboard.min.js` for `/js/clip.js` inside the two html files in the current state of https://github.com/sensu/sensu-docs/tree/add-copy-to-clipboard and I got the word copy to appear in code blocks. Most likely very wrong, but at least was able to see an impact of adding this live.

Everything I've read, along with the blog in this issue, goes over needing to instantiate the code.
https://clipboardjs.com/
https://alligator.io/js/clipboardjs/ (not sure if this is the same method, but at least shows a way to install it non-Hugo)

I think this would be more clear knowing more JS stuffs.

This one may also be useful (haven't read it yet myself):

https://webdesign.tutsplus.com/tutorials/copy-to-clipboard-made-easy-with-clipboardjs--cms-25086

**Comment by rgeniesse** [comment]
I have this working on my local hugo install using Chrome or Firefox

- index.html in layouts:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>constructor-selector</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-shell" data-lang="shell">sudo sensu-install -p <span style="color:#e6db74">&#39;sensu-plugins-disk-checks:3.1.0&#39;</span></code></pre></div>

    <script async type="text/javascript" src="{{"/js/clip.js" | absURL }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.0/clipboard.min.js"></script>
</body>
</html>
```

`clip.js` in `/static/js`

```
/*
 * clipboard for hugo
 */

(function(document, Clipboard) {

    var $codes = document.querySelectorAll('pre');

    function addCopy(element) {
        var copy = document.createElement("button");
        copy.className = "copy button is-pulled-right";
        copy.textContent = "copy";
        element.append(copy);
    }

    for (var i = 0, len = $codes.length; i < len; i++) {
        addCopy($codes[i]);
    }


    new ClipboardJS('.copy', {
        target: function(trigger) {
            return trigger.previousElementSibling;
        }
    });
})(document, Clipboard);
```

I used a CDN version of the `clipboard.min.js` because my local install was failing to find my own copy. I tried a few things on the actual doc site, but they only get the word copy in the code blocks and it is not functional.

Of note:
- had to change `    new Clipboard('.copy', {` to `    new ClipboardJS('.copy', {`
- I don't know why this works...at all.

**Comment by rgeniesse** [comment]
There is a conflict of some sort happening on the docs site. If I use my `index.html` on the docs site, the copy button works.

**Comment by rgeniesse** [comment]
Ok, I have this working on the docs site. `clip.js` stays the same, no scripts in `head.html` and these lines after `{{ .Content }}` in `single.html`:

```
      <script async type="text/javascript" src="{{"/js/clip.js" | absURL }}"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.0/clipboard.min.js"></script>
```

This puts the word `copy` in all code blocks, although it doesn't look like a button but you can click it and it copies the code block while highlighting it. No fancy ack that it was copied. Also possible this was working, but the code block background was making it difficult to test.

**Comment by asachs01** [comment]
@rgeniesse that gets us close! I think I know what to do to make the rest of it work. There needs to be a couple of things here:
- [ ] The copy/copied text 

OR

- [ ] A better button (clippy.svg)
- [ ] Styling to match the site

I can continue to hack on this at a later date. I'll probably have to redo the pull since the branch is so far behind.
