### ISSUE TITLE
Guide: Scaling Sensu Go

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#848]
Create a new guide at /guides/scaling based on https://docs.sensu.io/sensu-core/1.6/guides/scaling-overview/

Notes:
- when running w/ embedded etcd (the default) https://coreos.com/etcd/docs/latest/v2/admin_guide.html “fault tolerance table”
- https://blog.containership.io/etcd/
- (1) talk about how there is database & state FT within each instance because of using etcd backend (and not talk too much about etcd perhaps)
- (2) how we can achieve manual FT by having separate instances of Sensu backend, and by doing xyz in DNS or something, the agents will fail over to a backup instance and start writing to the databases  and we only lose partial state in etcd
- (3) some “coming soon” feature about UI failover

**Comment by hillaryfraley** [comment]
Seems like this one might be partially or completely resolved by https://docs.sensu.io/sensu-go/latest/guides/scale-event-storage/

**Comment by hillaryfraley** [comment]
@cwjohnston Richie suggested we would also need a guide on adding backends by themselves and how it's different from scaling datastore to complete the Go docs.

**Comment by hillaryfraley** [comment]
Is the content described in the scaling Sensu Go issue covered by a combination of our Scale Sensu Go with Enterprise datastore guide and our Run a Sensu cluster guide? The issue was created in Oct 2018 and mentions UI failover as "coming soon" -- was that part of HA Postgres?

**Comment by hillaryfraley** [comment]
Closing in favor of https://github.com/sensu/sensu-docs/issues/2272
