### ISSUE TITLE
Sensu Go reference: Sensuctl

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#853]
- [x] Decide whether to create a sensuctl category
- [ ] Document all Sensuctl commands, preferably using https://github.com/spf13/cobra/blob/master/doc/md_docs.md
- [ ] Document location of stored `sensuctl` configuration for all supported systems. Example: OSX is inside `~/.config/sensu/sensuctl/`

**Comment by rgeniesse** [comment]
I added an item to the list to document where `sensuctl` stores its configuration to disk.
