### ISSUE TITLE
Add load balacing options to scaling guide

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-docs#856]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [X] Update (Add missing or refresh existing content)

## Expected Behavior
Customers have questions regarding when to use a Load Balancer in front of the Sensu 1.x components. 

## Current Behavior
We don't have documentation calling out usage of Load Balancers and the components of Sensu 1.x.

## Possible Solution
Add that content, when to use the LB and when not to.

**Comment by hillaryfraley** [comment]
Pending EOL: won't fix
