### ISSUE TITLE
Per-product redirects/aliases for "latest" docs

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#86]
Under the existing middleman site we have a symlink for `latest` that points to the latest revision of the documentation. 

Ideally this site would have similar URLs, e.g. `/sensu-core/latest` or `/sensu-enterprise/latest`, which point to the most recent version of the docs as defined under `params.products.*.versions` in config.toml

From briefly reviewing hugo documentation it looks like aliases are often configured per-page using frontmatter, which doesn't seem practical for our case.

**Comment by dabria** [comment]
So it looks like hugo `0.32` supports symlinks.
> Full support for symbolic links inside /content, both for regular files and directories.
There was an issue with layouts breaking though, so I’ll have to investigate what sort of changes I need to make before I can attempt this.

**Comment by dabria** [comment]
With Hugo updated symlinks work. The URLs can be hit and render perfectly. However, because of the way menu items are generated and how the links are set up, when you navigate away your URL will instead contain the version number instead of latest.

While it might not be a perfect user experience, I think this should still suffice so long as those pages exist. Thoughts?

**Comment by dabria** [comment]
The way our menus are generated had caused Hugo to give a lot of warnings when we have identical items. The symlinks cause this issue and I don't think there's a way to suppress these at this time without changing the front matter on each item. While this can be ignored, it's definitely a pain, especially if you're debugging.
![Screenshot 2018-01-25 11.05.48.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596e5bc511f7b9001f9d94c8/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6416763e7b51e37a21cbb37df1162343434d0eee1e020a17b8eb8339a3e73e25885402bbd03c0d7dc63811acba8717b809bf298e5d99a4fedb1294b7607caddecd5d340c041f83fe5834a6904bcf59f148e74e5cb65e.png)

**Comment by mercul3s** [comment]
I pulled this branch down and built it against hugo v0.36.x; it appears to be working but I do also get the duplicate menu item errors. I don't know if there is a way around the errors due to the way symlinks work - if we change the front matter on an item, it will be reflected in the symlink as it points to the same file. I *think* hugo thinks the symlink is a duplicate. I'm not clear enough on the menu system within the docs site / hugo to know if there is a way to fix the duplicate menu items errors.

**Comment by grepory** [comment]
Ok. After talking to hugo support, and looking at our options, we should not do this the way that we've done it, and we have one of two options:

Programmatically modify frontmatter whenever we update "latest."

Host the documentation in a way that allows URL rewrites / redirects. For example, if we switched to deploying with Netlify, we could do something like splat redirection which is documented here: https://www.netlify.com/docs/redirects/

I know I suggested that we consolidate hosting providers, but Netlify solves our problem the fastest, I think, supports custom domains, and gets us where we gotta go.

**Comment by mercul3s** [comment]
Doing a redirect makes a lot more sense to me and seems like the easiest solution, aside from the fact that we'd need to use a different hosting provider. This would seem like something heroku *should* support - wouldn't this work with buildpack static? https://github.com/heroku/heroku-buildpack-static

**Comment by grepory** [comment]
OH! Yes, I believe it does!

https://github.com/heroku/heroku-buildpack-static#custom-routes

Nice catch!

**Comment by palourde** [comment]
It might not be the best solution but we could simply rename the latest version (e.g. `1.2`) to `latest` and store the actual version in an another variable when we need to display it. Here's a real-life example: https://github.com/camunda/camunda-docs-manual/blob/a4adcb936146b79c5a9ff80b7ecceda32723a2ce/config.yaml#L27  & https://docs.camunda.org/manual/latest/.

The only downside to that approach is that you can't have a permalink to the _latest_ version (e.g. `/1.2/reference/clients/`).

**Comment by cwjohnston** [comment]
@mercul3s wrote:
> wouldn't this work with buildpack static? https://github.com/heroku/heroku-buildpack-static

I do think this will work, and it doesn't seem like a major effort to combine the hugo buildpack with this static build pack. I have committed untested changes to support this [here](https://github.com/sensu/heroku-buildpack-static/compare/master...sensu:hugo). 

Here are some thoughts on the subject of maintaining our own buildpack:

Pros 
* More control via nginx config (automated in the static buildpack), including rewrite rules
* We can integrate search index build into the deploy process

Cons
* More code
* Code is somewhat heroku-specific
* Doesn't help us consolidate on a hosting single platform

**Comment by cwjohnston** [comment]
Closed by #230 and https://github.com/sensu/heroku-buildpack-static/commit/ca2c0f210ad371ee5359ba92b6f6b1e202615599
