### ISSUE TITLE
Audit SE integrations for those that support proxy configurations

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#865]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

## Expected Behavior
Describe integrations that allow for proxy attribute configuration

## Current Behavior
Some integrations have this capability, but it isn't called out

## Possible Solution
Audit the docs/integrations to determine which ones support proxy attributes.

**Comment by asachs01** [comment]
## Integrations currently supporting explicitly defined proxy configurations
- [x] : Chef

## Integrations supporting proxy configuration via `http_proxy` environment variable
- [x] : Influxdb
- [x] : Jira 
- [x] : Librato
- [x] : Opsgenie
- [x] : Puppet
- [x] : Rollbar
- [x] : Servicenow

## Integrations currently NOT supporting proxy configurations
- [ ] : Datadog
- [ ] : Email
- [ ] : Graphite
- [ ] : Graylog
- [ ] : Hipchat
- [ ] : IRC
- [ ] : Opentsdb
- [ ] : Pagerduty
- [ ] : Slack
- [ ] : SNMP
- [ ] : Timescaledb
- [ ] : Victorops
- [ ] : Wavefront

## Integrations in question re: proxy configurations
- [ ] : EC2 - The integration doesn't explicitly spell out using a proxy. If I'm in AWS, do I even need to use one? What about if I'm using an on-prem Sensu cluster with the EC2 integration?

**Comment by asachs01** [comment]
So the larger question here is how do we document these integrations, knowing that a handful only support using a http proxy via an environment variable, and one has its own proxy configuration? I'm not certain that documenting the workaround (env var) would serve our customers, or us well, knowing that if we make the decision to change how the http proxy configuration works for integrations, we'd have to then go and update the docs yet again. Personally, I'd rather update the docs once wrt the integrations, rather than essentially doubling the work. 

Though on the other hand, if this option is available, then perhaps it should be documented. @apaskulin do you have feels on this?

**Comment by hillaryfraley** [comment]
Pending EOL: won't fix
