### ISSUE TITLE
Enhance TTL documentation

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-docs#868]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [X] Update (Add missing or refresh existing content)

## Expected Behavior
TTL attribute is properly documented.

## Current Behavior
Based on customer call, it seems there is confusion when to use the TTL attribute. Confirm the following is present:

- TTL is optional
- Setting TTL on every check adds a lot of overhead
- Recommend TTLs for ad-hoc check results
- Cameron's favorite example: backup/restore scripts

## Possible Solution
Update documentation.

**Comment by hillaryfraley** [comment]
Rescope: add note to TTL attribute in check reference to say that adding TTLs to checks adds overhead. Please bear this in mind and use TTLs sparingly.
