### ISSUE TITLE
Update Slack handler commands in Sensu Go

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#876]
Page: https://docs.sensu.io/sensu-core/2.0/guides/send-slack-alerts/#why-use-a-handler

Error:

```
$ sudo tar -C /usr/local/bin -xzf slack-handler_0.0.1_linux_amd64.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Fix:

```
tar -C /usr/local/bin -xvf slack-handler_0.0.1_linux_amd64.tar.gz --strip 1
```

To do:
- Fix command in guide
- Look into [releases](https://github.com/sensu/sensu-slack-handler/releases) of sensu-slack-handler

**Comment by apaskulin** [comment]
I wasn't able to reproduce this using the latest version of the plugin

**Comment by schampseix** [comment]
Hi @apaskulin ,

Yes it is now working correctly because the build package didn't include the bin folder as it was present in the v.0.0.1 : 
https://github.com/sensu/sensu-slack-handler/releases/download/0.0.1/slack-handler_0.0.1_linux_amd64.tar.gz

So it can be closed now I think 

Best regards

**Comment by apaskulin** [comment]
Thanks @schampseix!
