### ISSUE TITLE
Product tagline updates

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#88]
![2018-01-30 at 2 56 pm](https://user-images.githubusercontent.com/148017/35593795-2a2946a8-05ce-11e8-8917-7059cd61ed85.png)

**Comment by mbbroberg** [comment]
@cwjohnston not officially. What I tend to say is: 

- Sensu Core is the open source extensible monitoring framework
- Sensu Enterprise is the powerful and simple monitoring product 
- Enterprise Dashboard extends the value of Uchiwa with built-in displays, Role-based access controls and more
- Uchiwa is the open source dashboard for the Sensu monitoring framework, built with Go and AngularJS
- Plugins are a curated collection of checks, metrics and handlers to power your Sensu deployment
- Extensions are a curated collection of high performance integrations for Sensu Core

Longer descriptions would look something like: 

> Sensu Enterprise is everything you know and love about Sensu Core, with performance optimizations and built-in integrations designed to get up and running with the tools you're already using.
& 
> Sensu Enterprise Heads Up Display (HUD), Role-based access controls, LDAP authentication (Active Directory, OpenLDAP, etc), GitHub.com / GitHub Enterprise authentication, GitLab authentication, Federated API w/ token-based authentication.

But I don't have these for everything.
