### ISSUE TITLE
Use docs.sensu.io subdomain

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-docs#89]
The new Sensu documentation site will use `docs.sensu.io`.

We intend to keep the doc site on Heroku. Create the DNS record with the DNSimple account.

**Comment by cwjohnston** [comment]
@mbbroberg we've discussed this recently and it was decided we'd hold off on using the sensu.io domain for now. What's a reasonable placeholder for soft launch? Perhaps docs-preview.sensuapp.(com|org) ?

**Comment by cwjohnston** [comment]
I've set up docs-preview.sensuapp.com and docs-preview.sensuapp.org, but the latter can't be added to the heroku configuration:

```
$ heroku domains:add -a sensu-docs-site docs-preview.sensuapp.org
Adding docs-preview.sensuapp.org to ⬢ sensu-docs-site... !
 ▸    docs-preview.sensuapp.org conflicts with a wildcard cert on app sensuapp, owned by ops@heavywater.io. Please ask the owner to add this domain.
```

**Comment by cwjohnston** [comment]
Trying to make some sense of this. [Heroku docs indicate]( https://devcenter.heroku.com/changelog-items/1100) that we might be having trouble here because sensu-docs-site and sensuapp apps are not owned by the same account.

Currently:

* sensu-docs-site is owned by portertech@gmail.com
* sensuapp is owned by ops@heavywater.io

**Comment by cwjohnston** [comment]
@portertech will you please log in to herokuapp.com and do the following?

1. Add ops@sensu.io as a collaborator on the sensu-docs-site app
2. Transfer ownership of sensu-docs-site app to ops@sensu.io

There's probably a step in between these two where I will need to accept the collaboration invitation, which email I will keep an eye out for.

**Comment by portertech** [comment]
@cwjohnston done!

**Comment by cwjohnston** [comment]
This is done! https://docs-preview.sensuapp.com and https://docs-preview.sensuapp.org now point to the heroku app.
