### ISSUE TITLE
Asset documentation should describe the asset directory structure

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-docs#891]
Asset documentation does not describe the expected format of the asset tarball. The asset tarball is expected to contain `lib`, `bin` and `include` directories.

**Comment by calebhailey** [comment]
We should also explain what Sensu does with each of these dirs, e.g. /bin is added to `$PATH` for the execution of the associated check - but not permanently; i.e. equivalent of: 

```
$ PATH=$PATH:/var/cache/sensu-agent/asset-sha/bin command -options -etc
```

Same for /lib being added to LD_CONFIG (or however that works). I think /include is just relative path files for the bins, yes?

**Comment by echlebek** [comment]
Simon pointed out that we do explain the structure in the reference section. Maybe we just need a link to that in the guide!

https://docs.sensu.io/sensu-go/5.0/reference/assets/#default-cache-directory

**Comment by echlebek** [comment]
@calebhailey yes, I think you are right on both counts.

**Comment by echlebek** [comment]
For the record, this is the documentation I was referring to originally: https://docs.sensu.io/sensu-go/5.0/guides/install-check-executables-with-assets/#how-to-create-a-check-that-depends-on-an-asset

This is what comes up when you google "create a sensu asset".
