### ISSUE TITLE
Create Sensu Go Getting Started Series

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#893]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior

Series of articles aimed at beginners getting their feet wet w/ Sensu Go. This could be adapted from sensu/sandbox

**Comment by apaskulin** [comment]
Closing as a duplicate of #842
