### ISSUE TITLE
Legacy Enterprise page includes broken links

### ISSUE THREAD

**Issue by Blue0ctober** [sensu/sensu-docs#899]
The sensu-docs link on the Legacy Enterprise page (https://docs.sensu.io/sensu-enterprise/legacy/) 
sends me to https://github.com/sensu/sensu-docs/tree/master/legacy which does not exists 

## This is an issue with:

- [x] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)

## Expected Behavior
Link should be to an older branch

## Current Behavior
404 Github Link

## Possible Solution
host legacy docs somewhere 😬

**Comment by cwjohnston** [comment]
The old docs are in this repo https://github.com/sensu/sensu-docs-legacy

**Comment by apaskulin** [comment]
Page to update: https://github.com/sensu/sensu-docs/blob/master/content/sensu-enterprise/legacy.md
