### ISSUE TITLE
users array is not documented in sensu enterprise dashboard configuration page

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-docs#904]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [X] Update (Add missing or refresh existing content)

## Expected Behavior
Configuration documentation should have all possible configuration options.

## Current Behavior
Sensu Enterprise Dashboard configuration documentation is missing the optional `users` array configuration attribute that goes under the `dashboard` object in `/etc/sensu/dashboard.json`. While I'd expect most Enterprise customers to have a supported OAuth implementation, this is a valid work around for OAuth issues, lab environments and possibly other use case for our users.

Example:

```
    "users": [
      {
        "username": "mine",
        "password": "secret"
      },
      {
        "username": "mine2",
        "password": "secret2"
      }
    ]
```

Current configuration documentation also shows you can encrypt your password.

https://docs.sensu.io/sensu-enterprise-dashboard/2.12/configuration/#example-dashboard-configuration

Example for context:

```
    "users": [
      {
        "username": "sensu_user_1",
        "password": "{crypt}EXAMPLEPASSFORUSER1"
      },
      {
        "username": "sensu_user_1",
        "password": "{crypt}EXAMPLEPASSFORUSER2"
      }
    ]
```

## Possible Solution
- Add the missing optional attribute under `dashboard` attributes.
- Ensure the optional encryption method is provided as well, will require research.

**Comment by apaskulin** [comment]
Reference: https://docs.sensu.io/uchiwa/1.0/getting-started/configuration/#multiple-users
