### ISSUE TITLE
Sensu Go metrics reference

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#907]
Create a metrics reference page at reference/metrics with everything you need to know to process metrics with Sensu Go.

### Outline

- Diagram showing metrics entering the pipeline
- Aggregating Prometheus metrics with Sensu
- Collecting metrics with Sensu checks
- Pushing metrics to Sensu using the agent API
- Using Nagios plugins with Sensu

**Comment by hillaryfraley** [comment]
Closing in favor of https://github.com/sensu/sensu-docs/issues/2924
