### ISSUE TITLE
Update monitor the monitor guide to include RabbitMQ consumers

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-docs#908]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [X] Update (Add missing or refresh existing content)

## Expected Behavior
Have all the basic ways to monitor the health of Sensu.

## Current Behavior
Missing an example to monitor the expected number of consumers.

## Possible Solution
Add example check using:

https://github.com/sensu-plugins/sensu-plugins-rabbitmq/blob/master/bin/check-rabbitmq-consumers.rb

or

https://docs.sensu.io/sensu-core/1.6/api/health-and-info/#how-to-obtain-api-status-information
https://github.com/sensu-plugins/sensu-plugins-http/blob/master/bin/check-http.rb

**Comment by hillaryfraley** [comment]
Pending EOL: won't fix
