### ISSUE TITLE
Evaluate installation method for SE on Deb/Ubuntu

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#916]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

## Expected Behavior
Use `/etc/apt/auth.conf` for authenticating to SE repo

## Current Behavior
This isn't present in the docs.

## Possible Solution
Update the docs to include new way of authing

`/etc/apt/auth.conf` should include something like:

```
machine enterprise.sensuapp.com/apt login $SE_UESR password $SE_PASS
```

Then the source is added:

```
echo "deb     http://enterprise.sensuapp.com/apt sensu-enterprise main" | sudo tee /etc/apt/sources.list.d/sensu-enterprise.list
```
Update using apt-get:

`sudo apt-get update`

Install SE/SED

`sudo apt-get install sensu-enterprise sensu-enterprise-dashboard`

**Comment by hillaryfraley** [comment]
Pending EOL: won't fix
