### ISSUE TITLE
Create Sensu Core 2.0 project

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-docs#92]
Create a Sensu 2.0 project and migrate the markdown documentation from https://github.com/sensu/sensu-alpha-documentation

**Comment by mbbroberg** [comment]
Working with @cwjohnston on scoping this and decided that: 

- Sensu Core 2.0 will be another version of Sensu Core, so it will go into that tile 
- Existing docs from the Alpha will be considered for migration on a case-to-case basis under Guides or References

Exact pattern or redirecting from the alpha repo to the beta docs will need further discussion before resolving so we don't end up updating two sets of the same docs.

**Comment by cwjohnston** [comment]
Relates to #149

**Comment by cwjohnston** [comment]
Closing this in favor of #149
