### ISSUE TITLE
Existing doc URL redirects

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-docs#93]
Setup redirects from all previous documentation resource URLs to the appropriate Sensu Docs Site URL.

**Comment by cwjohnston** [comment]
we should also ensure the top-level [FAQ URL](http://sensuapp.org/faq) redirects to the new docs FAQ

**Comment by cwjohnston** [comment]
https://github.com/sensu/website/pull/322 relates to this issue

**Comment by cwjohnston** [comment]
Closed by https://github.com/sensu/website/pull/322
