### ISSUE TITLE
Review all filter expressions

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#934]
https://docs.sensu.io/sensu-go/5.0/reference/filters/#handling-production-events includes two conflicting examples of filter expressions:

```"expressions": ["event.Entity.Namespace == 'production'"],```

```"expressions": ["event.entity.metadata.namespace == 'production'"],```

- [x] Fix this and review other expression examples in the docs.
- [x] Also add a note that metadata is an embedded field in go so it’s not necessary to reference it each time you want to obtain its data. Correct example: event.entity.namespace
- [x] potentials references to "statements"
- [x] Resources heading in glossary should be h4
- [x] Add token to glossary
- [x] RBAC role and cluster role example syntax highlighting not consistent
- [x] Replace proxy_entity_if with proxy_entity_name
- [ ] Broken link check
- [x] Search "Sensu 2"

**Comment by calebhailey** [comment]
Add https://docs.sensu.io/sensu-go/5.0/reference/assets/#metadata-attributes to the list. 

In the `spec` scope example is uses lowercase `"system.os == 'linux'"`. In the `filter` attribute example it uses upper case attributes `"System.OS=='linux'"`.
