### ISSUE TITLE
Add metadata docs section for 5.0, explain wrapper metadata and resource metadata

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-docs#940]
* Explain that wrapper object metadata becomes resource metadata when the resource is created.
* Explain "type" and "api_version" fields.
* Document metadata fields. (Already done in checks.md)

**Comment by echlebek** [comment]
@apaskulin you may need a debrief on the things that have changed!

**Comment by apaskulin** [comment]
Closing as a duplicate of #932
