### ISSUE TITLE
"Repeat in Versions" Tooling

### ISSUE THREAD

**Issue by mbbroberg** [sensu/sensu-docs#95]
There will be updates to documentation that will need to be copied between versions. I would love to see a utility included that makes it a little less painful to make these repeated sections. 

One idea that might not be possible, but explains what I'm hoping for: 

* In an ideal scenario, I run `./bin/repeat 1.2 1.1`  and it repeats the edits I just committed with git on 1.2 and adds them to the previous version of 1.1. Running `./bin/repeat 1.1 *" repeats for all versions. In the failure scenario, it could say "I can't merge that for you, but you should edit the following pages: " and it lists out the files to edit so they can be quickly clicked on for an IDE or opened in vim. 

Does anything that helps this process exist? If not, could it?

**Comment by grepory** [comment]
This is best done by manipulating patches, imo. If you get a patch-formatted diff from git, you could then just search and replace file names. Applying the resulting patch effectively just gives you this. At most, I think this could just be scripted somehow.

**Comment by grepory** [comment]
I think for anything more than that we should try to solve the problem by figuring out how to not duplicate documentation across versions.

**Comment by mbbroberg** [comment]
> figuring out how to not duplicate documentation across versions.

That would be ideal, though the team has said in there research they've found that other projects follow this same (in)convenience. For now I'm assuming that's not possible.

>  If you get a patch-formatted diff from git, you could then just search and replace file names

That is exactly what I'd love to see. Something in this repository that allows for reapplying the last commit (or named commit) across certain versions (thinking `*` would be helpful or listing multiple).

**Comment by grepory** [comment]
It's possible (it involves a lot more templates and content type front-matter) -- kind of annoying. It's basically like a "content partial". See: https://discourse.gohugo.io/t/load-multiple-content-files-in-a-single-template/2566

I guess I'm just a bit concerned that the script has diminishing returns. Patches use line numbers to match up segments. An off-by-one error makes it so that the patch is unable to be applied.

**Comment by hillaryfraley** [comment]
Manual process is preferable to full automation rn
