### ISSUE TITLE
API listen address, API URL config options

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-docs#963]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)

# Expected Behavior
We've deprecated `api-host` and `api-port` as flags & config options for the backend. These have been replaced with two new options with different purposes:

`api-listen-address` is used to specify which address the API daemon will listen for requests on. Default is `[::]:8080`.

`api-url` is used to specify the URL used to connect to the API. Default is `http://localhost:8080`.

**Comment by amdprophet** [comment]
Correction: instead of deprecating the old fields, we'll be completely removing them.

**Comment by asachs01** [comment]
@amdprophet so this should go in the backend reference doc? Given your last comment, `api-listen-address` and `api-url` will need to be added, or will those not be used.?

**Comment by amdprophet** [comment]
Yes, `api-listen-address` and `api-url` are new fields and we're removing `api-host` and `api-port`.
