### ISSUE TITLE
Add note regarding token substitution and values getting converted to strings

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-docs#969]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [X] Update (Add missing or refresh existing content)

## Expected Behavior
Token substitution documentation shows limitation on values it sends.

## Current Behavior
Token substitution does not call out that it converts integers to strings once substituted. 

## Possible Solution
Add the missing content.

## Context
We have at least one customer that is attempting to add an integer to a sensu attribute that expects an integer through token substitution. They get this error when doing so:

```"message":"client keepalive critical threshold must be an integer" ```

* Browser(s) and version(s): 
* OS:

**Comment by apaskulin** [comment]
Page: https://docs.sensu.io/sensu-core/1.6/reference/checks/#check-token-substitution
