### ISSUE TITLE
Sensu Go discovery event guide

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#976]
Create a new guide or sandbox lesson for monitoring entities using keepalives, similar to https://github.com/calebhailey/sensu-demo

- Registration & deregistration capturing metrics from containers as they come and go, with a Nagios plugin.

To do: Determine scope

**Comment by hillaryfraley** [comment]
Suggestions from @asachs01 :

- Provide a stale event/entity check example
- Doc should help users understand the benefit of enabling deregister (which is false by default): avoid inflated number of events
- Challenges: getting the deregister + keepalive timeouts right and finding the right place in the docs to provide this information

**Comment by hillaryfraley** [comment]
This issue references the [Sensu Go Demo](https://github.com/calebhailey/sensu-go-demo) as a go-by for creating the requested guide. However, Caleb's comments in the Sensu Go Demo readme seem to indicate that he intended for https://sensu.io/#getting-started to supersede it.

**Comment by hillaryfraley** [comment]
Another pattern doc: when an agent checks in for the first time (registration event) and sends its first keepalive and Sensu knows to start keeping track of this entity; flip side is Sensu agent getting message that entity is shutting down and sends message to Sensu to remove entity (deregistration event).

Another example: deregistration can go to another handler (ask AWS if compute instance still exists and if not, automatically deregister). Perhaps an integration doc for EC2.

**Comment by hillaryfraley** [comment]
We covered EC2 deregistration in https://docs.sensu.io/sensu-go/latest/operations/control-access/create-limited-service-accounts/

**Comment by hillaryfraley** [comment]
Examples that register agents and automatically add subscriptions based on the entity's OS: https://sumologic.slack.com/archives/C02ANQE1G2Y/p1646340952885389

See also step 5 at https://github.com/calebhailey/sensu-go-workshop#lesson-1-introduction-to-sensu-go

See explanation at https://sumologic.slack.com/archives/C024XK35Z3Q/p1646853288697319

**Comment by hillaryfraley** [comment]
Notes from Jun 23 docs inbox cleanup:

If deregister is not set true, entities just hang around and check requests are still sent. There will also be entities that should exist but don't. Easier to deregister: true from the start instead of go back and remove entities that were not automatically deregistered (can use plugin).

Goal: a prescriptive workflow.

Kube containers coming on and offline constantly. Set deregister helps avoid unnecessary process load due to the backend scheduling checks on entities that don't exist.
