### ISSUE TITLE
Redis sentinel configuration is not correct for centos7

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#985]
more details to follow...

**Comment by asachs01** [comment]
Ah, ok. So, there are a number of places where our docs on installing Redis/sentinel on CentOS 7 need correction:

1. The location of the config files is referencing `/etc/redis/` as the main directory. This is not correct:
```
# ls -al /etc/redis*
-rw-r-----. 1 redis root 46729 Oct 26 07:05 /etc/redis.conf
-rw-r-----. 1 redis root  7642 Oct 26 07:05 /etc/redis-sentinel.conf
```
So we need to update this to point to `/etc/redis.conf` and `/etc/redis-sentinel.conf`

2. Our docs reference no init scripts being installed and that there is a need to pull down custom install scripts. This is also not the case any longer, as there are systemd unit files installed with the package:
```
# systemctl enable redis-sentinel
Created symlink from /etc/systemd/system/multi-user.target.wants/redis-sentinel.service to /usr/lib/systemd/system/redis-sentinel.service.
```
This will probably warrant a full audit/walkthrough to ensure that the Redis install docs to ensure that they're updated. However, this seems like a somewhat lesser priority.

**Comment by hillaryfraley** [comment]
Pending EOL: won't fix
