### ISSUE TITLE
Clarify process for adding labels in the token reference

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#995]
The token reference relies on entity labels for its examples, but doesn't indicate how to add labels to agents using the agent config file. Update the token reference to make this process more clear.

**Comment by nixwiz** [comment]
Also, the examples use dashes in the token names.

` "command": "check-disk-usage.rb -w {{.labels.disk-warning | default 80}} -c {{.labels.disk-critical | default 90}}",
`

This is apparently a bad thing according to this error.

![image](https://user-images.githubusercontent.com/5530473/49671886-35994480-fa1e-11e8-852a-3bfa327df570.png)
