### ISSUE TITLE
Add Sensu Core 1.6.2 and Sensu Enterprise 3.3.1

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#998]
Documentation updates for version 1.6.2 of Sensu Core and version 3.3.1 of Sensu Enterprise

https://waffle.io/sensu/sensu?milestone=1.6.2

https://waffle.io/sensu/sensu?milestone=3.3.1

**Comment by cwjohnston** [comment]
I believe these will be changelog updates only.

These releases will address a bug in Redis Sentinel connection handling where Sentinel configuration referencing invalid or nonexistent hostnames would cause Sensu Server or Sensu Enterprise to crash. Actual code changes are in sensu-redis library: https://github.com/sensu/sensu-redis/pull/22.

The new behavior is to retry the failing Sentinel instance(s) until they become available, but proceed with normal operation as long as any one configured Sentinel is able to direct Sensu to the current Redis leader.
