### ISSUE TITLE
Use underscores in token substitution examples

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-docs#999]
It turns out that dashes don't (and can't) work in token substitution. We should change the examples.

**Comment by nixwiz** [comment]
Not only should the examples be changed, but the reader should be explicitly advised to avoid using dashes.

**Comment by rgeniesse** [comment]
@nixwiz  thanks for the additional call out.

I have a PR open to remove the examples using a `-`. 

https://github.com/sensu/sensu-docs/pull/1004

For now, we will not have any call out for not using `-` as internally we have a few points we want to clear up first:

- What are the valid/invalid chars for labels for token substitution?
- Even better, across Sensu Go's use of labels, what are the common characters that can be used in labels regardless of use case? We don't want users adding `-` (or other characters) to their labels, then going to use token substitution and finding out they have to make a bunch of other changes.
- The investigation to see if we can validate data sent to Sensu Go and returning a message that a character is invalid for that use.

**Comment by echlebek** [comment]
Ah, thanks for asking these questions. I meant to communicate this information but it slipped my mind.

> What are the valid/invalid chars for labels for token substitution?

The valid chars for token substitution selectors are the same as Go identifiers, _when using dot notation_. See https://golang.org/ref/spec#Identifiers (tl;dr - you can use a combination of letters, digits and underscores, but you cannot start a label with a number)

You can also use the _map indexing notation_, which is simply a space, in which case arbitrary strings are permitted. This looks like:
```
{{ metadata.labels "system-disk" }}
```

> Even better, across Sensu Go's use of labels, what are the common characters that can be used in labels regardless of use case? We don't want users adding - (or other characters) to their labels, then going to use token substitution and finding out they have to make a bunch of other changes.

Labels can be any valid string identifier - they just can't be used for token substitution with dot syntax. This is a limitation of Go's template substitution system.

Edit: for reference, the Go template syntax is fully described here: https://golang.org/pkg/text/template/

**Comment by apaskulin** [comment]
Thanks, @echlebek! Just to confirm, these limitations apply anywhere we're using dot notations, like in filter expressions?

**Comment by echlebek** [comment]
@apaskulin that is correct.

**Comment by jspaleta** [comment]
`{{ index .labels "foo.bar.baz" }}`

Will work for the more general case.

From the upstream docs
```
index
	Returns the result of indexing its first argument by the
	following arguments. Thus "index x 1 2 3" is, in Go syntax,
	x[1][2][3]. Each indexed item must be a map, slice, or array.
```

**Comment by apaskulin** [comment]
Thanks, @jef. Since this issue is closed, I opened https://github.com/sensu/sensu-docs/issues/1037 to track that update.
